# {-} Summary Introduction

In chapter 1, we outline the historical context for the spread of abortion in the twentieth century. We show how world wars and Communist tyranny set the stage for genocide in our very own homes. In addition to seeing the staggering number (billions) of souls who have been sacrificed in this most recent holocaust, readers may be shocked to see how dependent our society is on abortion's bloodshed. Perhaps the most difficult matter for Christians to accept will be the true nature of hormonal birth control, IUDs, and in vitro fertilization. To those who have ears to hear, we explain that many, if not most, of our little ones are being destroyed, not by surgeon's instruments late in pregnancy, but before our babies are even allowed to attach themselves to their mothers' wombs.

After building an understanding of how and to what extent we have given ourselves to this destruction, we then lay out in chapter 2 the many arguments which exist against the practice of abortion. Several sections of this chapter are very technical, drawing on research from a wide range of academic fields. We thank God for blessing Evangel Presbytery with godly brothers who are experts in the disciplines of economics, biochemistry, law, classical studies, and medicine. These brothers' careful and faithful labors unequivocally demonstrate abortion's vileness. The arguments assembled from their work build up to and conclude with Scripture's authoritative, clear, and multifaceted teachings against the practice of murdering our children.

In chapter 3, we lay the biblical foundation of what it looks like for (1) civil authorities, (2) church authorities, and (3) individuals to act and speak faithfully regarding the slaughter of the unborn. We answer many common questions and objections, but not all, since the work of application is necessarily specific to each person's unique calling, relationships, location, gifts, weaknesses, and so forth. Walking in obedience to God's will in these matters will require Christians to live together, counsel one another, and submit to one another in the fear of Christ (Eph. 5:21).

The thrust of the work before you is unavoidably negative. Our primary objective here is to awaken consciences to the depth of our bloodguilt. When we as a people have given ourselves to such evil for so long, we absolutely must do the painful work of exposing our unfruitful deeds of darkness (Eph. 5:11). We all must hear the condemnation of God's law. And then we must *repent*. To do so is to flee the wrath to come, and we know that God's wrath is certainly coming upon murderers, whose part will be "in the lake that burns with fire and brimstone, which is the second death" (Rev. 21:8). When we repent of murder, we run away from this second death.

Repentance, however, is more than just turning away from death. The repentance which our merciful God grants us is not just repentance *from death*, but repentance *unto life* (Acts 11:18). We flee *from* God's wrath and *towards* the eternal life promised in Christ Jesus. Then, as possessors of life eternal, we embrace God's gift of life here and now. This is why we conclude our work by showing that the end of abortion is not simply the denouncing of murder, but the embracing of God's beautiful blessing of fruitfulness, especially in His giving of woman to be the giver of life.