# Chapter 1. The Bloodshed of the Twentieth Century

When the record of our time is written, it will be a record of bloodshed on a scale previously unimaginable across the history of mankind. The heart of that bloodshed is the war carried out by the born against the unborn. The victims of this war are a class of persons constrained within the wombs of their mothers, and they live without sight, sound, or voice. The disability that unites them is their incapacity to lift a finger in their own defense.

Other great moral evils exist, of course, but abortion is unique in targeting the most helpless members of our society. Our bloodlust has never before found a class of victims so utterly vulnerable. For this reason abortion's bloodshed dwarfs every other bloodshed. How we repent of this bloodshed is thus the greatest moral issue of our time, and this repentance or its absence will be predictive of our repentance of a multitude of other moral evils of our age. Infanticide, euthanasia, and physician-assisted suicide are of the same moral fabric as our slaughter of little ones.

Some speak of this genocide as being on the decline today. This is false. Across the world, abortions are not falling, but rising. The United Kingdom's premier medical journal *The Lancet* reports abortions currently stand at 73.3 million per year.[^8] Based on that figure alone, we are killing 1 percent of the world's population each year---but we note this estimate *excludes* those babies aborted in their first week of life. To facilitate the murder of these babies, our medical authorities have (as we will see) declared that babies in the first week of life are not yet living beings.

Abortion's slaughter is staggering. Reading such estimates, we ask if it is possible we have murdered billions of babies? How can this be? Why did we not know this number? How did we get here? Who is responsible? What can be done about it?

The beginning of answering these questions is to take a step back.

## A Grim Progression

### War

The twentieth century---what would become history's bloodiest century---began with war between many nations. The warfare's scale, tactics, and techniques were unprecedented. World War I's trench warfare was so dehumanizing and the killing so sustained that many declared their optimism this horror would force a sea change in governments' ability to send their men into war. Thus H. G. Wells named World War I "the war to end all wars."

He was wrong. World War II followed hard on the heels of World War I so that, during the first half of the century, fatalities from these two world wars reached 77 million. But cloaked within this number was a detail foreshadowing the trajectory massive killing would take as the century continued.

### Targeting Civilians

Until the twenty-first century, Christendom had condemned the killing of civilians during warfare. Since the Middle Ages, the Western world had held to the necessity of *jus in bello*, and three commitments stood out among just war principles: soldiers who surrendered were not to be killed; suffering was to be minimized; and the indiscriminate killing of noncombatants was prohibited.

But at the turn of the twentieth century, Christendom itself was, in a sense, on the wane. Atheism and rebellion against God's moral law had grown in the centuries since the Enlightenment, and civilization was about to pay the price. Sadly, of the 17 million fatalities of the First World War, 7 million were civilians. The Second World War was worse: of an estimated 60 million fatalities, 40 million were civilians. Note that these numbers don't even include the tens of millions who died from secondary causes like disease and famine.

Thus, from the start, the twentieth century was exceedingly bloody. The wars were worldwide, the killing was beyond anything imaginable, and civilians were intentionally targeted so that the elderly, women, and children made up the majority of the wars' casualties. By the end of the Second World War, targeting civilians was a major strategy of both Axis and Allied forces. Both sides of the conflict used conventional bombs to kill the civilian populations of their enemies.

Speaking only of our Allied air forces' attacks on Japan, on March 9 and 10, 1945, the air raid called Meetinghouse sent 300 bombers to drop 1,665 tons of bombs on Tokyo, leaving close to 16 square miles destroyed and 100,000 dead. United States forces later dropped nuclear warheads on Hiroshima and Nagasaki, killing 105,000 men, women, and children.

By the end of World War II, Allied bombing had damaged or destroyed over one-quarter of German homes, killing or injuring 1 million German civilians. The relentless nature of Allied bombing of civilians is demonstrated by the fact that 50,000 tons of bombs were dropped on the city of Cologne alone.[^9]

In the end, during the first half of the twentieth century, war claimed 77 million souls, of whom 47 million were civilians. Just war principles had been cast aside. In its conduct of war, the Western world had sown the wind. In the justice of God, we would now reap the whirlwind.

### Rulers Killing Citizens

As the century continued, the killing turned from nations killing nations to rulers of nations killing their own people.

The Soviet Union's great prophet Aleksandr Solzhenitsyn estimated Joseph Stalin was responsible for the deaths of more than 60 million. Chairman Mao's Great Leap Forward, Great Famine, and Cultural Revolution claimed somewhere between 40 and 100 million lives. The death toll of Pol Pot's Khmer Rouge in Cambodia was only 2 million, but these 2 million souls comprised one-quarter of his nation's population.

First, World Wars I and II killed 77 million souls. Then Communism killed at least 100 million souls; and this was bloodshed in service, not to national boundaries defended as patriotism, but pure ideology. As Solzhenitsyn wrote documenting Stalin's death toll in the Soviet Union, "Thanks to *ideology*, the twentieth century was fated to experience evildoing on a scale calculated in the millions. This cannot be denied, nor passed over, nor suppressed."[^10]

First, soldiers killed soldiers. Then, soldiers killed civilians. Then, rulers killed their own people.

The prophet Hosea warned that bloodshed begets bloodshed,[^11] and so it was that the killing next turned inward to the home and family; fathers and mothers killed their own sons and daughters.

### Parents Killing Children

Domestic slaughter began with birth control.[^12] The first abortions were not surgical, but chemical and hormonal. Before women became willing to pay for their child to be cut out of their wombs, they began using birth control methods that had an abortifacient agency. As we will discuss in greater detail later, these methods include intrauterine devices (IUDs) and the Pill.

This was well-known and presented a problem the medical establishment felt the need to resolve. There was no debate in the scientific and medical world that the moment sperm and egg joined, a new life came into existence.[^13] Nor was there any question this preborn life had a rightful claim to all the protections accorded life outside the womb.

These truths, though, stood squarely in the path of the mid-century explosion of the practice of birth control so that, midway through the century, the American medical establishment undertook the project of denying these little ones were living human beings. Every scientist, physician, and mother knew conception was the beginning of life, so what was to be done?

The story is recounted by the American College of Pediatricians who report that, back in 1959, a physician with ties to Planned Parenthood named Bent Böving "argued for . . . moving the date of conception from when fertilization occurs to when implantation occurs."[^14] Böving suggested "the social advantage of \[birth control\] being considered to prevent conception rather than to destroy an established pregnancy could depend upon something so simple as a prudent habit of speech."[^15]

A few years later, Dr. Böving's "prudent habit of speech" was formally adopted by the American College of Obstetricians and Gynecologists who, in 1965, issued a bulletin changing the definition of conception from fertilization to implantation.[^16]

Consider the significance of this subterfuge promulgated by the American medical establishment. By redefining conception, the killing of babies during their first week of life by means of birth control methods was no longer "abortion," but "contraception." The baby was not aborted, because he was never conceived. The baby never died, because he never lived.

Never mind that these little ones are God's own image-bearers having unique DNA and needing nothing more than the sustenance and protection of their mother's womb to be born and live threescore and ten. Who could ever have imagined then, eight years before *Roe v. Wade*, the monstrous death toll that would result from this lie adopted as merely a "prudent habit of speech"? This saying is true: "What a tangled web we weave, when first we practice to deceive."

We can't be reminded often enough that murderers lie. In his book *Aborting America,* Dr. Bernard Nathanson confesses the history of his work legalizing abortion in the late sixties and early seventies. He speaks candidly of the lies he and his Abortion Rights Action League co-belligerents told. He writes:

> I confess that I knew the figures were totally false. . . . But in the "morality" of our revolution, it was a useful figure, widely accepted, so why go out of our way to correct it with honest statistics? The overriding concern was to get the laws eliminated, and anything within reason that had to be done was permissible.[^17]

The legalization and growth of the practices of birth control and abortion are inseparable. This fact must be faced squarely by the people of God. The use of birth control would not have spread as it did without the lie that life doesn't begin at conception. This wicked lie has metastasized across the past seventy years, and now the life of the unborn is denied during all three trimesters.

Abortifacient birth control methods that killed children in their first days of life gave birth to abortions throughout pregnancy so that, today, in some places late-term abortions are legal even as the baby is in the birth canal about to take his first breath outside the womb.

Thus, in the decades following 1950, abortion came to dwarf every other killing field of the twentieth century.

Today, it is commonly thought, at least in the United States, that the slaughter of abortion was unleashed by the Supreme Court's 1973 decision *Roe v. Wade*. This is factually wrong. Birth control of an abortifacient agency as well as surgical abortions were widely practiced prior to the Supreme Court's *Roe v. Wade* ruling. In 1972 alone, the year prior to *Roe v. Wade*, the death toll of unborn babies surgically aborted in the United States was 586,760.[^18]

Abortifacient birth control methods propped up by scientists and physicians redefining conception and life make no sense outside a world that had become inured to the bloodshed of innocents. World wars and Communist ideologies had killed their hundreds of millions. Now the bloodthirst turned inward, and the home became the killing field.

Not surprisingly, this intimate familial bloodshed was first normalized behind the Iron Curtain within the Soviet Union where Russians and Eastern Europeans began killing their unborn children in the early fifties. But it didn't take many years for this horror to spread to Western Europe and North America; and now, most of the world. Violence begets violence.

We become proficient at killing, thinking we have it under control. But actually, the bloodshed has us under its control, and its appetite is voracious and growing.

## Abortion's Consequences

The destruction caused by the spread of abortion becomes more clear as we examine some of its additional consequences.

### Sex-Selective Abortion

Across South Asia, sex-selective abortion is now widespread. It was first practiced in South Korea, producing in certain cities a sex ratio at birth (SRB) of 125 boys to 100 girls.[^19] China copied the practice so that, now, a number of provinces have an SRB of 130 boys to 100 girls. Soon, the practice spread to India where several states now have an SRB of 120 boys to 100 girls. The National Library of Medicine of the National Institutes of Health gave the following report concerning China:

> The SRB across the country for first-order births is 108, for second-order births it is 143 and for the (albeit rare) third-order births it is 157.[^20]

In 2012, Planned Parenthood's research arm, The Guttmacher Institute, reported:

> The Chinese Academy of Social Sciences predicts that by 2020, China will have 30--40 million more boys and young men under age 20 than females of the same age. India, too, is facing a national crisis with its sex ratios. The Indian census does not publish sex ratios at birth, but rather child sex ratios, expressed as the number of females below age seven for every 1,000 males. The last four census surveys point to rapidly increasing disparities: The child sex ratio dropped from 962 (girls to 1,000 boys) in 1981 to 945 in 1991 to 927 in 2001, and according to the latest census, in 2011, the ratio decreased further, to 914.
> 
> . . . The northern Indian states of Haryana and Punjab are notorious for their exceedingly disparate ratios, at 830 and 846, respectively, with some districts dipping into the 770s.[^21]

*The Guardian* reports, "India is estimated to have 63 million fewer women since sex determination tests took off in the 1970s."[^22]

A decade ago, *The Economist* reported:

> China alone stands to have as many unmarried young men---"bare branches," as they are known---as the entire population of young men in America.[^23]

More recently, *The Economist* did a piece on gendercide in the Caucasus states, especially Georgia, Azerbaijan, and Armenia:

> But in Armenia and Azerbaijan more than 115 boys are born for every 100 girls and in Georgia the ratio is 120. These are bigger distortions than in India. In all three the figure has risen sharply since 1991. . . . In 2010, reckons Marc Michael of New York University's Abu Dhabi campus, the number of girls born was 10% lower than it would have been had the ratio been normal. The gap is second only to China's.[^24]

Enlightened Westerners condemn this killing of unborn girls for its "sexism." They are rightly horrified at the denial of the equality of the sexes it demonstrates. The image of God is the foundation of our personhood and is equally shared by man and woman, so any denial of woman's equal worth is an assault on God Himself.

Yet if we place this practice under scrutiny, it becomes clear something much worse than the denial of the equality of persons is motivating this gendercide. Consider feminist women who argue in defense of the right of women to have gender-selective abortions. In *Gendercide: The Implications of Sex Selection*, the late Mary Anne Warren, philosophy professor at San Francisco State University, argued against any legal prohibition of gender-selective abortion. Dedicating her book "To utopian feminists, who dream of alternative futures," Warren wrote:

> I will argue that the objections to sex selection are insufficient to show that it is inherently immoral to preselect the sex of a child.[^25]

Speaking of the need to "resist prohibition" of gender-selective abortion in her chapter titled "The Case for Freedom of Choice," Warren writes:

> There is great danger that the legal prohibition of sex selection would endanger other aspects of women's reproductive freedom \[including\] the right to choose abortion.[^26]

In her book's conclusion, Warren states:

> We must not accept the argument that women who opt for sex selection \[abortion\] . . . are not making *real* choices.[^27]

Warren's foundational principle is women's self-determination. It must take precedence over the life of the unborn child. The liberation of women is of such importance and the ability to abort one's child is so central to that liberation that even the killing of unborn children based on their sex must be legitimated to serve this commitment. Women must have the right to kill any unborn child they do not want, even if the mother doesn't want that child because she's a girl.

This same underlying commitment is shared by all those who kill their unborn children. Regardless of why she is unwanted, an unwanted child is an unwanted child, and that's the end of it.

When we justify the murder of our little ones by talk of self-determination and our desires and goals being foiled by this baby in our womb, what does it really matter what those desires and goals are, so long as our ability to kill the child remains unimpeded? So, as to the sex-selective feticides of the East killing unborn baby girls particularly, the West has no reason to express concern or moral disapproval. Those in the West who declare that unwantedness of any sort justifies a mother killing her child have no basis to say the unwantedness of a child in the East is morally reprehensible. To each her own.

But really, did anyone anticipate the normalization of sex-selective abortion in India alone would result in 63 million sons unable to marry because their fathers and mothers murdered 63 million daughters?

### In Vitro Fertilization: Babies in the Fridge

A further consequence of the normalization of abortion is the growth of in vitro fertilization (IVF; literally, "fertilization in glass").[^28] This procedure removes eggs from a woman's ovaries to fertilize them with sperm outside the body in a laboratory dish.[^29] Normally, several eggs at a time are taken from the mother in order to fertilize them and have several children on hand from which to select the one or two who will be implanted in their mother's womb. Not every embryo will successfully attach himself to his mother's womb, so fertility clinic doctors make a habit of fertilizing several eggs at a time.[^30]

Those embryos not given the privilege of implantation in their mother's womb are cryogenically frozen and stored for usage later by their parents in another IVF cycle (if the child's sibling doesn't survive[^31] implantation), donated for scientific research (requiring the child's death), offered to another infertile couple, or simply destroyed.

Note here precisely what it is under discussion. IVF companies conceive image-bearers of God in a test tube, freeze them, make utilitarian calculations about how many babies they need, and so on.

In August 1989, world-renowned geneticist Jerome Lejeune testified in a Tennessee court concerning what he refers to as "little ones kept in the fridge." He opened up the ghoulish premises and procedures at the heart of the in vitro fertilization business. We quote extensively from Lejeune's testimony because of the close application of his testimony to those babies aborted at the same early stage of development through birth control. The human life that Dr. Lejeune testifies exists after conception is the same stage of embryonic life of those little ones prevented from attaching themselves to their mother's womb by IUDs and hormonal methods of birth control. Those babies imprisoned and killed by IVF procedures are the same age as those killed by IUDs and hormonal birth control.

The following is from Dr. Lejeune's court testimony:

> Each of us has a unique beginning, the moment of conception. . . . As soon as the program is written on the DNA, there are twenty-three different pieces of program carried by the spermatozoa and there are twenty-three different homologous pieces carried by the ovum. As soon as the twenty-three chromosomes carried by the sperm encounter the twenty-three chromosomes carried by the ovum, the whole information necessary and sufficient to spell out all the characteristics of the new being is gathered. . . .
> 
> . . . Now, I know that there has been recent discussion of vocabulary, and I was very surprised two years ago that some of our British colleagues invented the term of pre-embryo. That does not exist, it has never existed. I was curious, and I went to the encyclopedia, to the French encyclopedia, the one I inherited from my great father so it was fifty years ago it was printed.
> 
> And at the term of embryo it was said: "The youngest form of a being," which is very clear and simple definition, and it stated: "it starts as one fertilized cell, (fertilized egg, which is called also zygote), and when the zygote splits in two cells, it is called a two-cell embryo. When it split in four it is called a four-cell embryo." Then it's very interesting because this terminology was accepted the world over for more than fifty years by all the specialists of the world, and we had no need at all of a sub-class which would be called a pre-embryo, because there is nothing before the embryo. Before an embryo there is a sperm and an egg, and that is it. And the sperm and an egg cannot be a pre-embryo because you cannot tell what embryo it will be, because you don't know what the sperm will go in what an egg \[*sic*\], but once it is made, you have got a zygote and when it divides it's an embryo and that's it. . . .
> 
> If we stop the process, if we slow down the movement of the molecules, we progressively come to a relative standstill, and when the embryo is frozen, these tiny human beings, they are very small, one millimeter and a half of a dimension, a sphere a millimeter and a half, you can put them in canisters by the thousands. And then with the due connotation, the fact of putting inside a 19 \[degree\] very chilly space, tiny human beings who are deprived of any liberty, of any movement, even they are deprived of time, (time is frozen for them), make them surviving, so to speak, in a suspended time, in a concentration can. It's not as hospitable and prepared to \[give\] life as would be the secret temple which is inside the female body that is a womb which is by far much better equipped physiologically, chemically, and I would say intellectually than our best laboratories for the development of a new human being. . . .
> 
> . . . There is no, no difficulty to understand that at the very beginning of life, the genetic information and the molecular structure of the egg, the spirit and the matter, the soul and the body must be that tightly intricated because it's a beginning of the new marvel that we call a human.

In response to the question, "What ethical considerations do you have about freezing?" Dr. Lejeune responded:

> I think love is the contrary of chilly. Love is warmth, and life needs good temperature. So I would consider that the best we can do for early human beings is to have them in their normal shelter, not in the fridge.[^32]

It's natural to sympathize with those who desire to have children and are unable to do so naturally. In God's Word, there are a number of women who longed for children and mourned their empty wombs. In this connection, Scripture says repeatedly that it is God who opens and closes the womb.[^33] Yes, children are a gift from the Lord, but when God has closed the womb, is it right for those mourning their barren wombs to take matters into their own hands at the cost of most of their children conceived at IVF businesses being kept in a concentration can, or killed?[^34]

"You shall not murder" is true even if murdering will allow you, finally, to have a baby of your very own.

### Fetal Cell Lines: Cannibalization of Unborn Babies' Body Parts

A further consequence of the normalization of abortion is the global traffic in baby parts. This has been known and documented for a number of decades, although mostly in specialist literature. More recently, though, some of this trafficking has been brought to the attention of the broader population through the work of the Center for Medical Progress which received broad news coverage back in 2015 when they published videos of conversations they had with abortionists arranging the purchase of body parts from babies the abortionists had murdered. Then, more recently, because of Covid-19, there has been a surge in the discussion (limited mostly to Christians) of the use of fetal cell lines in the development and/or testing of vaccines.

Both appearances of public discussion of this horror received their fifteen minutes of attention, and were quickly gone. The roots of this horror go very deep, though, and those profiting from this business work to keep it hidden.

In 2015 *Nature* ran an article by Meredith Wadman titled "The Truth about Fetal Tissue Research," with the subheading, "The use of aborted fetal tissue has sparked controversy in the United States, but many scientists say it is essential for studies of HIV, development and more."[^35] Wadman explained the context for her article:

> An explosive climate has surrounded US research with fetal tissues since July, when an anti-abortion group called the Center for Medical Progress in Irvine, California, released covertly filmed videos in which senior physicians from the Planned Parenthood Federation of America bluntly and dispassionately discussed their harvesting of fetal organs from abortions for use in research.[^36]

The article began:

> Every month, Lishan Su receives a small test tube on ice from a company in California. In it is a piece of liver from a human fetus aborted at between 14 and 19 weeks of pregnancy.
> 
> Su and his staff at the University of North Carolina at Chapel Hill carefully grind the liver, centrifuge it and then extract and purify liver- and blood-forming stem cells. They inject the cells into the livers of newborn mice, and allow those mice to mature. The resulting animals are the only "humanized" mice with both functioning human liver and immune cells and, for Su, they are invaluable in his work on hepatitis B and C, allowing him to probe how the viruses evade the human immune system and cause chronic liver diseases.
> 
> "Using fetal tissue is not an easy choice, but so far there is no better choice," says Su, who has tried, and failed, to make a humanized mouse with other techniques. "Many, many biomedical researchers depend on fetal tissue research to really save human lives," he says. "And I think many of them feel the same way."[^37]

Medical research made great progress during the twentieth century, and the benefits have been remarkable. Yet the cost of this progress has often been the cannibalization of body parts of the unborn, as Wadman describes. Those opposing Covid vaccinations have described a part of this research to their constituents, explaining the development of these vaccines is dependent upon fetal cell lines largely derived from the bodies of babies killed through elective abortions. However, their explanations have been very limited concerning the origin, history, and present pervasive use of these cell lines.

Fetal cell lines go by esoteric names like HEK 293, WI-38, MRC-5, and Walvax-2. They are valued by scientists because of their ability to reproduce in great numbers while still being genetically and functionally normal, making them useful for a variety of purposes.[^38] They are developed from tissue---often the lungs---from aborted babies.

These cell lines have been under development since the 1960s, and the amount known about the aborted babies used to create them varies. Some of the babies whose tissue was used were aborted by the mother for psychological reasons. Other babies whose tissue was used were aborted for reasons that aren't known. It is possible some of these babies were not killed by elective, but rather spontaneous, abortions. Due to the research methodology, though, it's clear the vast majority of the babies died through elective abortions.[^39]

As mentioned above, it was the political ferment over Covid-19 vaccines that led to a discussion of these cell lines recently, largely among Christians. Vaccine development is one of the original-use cases for fetal cell lines. Rather than growing attenuated viruses in animal cells such as chicken eggs, it is beneficial that the environment these viruses replicate in is of human origin.[^40] This is nothing new, nor is it unique to Covid-19 vaccines.

The cell line called MRC-5 was developed in 1966 from the lung tissue of a 14-week-gestation male who was aborted for psychiatric reasons by a healthy 27-year-old mother.[^41] The MRC-5 cell line is broadly used for the production of vaccines used against diseases such as chickenpox, shingles, rabies, hepatitis A, and polio. A variety of other fetal cell lines have been used in the development of a variety of other vaccines, and such research is ongoing. For decades, without question or ethical opposition, Christians have used these vaccines for themselves and their children.

New cell lines continue to be created. One named Walvax-2, for example, was released in 2015 after four years of work. This cell line is an attempt to improve on other cell lines already in use for vaccine development in China. Walvax-2 "was derived from fetal lung tissue (similar to WI-38 and MRC-5) obtained from a 3-month old female fetus aborted because of the presence of a uterine scar from a previous Cesarean birth by a 27-year old healthy woman."[^42] Nine aborted children were used in the process, each carefully selected. Their parents gave what was purported to be a proper substitute for their baby's informed consent. The parents themselves had to be healthy and employed in careers that didn't involve any exposure to chemicals. The location of the abortion was prescribed so the "freshly aborted" body could be "immediately sent to the laboratory for the preparation of the cells."[^43] The method of abortion was also specified: in order to protect the baby's body from harm during the process of his birth, labor was to be induced by breaking the mother's water.

Given the emphasis on speed and freshness of tissue, it is not cynical to ask whether these babies were truly deceased before their lungs were removed from their bodies. If these babies were living while their tissue was taken, this would be consistent with many precedents documented in the pages of the literature of the fetal medical research industry.

Still, vaccine research and development is merely one small area of medical research and product development that depends upon the ongoing supply of tissue and body parts harvested from living little ones ripped from their mother's womb.

Alvin Wong, MD, describes the many uses of the fetal cell line HEK 293:

> The human embryonic kidney (HEK) 293 cell line is widely used in laboratory research. HEK 293 was derived from the kidney cells of a human embryo, as its name denotes. A student or fellow involved in life sciences research would almost inevitably encounter this cell line in the course of his work. A common use for it is in the field of gene therapy, where it is used to propagate adenovirus. Adenovirus is a common vehicle used to deliver experimental genes. There are also other derivatives of HEK 293 used in this field.[^44]

For several reasons, the fetal cell line HEK 293 is a special case. First, both researchers who developed this line have stated they have no knowledge whether the unborn baby they used died from a spontaneous or elective abortion.[^45] This might be the only cell line where this information is *not* known.

HEK 293 is also unique because it has been "immortalized," meaning the cells can keep undergoing division without losing their useful properties. This makes the cells less useful for vaccine development, but they are widely used in other categories of research. As Dr. Wong indicated, HEK 293 is so widely used it's unlikely any student or researcher can avoid it. But beyond students and researchers, it's practically impossible for the average person to avoid benefiting from HEK 293 research in his day-to-day life.

Christian, stop and think about this. If we're going to battle against abortion and its surrounding industries, we must count the cost. Certainly many will declare us enemies of women's dignity and value, but those involved in science will also denounce us, saying, "You're going to hinder medical research everyone benefits from, often in ways that protect human lives!" Are we prepared to respond, "Yes, our resolve is firm. It is more important to defend babies' lives than to defend the availability of their body parts for research and development, even if those body parts are used in the development of lifesaving procedures and products."

Can Christians really sustain one more accusation of being "against science"? Having delved deeply into the literature of this grisly practice and trade in fetal parts beyond the limited area of the development of cell lines, we assure readers we have avoided recording here the most awful acts imaginable committed against some of these little ones. These crimes have been documented for many decades now, even in the pages of our own US government publications,[^46] and we will not elaborate here other than to say the church has no excuse for how long our eyes have been blind. Pro-life is as pro-life does, and pro-lifers have only done what is obvious---what smacks us in the face and stays there mocking us.

The recent popular exercise of Christian conscience in opposing the relationship of abortion to fetal cell lines has been selective. Covid vaccines were fortuitous in allowing some to raise the issue of the cannibalization of our unborn children's bodies for Covid vaccines specifically, but this present awakening appears to have been quite limited in its scope. It has not matured into any parallel awakening of Christian conscience in the abuses of unborn children's bodies (not related to cell lines) which are ubiquitous in the developed world and have been for decades.

Many opposed Covid vaccinations, saying, "Fetal cells have been used to develop and test these vaccines, and I'll have no part of it." This led to the assumption that Covid vaccines were unusual in this regard, representing a new tyranny extending into our lives by requiring this participation in abortion's bloodshed.

Now, though, we have presented a larger picture demonstrating that Covid vaccines are a small aspect of medical and corporate scientific dependence on the body parts of aborted babies. Whether we know or admit it, we participate.

In retrospect, the internal logic of the thing is inevitable. With the slaughter of babies in the billions, why not salvage some value by utilizing body parts as the little one's non-consensual donations to the well-being of the larger human community? As some medical ethicists might put it, "Do these little ones not have a duty to contribute their own legacy to our social contract? Ought we not to assume they would affirm their own moral obligation to make some small contribution to the lives of others?"[^47]

During the half century that has passed since *Roe v. Wade*, God's people have learned the intense difficulty of reversing this bloody decision. It has been a long, hard political battle with almost none of us anticipating this late victory recently gained here in 2022.

Yet now, with the reversal of *Roe v. Wade*, we come to recognize the relative insignificance of this reversal for the protection of our little ones. It seems likely the majority of abortions will continue unabated as chemical abortions in the first weeks and days of life predominate. Thus, faced with the now-present reality of a post-*Roe* world, we have died to the previously widely held conviction that *Roe v. Wade*'s reversal would restore protection under the rule of law to preborn babies. This conviction has proved to be as illusory as any parallel hope that the reversal of *Roe v. Wade* would also bring an end to the trafficking in body parts on which modern medical research is dependent.

The genocide of the preborn has become so integral to Western society that it's hard to conceptualize a path forward that would provide any substantive hope of bringing it to an end. Across the developed world, society has become dependent upon the systematic extinction of all preborn life judged to be inconvenient. Add to this our medical-industrial complex's dependence on the bodies of this holocaust's victims for many of the raw materials needed for their research and development, and the near impossibility of restoring the protection of every child's right to life, liberty, and the pursuit of happiness from the moment of conception becomes clear.

Repentance and reform are always difficult, though, and we must confess publicly that this world was created by the God who is truth, and truth is its own justification.

Now then, to make any claim to democracy is to make a parallel claim to the value of each individual. Do each of these little ones robbed of life while nestled safely in the body of their mother not have a right to be born, to live, to work, to study, to play, to laugh, to cry, to marry, to have their own children; and as they die, to leave an inheritance to their grandchildren?

Yet here we are, the Great American Empire spreading democracy around the world while robbing these little ones of every one of their human rights. The little ones don't even get a vote on the use of their leftover body parts by medical science and product development.

All of the ghoulish trafficking and research happen behind laboratories' closed doors, so it's easy for us to claim ignorance, trotting out a modicum of knowledge only when it is useful politically, to further some other more expedient end. Are we wrong, then, to force the church to see the extent of this horror? Would it not be better to allow our brothers and sisters in Christ to continue to live in ignorance, or at least plausible deniability?

Surely not. It is the duty of God's servants to tell the whole bloody truth. Until we see this truth, we will never know what is being done to our little neighbors, and our love will never extend to these particular "least of these" of our Lord. The traders in the body parts of preborn babies might think they're getting away with it---and humanly speaking they are. But across Scripture, God speaks the same truths He spoke to the prophet Ezekiel:

> The iniquity of the house of Israel and Judah is very, very great, and the land is filled with blood and the city is full of perversion; for they say, "The [Lord]{.smallcaps} has forsaken the land, and the [Lord]{.smallcaps} does not see!" But as for Me, My eye will have no pity nor will I spare, but I will bring their conduct upon their heads. (Ezek. 9:9--10)

The bloodshed associated simply with researchers' constant need for fetal body parts runs so deep, and is so pervasive, that readers may wish us to be specific in our guidance here, providing particular steps we should take to begin to oppose it. But here, we think it best to refrain from doing so.

Remember, fetal research encompasses a very broad sphere of scientific investigation involving far more than the development of cell lines. Keep in mind also that in this more encompassing area we are referring to as "fetal research," the church at large is very limited in its understanding. As God's people are taught and grow in our knowledge of this evil, consciences will be awakened to the multifaceted nature of this thorny issue and choose this or that method of defending these lives too. Likely there will be those who decide they will not allow any vaccinations in their family, whether for children or adults, whether for diseases similar to polio or to this year's flu. Others will decide to work toward the growth of scientific research that displaces the continued need for dependence on present cell lines for valuable testing and research. Many voices will produce a variety of places of conscience and witness, as God leads each of us.

But wherever this or that person or congregation chooses to stand, every effort must be taken to avoid making that standing place a test of orthodoxy or Christian faith. We must avoid such division and schism. Where one conscience has been awakened and pricked on such matters, there is also the potential for judging another conscience that does not share that person's precise convictions. And of course, we know that every man thinks every other man should share his convictions, so on an issue with such weight as the bodies of little babies, the possibility of censoriousness is great.

The firestorm in the church over Covid has recently shown the great potential for schism over secondary and tertiary matters, but it has also shown that a variety of Christian responses can be within the bounds of Scripture and according to godly principles.[^48] For example, on the question of vaccines and fetal research, Cardinal Ratzinger's letter on the use of vaccines prepared from cells derived from aborted babies shows but one way of approaching the topic in a careful and Christian way.[^49] Other such evaluations could and should be written, and it is our hope that God through His Spirit grants the church an increasing knowledge and wisdom on how to address these matters with courage, wisdom, and unity.

## The Church's Response to Abortion

Back in the fifties when what was called "birth control" was first normalized in conjunction with the change of definition of "conception" and "life," this change in definitions had the inevitable result of allowing abortion to throw off its guilt and shame. Christians and pagans together grew used to employing birth control technology to prevent children so that, as surgical abortions came forward and began to increase in frequency, Christians were desensitized. The horror of doctors taking money to cut apart and remove infants from their mother's womb didn't register among the people whose practice of birth control depended upon conception not being conception and life not being life.

As pointed out earlier, the explosion of surgical abortions preceded 1973's *Roe v. Wade* decision. Nevertheless, *Roe v. Wade* threw the door open in a way the previous laws of the fifty states had not done.

### Protestants and Whatever Happened to the Human Race?

How did the church respond to *Roe v. Wade*?

Roman Catholics didn't waver in their longstanding, historical opposition to contraception and abortion, but Protestants---including Evangelicals---simply accepted *Roe v. Wade* as the law of the land. The Supreme Court was the standing civil authority and Evangelicals believed God required them to honor this Supreme Court ruling.

Undoubtedly some readers survey the contemporary disrespect for authority, and particularly the opposition to surgical abortion which is now so characteristic of conservative Protestant churches in North America, and have trouble believing the same disrespect and opposition to the Supreme Court's *Roe v. Wade* ruling was not present in 1973 and years following.

In the wake of *Roe v. Wade*, it's a tragic fact that Evangelicals were silent and compliant. This can be demonstrated in many ways, but the most obvious way is the national barnstorming tour of C. Everett Koop and Francis Schaeffer showing their films and giving lectures based on their jointly authored book *Whatever Happened to the Human Race?*

It wasn't until 1979 that Koop and Schaeffer toured the country's major cities calling attendees to wake up to the horrors of surgical abortions, and their attendees were exclusively Evangelicals. At the time, Koop (later to become surgeon general under President Reagan) and Schaeffer complained to their Denver audience[^50] that they had contacted fifteen or so Evangelical leaders in Wheaton, inviting them to attend their Chicago series, but none of them had been willing to come. This, they explained, was one more proof of the lack of concern over abortion on the part of Evangelicals, and particularly Evangelical leaders.

Nevertheless, Koop and Schaeffer were respected within Evangelicalism's rank and file, and their prophetic witness of 1979 single-handedly woke Evangelicalism up so that conservative Protestant Christians still today view opposition to abortion as a fundamental part of Christian ethics.[^51] Since 1979, therefore, pro-life commitments have been a fundamental component of Christian political witness and action.

But notice that *Roe v. Wade* was issued in 1973, and Koop and Schaeffer did not publish their book and give their lectures until 1979---six years later.

### Pro-Life Protestants and the Growth of Chemical Abortions

It is God's kindness that the conservative Protestant church has mostly been firm in her opposition to abortion since 1979, but that opposition has been focused almost exclusively on surgical abortion. More recently, there has been some opposition to later chemical abortions that are committed up until the tenth week of pregnancy by means of the drugs mifepristone (RU-486) and misoprostol, but the pro-life commitments and witness which grew out of Koop and Schaeffer's witness never matured into opposition to abortifacient birth control methods not involving surgery or mifepristone and misoprostol.

Even as we write, IUDs and hormonal birth control methods like the Pill continue to be widely used by conservative Protestants who consider themselves pro-life. Most of them remain oblivious to the abortifacient nature of their hormonal methods and IUDs.

Meanwhile, surgical abortions are in decline and chemical abortions have taken over.

In 2019, one medical journal co-sponsored by The Faculty of Sexual & Reproductive Healthcare of the Royal College of Obstetricians & Gynaecologists estimated "medication (or medical) abortion accounts for at least half of all abortions in the majority of countries."[^52] Again, keep in mind that this estimate excludes the abortion of little ones by birth control methods that have an agency preventing the child's implantation in his mother's womb. When the Royal College's obstetricians and gynecologists speak of "medication abortions," they are only referring to later abortions committed by means of the drugs mifepristone and misoprostol up through ten weeks of gestation.

Remember that the scientific and medical communities redefined "conception" and "life" in order to normalize the mid-century birth control pill known to have an abortifacient agency. Largely by means of these redefinitions almost sixty years ago, the word "abortion" has never been associated with the Pill, the IUD, or any other hormonal birth control.

Within the broader pro-life community, there has been some opposition to later-term mifepristone and misoprostol abortions. Some have recognized the peculiar danger of these drugs due to the perception that they are a kinder, gentler way of killing than scalpels and suction machines. But what about the abortifacient agency of IUDs and hormonal drugs and devices? Shouldn't our pro-life witness be consistent?

The child conceived by his father's fertilization of his mother's egg takes six or seven days to wend his way to his mother's uterus and attach himself to her uterine wall. Rightly understood, chemical abortions are not just mifepristone and misoprostol given later in pregnancy, but they include IUDs and drugs that obstruct the child's attachment to the wall of the uterus, denying him the nurture and protection of his mother's womb.

Note carefully: the deaths of children caused by IUDs, by early birth control methods with a hormonal component, by later birth control methods utilizing mifepristone and misoprostol, and by surgical abortions all break the Sixth Commandment. But all these killings are not equally visible and felt.

The blood, body parts, and shame of surgical abortions are hard to hide, but it's easy to hide the tiny little ones killed by IUDs and the Pill. Thus with surgical abortion's decline, the emotional and spiritual toll of abortion has grown increasingly hidden.

Unlike the death-camp victims of World War II, aborted babies who are also the victims of genocide have not been liberated, and their pictures have not been taken. No holocaust museum recounts their chemical tortures and deaths. As abortions continue to move toward the first weeks of pregnancy and the chemical removal of the child, it will become ever more difficult to see and oppose this bloodletting. Mothers will hide their murders at home, inside their wombs, and this secrecy will make it exceedingly difficult to protect the little victims in any court of law.

Nevertheless, God sees these murders, and all the blood will be brought to His bar of justice. It will not remain hidden:

They even sacrificed their sons and their daughters to the demons,

And shed innocent blood,

The blood of their sons and their daughters,

Whom they sacrificed to the idols of Canaan;

And the land was polluted with the blood.

Thus they became unclean in their practices,

And played the harlot in their deeds.

Therefore the anger of the [Lord]{.smallcaps} was kindled against His people . . .

(Ps. 106:37--40)

## The Truth about Hormonal Birth Control

To come to some awareness of the scale of this bloodshed, we must reckon with the many abortions caused specifically by IUDs and hormonal birth control. This is a very difficult question for many Christians today. How can the default birth control methods used by Christians within the church for the past seventy years be called into question? Surely the medical establishment (and particularly Christians who are a part of that establishment) would have warned us if their birth control methods were aborting our children, right? Is the goal here simply to condemn all forms of birth control? Are the authors of this document Roman Catholic?

Good questions, and no, your authors are not condemning all use of birth control. Although we believe most practices of birth control today are not morally justified, there are occasions where pregnancy prevention is justified, and in such cases there are methods of pregnancy prevention which are truly and only pregnancy prevention---that is, which are truly contraceptive. Which is to say, there are methods of preventing pregnancy that prevent conception rather than preventing implantation. There are methods of pregnancy prevention that do not have any abortifacient agency and do not kill children. Sadly, these methods do not include some of the most common methods of birth control used today.

### IUDs, the Pill, and the Prevention of Implantation

Among the 61 percent of women in the United States between the ages of 15 and 49 using some method of pregnancy prevention in 2019, close to half (27 percent of the same demographic) employed methods with an abortifacient agency.[^53] IUDs and all hormonal birth control methods include a significant agency of preventing a very young child from attaching himself to the wall of the uterus. For a few days the little one lives, but then he is denied the nurture and protection of his mother's womb, and this kills him.

The official and scientific sources confirming this are endless, and have been for generations. For this reason scientific and medical authorities changed the definition of conception in the 1960s, as documented above.

This subterfuge enabled them to declare that IUDs and hormonal birth control methods are *absolutely not* abortifacients. This subterfuge enabled our obstetricians and gynecologists also to redefine the beginning of life as implantation---not fertilization. Because of this deception, these forms of birth control have been embraced by an unknowing public for nearly sixty years now. And through these years, our obstetricians, gynecologists, and pharmacists, Christian and pagan alike, have been assuring us there's no danger of the products they prescribe killing our little ones.

The project is larger than denying these little ones are living human beings. This denial requires a prior denial that IUDs and hormonal methods of birth control have any agency at all of preventing implantation. Christians and pagans have thus become allies, joining together in opposing and obstructing woman's wonderful nature decreed by God as "the mother of the living" and "life-giver."[^54]

Some would claim it doesn't really matter if a woman's method of birth control prevents the little one from attaching himself to his mother's womb so long as the prevention of implantation is not the primary agency of the mother's choice of birth control. The risk is small and neither her doctor nor her pharmacist are selling her drugs with the intent to kill her babies. Their intent is simply to help their client interrupt her normal cycle; or, failing that, to help the woman's body to attack her husband's sperm so it is unable to fertilize any egg that happens to make it down her fallopian tubes. They go on to point out that all of life has risks, and this risk of killing the little one is reasonable given the large benefit of preventing the birth of another "unwanted child," or a child who would harm the chances of his siblings going to college.

Thus what Hannah Arendt referred to as the banality of evil[^55] continues into the twenty-first century, although Jews and "useless eaters" are no longer the intended victims. Lately, the victims are our own sons and daughters. If, over the course of twenty or thirty years of fertility, killing a few of her children is the cost of one mother limiting her painful pregnancies and childbirth, and minimizing the burden of raising a child to adulthood---it's a small price to pay for such a significant relief.

Of course, it's neither the mother nor her husband paying any price, but rather their dead sons and daughters. It cost these little ones their lives. They didn't live a life of slavery. They were murdered in the womb before they saw the light of day or took a breath.

It would be preferable not to have to discuss the pragmatic and callous rationalizations Christians employ to justify their murder of their unborn children, but such rationalizations are common within the church. Men and women today style themselves sensitive to the suffering of others, but unborn children haven't made the cut. Christian men and women assure one another that compassion is their highest commitment, but let's look carefully at this fruit of our compassion.

We sympathize with sisters in Christ fearful of being overwhelmed by scads of children. We sympathize with Christian mothers of a certain age fearful of giving birth to a child with a genetic defect. We sympathize with Christian mothers who are tired of being pregnant and want to "get on with life." We sympathize with Christian mothers who want to defer having their own biological children so they can adopt others' unwanted children. We sympathize with women who suffer debilitating pain from conditions, such as endometriosis, whose doctors prescribe the Pill to relieve that pain. We sympathize with Christian mothers who give all these reasons for using abortifacient methods of birth control.

Of course, all of us should have and express sympathy in such situations, but that sympathy must issue from a compassion that is true, not false. How do we recognize false sympathy and compassion?

False compassion has no patience for truth. It brushes it aside. Concerning conception and the life of the preborn, false compassion expresses sympathy to the mother who is visible while leaving the child who is not present alone in his vulnerability, invisibility, and silence.

Having compassion is godly, but only if that compassion is godly, which necessarily means only if that compassion is truthful. Yes, we are called by God to have compassion on women bearing these burdens and having such a desire, but that compassion must always be expressed to the mother for both her life and the lives of her babies. In our day of cheap sentiments spread through social media by emoticons, Christians should balk at the whole mess, understanding how costly true compassion is, and having the unerring ability to see where it needs to be defended.

Flannery O'Connor, that great southern author who had such an unerring instinct for the ways original sin twists our lives, compared the tenderness of past ages to the tenderness of our own age:

. . . now, we govern by tenderness. It is a tenderness which, long since cut off from the person of Christ, is wrapped in theory. When tenderness is detached from the source of tenderness, its logical outcome is terror. It ends in forced-labor camps and in the fumes of the gas chamber.[^56]

Our tender sympathies have borne the fruit of infant slaughter. We must face it.

Princeton ethicist Paul Ramsey pointed out that a deer hunter is guilty of manslaughter if he finds himself wondering what that movement is in the underbrush, but goes ahead and pulls the trigger, and kills a man. The law requires the hunter to wait to shoot until he's established his target is not a man. Man is the most precious of all God's creatures,[^57] and thus it is a criminal act to take unnecessary risks of shedding his blood. He alone bears God's image and likeness. Even a minute or two old, he is known and precious in God's sight.

In light of this basic moral principle, we stop and consider the fact that hormonal methods of birth control have an agency of preventing the little one from availing himself of the nurture and protection of his mother's womb. This fact is scientifically incontrovertible. Over the years, there have been some Christians who have tried to deny it, but the testimony of secular scholars, physicians, and pharmaceutical firms is nearly unanimous: IUDs and hormonal methods of birth control have an undeniable abortifacient agency.[^58]

Taking hormonal methods, specifically, the simplest search of the web returns page after page from pharmaceutical firms, non-profits working to limit world population, and healthcare information sites, all matter-of-factly stating their agency of preventing implantation. Such statements vary in terminology, but here are typical examples.

Here is an excerpt from an article on the website of the National Center for Biotechnology Information of the National Institutes of Health:

The hormones in contraceptives don't only prevent ovulation. Some also prevent fertilized eggs from implanting into the womb.[^59]

The American Society for Reproductive Medicine publishes ReproductiveFacts.org, where they ask the question, "How do hormonal contraceptives work?" Here is their answer:

Hormonal contraceptives contain a progestin (progesterone medicine) with or without an estrogen. . . . These two hormones together, or the progestin alone, work in several ways to prevent a pregnancy:

-   They can prevent ovulation (the release of an egg).

-   They make the mucus around the cervix (mouth of the womb) thicker so that sperm cannot enter the uterus (womb).

-   They make the lining of the uterus (womb) thinner to prevent a fertilized egg from attaching itself.[^60]

The following is from the University of Michigan Health website:[^61]

+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Method**                | **How it prevents pregnancy**                                                                                                              |
+===========================+============================================================================================================================================+
| Hormonal                  | -   Prevents ovulation                                                                                                                     |
|                           |                                                                                                                                            |
|                           | -   Thickens mucus at the cervix so sperm cannot pass through                                                                              |
|                           |                                                                                                                                            |
|                           | -   Changes the environment of the uterus and fallopian tubes to prevent fertilization and to prevent implantation if fertilization occurs |
+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Intrauterine device (IUD) | -   There are two types of IUDs (hormonal and copper). Both types may work by preventing:                                                  |
|                           |                                                                                                                                            |
|                           |     -   Fertilization of the egg.                                                                                                          |
|                           |                                                                                                                                            |
|                           |     -   Implantation in the uterus.                                                                                                        |
+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+

Similar documentation is spread across the web. One prominent example is an online course in human embryology developed by the prestigious Swiss universities of Fribourg, Lausanne, and Bern. In their module 6.5, we read:

Contraception can take place on three different levels: preventing oocytes from meeting sperm cells, hindering ovulation, \[or\] hindering fertilization or the implantation of the fertilized oocyte.[^62]

The embryology course's supplementary link goes on to specify this concerning hormonal birth control:

They transform the uterine endometrium so it becomes pseudoatrophic, thereby making an implantation practically impossible, should an ovulation and fertilization take place.[^63]

They describe the *primary* abortifacient agency of the IUD:

With an intra-uterine device (IUD) a double function is involved: firstly, implantation is hindered and, secondly, sperm cells are immobilized.

Some researchers are working to prove this abortifacient agency of the IUD is minor or absent, as shown by a recent (2020) study published in *Nature*'s *Scientific Reports*.[^64] Relias Media cites one of the study's authors, Karen Smith-McCune:

We always assumed, from the 1980s on, that the IUD was preventing implantation, but that's never been proven.[^65]

Consider carefully this long-held assumption. It was the cover for governmental, scientific, and medical authorities to promote, prescribe, sell, and insert IUDs for decades, all the while knowing their IUDs were abortifacients.

Smith-McCune goes on to report her study found hormone-releasing IUDs indeed caused inflammation of the uterine wall, but copper-releasing IUDs did not. From this Smith-McCune concludes copper-releasing IUDs do not prevent implantation. Her conclusion, however, is logically wrong; copper-releasing IUDs might have other effects preventing implantation consistent with the traditional assumption. The authors indirectly admit the weakness of their conclusion, calling it a "suggestion." In a matter of life and death, why would serious researchers content themselves with suggestions? Smith-McCune seeks to answer that question:

I think the results present a counterargument to resistance to the IUD. Policymakers who are resistant to IUD use can take our data as evidence that strongly suggests it is not preventing implantation.

Note in her statement the distinction between hormonal and copper-releasing IUDs has conveniently disappeared. Moreover, note this is not science. The study is catering to political interests intent on breaking down political resistance against the use of IUDs based on moral grounds.

Furthermore, Smith-McCune's suggestion cannot account for the fact that IUDs, whether copper or hormonal, are over 99 percent effective as "emergency contraception" for up to five days after intercourse, just like the morning-after pill.[^66]

Now then, once more: What follower of Jesus Christ is satisfied with assurances that his chances of killing his child are small, with suggestions that some IUDs might work differently than others? Remember that all he and his wife must do to avoid killing their child is refuse to use the IUD and other hormonal forms of birth control.

It's understandable for worldlings to be dismissive of such violations of the Sixth Commandment, but Christians? Have we forgotten the warning of the Apostle John concerning "murderers," that they "will be in the lake that burns with fire and brimstone, which is the second death" (Rev. 21:8)? Is God's commandment, "Whoever sheds man's blood, by man his blood shall be shed" (Gen. 9:6), limited to babies we allow to be born? Babies we allow to attach themselves to their mother's womb?

Those who hate God and His moral law are unconcerned about such matters, but are we not God's people? Have we not heard His warnings that He hates those who shed the blood of innocents? Are babies anyone's enemies? Do we not welcome and rejoice in His precious gift of life? Do we not join our forefathers in giving Him praise and thanks for opening the womb of our mothers and wives?

### The Significance of Our Lord's Incarnation

One of the most beautiful things about recovering the personhood of the embryo created by God and only a couple days old is that we recover the beauty and wonder of the incarnation of our Lord Jesus. When we sing, "Lo, He abhors not the Virgin's womb,"[^67] our thoughts naturally turn to a visible baby bump and Jesus residing there with blessed Mary resting her hands on her womb, radiating her love to the Son of God. Which is to say, who thinks of our Lord's incarnation when it was but a day or two old?

The King of Glory through whom the stars were formed, and the earth holds together yet today, dignified the embryonic life of each of us by living that life Himself. This is amazing and must surely instruct us concerning reverence due the embryonic life He still creates and places in woman, the life-giver. We may callously dismiss this life, but we do so forgetting the Son of Man was Himself a mere second old, and was that very second fully Man and fully God. Would we dare to deny His Personhood the millisecond after the Holy Spirit came upon Mary and she became pregnant with the Savior of the world? And if we would not deny His Personhood at that moment, why would we deny any baby's personhood whom Jesus Himself brothered by His own conception?

Theologian Thomas F. Torrance writes:

The Son of God became a human being for us in the womb of the Virgin Mary, bone of our bone and flesh of our flesh. He became what we are. Think of the importance of the incarnation, then, for our understanding of and regard for the unborn child. Every child in the womb has been brothered by the Lord Jesus. In becoming a human being for us, he also became an embryo for the sake of all embryos, and for our Christian understanding of the being, nature and status in God's eyes of the unborn child. So, to take no thought, or no proper thought, for the unborn child is to have no proper thought of Jesus himself as our Lord and Savior or to appreciate his relation as the incarnate Creator to every human being.[^68]

Consider this account written by the physician Luke, found in the first chapter of his gospel. There we read that the angel Gabriel told the Virgin Mary:

Do not be afraid, Mary; for you have found favor with God. And behold, you will conceive in your womb and bear a son, and you shall name Him Jesus.

The angel tells Mary, "you will conceive in your womb." She hasn't yet conceived, but at some point in the future, she "will."

Mary asked how this could be, since she was a virgin. The angel explained:

The Holy Spirit will come upon you, and the power of the Most High will overshadow you; and for that reason the holy Child shall be called the Son of God.

At some point in the future, the Holy Spirit "will come upon" her, and "the power of the Most High will overshadow" her. Again, at some point in the future these things "will" be accomplished. It's as certain as every word of God, but its accomplishment is not yet. The holy Child "shall" be called.

Jesus will be fully man, but is not yet. The prophecy has been given, but it has not yet been fulfilled. His taking on manhood through His conception is still in the future.

Then Gabriel strengthens Mary's faith:

And behold, even your relative Elizabeth has also conceived a son in her old age; and she who was called barren is now in her sixth month. For nothing will be impossible with God.

After this shocking announcement that her relative Elizabeth has miraculously conceived and is in her sixth month, we read Mary declaring her submission to God's will, after which the angel Gabriel leaves her.

Then what?

Now at this time Mary arose and went in a hurry to the hill country, to a city of Judah, and entered the house of Zacharias and greeted Elizabeth.

We aren't told where Elizabeth and her husband Zacharias lived---only that it was a city of Judah in "the hill country." We're also told as soon as the angel left her, Mary arose and "went in a hurry" there. When did the Holy Spirit come upon her, and the power of the Most High overshadow her, so that the embryonic Savior indwelt her? Sometime between Gabriel's announcement that she would (future tense) become pregnant and her arrival and entry to Elizabeth's house there in the hill country. How do we know she was pregnant when she arrived?

Because of this account of her arrival, also by the beloved physician Luke:

When Elizabeth heard Mary's greeting, the baby leaped in her womb; and Elizabeth was filled with the Holy Spirit. And she cried out with a loud voice and said, "Blessed are you among women, and blessed is the fruit of your womb! And how has it happened to me, that the mother of my Lord would come to me? For behold, when the sound of your greeting reached my ears, the baby leaped in my womb for joy."[^69]

There it is: "blessed is the fruit of your womb!" Mary is now pregnant. She is now bearing fruit. She is now "the mother" of our Lord.

How old is our Lord at this moment?

Our best guess is somewhere around a week of age. We're not sure Mary left to visit Elizabeth the same day she received the prophecy. She may have left a day or two later. What we do know is that as the angel Gabriel left her, it was "at this time" that she "arose" and "went in a hurry." Various guesses are made about the town Mary traveled to and its distance. If we accept church tradition, the village was Ein Karem, about eighty miles from Nazareth, so it took Mary about a week to get there.

If our Lord took up His embryonic residence in Mary's womb immediately upon Gabriel's departure, right as Mary began hurrying to Elizabeth's home, Jesus was likely somewhere between seven and ten days old. If Mary conceived our Lord halfway through her journey, Jesus was likely somewhere between three and seven days old.

Stop and consider that little ones normally take five or six days to implant themselves on the wall of their mother's uterus. It's possible then, and maybe even likely, that as His mother traveled, Jesus did also, moving towards the rest, safety, and nourishment of attachment to Mary's womb.

Jesus brothered us at conception. Not any time later. Not at implantation. Not at quickening. Not at birth. His conception, no less than His implantation, quickening, and birth, redeemed our own conception, no less than our own implantation, quickening, and birth.

There is no place for the follower of Jesus Christ to kill any human being at any stage of life which He, our Lord Jesus, blessed by living it with and for us. No Christian kills an embryo any more than he or she kills a newborn baby with Down syndrome or an elderly parent who's had a stroke.

We protect the weak and vulnerable. We do not kill them.

## The Body Count

Coming face to face with the lies and bloodshed, we can't help seeking to quantify the slaughter around us. What is a truthful estimate of the number of little ones we have sacrificed through abortion since the 1950s and '60s?

As Christians and pro-lifers in general have tried to come to terms with the slaughter of the twentieth and twenty-first centuries, it's become commonplace to speak in terms of large figures that boggle the mind, but even the most informed pro-lifers today speak only of "millions" of babies lost. Anything larger seems needlessly inflammatory, and "billions"? Surely not . . .

Let's take a count of the victims of our bloodshed.

### Surgical and Chemical Abortions

Back in 1999, Planned Parenthood's research arm, the Guttmacher Institute, published "The Incidence of Abortion Worldwide," in which they stated, "Worldwide, about one-fourth of the approximately 180 million pregnancies known to occur each year are resolved by abortion."[^70] At the time, this would have been 0.75 percent of the world's population killed each year, but this was decades ago.

Acknowledging the growth of abortions worldwide across the past twenty years, a 2020 article in *The Lancet* estimated that between 2015 and 2019 the yearly average of abortion victims had increased to 73 million---0.98 percent of the world's population.[^71] At this rate, it takes thirteen and a half years to reach a billion. Meanwhile, keep in mind that abortions have been common in Russia and Eastern Europe since the early fifties, and the United States since the seventies.

China is unique due to their longtime enforcement of population control. From 1980 through 2016, the Chinese government worked to reduce their nation's birth rate by limiting most married couples to one child.[^72] They enforced this policy by forcibly aborting mothers' babies[^73] so that, from the adoption of China's one-child policy in 1980 through the government's repeal of the policy on January 1, 2016,[^74] China's Health Ministry revealed it had done 336 million abortions.[^75] During those years alone, China committed one-third of a billion abortions.

From statistics compiled over the years, the Guttmacher Institute now places the number of babies murdered at 1.6 billion (and no, they don't call it "murder"). Yet if we examine this abortion count more deeply, it becomes clear the Guttmacher Institute's numbers are still drastically underreported.

### Accounting for Hormonal Birth Control and IUDs

Recall how prevalent hormonal birth control methods are across the world and that one of their agencies is preventing implantation. How many deaths of little ones due to this agency of hormonal methods have occurred in the world since 1950? Let us consider all hormonal methods including pills, injectables, implants, IUDs, and emergency contraceptive pills (ECPs).

To enforce its one-child policy, not only has China engaged in forced abortion, but government authorities have implanted IUDs in their nation's women so that, as the *New York Times* reports, "from 1980 to 2014, according to official statistics, 324 million Chinese women were fitted with IUDs."[^76] Those 324 million IUDs prevented countless births by obstructing little ones from attaching themselves to their mother's womb. What was the death toll in China?

But beyond China and IUDs, recall how prevalent hormonal birth control methods are across the world. Can we estimate how many women lost their babies through these birth control methods since their normalization in the 1960s?

Because current and hard data is not available on these questions, we must take recourse to some estimates to get an idea of the order of magnitude we should think about. Let's start with the Pill. In 1999, Dr. William F. Colliton reported data from the Guttmacher Institute indicating that 10.4 million women were using the Pill in the US.[^77] Based on 28-day cycles and a 14 percent chance of an ovulation occurring for women taking the Pill, this would imply 18.95 million exposures to pregnancy per year. Taking into account the likelihood of spontaneous abortions, Dr. Colliton estimated that the number of abortions induced by the Pill making the womb less hospitable for fertilized eggs to between 1.1 million and 1.9 million per year. He also reported a more cautious estimate based on a 20 percent fecundity rate that put the number of Pill-induced abortions to between 0.1 million and 1.6 million per year.

More recent CDC data indicate that currently about 10.2 million women in the US take the Pill.[^78] Based on a pregnancy rate of 85 percent for women using no birth control and 9 percent for women using the Pill, 76 percent of these 10.2 million, or 7.7 million would have become pregnant in a given year had they not used the Pill nor any other birth control method.[^79] Given that the Pill reduces the frequency of ovulation by 57.4 percent to 98.75 percent,[^80] the loss of births due to the reduction of ovulation frequency would be between 4.4 million and 7.6 million. If the remaining losses of births are caused by the abortifacient effect of the Pill, the number of induced abortions would be between 0.97 million and 3.3 million. This corresponds to between 0.0095 and 0.33 Pill-induced abortions per woman taking the Pill every year. This means that a woman using the Pill runs the risk of unknowingly killing one of her children between once in three years and once in one hundred years.

According to United Nations data, 152.1 million women of childbearing age around the world were taking the Pill in 2018.[^81] Applying the US estimate, the number of Pill-induced abortions would range between 1.4 million and 50.2 million annually. We emphasize again that these are rough estimates only. But they clearly show us that we are looking at a large phenomenon. Keep in mind that we are here talking only about the Pill. We have not included other hormone-based birth control methods such as injectables, implants, and IUDs which, in 2019, the UN estimated at 10 percent of the 60 percent of women of childbearing age employing "any method" of birth control. Nor does this estimate include ECPs (morning-after pills).[^82]

Considering all IUDs (inert, copper, and hormonal), each has post-fertilization effects preventing pregnancies.[^83] These work by preventing the fertilized egg access to the endometrium, prohibiting the little one's attachment there. Stanford and Micolajczyk estimate that the post-fertilization effects of inert IUDs inhibit implantation in 99.1 percent of all cases of fertilized eggs. For copper and hormonal IUDs their estimates vary between 99.1 percent to 99.5 percent and 99.8 percent to 99.95 percent, respectively. Thus the post-fertilization effects are very powerful, and they must be, given the relatively large rate of fertilizations per cycle (15.6 percent for inert IUDs, 4.1 percent to 8.1 percent for copper IUDs, and 14 percent for hormonal IUDs) on the one hand, and the low rate of pregnancies of women wearing IUDs on the other. The authors estimate that 0.72 to 1.97 fertilized eggs fail to implant per woman wearing inert IUDs per year. For copper and hormonal IUDs, the corresponding numbers are 0.19 to 1.04 and 0.19 to 1.82, respectively. That is, women wearing copper IUDs are likely to effectively abort a child between once a year and once every five years. Women wearing hormonal IUDs are likely to abort a child between every 6.6 months and every five years.

According to UN data released in 2019, 8.3 percent of the 74.7 million women of childbearing age in the US (6.2 million women) were using IUDs of some kind.[^84] Taking the above numbers, the implied annual loss of fertilized eggs (little ones bearing the image of God) due to the post-fertilization effects of IUDs in the United States alone would be between 1.18 million (if all IUDs were copper and the low estimate prevails) and 12.2 million (if all IUDs were inert and the high estimate prevails).

Let us reiterate that these estimates are the number of lives lost in the US each year merely from the abortifacient agency of IUDs, and that no estimates of the death toll from prevention of implantation after conception are ever included in any organization's reports of numbers of abortions. Their statistics are only the number of babies killed after those babies have survived through implantation.

### Accounting for In Vitro Fertilization

Now consider the death toll from IVF.[^85] Here, the true cost of human life in this process is again hidden by definitions of conception and the use of medical jargon, but the Human Fertilisation & Embryology Authority (HFEA), an organization in the United Kingdom that is responsible for regulating the practice of IVF throughout the UK, reported to Parliament that from August 1, 1991, to December 31, 2011, 3,546,818 embryos were created. Of these, 1,714,570 were "discarded," i.e., thrown away like trash (whether because they died in the lab, or for reasons of quality, or for reasons of eugenics, the report does not say). Meanwhile, 5,876 embryos were frozen with the intent to give them to research (a sentence of death), while 841,396 were frozen for future use. Only 1,388,443 of the created embryos from this period were "transferred" to a womb, thus creating a pregnancy.[^86] For a nearly coterminous period---1991 to June 30, 2010---the HFEA reported that 101,605 embryos were given for research---again, a sentence of death.[^87] When we put the numbers together from these slightly diverging time periods of embryos discarded or given for research, the death toll for this twenty-year period comes to 1,816,175. But this death toll is not yet complete, as we will see.

According to the 2012 annual report of the HFEA, "In the UK, 224,196 babies were born after IVF treatment between 1991 and 2011."[^88] Subtracting the number of babies born from the number of embryos transferred to a woman's womb, we see that 1,164,247 embryos died during pregnancy.[^89] This plus the previous death toll gives us 2,980,422 dead little ones. Simplifying this data, the numbers indicate that for every one baby born via IVF in the UK between 1991 and 2011, roughly sixteen embryos were created. Of these sixteen, nine were "discarded," five died during pregnancy, one was frozen, and one was born.

Getting an exact number of how many children have been sacrificed and placed in "concentration cans" worldwide through IVF is difficult. In 2018, the International Committee for Monitoring Assisted Reproductive Technology reported that more than 8 million IVF children had been born since IVF's introduction in 1978.[^90] When we consider that the UK's practice of IVF is very well-regulated in comparison to, for instance, that of the United States,[^91] it is hard to accept a ratio of one child born to sixteen children created, or a ratio of one child born to fourteen children dead, as a realistic ratio for the entire world---the actual ratio is likely to be significantly worse. But accepting it for the sake of an estimate, we find that 8 million IVF children born means that 128 million IVF children were created, 112 million were killed outright or died, and another 8 million were frozen to await one fate or another. That makes 120 million children conceived through IVF who were not born, from 1978 through 2018.

### The Total

Based on the reporting of *The Lancet* that abortions worldwide have increased to 73 million (0.98 of current world population) per year, and assuming the accuracy of the Guttmacher Institute's statistics on world abortions presently totaling 1.6 billion, we conclude that, by 2027, the little ones slaughtered after their survival of implantation will be greater than 2 billion.

Now stop and consider how many little ones aren't included in *The Lancet* and Guttmacher Institute totals. How many babies have been frozen or killed through in vitro fertilization? How many babies have been killed by IUDs preventing their implantation? How many babies have been killed by mothers using the 255 forms of hormonal birth control sold by pharmaceutical firms and reviewed on Drugs.com?[^92]

## Conclusion: Genocide

To summarize, the twentieth century has seen mankind keep descending down into the moral abyss of bloodshed which started with world wars, moved to world wars targeting civilians, then to governments targeting their own countrymen; and finally, to fathers and mothers waging war against their own sons and daughters. At each stage of these changes in the method and scale of the killing, the number of deaths multiplied so that, now, the death toll of our war on unborn babies dwarfs the combined death tolls of all these previous bloodsheds. Mankind today has turned inward against himself, devouring his own offspring.

How do we reckon with such unspeakable horrors? Are there words able to convey such savagery? Are there texts of Scripture revealing the Almighty's hatred of such wickedness and the certainty of His coming judgment of those who have committed such crimes?

Living in a day puffed up with the pride over its concern for what it speaks of as "basic" or "fundamental" human rights, we must puncture this pride with such firm conviction and will that those who hear us may never lie to themselves again concerning their pursuit of "social justice" or "compassion," nor of their being in any way righteous because of any stand they have taken against systemic evils. A good beginning to the destruction of this pride can be accomplished by applying a label to the slaughter of the unborn which has been avoided before this present time.

From Greek *genos* ("birth, race, kind") and Latin *caedere* ("kill"), this word has long been used to refer to the slaughter of a group distinguished by ethnicity or nationality. Age, though, is a parallel category to race and ethnicity. Further, unborn children are, in fact, distinguished by specific physical characteristics, being housed and protected within their mothers' wombs. From here on out, we must make it a habit of speaking of the intentional destruction of unborn children as *genocide*.

Some might cavil that there is no widespread targeting of unborn children *in toto*, but rather only those children in specific circumstances. But even granting the premises of such a wicked counterargument does not nullify the argument we make here. Genocide does not require the intention to kill *all* members of the *genos*, but only the intentional targeting and killing of members of that class *as such*.[^93] Note this resolution by the UN General Assembly back in 1946, whose concepts became cornerstones of international law regarding genocide:

Genocide is a denial of the right of existence of entire human groups, as homicide is the denial of the right to live of individual human beings; such denial of the right of existence shocks the conscience of mankind, results in great losses to humanity in the form of cultural and other contributions represented by these human groups, and is contrary to moral law and the spirit and aims of the United Nations.[^94]

The cornerstone of child murder today is a denial of unborn babies' right to existence. It "shocks the conscience" of those consciences not yet deadened to it. It causes unthinkable "losses to humanity" in the potential it snuffs out, and it is certainly contrary to the moral law of God.

This is genocide, and we, the people of God, must acknowledge our complicity and participation in it.

No doubt Asia's long history of the bloodshed of its children is a consequence of the East's commitment to false religion across thousands of years. But let us examine the West.

Within the pagan idolatry of the ancient Roman Empire there was no question of the absolute authority of the father of the household over the life and death of his children. Called *patria potestas*, this power enabled fathers to throw their children on the hillsides, exposed there to die. This was the context of the New Testament church as it grew in its first few centuries, and in time the witness---the salt and light of the church---first caused these little ones who were the cast-offs from pagan idolatry to be rescued and adopted by Christians, then caused this horror to be outlawed as Christendom displaced the immoralities of paganism.

For most of the past two thousand years, Christendom has been identified by this same love and protection of the weak and defenseless---particularly children. Now though, we find the West hell-bent on flipping every godly commitment of Christendom upside down, starting with its former protection of those on the margins of society. Nor have we ever been as hell-bent on this reversal as in our return to the slaughter of children. The slaughter of children pervasive across our world today could not possibly be more of a rejection of the Christian faith.

What is the moral responsibility of the church in this?

Christians know the truth that life begins with conception. God blesses a husband and his wife with the fruit of the womb and that fruit bears His own image and likeness from the moment of conception. From that point forward, all the little one needs is his mother's womb. Christians know (or have no excuse for not knowing) that we kill that little one when we obstruct his implantation. (And those who claim ignorance are helped by this present document, which is part of its purpose.) Christians must never lie about murder. Christians must never dissimulate about bloodshed. Christians must move heaven and earth to avoid placing a stumbling block in the path of just one of our Lord's little ones.

So now, how do God's people stand in the presence of God and worship Him given a death toll for abortions this past century that is surely in the billions? Given that our ground is saturated by blood?

Do not defile yourselves with any of these things; for by all these the nations are defiled, which I am casting out before you. For the land is defiled; therefore I visit the punishment of its iniquity upon it, and the land vomits out its inhabitants. (Lev. 18:24--25)

So you shall not pollute the land where you are; for blood defiles the land, and no atonement can be made for the land, for the blood that is shed on it, except by the blood of him who shed it. Therefore do not defile the land which you inhabit, in the midst of which I dwell; for I the [Lord]{.smallcaps} dwell among the children of Israel. (Num. 35:33--34)

As we live and God's patience remains, we may repent; and repent we must. It is our prayer that, through this paper, all of us who belong to God will turn and rend our garments and throw ashes on our heads in repentance.

In this section we have opened up our bloodlust. Now, we must hear again the decrees of God against it, found both in His Word and in nature as created by the Word Himself. As churchmen, as magistrates, and as men, what must we do to repent of this wickedness so that God may see fit to renew our minds and hearts, restoring to us and our children His law, His perfections, and His love for little ones?

May God, who alone hath the power, inscribe these teachings on the hearts of those who hold sway over the Christian world. May He grant to them a mind possessing knowledge of divine and human law, and having ever before it the reflection that it hath been chosen as a servant for the rule of man, the living thing most dear to God.[^95]May God, who alone hath the power, inscribe these teachings on the hearts of those who hold sway over the Christian world. May He grant to them a mind possessing knowledge of divine and human law, and having ever before it the reflection that it hath been chosen as a servant for the rule of man, the living thing most dear to God.[^95]
