## A Grim Progression

### War

The twentieth century---what would become history's bloodiest century---began with war between many nations. The warfare's scale, tactics, and techniques were unprecedented. World War I's trench warfare was so dehumanizing and the killing so sustained that many declared their optimism this horror would force a sea change in governments' ability to send their men into war. Thus H. G. Wells named World War I "the war to end all wars."

He was wrong. World War II followed hard on the heels of World War I so that, during the first half of the century, fatalities from these two world wars reached 77 million. But cloaked within this number was a detail foreshadowing the trajectory massive killing would take as the century continued.

### Targeting Civilians

Until the twenty-first century, Christendom had condemned the killing of civilians during warfare. Since the Middle Ages, the Western world had held to the necessity of *jus in bello*, and three commitments stood out among just war principles: soldiers who surrendered were not to be killed; suffering was to be minimized; and the indiscriminate killing of noncombatants was prohibited.

But at the turn of the twentieth century, Christendom itself was, in a sense, on the wane. Atheism and rebellion against God's moral law had grown in the centuries since the Enlightenment, and civilization was about to pay the price. Sadly, of the 17 million fatalities of the First World War, 7 million were civilians. The Second World War was worse: of an estimated 60 million fatalities, 40 million were civilians. Note that these numbers don't even include the tens of millions who died from secondary causes like disease and famine.

Thus, from the start, the twentieth century was exceedingly bloody. The wars were worldwide, the killing was beyond anything imaginable, and civilians were intentionally targeted so that the elderly, women, and children made up the majority of the wars' casualties. By the end of the Second World War, targeting civilians was a major strategy of both Axis and Allied forces. Both sides of the conflict used conventional bombs to kill the civilian populations of their enemies.

Speaking only of our Allied air forces' attacks on Japan, on March 9 and 10, 1945, the air raid called Meetinghouse sent 300 bombers to drop 1,665 tons of bombs on Tokyo, leaving close to 16 square miles destroyed and 100,000 dead. United States forces later dropped nuclear warheads on Hiroshima and Nagasaki, killing 105,000 men, women, and children.

By the end of World War II, Allied bombing had damaged or destroyed over one-quarter of German homes, killing or injuring 1 million German civilians. The relentless nature of Allied bombing of civilians is demonstrated by the fact that 50,000 tons of bombs were dropped on the city of Cologne alone.[^9]

In the end, during the first half of the twentieth century, war claimed 77 million souls, of whom 47 million were civilians. Just war principles had been cast aside. In its conduct of war, the Western world had sown the wind. In the justice of God, we would now reap the whirlwind.

### Rulers Killing Citizens

As the century continued, the killing turned from nations killing nations to rulers of nations killing their own people.

The Soviet Union's great prophet Aleksandr Solzhenitsyn estimated Joseph Stalin was responsible for the deaths of more than 60 million. Chairman Mao's Great Leap Forward, Great Famine, and Cultural Revolution claimed somewhere between 40 and 100 million lives. The death toll of Pol Pot's Khmer Rouge in Cambodia was only 2 million, but these 2 million souls comprised one-quarter of his nation's population.

First, World Wars I and II killed 77 million souls. Then Communism killed at least 100 million souls; and this was bloodshed in service, not to national boundaries defended as patriotism, but pure ideology. As Solzhenitsyn wrote documenting Stalin's death toll in the Soviet Union, "Thanks to *ideology*, the twentieth century was fated to experience evildoing on a scale calculated in the millions. This cannot be denied, nor passed over, nor suppressed."[^10]

First, soldiers killed soldiers. Then, soldiers killed civilians. Then, rulers killed their own people.

The prophet Hosea warned that bloodshed begets bloodshed,[^11] and so it was that the killing next turned inward to the home and family; fathers and mothers killed their own sons and daughters.

### Parents Killing Children

Domestic slaughter began with birth control.[^12] The first abortions were not surgical, but chemical and hormonal. Before women became willing to pay for their child to be cut out of their wombs, they began using birth control methods that had an abortifacient agency. As we will discuss in greater detail later, these methods include intrauterine devices (IUDs) and the Pill.

This was well-known and presented a problem the medical establishment felt the need to resolve. There was no debate in the scientific and medical world that the moment sperm and egg joined, a new life came into existence.[^13] Nor was there any question this preborn life had a rightful claim to all the protections accorded life outside the womb.

These truths, though, stood squarely in the path of the mid-century explosion of the practice of birth control so that, midway through the century, the American medical establishment undertook the project of denying these little ones were living human beings. Every scientist, physician, and mother knew conception was the beginning of life, so what was to be done?

The story is recounted by the American College of Pediatricians who report that, back in 1959, a physician with ties to Planned Parenthood named Bent Böving "argued for . . . moving the date of conception from when fertilization occurs to when implantation occurs."[^14] Böving suggested "the social advantage of \[birth control\] being considered to prevent conception rather than to destroy an established pregnancy could depend upon something so simple as a prudent habit of speech."[^15]

A few years later, Dr. Böving's "prudent habit of speech" was formally adopted by the American College of Obstetricians and Gynecologists who, in 1965, issued a bulletin changing the definition of conception from fertilization to implantation.[^16]

Consider the significance of this subterfuge promulgated by the American medical establishment. By redefining conception, the killing of babies during their first week of life by means of birth control methods was no longer "abortion," but "contraception." The baby was not aborted, because he was never conceived. The baby never died, because he never lived.

Never mind that these little ones are God's own image-bearers having unique DNA and needing nothing more than the sustenance and protection of their mother's womb to be born and live threescore and ten. Who could ever have imagined then, eight years before *Roe v. Wade*, the monstrous death toll that would result from this lie adopted as merely a "prudent habit of speech"? This saying is true: "What a tangled web we weave, when first we practice to deceive."

We can't be reminded often enough that murderers lie. In his book *Aborting America,* Dr. Bernard Nathanson confesses the history of his work legalizing abortion in the late sixties and early seventies. He speaks candidly of the lies he and his Abortion Rights Action League co-belligerents told. He writes:

I confess that I knew the figures were totally false. . . . But in the "morality" of our revolution, it was a useful figure, widely accepted, so why go out of our way to correct it with honest statistics? The overriding concern was to get the laws eliminated, and anything within reason that had to be done was permissible.[^17]

The legalization and growth of the practices of birth control and abortion are inseparable. This fact must be faced squarely by the people of God. The use of birth control would not have spread as it did without the lie that life doesn't begin at conception. This wicked lie has metastasized across the past seventy years, and now the life of the unborn is denied during all three trimesters.

Abortifacient birth control methods that killed children in their first days of life gave birth to abortions throughout pregnancy so that, today, in some places late-term abortions are legal even as the baby is in the birth canal about to take his first breath outside the womb.

Thus, in the decades following 1950, abortion came to dwarf every other killing field of the twentieth century.

Today, it is commonly thought, at least in the United States, that the slaughter of abortion was unleashed by the Supreme Court's 1973 decision *Roe v. Wade*. This is factually wrong. Birth control of an abortifacient agency as well as surgical abortions were widely practiced prior to the Supreme Court's *Roe v. Wade* ruling. In 1972 alone, the year prior to *Roe v. Wade*, the death toll of unborn babies surgically aborted in the United States was 586,760.[^18]

Abortifacient birth control methods propped up by scientists and physicians redefining conception and life make no sense outside a world that had become inured to the bloodshed of innocents. World wars and Communist ideologies had killed their hundreds of millions. Now the bloodthirst turned inward, and the home became the killing field.

Not surprisingly, this intimate familial bloodshed was first normalized behind the Iron Curtain within the Soviet Union where Russians and Eastern Europeans began killing their unborn children in the early fifties. But it didn't take many years for this horror to spread to Western Europe and North America; and now, most of the world. Violence begets violence.

We become proficient at killing, thinking we have it under control. But actually, the bloodshed has us under its control, and its appetite is voracious and growing.