# Abortion's Assault upon God's Character and Law

<div id="fninfo" data-fnstart="1"></div>

Our purpose here is not to provide an exhaustive treatment of the moral issues surrounding abortion. Such a work would fill volumes. Yet in the spirit of saying *something* so that we be not silent,[^96] we provide here some limited accounting of the moral harm caused by abortion. Any of these examples of abortion's moral harm is sufficient to demonstrate to tender Christian consciences the wickedness of abortion. Taken together, these examples expose the monstrosity of this sin.

## Moral Arguments

<div id="fninfo" data-fnstart="2"></div>

From birth to death, every man knows that to kill another man is a crime against man and God. Scripture and history provide irrefutable evidence that God has written this law on every man's heart. This testimony of man's conscience is ineffaceable. Indeed, even the national, state, and local battles fought over abortion during the twentieth and twenty-first centuries bear witness to the testimony of the Spirit of God against this form of murder. Despite the corruption of man's fallen nature, the horrors of this crime against the little ones cry out against us.

### Overthrowing Our Creator's Command against Murder

To murder has always been a great wickedness. From Creation, all races, nations, and societies have recognized that, if any crimes exist, murder is the most fundamental. Abortion is no exception.

### Denial of the Right to Life

Abortion denies the most fundamental right God has given man, which is the right to live. For centuries, arguments have raged over the nature and extent of man's right to live, and in what judicial cases man forfeits that right. What has been undeniable under the rule of law of the Western world is that no individual may decide whether another lives or dies. That prerogative is one owned solely by God and those institutions to whom He delegates the sword in the exercise of justice.

Yet in 1973---and quite suddenly---the Supreme Court of the United States declared the laws against murder by abortion null and void---laws which were, at the time, written on the books of almost every state of the Union. Planned Parenthood records the change enforced by *Roe v. Wade* this way:

> *Roe* has come to be known as the case that legalized abortion nationwide. At the time the decision was handed down, nearly all states outlawed abortion except to save a woman's life or for limited reasons such as preserving the woman's health, or instances of rape, incest, or fetal anomaly. *Roe* rendered these laws unconstitutional.[^97]

This federal reversal of states' laws was unprecedented and led to an embarrassing dilemma among physicians. Sadly, like most Americans of the time, the medical establishment raised no outcry over the newly invented right of mothers to kill their babies. Now that this right had been created, the question remained: Who would carry out these murders?

At that time, the nation's physicians had been initiated into the practice of medicine by taking the Hippocratic Oath, part of which read:

> I shall never give a deadly drug (*pharmakon*) to anyone if asked, nor shall I recommend such counsel; and likewise I shall not give a woman a pessary for an abortion.
> 
> With purity and in accordance with divine law I will keep my life and my art.[^98]

The Hippocratic Oath originated two and a half millennia ago, and it represented the most basic commitments of physicians in their practice of the healing arts. So, when *Roe v. Wade*'s new mandate came down, it raised the question whether physicians would continue to honor their oath. Or, would they begin to accept money in payment for "causing an abortion"?

There was never any significant debate. Doctors across our nation began to break their oath and take money from mothers seeking doctors' assistance in killing their little ones. To clean up the mess, the Hippocratic Oath was sometimes edited and sometimes removed from physicians' initiation rites.

### The Removal of Woman's Moral Agency

Abortion also required the diminishment of woman's moral agency. At the heart of personhood is individual responsibility for one's own deeds. The rule of law flows from this individual moral agency. Whether in the workplace, government, church, or family, the rule of law holds every man and woman accountable for his actions. The roofer is accountable to put on a roof that doesn't leak. The lawyer is accountable to provide his client truthful counsel. The judge is accountable to issue just judgments that do not abandon the meek and lowly to oppression by the sleek, rich, and educated. The pastor is accountable to keep his sheep's blood off his hands by speaking to them precisely what God commands.

Concerning moral agency, feminism had long argued that male authority diminished female responsibility. Feminists declared it would only be when male authority was brought to an end that women would possess full personhood equal to men, and thus bear the full weight of the consequences of their actions. They must be granted self-determination and freedom to choose. Only when this equality was established could women be said to have the same moral agency as men. These themes are constant across feminist and pro-abortion literature of the past fifty years.

When feminists promoted abortion, though, they set this claim aside. No mother was to be judged for procuring the murder of her child.

Today, the male authority that God established when He created Adam first, then Eve, has been repudiated, and yet it is notable that mothers who pay doctors to murder their little ones are viewed as the victims of their boyfriends, husbands, fathers, or a patriarchal society. If there is any moral judgment involved in any abortion, it is the condemnation of bad men who force good women to kill their children. Society is condemned for robbing women of power and self-determination, forcing them to commit bloodshed in order to establish their power and self-determination. Personhood begins with freedom of choice, and what freedom of choice do women have if they are unable to rid their own bodies of these parasites clinging to their wombs? In fact, the ability to choose abortion is said to be central to women's self-determination. Women cannot truly be free and equal until they are granted this fundamental freedom of choice. Feminists demand that their sex's life-givingness[^99] must be subject to the mother's choice whether or not to allow this life God has placed in her to continue. This is necessary to establish women's equality and personhood.

This is the grotesque reasoning feminists have used to reduce mothers to the very status they had previously condemned. In order to gain moral agency on a par with men, feminists demanded women be granted the right to kill their children. And yet, if women exercised this right, they were to bear no guilt for it. Rather, they must be judged to have killed their children under compulsion. They are free of any responsibility for the murder of their little ones they paid to have killed.

But when guilt is denied, repentance is also denied. What is purportedly done from respect for women results in barring women from confessing their sin to the holy God and receiving forgiveness through the mercy and love of God in Jesus Christ. If women commit no crime subject to man's law when they kill their babies, the only logical conclusion is that women who kill their babies commit no sin subject to God's law either.

Women must not seek God's forgiveness for shedding the blood of the children God gave them as His blessing, and the civil authorities must enact no laws testifying to their maternal bloodguilt. The woman has, in effect, become what the feminists feared: a non-agent, functioning only as the victim of male figures in her life, denied any responsibility for her own actions.[^100]

Yet why should this be so? After all, the man who beats his wife or children is responsible for the harm and suffering he causes the members of his household. Equally so the woman who beats her husband or children: she too is responsible for the harm and suffering she causes her intimate family members. If a father rapes or murders one of his children, no prosecutor, court, judge, or jury will hesitate to punish him for his crimes. Equally so the mother who rapes or murders one of her children: any just society will demand her trial and punishment, and the judicial system will carry out this difficult work.

Why, then, have eighty-three pro-life leaders of national and state organizations issued a press release opposing any laws to "punish" mothers who kill their preborn children? Their press release was issued in the weeks following *Politico*'s leak of Justice Alito's draft opinion in *Dobbs v. Jackson Women's Health Organization*, and it was drafted and signed by the leaders of organizations including the Ethics and Religious Liberty Commission of the Southern Baptist Convention, the US Conference of Catholic Bishops, Americans United for Life, the Faith & Freedom Coalition, Life Issues Institute, the National Association of Pro-Life Nurses, and the National Right to Life. The letter reads:

> **Women are victims of abortion and require our compassion and support** . . .
> 
> **As national and state pro-life organizations, representing tens of millions of pro-life men, women, and children across the country, let us be clear: We state unequivocally that we do not support any measure seeking to criminalize or punish women and we stand firmly opposed to include such penalties in legislation.** . . .
> 
> We understand better than anyone else the desire to punish the purveyors of abortion who act callously and without regard to the dignity of human life. But turning women who have abortions into criminals **[is not the way.]{.underline}**[^101]

While it is true women and men other than the baby's mother usually share the bloodguilt of the murder of the preborn, it remains hard to fathom this denial of the moral agency of the women who most often are the ones who actually pay for the drugs or surgery to kill their baby. Wise Solomon recognized the mother who wanted the baby dead to be the evil moral agent in the dispute, and penalized her for it.[^102] Was Solomon wrong?

How have we come to think so lightly of the minds, consciences, and souls of women, that we issue statements absolving them of any responsibility for their murder of their own children? Do these pro-life leaders claim to speak for God in their dispensing this public absolution to mothers who have aborted their preborn children?

No murder is hidden from God. Every one of us will soon give an accounting for our bloodguilt on that Final Day of Judgment, when the secrets of all men will be revealed before the Great Judge Eternal. It is of the essence of the gospel message preached by John the Baptist, Jesus Christ, the Apostles, and every gospel witness down through two millennia of church history to "flee the wrath to come." How then can those professing faith in Jesus issue public statements that women who have murdered their preborn children are merely "victims of abortion" who "require our compassion and support," and that they are adamantly opposed to any law which would declare these women "criminals"?

To be sure, these post-*Roe* days will require wisdom in the writing and debate over states' abortion legislation. No two states are alike, and civil authorities of each state will bear the responsibility of decisions concerning who should be held accountable for the shedding of these little ones' blood, as well as how, when, and in what way. Given a particular state's demography, it may be wise not to use the force of law against mothers who buy the murder of their preborn children. Nevertheless, no follower of Jesus Christ should ever declare moral or criminal absolution concerning such mothers. God will judge us, and it is no kindness for any leader to declare that those bearing bloodguilt are only "victims" of this abortion they have purchased, and that no one should "punish" them.

On the other hand, assuming such pro-life leaders are successful in their attempts to stave off any criminalization or punishment of mothers who abort their little ones, the truth always held precious by the church of Jesus Christ remains with us today---to proclaim repentance for the forgiveness of this sin too, as also every other form of wickedness:

> [Jesus] said to them, "Thus it is written, that the Christ would suffer and rise again from the dead the third day, and that repentance for forgiveness of sins would be proclaimed in His name to all the nations. (Luke 24:46--47)

The path forward from the bloodguilt of abortion is not claiming victimhood and denying one's moral agency, but acknowledging our guilt and fleeing to the cross of Jesus Christ for His forgiveness. Those of us who love Jesus have done the same (and continue to do so daily) and will welcome you into the household of faith, the church of the Living God.

### The Death of the Conscience

Mother Teresa of Calcutta used to say there are two deaths in every abortion:

> The mother herself kills, destroys, murders her own child. Created by God Himself for greater things: to love and to be loved. Created in the image of God. Created to be His presence in the world today. I mean destroying. And in killing that living reality of the tenderness of God's love, the mother kills two: the child and her (own) conscience. For life she will know she has murdered her own child with her own decision.[^103]

God's moral law is written on each man's heart so that our conscience testifies to each of us what ought and ought not to be done. When women and men act against their conscience, particularly on an issue of such gravity, they sear their conscience and leave it on life support.

Despite all the supposed evidence denying the suffering of mothers who choose abortion, the murderess bears her guilt and shame for the rest of her life. Grievous (and often, repeated) sin of this nature can so harm the conscience that it ceases to function. Such a woman has lost not only her child, but God's gift of knowing what sin she has committed. For herself, her family, and her society, this grave evil gives birth to grave consequences among all those who know and love her. They may not know the cause of her moral disease, but they suffer it along with her. As one example, the children she chooses to give birth to end up being her *wanted* children, and they too suffer guilt and shame, sometimes called "post-abortion survivor syndrome."[^104]

We must not allow our bloodlust to fool us:

> Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap. For he that soweth to his flesh shall of the flesh reap corruption; but he that soweth to the Spirit shall of the Spirit reap life everlasting. (Gal. 6:7--8, KJV)

## Natural Law Arguments

<div id="fninfo" data-fnstart="10"></div>

All creation declares abortion's ingratitude and rebellion against our Creator. But men make science their god and mock God's truths, so we are tempted to retreat within the walls of special revelation, consigning the natural world and its scientific investigation as a pagan domain. This is a grave mistake. Natural revelation is a key part of knowing and understanding God. God's book of nature helps us to know *what* He has done and *how* He works among us. Indeed, Scripture itself teaches us to ask, "Does not even nature itself teach you?" (1 Cor. 11:14).

Those truths proclaimed by nature must not be abandoned in favor of those truths revealed by Scripture.[^105] Nature is a handmaid to Scripture. It too reveals the character of God, at times in areas Scripture does not. Sacred Scripture is infallible, yet not all texts of Scripture are spoken with equal clarity; where Scripture is unclear, the book of nature helps us evaluate what interpretations of God's Word are most sound.[^106] Some of our fallible understandings of Scripture need refinement by nature.[^107] Properly understood, natural revelation cannot contradict special revelation.[^108] Any conflict between natural and special revelation, then, is due to some error in our interpretation of either (or both).

Conversely, when both of God's spheres of revelation address a matter, we do well to take special heed. Thus we here state that our condemnation of abortion is not only based on God's written moral law, but also God's book of nature. Together they bear unanimous testimony against the monstrosity of this crime.

### Man as Unique Creation

Scientific research shows that, from the moment of conception, the unborn child possesses all the genetic information that distinguishes him from any other created species or being. The unborn child conceived in his mother is not a tree, monkey, or tumor.[^109] He is a human being bearing the image of God with forty-six chromosomes and the DNA that sets him apart from the rest of creation. He is demonstrably different from either his father or mother, with DNA drawn from both of them. He is a unique human being.

As detailed earlier, physicians have tried to change the definition of *conception* from fertilization to successful implantation in the mother's womb. But this change makes a mockery of science and reason. The safe attachment of the child to his mother's womb does not change him in any way. There is no scientific or rational reason why implantation should define the beginning of life or qualify that life for protection. It is true that, from implantation, the little one's reliance on his mother for nourishment increases, but this increase does not bear on his right of protection. Indeed, such an argument contradicts one typical argument for abortion "rights"---namely, that one person dependent on another is *less* deserving of protections and rights. What a callous response to the interrelatedness of life, and specifically the charity God commands between us in light of His charity toward us!

### Personhood from the Beginning

If, for the sake of argument, we grant that the personhood of the human embryo is not yet proven to exist at fertilization, arguments based on this irrational supposition still fall flat. For, in order to justify the moral rectitude of abortion at any point, one would need to establish that there is no possibility of the abortion killing a person. Yet it is impossible to demonstrate the newly conceived embryo lacks personhood. Indeed, all the evidence is to the contrary.

Again, if for the sake of argument we were to accept this irrational premise, it would immediately leave us asking at what stage of later embryonic development personhood is acquired? At what stage does what is not man somehow become man?

The irrationality of this project is clear to everyone who has not allowed himself to become a bloody ideologue. This little one is a living human being when he emerges from his mother's womb because he is a living being at the moment when his life *qua* human begins---always and forevermore at conception.

Yes, we can muddy the waters by raising abstract, speculative questions on ensoulment, personhood, or quickening, desperately working to deny that conception is the beginning of life. But why such intensity in our efforts to deny protection to these little ones? The truth is, throughout history, men (often with better intentions than our own) have discussed the mystery of how and when our heavenly Father "ensouls" an infant. Many of the church fathers wrote extensively on the matter, yet their opinions were never settled matters of dogma, in large part because Scripture does not directly address the topic.[^110] Nor did these theories cause the slightest hesitation in their condemning abortion as a grave sin from the moment of conception. In *Evangelium Vitae,* John Paul II puts it directly:

> Some people try to justify abortion by claiming that the result of conception, at least up to a certain number of days, cannot yet be considered a personal human life. But in fact, "from the time that the ovum is fertilized, a life is begun which is neither that of the father nor the mother; it is rather the life of a new human being with his own growth. It would never be made human if it were not human already. . . ."
> 
> Furthermore, what is at stake is so important that, from the standpoint of moral obligation, the mere probability that a human person is involved would suffice to justify an absolutely clear prohibition of any intervention aimed at killing a human embryo. Precisely for this reason, over and above all scientific debates . . . , the Church has always taught and continues to teach that the result of human procreation, from the first moment of its existence, must be guaranteed that unconditional respect which is morally due to the human being in his or her totality and unity as body and spirit.[^111]

The church has always taught and continues to teach that abortion is the direct assault upon the providence and authority of God, our Creator.

### SLED Arguments

Many of the arguments employed by advocates of abortion can be divided into four categories referred to by the acronym SLED, referring to the Size, Level of development, Environment, and Degree of dependency of the preborn child.[^112]

1. *Size:* Some argue abortion is justified because these little ones are beyond our view. It is permissible to kill the little one because he is too small to see hidden inside his mother's womb.

    Yet God's creation is full of small organisms and many of them have the protection of law and the sympathy of society, such as the world's smallest primate and smallest marine mammal. Shall we justify the killing of these organisms because of their size? On the contrary, it is much more grievous to destroy these little ones because of how tiny and defenseless they are. Only a monster would argue that the smaller and weaker the baby, the less claim that baby has on our protection.

2. *Level of development:* Some argue the limitations of the child during his early development make it permissible to kill him. The unborn child can't feel pain, can't think, isn't self-aware, and is not yet sentient, so we may kill him.

    Yet science is proving the little one's sensitivity to his environment at younger and younger stages of his life in the womb.[^113] The limitations of development are irrelevant. One's right to life is not dependent on one's capacities to enjoy life or assert his personhood. Children or adults who suffer sickness, wounds, or genetic anomalies which leave them with limited capacities have as much claim to society's protection as those with no such limitations, both outside and inside the womb.

3. *Environment:* Some argue the environment in which the unborn child exists invalidates his right to be considered human. Since the unborn child doesn't, for example, breathe air, he is sufficiently "other" so that he deserves no protection.

    Of course, the same argument would never be made concerning residents of the South Pole or the International Space Station. Neither of those locations can sustain life naturally without the provision of extraordinarily complicated and costly artificial supports. The same can be said concerning victims of polio who have, for decades, continued to live only by the support of an iron lung.[^114]

4. *Degree of dependence:* Some argue the unborn child's dependence upon his mother undermines his right to the protection of his life.

    This argument is especially pernicious, for it strikes at the heart of one of the principal blessings God has ordained in human society, which is our interdependence. God has woven interdependence across His creation: the tree and soil, the citizen and ruler, the husband and wife, teacher and student, doctor and patient; and most preciously, mother and child.

    No man is an island.[^115] No man is independent. By arguing that dependence diminishes value, this argument also targets the handicapped, the elderly, the sick, the infirm, and anyone who depends on another for nourishment and care. This is the trajectory of the pro-abortion argument. This world of callous disregard for the weak and defenseless must be rejected.

## Societal Arguments

<div id="fninfo" data-fnstart="21"></div>

### Man as Social Being

God has ordained men to live, not to themselves, but in bonds of fellowship one with another, so that when one suffers, all suffer. This has been seen more clearly in recent days as the negative effects of isolation because of Covid have continued to make themselves known. As Calvin put it:

> The human race has been joined together by a sacred link of community. . . . They are all next to [*or*, neighbors to] one another. To be our next [neighbor], it is enough for someone to exist as a human being, for we do not have the right to destroy our common nature.[^116]

Not coincidentally, the account of the first assault on God's gift of life committed by Cain, who murdered his brother Abel, records Cain's justification: "Am I my brother's keeper?" Cain was denying his obligation to love his neighbor. The answer implied by Cain given his question is, "No, I am not my brother's keeper." This is the heartless answer implicit in every violation of the second table of God's moral law: we are not our neighbor's keeper. No violation of neighbor-keeping, of loving our neighbor as we love ourselves, is more fundamental than robbing our neighbor of his very life.

God's condemnation of the manslayer Cain demonstrates the wickedness of Cain's self-justification. We are in fact our neighbor's keeper, and this sacred duty declared by God has governed all subsequent human society. By God's design, society is a fellowship of His image-bearers. Men are bound together in this mutuality. We have a large degree of freedom, yet that freedom is defined by the moral law requiring that we love and defend our neighbor.

Notwithstanding the corruption of man by Adam's Fall, human societies throughout history and across the world have enacted statutes against murder. From the Code of Hammurabi to the law codes of Draco and Solon to the Roman Twelve Tables to the laws of the Zhou Dynasty and the three constitutional principles of the Han Dynasty, man's societies have recognized that murder destroys the foundation of the consent under which men live together bound by law; and that, left unchecked, murder leads to disarray, anarchy, and ruin:

> Protecting the life of the unborn child has been a major concern of the earliest laws known to us. It has continued to be an object of law-making in every subsequent civilization which has contributed to our own because it springs from a universal feeling which in the past has ceased to move men only when a nation was in decay.[^117]

When anyone kills another man (even himself) with whom we are bound in union, it is not a "personal decision," or a "reproductive choice," but an offense against all. And so it is with the unborn:

> A choice cannot be private which affects another's life. The child in the womb has blood and brains, a respiratory system, a circulatory system, a urinary system that are not those of his or her mother. The child in the womb is not the property of his or her parent. The body of the child in the womb is not that of his or her parent. Sexuality may be private, reproduction may be private, but the taking of the life of the unborn cannot be private. It is a social act. Multiplied by 1 million times a year, it is a social act amounting to atrocity.[^118]

### The Loss of Potential

Much has been made in recent years of man's squandering of the earth's natural resources. But the resource with the most potential for the betterment and sustainability of human society is neither geological nor ecological, but anthropological. Man is the ultimate resource created by God, called by Him to "subdue" the rest of His creation.

God commanded us to subdue creation, and man's obedience to this command has been responsible for every advancement in law, medicine, politics, and art. Even conservation comes through man managing creation towards the betterment of mankind and the prosperity of the rest of creation.

Abortion, birth control, and contraception attack man's potential to bless all creation in this and other ways. To refuse God's blessings of children is to steal from future generations the benefits He has ordained we bequeath them. The loss of each child by that murder of abortion is the loss of immeasurable blessings which otherwise would rain down from heaven on our descendants. Perhaps that child would have been the next Jonas Salk, curing not polio, but cancer. Perhaps that child would have been the next Bach. The next Da Vinci? The next Martin Luther? The next George Washington Carver? The next Edison? Or even the next Fred Rogers?

Each of these men blessed multiple generations through those gifts God gave them. Are we not grateful their parents did not kill them? Are we not grateful they were conceived and born during a time when their societies still forbade mothers killing their unborn children?

### Economic Considerations

In their 2005 book *Freakonomics*,[^119] Steven D. Levitt and Stephen J. Dubner argued that the liberalization of abortion led to a significant reduction in the crime rate. Empirically, their argument was based on the observation that the crime rate in states that allowed abortion fell some fifteen years after the new legislation came into effect. Specifically, Levitt and Dubner argue that *Roe v. Wade* was the cause of the drop in crime rates in the early 1990s. The argument is simple and cynical: *Roe v. Wade* made abortions cheaper so that abortions became affordable to low-income women. Unwanted children of low-income mothers are more likely to be criminals later in life.[^120] Hence the benefit of *Roe v. Wade* is fewer criminals, fewer prison inmates, and thus a fiscal gain to society.

Apart from the fact that any correlation spanning over fifteen years is necessarily tenuous because there are a multitude of intervening factors that need to be controlled for, it is also completely inappropriate for the issue at hand. Levitt and Dubner say that "one study has shown that the typical child who went unborn in the early years of legalized abortion would have been 50 percent more likely to live in poverty" and in a single parent home.[^121] They do not indicate where that study was published. They go on, citing "another study [that] has shown that low maternal education is the single most powerful factor leading to criminality [of the child]."[^122] They don't bother telling the reader where this study was published and by whom. Did Levitt and Dubner make it up? Maybe. We don't know. In any case, two "studies" with no references and no explanation of data or methodology cannot be used to justify the deaths of some 750,000 human beings in the first year after *Roe v. Wade*.[^123] Far from being serious economists, Levitt and Dubner wrote a book to amuse their readers and themselves with absurd statements and they amused themselves with the deaths of millions of children.

Levitt and Dubner's argument is also flawed because abortion occurs not only among low-income classes. They would have had to show that after *Roe v. Wade*, abortions occurred *primarily* in low-income families. Yet we know that they occur in all income groups. We also know that abortions often cause mental harm---the treatment of which must be counted against what Levitt and Dubner seem to perceive as a fiscal benefit to US society.

How then should we look at the economic implications of abortion? For every economy today, it remains true that human beings contribute the most to economic well-being. In the US, the labor share (i.e., the percentage of annual value added that accrues to workers and proprietors as compensation for their work) is around 60 percent.[^124] It is slightly higher on average in the twenty most important economies of the world (the G20).[^125] This implies that every aborted child inflicts an economic damage on the US economy in the form of lost income.

Can we estimate that damage?

We begin by noting that the average productivity of an American is annual GDP per employed person, which was $131,812[^126] in 2019.[^127] (We use data for 2019, since these are not affected by the Covid pandemic.) Next we calculate his or her average years in the workforce by multiplying Americans' years of age by their age-specific participation rates, i.e., the percentage of Americans in that age group being in the workforce.[^128] Then we multiply their years in the workforce by their age-dependent productivity, assuming that Americans' relative productivity over the life-cycle is reflected by relative weekly earnings over the life-cycle.[^129] Finally, we take the present value over their lifetimes; that is, we sum up their average productivity over the ages of their lifetime and discount the values after their first entry into the workforce. We assume an annual real (i.e., inflation-adjusted) interest rate of 4 percent, which is realistic for the US economy. This yields an estimate of average lifetime productivity and, therefore, an estimate of the economic loss to the US economy from aborting a child.

This number is 14.5 times the annual GDP per employed person, or $1.91 million. This is the loss of economic wealth the US economy incurs due to an abortion in 2019. Take this times the number of aborted per year, which was 629,898 in 2019 according to CDC data,[^130] and you have the estimated economic cost of abortion. The result is a loss of wealth due to abortions in 2019 of $1.2 trillion, roughly 1.1 percent of total household wealth in the US in 2019,[^131] or 5.6 percent of annual economic output in 2019. Clearly, abortion inflicts a serious economic damage on the US economy.

The discount factor obviously plays a large role in these calculations. In the above calculations, we assumed that there is no productivity growth over the lifetime of a person born today. This is clearly unrealistic in light of past evidence. Productivity growth effectively reduces the annual discount rate. If productivity grows at an average rate of 1 percent over the lifetime of the individual (conservative estimate), the relevant real interest rate falls to 3 percent and his lifetime production is 17.9 times annual production. The discounted value of an individual's lifetime production would be $2.36 million.

Some people object to this, arguing that abortion is necessary to keep overpopulation in check. For example, Mumford and Kessel argued in 1986 that developed countries needed to maintain an abortion rate of 201 to 500 per 1,000 live births to keep their population growth rates close to 1 percent or less.[^132] Max Kummerow claims that opposition to abortion is today's equivalent of the Roman Catholic Church forcing Galileo to recant his claim that the earth revolves around the sun (which, incidentally, never happened).[^133] Kummerow argues that abortion should be regarded as a valid instrument of keeping population growth in check, which, he proposes, is necessary to assure that mankind does not deplete Earth's resources.

Such arguments seem plausible, but lack economic substance. Kummerow refers to the (in)famous "Meadows Report," published as *The Limits to Growth* by the think tank Club of Rome in 1972, as well as its update published in 2004.[^134] Both reports argue that unless mankind manages to reduce population growth by all means, the current economic system will collapse. The original report predicted that collapse would occur around 2010. It also predicted that the world would run out of crude oil by that time. Neither one has happened.

Why not? Because the authors of these and similar reports are engineers who do not understand economics. The economics of resource depletion is that when resources become scarce, their prices increase and this creates incentives in a variety of directions: economizing on the use of these resources, increasing the use of recycled materials, investing in new technologies to detect and exploit resource deposits. Today, the estimated time to deplete currently known crude oil deposits at current extraction rates is about forty to fifty years from now, very similar to what the 1972 report foresaw. In the developed world, the oil intensity of economic production, measured in terms of barrels of crude oil per $1,000 of GDP, has declined by 56 percent since 1973.[^135] Because of the "green revolution," the development of more productive rice plants and other grains, there is no food scarcity in principle on earth today. The world's food supply in terms of calories per day per capita has increased by 34 percent between 1947 and 2018. Today's level of 2,928 calories well exceeds the daily need per person of 1,800 calories calculated by the Food and Agricultural Organization (FAO), a branch of the United Nations. Still, the FAO estimates that some 690 million people globally, or 8.9 percent of the world's population suffer from chronic hunger today.[^136] But they do so because they lack *access* to food, not because food itself is lacking. Human greed and hatred toward other human beings are the causes of hunger. This goes right to the heart of the Christian faith: 690 million people starve from a lack of brotherly love.

Overpopulation is not the problem. In fact, given today's state of agricultural productivity, the world could sustain a population larger by 62 percent. Even the wildest population forecasts do not foresee such an increase. Population growth rates have long been falling. To the best of our knowledge, the world's population will reach 10 billion by 2050 and then first stagnate and finally decline.

Obviously, then, abortion is not required to keep population growth in check and prevent a global hunger crisis. Ultimately, killing a baby is the most explicit expression of denying him access to food and all other parts of the comforts of life. Call it greed and hatred, if you wish. An economic rationale for abortion simply does not exist.

### Devaluing One Devalues All

In modern society, the rights of the underprivileged are top government priorities. Every good citizen will champion the unique gifts that these groups bring to society as a whole. Why does this not hold true for those being murdered in their mother's wombs? Why does society not hear their voices too? To speak bluntly about the hypocrisy, the very voices that vociferously condemn any slightest insensitivity toward the underprivileged are the same voices that aggressively promote the continuance of our slaughter of the unborn. The same voices known for denouncing the slightest indifference toward the plight of other underrepresented ethnic, racial, or socioeconomic minorities show not the slightest concern for that most underrepresented of all minorities, the unborn.

Keep in mind that devaluing the rights of others is a slippery slope. Those protections found in the United States Constitution are predicated on God's creation of men equal in His sight. Abortion denies this truth that is fundamental to the rule of law. Abortion disenfranchises an entire category of unrepresented across our society, consigning them to death. Our nation's fathers in past generations declared their slaves to be worth only three-fifths of other men in representation.[^137] As unjust as our past laws were, though, today we have decayed to such a morally degraded state that we say the unborn are worth nothing at all. Early twentieth-century laws were enacted to prevent "deficient" people from "breeding."[^138] Today, we have enacted laws denying the unborn birth itself.

How can any society that denies the rights of its unborn claim to value the rights of any other class of vulnerable persons? What madness is it that drives a society to protect a host of special people groups while decreeing the wholesale slaughter of its own children? Any society that refuses to defend its innocent and defenseless babies highlights the high hypocrisy of every other social justice it preens itself over. If unborn children are devalued, every other group is as well, and so are we all. Mother Teresa speaks truly:

> America needs no words from me to see how your decision in *Roe v. Wade* has deformed a great nation. The so-called right to abortion has pitted mothers against their children and women against men. It has sown violence and discord at the heart of the most intimate human relationships. It has aggravated the derogation of the father's role in an increasingly fatherless society. It has portrayed the greatest of gifts---a child---as a competitor, an intrusion, and an inconvenience. It has nominally accorded mothers unfettered dominion over the independent lives of their physically dependent sons and daughters. And, in granting this unconscionable power, it has exposed many women to unjust and selfish demands from their husbands or other sexual partners. Human rights are not a privilege conferred by government. They are every human being's entitlement by virtue of his humanity. The right to life does not depend, and must not be declared to be, contingent on the pleasure of anyone else, not even a parent or a sovereign.[^139]

### The History and Destruction of the Unborn's "Right to Life" in the West

Today, any discussion of man's interaction with his fellow man in society introduces the notion of rights. This is true above all on the matter of laws, mores, and customs protecting unborn babies from being killed. For several hundred years now, Christian philosophers and theorists have recognized that God, as Creator and the Source of all political equity and liberty, has given man as the crown of His creation certain rights that flow from his identity as the crown of God's creation and possessor of the *imago Dei*. Chief among these is a right to life.[^140]

Yet a Christian must tread carefully here. In the last two hundred years here in the West, and with amazing speed in the late twentieth and early twenty-first centuries, rights have proliferated. Almost everything is declared a right: healthcare, housing, food security, education, euthanasia---even access to the internet. Perhaps compensating for the lack of substance to such claims, people declare almost anything desired a fundamental human right. With such a plethora of rights, the meaning of human rights has depreciated socially and morally.

Thirty years ago, an American legal dictionary defined "right" fairly accurately as follows:

> As a noun, and taken in the *concrete* sense, a power, privilege, faculty, or demand, inherent in one person and incident upon another. Rights are defined generally as "powers of free action." And the primal rights pertaining to men are enjoyed by human beings purely as such, being grounded in personality, and existing antecedently to their recognition in positive law. But leaving the abstract moral sphere, and giving to the term juristic content, a "right" is well defined as "a capacity residing in one man of controlling, with the assent and assistance of the state, the actions of others."[^141]

This is a useful rendering of the meaning in several respects. First, one man's right always implies another man's corresponding duty. Second, not all rights are of equal importance. Third, natural rights (referred to in the definition as "primal") exist independently of and prior to recognition in man's law. In other words, man's law does not create or grant such rights; man's law can only discern and enforce them. Fourth, a man may invoke the state to vindicate his right against another man.

This meaning applies perfectly to the right to life. First, a man is obligated to avoid taking the life of another man unless justified by self-defense, just war, or the exercise of capital punishment. Second, the right to life is of paramount importance. Without life, it is impossible to exercise any other right. Third, God gives a man life, and thus a right to life that civil authorities must recognize and faithfully secure. In other words, civil authorities do not grant and cannot withdraw (unless justified) a man's right to life. Fourth, a man can invoke the power of the state to secure his life against harm from another man.

In the formulation of the American Declaration of Independence, government is instituted to secure a man's basic rights, including his right to life: "all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness. That to secure these rights, Governments are instituted among Men . . ."

We must recognize that a government itself violates the right to life when, having the ability to do so, it refuses to secure any man's life from dangers. When civil authorities neglect their duty to protect life on a mass scale over a long period, they nearly forfeit their reason for existence. Government, because of its obligation to defend the oppressed from the predator, shares culpability when it refuses to protect the unborn. It is not simply a matter of one private individual committing harm against another private individual. Some civil authorities themselves will be judged by God for their active sin of commission in legitimating abortion as lawful; other civil authorities will be judged for their sins of omission in failing to protect vulnerable unborn lives.

The Fifth Amendment to the US Constitution (ratified in 1791) protects the right to life: "No person shall be . . . deprived of life, liberty, or property, without due process of law." The Fourteenth Amendment (ratified in 1868) similarly protects the right to life from deprivation by the State: "nor shall any State deprive any person of life, liberty, or property, without due process of law."

British common law recognized an unborn child's right to life at quickening:

> I. The right of personal security consists in a person's legal and uninterrupted enjoyment of his life, his limbs, his body, his health, and his reputation.
>
>    1. Life is the immediate gift of God, a right inherent by nature in every individual; and it begins in contemplation of law as soon as an infant is able to stir in the mother's womb. For if a woman is quick with child, and by a potion or otherwise, killeth it in her womb; or if any one beat her, whereby the child dieth in her body, and she is delivered of a dead child; this, though not murder, was by the ancient law homicide or manslaughter. But the modern law doth not look upon this offence in quite so atrocious a light, but merely as a heinous misdemeanor.[^142]

Medical science and knowledge advanced in the 1800s, making it impossible to cavil that life begins at any time other than at conception. These advancements also included the introduction of anesthesia and instruments to make childbirth safer and less agonizing. The American Medical Association led the effort to strengthen legal protections of the preborn through state statutes codified in the mid- to late-1800s. These protections expanded the civil authority's criminalization of abortion to include the killing of the preborn before quickening---at any time after the moment of conception. These laws also punished the advertising and use of abortifacient drugs, which to that point had been advertised in many newspapers and kept for sale by local druggists in a wink-wink, under-the-counter manner. This progress in protection of preborn life was in keeping with the general acknowledgment that the common law had defects which needed correction.

*Bouvier's Law Dictionary*, a then-respected law dictionary published in its third revision in 1914, indicates that the legal profession had modernized (in the best sense of the word) its formerly antiquated and ignorant understanding of the beginning of a preborn infant's life. In other words, the legal profession had rejected that life began at "quickening":

> It was formerly supposed that either the child was not alive until the time of quickening, or that it had acquired some new kind of existence that it did not possess before: hence the presumption of law that dates the life of the child from that time [i.e., quickening].
> 
> The child is, in truth, alive from the first moment of conception, and, according to its age and state of development, has different modes of manifesting its life, and, during a portion of the period of gestation, by its motion. By the growth of the embryo, the womb is enlarged until it becomes of too great a size to be contained in the pelvis, it then rises to the abdomen, when the motion of the foetus is for the first time felt.
> 
> Quickening as indicating a distinct point in the existence of the foetus has no foundation in physiology: for it arises merely from the relation which the organs of gestation bear to the parts that surround them; it may take place early or late, according to the condition of these different parts, but not from any inherent vitality for the first time manifested by the foetus.[^143]

In the latter third of the twentieth century, *Griswold v. Connecticut*, *Roe v. Wade*, and *Doe v. Bolton* abolished these legal protections through what one Supreme Court Justice White (dissenting in *Roe v. Wade*) called a "raw exercise of judicial power." Thus judicial fiat established the mother as sole arbiter of her preborn child's life. Ignoring over a hundred years of scientific knowledge and medical advancements, the Supreme Court's abortion opinions were a retrograde movement back to a more primitive and barbaric (if not sophistical and self-interested) belief about the beginning of life.

Now, in 2022, in God's kind providence the unexpected has come to pass, as a majority of the Supreme Court in *Dobbs v. Jackson Women's Health Organization* has finally recognized what has been patently obvious to all: the penumbras of *Roe* were a legal fiction designed to grant the murder of children the protection of law, and such judicial inventions should not be allowed to stand as precedent. Without question, the overturning of *Roe* is a victory to those who have fought for years to remove this stench of legal manipulation from the books. Writing for the majority, Justice Alito speaks truly:

> We hold that *Roe* and *Casey* must be overruled. The Constitution makes no reference to abortion, and no such right is implicitly protected by any constitutional provision. . . .
> 
> . . . *Roe*'s defenders characterize the abortion right as similar to the rights recognized in past decisions involving matters such as intimate sexual relations, contraception, and marriage, but abortion is fundamentally different, as both *Roe* and *Casey* acknowledged, because it destroys what those decisions called "fetal life" and what the law now before us describes as an "unborn human being."
> 
> . . . *Roe* was egregiously wrong from the start. Its reasoning was exceptionally weak, and the decision has had damaging consequences.[^144]

That *Roe* has been overturned is a victory. Yet this victory must not blind Christians to what is glaringly absent in the majority opinion of *Dobbs*: the recognition of the personhood of the unborn child. Omission of this was perhaps understandable in previous ages, but as has been detailed here, the last two hundred years of scientific progress and discovery has rendered this failure inexcusable. *Dobbs* may result in repealing some of the barbarism on blatant display for the last fifty years, but it leaves us still inferior to even our recent forefathers in recognizing the personhood bestowed by God on every human being made in His image.

## The Witness of Church History

<div id="fninfo" data-fnstart="50"></div>

As Protestants, we hold that only the testimony of Scripture is infallible. Yet not all areas of Scripture are equally clear, so there has been significant variation in many areas of doctrine across the history of the church. But on the matter of abortion, this has not been so. For over two thousand years, there has been unanimity in declaring abortion a grave evil and crime.

Long before God became flesh and dwelt among us, God's people abominated abortion.[^145] Among the Jews, it was offensive, and indeed the Jews were famous for their hostility to both exposure[^146] and abortion.[^147] As was true with the later church fathers, there was debate and discussion on matters related to ensoulment and quickening, but deliberate abortion was considered a violation of the law of God, and an affront to the sanctity of life.[^148] Former chief justice of the Supreme Rabbinical Court of America, Rabbi Marvin S. Antelman, offers this summary:

> All major religions have their parochial and their universal aspects, and the problem of abortion is *not* a parochial one. It is of universal morality, and it is neither a Catholic problem, nor a Jewish problem, nor a Protestant problem. It involves the killing of a human being, an act forbidden by *universal* commandment.[^149]

Similarly, Chief Rabbi Dr. Immanuel Jakobovits of the United Kingdom explains Jewish thinking on the value of human life:

> Jewish law sees every human life as having the sanctity of intrinsic and infinite worth. One life has as much value as one hundred or one thousand; you cannot multiply infinity and you cannot divide it. So every human being has an identical worth and is identically worth saving.[^150]

This care for the life of the unborn is precisely what we witness in the Jewish world recorded by the gospels. We see the affirmation of the agency of John the Baptist in the womb of Elizabeth, and her reaction thereto testifying to her son's personhood (Luke 1:41--45). We see the great care taken by Joseph and Mary for our Lord, which perfectly accords with a culture that affirmed the preciousness of life. We see the revulsion of the Apostle Matthew who, through the Holy Spirit, exposes Herod's murder of the innocents with no hint that it could ever be excusable (Matt. 2:16--18). And we see in our Lord's words the care for the unborn and the recognition of their personhood (John 16:21).[^151]

With the development of the New Testament church, some of the defining features that had marked God's people began to change. With the abrogation of Old Testament ceremonial law and the expansion of faith and the covenant people to the Gentiles, many of the old distinguishing marks between God's chosen people and the rest of the world became obsolete. In such an environment, one might anticipate the stringency of earlier Judaic condemnations of abortion would be softened, or fall by the wayside.

What happened was just the opposite. Christian condemnations of abortion intensified beyond earlier Jewish ones. The Jews had focused on abortion as a crime against man, but Christians came to speak of abortion as a crime against God. Where Jewish rabbis had refrained from according status to the unborn, even carving out exceptions where abortion might be permitted,[^152] Christians were adamant, speaking in absolute terms concerning its evil.

Opposition to abortion had previously been a feature of close-knit Jewish communities, but with the new Christian church crossing national boundaries, the rejection of abortion no longer remained an ethnic distinctive. It was now a fundamental moral commitment of the new, burgeoning, multiethnic Christian church. Jewish opprobrium towards abortion and the exposure of infants was common across the Roman Empire, but this opprobrium focused on their own communities. It was not so with the Christians. It was no longer enough for God's people to condemn abortion and exposure as unworthy of the covenant community, but now the Christian church opposed these murders even among the pagans---in rhetoric, in policy, and eventually in law. Most importantly, Christians rescued these little ones exposed by their pagan parents, taking them from the hillsides into their homes and adopting them as their own children. This act of Christian compassion was well-known across the Empire. It was a defining mark of these first Christians.

It is not surprising, then, that during the Apostolic Age and immediately thereafter, we find clear prohibitions of abortion in the writings of church fathers:

> You shalt not murder a child by abortion, nor kill that which is begotten. (*Didache* 2.2, AD 50--100)

> You shall not murder a child by abortion, nor in turn shall you kill him after it is born. (*Letter of Barnabas* 19, AD 80--130)

> All of life could proceed according to nature for us if we exert power over our desires from the beginning and do not by evil devices and schemes kill the human offspring, designed by divine forethought and intention. For those women who, to cover their immorality, use abortifacient drugs [*phthoriois pharmakois*] that expel the matter entirely dead, abort along with the embryo their own affection for mankind. (Clement, *The Tutor* 2.10.96.1, c. AD 198)

> But for us [Christians], since homicide has once for all been forbidden, it is not permitted to pull apart even what has been conceived in the womb. . . . Prevention of birth is hastened homicide; nor does it matter whether one tears away a life that has been born or pulls apart one in the midst of birth. He who will be a man is a man already: for indeed the entire fruit exists already in the seed. (Tertullian, *Defense of the Christians Against the Heathen* 9, c. AD 197)

> Therefore the fetus is a human being in the womb from the time that its form is complete. For also the law of Moses judges abortion worthy of penalties, given there exist already the rudiments of a man, since to him is already allotted the condition of life and death when he is assigned to his fate---even though, by still living within the mother, he shares his fate for the most part with her. (Tertullian, *A Treatise on the Soul* 37, AD 208--212)

> When a woman has with intentionality destroyed (*phtheirasa*) a fetus, she is held to be guilty of murder. No fastidious distinction (*akribologia*) between "completely formed" and "unformed" exists with us. For in this case not only the child about to be born will be vindicated, but also the woman herself who plotted against herself: inasmuch in most cases women perish from such attempts. And there is added to this also a second murder, the destruction (*phthora*) of the embryo---at least as far as the purpose of those who dare these things. (Basil, *Letter to Amphilocus on the Canons* 188.2, fourth century AD)

> Also, the rich themselves, lest their inheritance be divided among many, kill their own offspring in the womb, and by parricidal liquids they snuff out the children of the womb in the genital organs themselves---and life is taken away before it be imparted. Who except man has taught us how to renounce our own sons? (Ambrose, *Hexameron* 5.18.58, AD 386--390)[^153]

> You shall not use magic. You shall not use potions; for He says, You shall not permit witches [*lit.*, potionists] to live. You shall not slay your child by abortion, nor kill that which is begotten; for everything that has been formed and has received a soul from God shall be avenged if slain, as unjustly destroyed. (*Apostolic Constitutions* 7.1.3, AD 375--380)

> Some, when they know they have conceived through wickedness, turn to abortive drugs; often, when they too have themselves perished, they are brought to the lower world guilty of three crimes: suicide, adultery against Christ, and parricide of their unborn child (Jerome, *Letters* 22.13, c. AD 384)

> Indeed, sometimes this lustful cruelty or cruel lust [*libidinosa crudelitas vel libido crudelis*] extends so far that it obtains poisons of sterility [*sterilitatis venena*]; and, if nothing else works, [it] snuffs out and breaks up by some means the offspring conceived in the womb, preferring its own offspring to perish before it lives [*prius interire quam vivere*]; or, if it was already living in the womb, to be killed before being born [*occidi antequam nasci*]. (Augustine, *On Marriage and Concupiscence* 1.17 [15], AD 419--420)[^154]

Over a millennium later, the Protestant reformers repeated this condemnation of abortion---always a distinctive mark of Christian morality and charity:

> How great, therefore, the wickedness of human nature is! How many girls there are who prevent conception and kill and expel tender fetuses, although procreation is the work of God! Indeed, some spouses who marry and live together in a respectable manner have various ends in mind, but rarely children. The God who declares that we are to be fruitful and multiply regards it as a great evil when human beings destroy their offspring. (Martin Luther, comments on Gen. 25:1--4)[^155]

> The foetus, though enclosed in the womb of its mother, is already a human being, and it is almost a monstrous crime to rob it of the life which it has not yet begun to enjoy. If it seems more horrible to kill a man in his own house than in a field, because a man's house is his place of most secure refuge, it ought surely to be deemed more atrocious to destroy a foetus in the womb before it has come to light. (John Calvin, comments on Exod. 21:22ff.)[^156]

From ancient times down to the present day, the position of the church across all its branches---Roman Catholic, Orthodox, and Protestant---has been adamant and unchanging: abortion in all its manifestations is a grave, unspeakable evil:

> Throughout Christianity's two thousand year history, this same doctrine of condemning all direct abortions has been constantly taught by the Fathers of the Church and by her Pastors and Doctors. Even scientific and philosophical discussions about the precise moment of the infusion of the spiritual soul have never given rise to any hesitation about the moral condemnation of abortion.[^157]

## The Testimony of Scripture

<div id="fninfo" data-fnstart="63"></div>

Leaving all other arguments to the side, Scripture's authority is absolute. Scripture is not the word of man, but the Word of God. We must submit our judgments concerning abortion to Scripture, where the duty of God's people to uphold His image placed in mankind is everywhere revealed, both implicitly and explicitly.

### Imago Dei

We begin with the doctrine from which flows the clearest condemnation of abortion. God created man in His own image:

> Then God said, "Let Us make man in Our image, according to Our likeness; and let them rule over the fish of the sea and over the birds of the sky and over the cattle and over all the earth, and over every creeping thing that creeps on the earth." God created man in His own image, in the image of God He created him; male and female He created them. God blessed them; and God said to them, "Be fruitful and multiply, and fill the earth, and subdue it; and rule over the fish of the sea and over the birds of the sky and over every living thing that moves on the earth." (Gen. 1:26--28)

While all creation proclaims God's glory, the singularity of man is clearly stated to be that he alone---both male and female---bears the *imago Dei*. None of the rest of God's creatures bear His image and likeness, and although we may argue concerning the precise meaning of "image" and "likeness," God doesn't leave us guessing as to its central significance in life-and-death matters.

We find this significance stated in connection with Scripture's second mention of man bearing God's image and likeness in Genesis 9:

> And God blessed Noah and his sons and said to them, "Be fruitful and multiply, and fill the earth. The fear of you and the terror of you will be on every beast of the earth and on every bird of the sky; with everything that creeps on the ground, and all the fish of the sea, into your hand they are given. Every moving thing that is alive shall be food for you; I give all to you, as I gave the green plant. Only you shall not eat flesh with its life, that is, its blood. Surely I will require your lifeblood; from every beast I will require it. And from every man, from every man's brother I will require the life of man.
> 
> "Whoever sheds man's blood, \
> By man his blood shall be shed, \
> For in the image of God \
> He made man. \
> "As for you, be fruitful and multiply; \
> Populate the earth abundantly and multiply in it." \
> (Gen. 9:1--7)

Today, intellectuals, philosophers, and scientists (as well as some pastors and theologians) join together in assuring man that God is not his Maker, and he need not fear returning to God for judgment following his death. They contradict Scripture's declaration, "It is He who hath made us, and not we ourselves" (Ps. 100:3). From their fervid religious commitment to evolution, they declare the opposite: "It is not He who hath made us, but we ourselves."

Abortion is the godless pagans' most terrible violation of nature, but this violation didn't start with abortion. It began with their denial that God created all things, and that man as male and female is the crown of His creation. Consider the ways the text above from Genesis 9 teaches this truth and could not be more contrary to the spirit of our age.

First, through Noah, God commands the race He named "man" (Hebrew *\'āḏām*) to "be fruitful, and multiply, and fill the earth." Not just "be fruitful," but "multiply." Not just "multiply," but "fill the earth." This series of commands is then repeated at the end of the passage.

Man is God's priority on His earth, and He goes on to make man's primacy more clear by declaring, as a blessing, that man will strike "fear" and be a "terror" to all other creatures. This is God's doing, and therefore it is good. Then He makes it even more clear by stating to man concerning all other creatures of His creation, "into your hand they are given."

He adds that, just like plants, animals are His gift to man for food, and that man is free to kill the creatures, whereas the creatures are forbidden to kill man: "Surely I will require your lifeblood; from every beast I will require it."

Then, not only animals are forbidden to kill man, but man himself is forbidden to kill man. Why? Because man is God's image-bearer:

> Whoever sheds man's blood, \
> By man his blood shall be shed, \
> For in the image of God \
> He made man. \

Flip this upside down and we have the spirit of our age. Man's population must decline. Man must discipline his fecundity so that his numbers on the earth stop expanding and begin to contract. Rather than subduing the earth and its creatures, man must subdue his multiplication because his multiplication is unsustainable. Man must not rule creation. Such anthropocentric thinking is not creation-keeping, but creation-destroying.

Contradicting God, the spirit of our age declares nature must not serve man, but man must serve nature. It declares there is no distinction in principle between man and animal, and thus the high priest of paganism, Princeton ethicist Peter Singer, writes:

> My suggestion, then, is that we accord the fetus no higher moral status than we give to a nonhuman animal at a similar level of rationality, self-consciousness, awareness, capacity to feel and so on. Because no fetus is a person, no fetus has the same claim to life as a person. Until a fetus has some capacity for conscious experience, an abortion terminates an existence that is---considered as it is and not in terms of its potential---more like that of a plant than of a sentient animal like a dog or a cow.[^158]

We see how deeply this rebellion against God has infiltrated the church in any number of ways, but note particularly how many believers choose dogs and cats over children. Also note how many Christians today decline to eat the very animals God gave us to eat when He declared, they "shall be food for you." Of course, Christians who are vegans and vegetarians are eager to reassure other believers this is only their preference---not their principle. But note how meatlessness grows in the church even as Singer promotes his ethical anarchy---and then the entire world prattles on about cruelty to animals and free-range chickens. Five centuries ago, Calvin made this observation which is still true:

> It is usual with hypocrites to reckon it a greater crime to kill a flea than to kill a man.[^159]

Given this flipping of God's order of creation, it should surprise no one that we've also flipped capital punishment upside down. God commands that murderers be executed because murder destroys an image-bearer. Today, though, man outlaws the execution of murderers. Today, it's murderers who awaken the compassion of men and women. Murderers are protected from execution while innocent babies are abandoned.

The various Green advocates of sustainability have repudiated God as the Creator of the universe, and have thus inevitably denied man's dignity as the crown of God's creation. These pagans have replaced the truths of God with the worship of creation, ushering back into Christendom the very idolatries and sexual perversions condemned by the Apostle Paul in the first chapter of his letter to the church in Rome. Refusing to honor and give thanks to their Creator, pagans are turned over by God to the same unimaginable horrors that led God to command the sons of Israel to wipe out the Canaanites of the Promised Land.

The image of God marks man's whole being, body and soul. Thus to kill a man is to destroy God's image in that man, and thus openly defy the God who placed it there. To kill a man or woman, boy or girl, is wrong not only because of the harm done to the individual, but also because of the assault upon God. When one man murders another, it is an act of war against God. God declares the shedding of innocent blood pollutes the land and must be avenged by the execution of the manslayer:

> So you shall not pollute the land in which you are; for blood pollutes the land and no expiation can be made for the land for the blood that is shed on it, except by the blood of him who shed it. You shall not defile the land in which you live. (Num. 35:33--34)

### "Your Hands Formed Me"

God is Creator, and every child conceived reveals the purposeful and formative hand of God in His design.[^160] Scientific advancement has done much to open up the astonishing nature of conception, yet this ought not cause us to be materialists in our understanding, supposing that new life can be explained simply in terms of sperm, egg, DNA, mitosis, and so on. To be sure, our Lord shows us His glory through these means, but He also fashions each child in invisible, spiritual, and unfathomable ways:

> Just as you do not know the path of the wind and how bones are formed in the womb of the pregnant woman, so you do not know the activity of God who makes all things. (Eccles. 11:5)

Abortion is an assault on this secret and divine creation. It takes the greatest mystery in our lives, the creation of life, and destroys it. It takes one of God's greatest mercies to sinful man and mocks it. It is an extolling of death, and thus a denial of God. God creates life. Satan hates and destroys life.

### Woman as Life-Giver

The gift of procreation was only given to man when God created woman. As companion to Adam, she was to be a help meet (fitting or suitable) for him, and central to that suitability for man is woman's gift of bringing life into the world. When Adam named her "Eve" ("living one," or "life-giver"), this was not merely descriptive, but prescriptive:

> Now the man called his wife's name Eve, because she was the mother of all the living. (Gen. 3:20)

> Now the man had relations with his wife Eve, and she conceived and gave birth to Cain, and she said, "I have gotten a manchild with the help of the [Lord]{.smallcaps}." (Gen. 4:1)

> God created man in His own image, in the image of God He created him; male and female He created them. God blessed them; and God said to them, "Be fruitful and multiply, and fill the earth, and subdue it." (Gen. 1:27--28)

Life-giving is fundamental to the mission of woman. God is pleased to bring life into this world through her:

> For as the woman originates from the man, so also the man has his birth through the woman; and all things originate from God. (1 Cor. 11:12)

Life-giving is woman's highest calling and most noble purpose. This is not to say woman's only value is her ability to give life. Many women are single. Many married women have not had their wombs opened by God. Nevertheless, to declare that God created woman's physiology, nature, and being as life-giver is no abuse of women who are childless. It is simply to state what is the doctrine of Scripture and has been obvious to all men everywhere across the ages. Moreover, this blessing of God will continue to be obvious both in Scripture and nature until our Lord returns. We may strive against it and seek to twist and deform our sisters, daughters, and wives until their lives are a visible effort to deny this truth, but nature and nature's God will have the victory.

It is this life-giving nature of woman that abortion attacks. Turning God's creation and distinctions upside down once more, the modern worshiper of Molech tells woman that God's greatest gift is only a gift if she herself desires it. He repeats the serpent's lies, assuring woman that by denying God's command she may be like God.

Thus, Satan promises the very thing we lose if we believe his lies: fertility. Human and child sacrifice have been connected with fertility cults down through history. "Molech" may be a separate deity that we know little about, but the name may also simply be an epithet for Baal,[^161] the Canaanite god of fertility.

Why would a woman sacrifice her child?

Dr. Josephine Quinn of Oxford University's Faculty of Classics suggests that Carthaginians did it because they believed "the good the sacrifice could bring the family or community as a whole outweighed the life of the child."[^162] Likewise, in 2013 an author in *Salon* acknowledged the same motivation for abortion, saying, "She understands that [abortion] saves lives not just in the most medically literal way, but in the roads that women who have choice then get to go down, in the possibilities for them and for their families. And I would put the life of a mother over the life of a fetus every single time---even if I still need to acknowledge my conviction that the fetus is indeed a life. A life worth sacrificing."[^163]

Similarly, in 2010, the "Urban Shaman and ritual expert" Mama Donna Henes wrote an article in *HuffPost* titled "Harvest Rites: The Connection Between Fertility and Sacrifice." She begins her explanation of the fertility benefits of human sacrifice as follows:

> At the harvest, one can easily imagine that the Earth Goddess has offered up Her life in the form of the fruits of the land, and that in doing so, She commits the supreme sacrifice. She expends all of Her generative energy. It is as if Mother Nature in autumn is in the midst of Her menopause, Her sacred seed spent. In grateful response, people fed Her fresh blood to replenish Her powers of procreation.[^164]

She then proceeds to recount unapologetically the cruel, barbaric practices from civilizations around the world that have given themselves to human sacrifice in a quest for fertility. Starting with "the Kandhs of Bengal" who "sacrificed a person for the Earth Goddess, Tari Pennu, in order to ensure healthy crops," then moving to "the Uraons of Chota Nagpur [who] offered human sacrifices to Anna Kuari, who blesses the harvest. And the Lhota Naga of Brahmapootra severed the heads, hands and feet of their victims and planted them in the fields for fertilizer." She then describes the Aztecs: "At the celebration of the broom harvest of the Earth Mother, first an older woman, and then a young girl were beheaded and their blood spread on fruit, seeds and grain to guarantee abundance." After numerous other examples, she concludes with a defense of the practices:

> With the martyred death of the sacrificial victim, the fertile blood seed, like the grain, brings life anew to the world. And, thus, the circle is complete. The death of the old grain, the old sun, the old season, feeds the continuing life of the people. The death of a representative person is then offered in obeisance as repayment of the ultimate debt of life. Death feeds life feeds death, the enduring saga of the eternal cycle of survival.

So it is today as women seek control over their own fertility, sacrificing some children in order to have others through IVF, or choosing the sacrifice of abortion, supposedly for the sake of the financial benefits that will accrue to her and the greater community as a result. This is nothing less than blood sacrifice to the goddess of fertility.

Thus this beautiful creature, woman, whom God has made life-giver, enticed by the serpent and his willing helpers, turns her womb into a grave. She is convinced her individual destiny, the integrity of her personhood, and the well-being of the community require her to destroy the life God gave her as a blessing to husband, family, and God's green earth.

### God as Sanctifier of Birth

God sanctifies and calls us from the womb. Not only does He form and fashion our substance, but from the womb He also establishes our course and sets our feet on His path. Note His words to the prophet Jeremiah:

> Before I formed you in the womb I knew you, \
> And before you were born I consecrated you; \
> I have appointed you a prophet to the nations. \
> (Jer. 1:5)

Through his movements inside his mother, the yet-to-be-born prophet John the Baptist testified to the presence and glory of our yet-to-be-born Savior Jesus Christ, who was then inside the womb of His mother, Mary:

> When Elizabeth heard Mary's greeting, the baby leaped in her womb; and Elizabeth was filled with the Holy Spirit. And she cried out with a loud voice and said, "Blessed are you among women, and blessed is the fruit of your womb! And how has it happened to me, that the mother of my Lord would come to me? For behold, when the sound of your greeting reached my ears, the baby leaped in my womb for joy." (Luke 1:41--44)

To the ancient world, the true scandal of Christianity was not so much the divinity of our Lord, but His manhood. It was unthinkable the divine Word would enter into physical creation, take on human flesh, and experience the suffering, indignity, and weakness of our mortal frame. Yet conceived by the Holy Spirit and born of a woman, our Lord sanctified what was considered the indignity of man and woman's corporeal existence:

> "For thou," says He in the Psalms, "art He that took Me out of the womb." Mark that carefully, He that took Me out of the womb, signifying that He was begotten without man, being taken from a virgin's womb and flesh. For the manner is different with those who are begotten according to the course of marriage.
> 
> And from such members He is not ashamed to assume flesh, who is the framer of those very members. But then who tells us this? The Lord says unto Jeremiah: "Before I formed you in the belly, I knew you: and before you came forth out of the womb, I sanctified you." . . . It is God who even now creates the children in the womb, as it is written in Job, "Have you not poured me out as milk, and curdled me like cheese? You have clothed me with skin and flesh, and hast knit me together with bones and sinews." There is nothing polluted in the human frame except a man defile this with fornication and adultery. He who formed Adam formed Eve also, and male and female were formed by God's hands. None of the members of the body as formed from the beginning is polluted. Let the mouths of all heretics be stopped who slander their bodies, or rather Him who formed them.[^165]

That the ineffable God should become the weakest of all creatures, an embryo seeking to attach himself to his mother's womb, opposed all the wisdom of the world. Yet our Lord flew in the face of that wisdom, putting on eternal display the glory of the womb by His divine presence and occupancy there for nine months at the very inception of His incarnation. Conceived by the Holy Spirit there, He was nourished in the body of the Virgin Mary, dignifying for all time the glorious motherhood of conception, gestation, and birth. Thus every woman who presents her womb to God in obedience to His will of fruitfulness follows blessed Mary in her own submission of her life-givingness to her Creator.

### Children as Gift from the Lord

Children are a gift from the Lord. This is the categorical and unequivocal declaration of God:

> Behold, children are a gift of the [Lord]{.smallcaps}, \
> The fruit of the womb is a reward. \
> Like arrows in the hand of a warrior, \
> So are the children of one's youth. \
> How blessed is the man whose quiver is full of them; \
> They will not be ashamed \
> When they speak with their enemies in the gate. \
> (Ps. 127:3--5)

Throughout Scripture, then, a barren womb is the occasion of grief. Elkanah's wife Hannah is typical in Scripture, which records that it was God who "closed her womb" and caused her heartache:

> When the day came that Elkanah sacrificed, he would give portions to Peninnah his wife and to all her sons and her daughters; but to Hannah he would give a double portion, for he loved Hannah, but the [Lord]{.smallcaps} had closed her womb. Her rival, however, would provoke her bitterly to irritate her, because the [Lord]{.smallcaps} had closed her womb. It happened year after year, as often as she went up to the house of the [Lord]{.smallcaps}, she would provoke her; so she wept and would not eat.
> 
> Then Elkanah her husband said to her, "Hannah, why do you weep and why do you not eat and why is your heart sad? Am I not better to you than ten sons?" (1 Sam. 1:4--8)

Throughout the sacred text of Scripture, fruitfulness is declared one of God's greatest blessings. The endless statements that fruitfulness is God's blessing never vary. We may say without hesitation that children are still as much a blessing today as they were when God presented Eve to Adam, then Cain and Abel to Eve and Adam. Even the children of evil, pagan rulers are given by God's blessing and creative power (Gen. 20:18).

### Murder Incompatible with God's Character

God's decrees flow from His character, and are the final standard for all ethics and law. His law from Genesis onward, revealed most directly in the Ten Commandments, explicitly forbids murder (Exod. 20:13). Who could ever conceive of this not including the murder of the unborn child? Is he not also our neighbor?

And what is the penalty for murder? Scripture declares murderers will not inherit the kingdom of God (1 John 3:15).

### Man Accountable to God for the Shedding of Blood

Deuteronomy 21:1--9 teaches that God holds whole communities accountable for the shedding of innocent blood:

> If a slain person is found lying in the open country in the land which the [Lord]{.smallcaps} your God gives you to possess, and it is not known who has struck him, then your elders and your judges shall go out and measure the distance to the cities which are around the slain one. It shall be that the city which is nearest to the slain man, that is, the elders of that city, shall take a heifer of the herd, which has not been worked and which has not pulled in a yoke; and the elders of that city shall bring the heifer down to a valley with running water, which has not been plowed or sown, and shall break the heifer's neck there in the valley. Then the priests, the sons of Levi, shall come near, for the [Lord]{.smallcaps} your God has chosen them to serve Him and to bless in the name of the [Lord]{.smallcaps}; and every dispute and every assault shall be settled by them. All the elders of that city which is nearest to the slain man shall wash their hands over the heifer whose neck was broken in the valley; and they shall answer and say, "Our hands did not shed this blood, nor did our eyes see it. Forgive Your people Israel whom You have redeemed, O [Lord]{.smallcaps}, and do not place the guilt of innocent blood in the midst of Your people Israel." And the bloodguiltiness shall be forgiven them. So you shall remove the guilt of innocent blood from your midst, when you do what is right in the eyes of the [Lord]{.smallcaps}.

Notice that even if the people are not guilty of slaying the man, nor of standing idly by when the crime was committed, they still bear responsibility before God for the innocent man's blood. They must investigate the death, ensure that justice is done as far as possible, make a sacrifice to atone for the blood, and, essentially, recommit themselves to protecting the innocent. Until they do all these things, God holds them responsible for bloodguilt.

### God's Hatred for the Shedding of Blood

Alongside God's command not to murder our neighbor and our obligation to deal with the shedding of innocent blood is God's promise of justice to all whose blood is shed. He will vindicate those robbed by the murderer of their lives. His retributive justice will fall on the murderer (Gen. 4:10; 9:5; Deut. 19:10). This promise of God's retributive justice against the manslayer is repeated throughout Scripture---from His condemnation of Cain for his fratricide (Gen. 4:10), to His overthrowing of the Canaanites whose bloodshed and child murder caused the land to vomit them out (Lev. 18:25), to the denunciation of King Manasseh for filling Jerusalem with blood (2 Kings 21:16), to the final judgment when God our Maker will judge and condemn the nations "drunk with the blood of the saints, and with the blood of the witnesses of Jesus" (Rev. 17:6).

God's retribution against those who shed blood is clear and severe. He has promised He will not hear the prayers of those whose hands are covered in blood (Isa. 1:15). He has promised to bring retribution on those who practice this evil, but also those who give bloodshed their hearty approval (Rom. 1:32). And specifically, He has promised He will set His face against, and cut off from His people, those who act as if they don't see or know about the shedding of the blood of innocent babies:

> Then the [Lord]{.smallcaps} spoke to Moses, saying, "You shall also say to the sons of Israel:
> 
> 'Any man from the sons of Israel or from the aliens sojourning in Israel who gives any of his offspring to Molech, shall surely be put to death; the people of the land shall stone him with stones. I will also set My face against that man and will cut him off from among his people, because he has given some of his offspring to Molech, so as to defile My sanctuary and to profane My holy name. If the people of the land, however, should ever disregard that man when he gives any of his offspring to Molech, so as not to put him to death, then I Myself will set My face against that man and against his family, and I will cut off from among their people both him and all those who play the harlot after him, by playing the harlot after Molech. (Lev. 20:1--5)

Not one drop of blood will be forgotten. When Cain killed his brother Abel, God said to Cain, "What have you done? The voice of your brother's blood is crying to Me from the ground" (Gen. 4:10). He has promised retribution against those who kill his prophets; that He will exact all their blood from Abel down to this present generation (Matt. 23:35). Finally, note particularly God's condemnation of the sons of Ammon for their heinous sin:

> Thus says the [Lord]{.smallcaps}, \
> "For three transgressions of the sons of Ammon and for four \
> I will not revoke its punishment, \
> Because they ripped open the pregnant women of Gilead \
> In order to enlarge their borders." \
> (Amos 1:13)

### God's Particular Hatred for the Shedding of the Blood of Children

Consider the eye-for-eye passage found in Exodus 21:22--25.[^166] Elsewhere in the law, punishment was only demanded when actual physical harm was brought upon one of the parties, but here restitution is required for the harm caused to the child (and thereby to the mother, father, and family). Whether "life for life" refers to mother or child, God opposes even the accidental bloodshed of the unborn.

The condemnation of child sacrifice is ubiquitous across the Old Testament, and what's horrible to read is that these condemnations are pronounced alike against the Canaanites and the sons of Israel.[^167] The people of Israel were surrounded by Canaanite religion and its demon gods worshiped through the sacrifice of the Canaanites' little ones. Molech worship required that a child be placed in the mouth of the god as a burnt offering. This is a sin so heinous to God that it is the only evil said never to have entered His mind (Jer. 32:35).

This ancient child sacrifice reached its nadir in Carthage where the burial ground Tophet, containing infants in their urns, was excavated, first in 1925, then again in 1970. It proved to be "the largest cemetery of sacrifice of humans ever discovered," containing infants' remains who were sacrificed over the course of six centuries. Archeologists have estimated that between 400 and 200 BC, as many as twenty thousand urns containing the remains of little children were buried there.[^168]

What was the nature of these child sacrifices? Here is a paraphrase of a description from an ancient Greek writer, Kleitarchos, during the third century BC:

> Out of reverence for Kronos [the Greek equivalent of Ba'al Hammon], the Phoenicians, and especially the Carthaginians, whenever they seek to obtain some great favor, vow one of their children, burning it as a sacrifice to the deity, if they are especially eager to gain success. There stands in their midst a bronze statue of Kronos, its hands extended over a bronze brazier, the flames of which engulf the child. When the flames fall upon the body, the limbs contract and the open mouth seems almost to be laughing, until the contracted [body] slips quietly into the brazier. Thus it is that the "grin" is known as "sardonic[^169] laughter," since they die laughing.[^170]

Tertullian, the church father of the late second and early third century AD, lived in Carthage and wrote:

> In Africa infants used to be sacrificed to Saturn, and quite openly, down to the proconsulate of Tiberius, who took the priests themselves and on the very trees of their temple, under whose shadow their crimes had been committed, hung them alive like votive offerings on crosses; and the soldiers of my own country are witnesses to it, who served that proconsul in that very task. Yes, and to this day that holy crime persists in secret. . . . Saturn did not spare his own children; so, where other people's [children] were concerned, he naturally persisted in not sparing them, and their own parents offered them to him, were glad to respond, and fondled their children that they might not be sacrificed in tears. And between murder and sacrifice by parents---oh! the difference is great![^171]

Now then, we read with some understanding this most awful judgment by God against His people spoken by His prophet Jeremiah:

> Thus says the [Lord]{.smallcaps}, "Go and buy a potter's earthenware jar, and take some of the elders of the people and some of the senior priests. Then go out to the valley of Ben-hinnom, which is by the entrance of the potsherd gate, and proclaim there the words that I tell you, and say, 'Hear the word of the [Lord]{.smallcaps}, O kings of Judah and inhabitants of Jerusalem: thus says the [Lord]{.smallcaps} of hosts, the God of Israel, "Behold I am about to bring a calamity upon this place, at which the ears of everyone that hears of it will tingle. Because they have forsaken Me and have made this an alien place and have burned sacrifices in it to other gods, that neither they nor their forefathers nor the kings of Judah had ever known, and because they have filled this place with the blood of the innocent and have built the high places of Baal to burn their sons in the fire as burnt offerings to Baal, a thing which I never commanded or spoke of, nor did it ever enter My mind; therefore, behold, days are coming," declares the [Lord]{.smallcaps}, "when this place will no longer be called Topheth or the valley of Ben-hinnom, but rather the valley of Slaughter. I will make void the counsel of Judah and Jerusalem in this place, and I will cause them to fall by the sword before their enemies and by the hand of those who seek their life; and I will give over their carcasses as food for the birds of the sky and the beasts of the earth. I will also make this city a desolation and an object of hissing; everyone who passes by it will be astonished and hiss because of all its disasters. I will make them eat the flesh of their sons and the flesh of their daughters, and they will eat one another's flesh in the siege and in the distress with which their enemies and those who seek their life will distress them."'" (Jer. 19:1--9)

We too must tremble at the wrath of God against our own filling of our place with the blood of our own innocents.

### The New Testament's Condemnation of *Pharmakeia*

Advocates of permissive abortion laws commonly argue that Scripture never addresses abortion. Aside from disregarding the texts of Scripture enumerated above, they also take no account of New Testament passages which condemn *pharmakeia* (Greek φαρμακεία) and those who pay for these services.

Words with this root occur five times in the New Testament. While the basic meaning of *pharmak*- is "drug," its derivatives have a broad semantic range encompassing "poison," medicinal and psychotropic "drugs," "potions," etc. These words often carry nuances of magic or the occult.

Most significant for our purposes, though, throughout the ancient world these words referred to drugs, potions, and spells that were associated with abortions.[^172] John Riddle, a pro-abortion Harvard scholar whose work has overturned prior assumptions about birth control in the ancient world, writes:

> Some statements by the Christians indicate that they did not approve of drugs employed for birth control. . . . In Galatians 5:20 Paul provides us with a list of sins of the flesh, and among them is the sin of *pharmakeia*, often translated into English as "sorcery" or "magic." . . . This is the same word that Socrates through Plato had used in reference to birth control: "drugs [*pharmakia*] and incantations." . . . There is likely a direct connection between the *pharmakia* [*sic*] of the New Testament and the "root poisons" of Hebrew literature.[^173]

English Bible translations have had difficulty expressing the range of *pharmakeia*'s nuances. It was not this way when Jerome produced his fourth-century Vulgate. He translated this word into Latin as *veneficium*, and here, the Latin closely matches the Greek, admirably preserving the choices possible among *pharmakeia*'s variable meanings. In English, though, we have nothing close to these Greek and Latin words, so translations have overly emphasized the occult element, translating *pharmakeia* as "witchcraft" (KJV) or "sorcery" (more recent translations).

Why have scholars translated *pharmakeia* as "sorcery"?

In the ancient world, many of the categories we think of as distinct were blurred. This is particularly evident reading the medical authorities of the time. Like us (especially if they were what we might refer to as middle or upper class), they would consult a doctor about their illness. But unlike us, they might also hire a conjurer---someone with spiritual power who used incantations in conjunction with chemicals we today refer to as "drugs." In other words, the line between medicine and magic was blurred in a way it isn't for us today.

Moderns are tempted to sever the body from the soul, thinking medicine has only to do with the body. We congratulate ourselves on having arrived at a time when medicine is an entirely empirical science.[^174]

Not so in the ancient world where the spiritual and physical were inseparable. Commitment to specific deities of Greco-Roman polytheism varied over time, but overall, men were acutely aware of the spiritual. The Apostle Paul made this simple observation:

> For our struggle is not against flesh and blood, but against the rulers, against the powers, against the world forces of this darkness, against the spiritual forces of wickedness in the heavenly places. (Eph. 6:12)

Concerning conception and childbirth, the intermingling of flesh and blood and the spiritual forces of wickedness was not yet subjected to any post-Enlightenment hermeneutic.

The ancient world lived for children in a way our world finds incomprehensible. They had higher rates of fertility, and mother and child faced much higher rates of death during childbirth.[^175] Childbirth was far more dangerous for them than for us today.

But whereas a woman today would rest her confidence in all kinds of "specialists," including her gynecologist, obstetrician, and midwife, in the ancient world a single figure often performed these roles. For the upper (and perhaps middle) class, that might have been a doctor; for the lower classes, more often it was a midwife (even a family member).

Thus when we consider the practice of *pharmakeia*, we must not think in modern medical terms---say, for instance, physicians and pharmacists. *Pharmakeia* did not include FDA-approved drugs whose agency and side effects were researched, graphed, and charted. It is more accurate to think of a shaman or medicine man, someone who is as connected to the occult as he (or she) is to medicine. In other words, the biblical prohibition of *pharmakeia* was closely connected to the prohibition of the occult.

In Greek, the terminology used to designate these figures is often ambiguous. A number of terms are used, including *mageos*, *pharmakeus,* and *pharmakos*.[^176] Their semantic range is broad and overlaps. Such figures sold both drugs and incantations. They were as mindful of the spiritual as they were of the physical, for potions and incantations both accessed and manipulated the spirit world.

For this reason, Scripture forbids *pharmakeia* to the people of God. God's people are to have nothing to do with magic, mediums, incantations, amulets, and potions. The members of Christ's church are not to make the slightest effort to access or control the "secret things" of God (Deut. 29:29). Manipulation of this unseen world is a crime among God's covenant people of the Old Testament, and the New Testament condemns these practices also.[^177]

The book of Acts records the interface of such occult practices and practitioners with the church of the Apostles in its record of the conversion and subsequent sin of Simon Magus:

> Now there was a man named Simon, who formerly was practicing magic [*mageuōn*] in the city and astonishing the people of Samaria, claiming to be someone great; and they all, from smallest to greatest, were giving attention to him, saying, "This man is what is called the Great Power of God." And they were giving him attention because he had for a long time astonished them with his magic arts [*mageiais*]. But when they believed Philip preaching the good news about the kingdom of God and the name of Jesus Christ, they were being baptized, men and women alike. Even Simon himself believed; and after being baptized, he continued on with Philip, and as he observed signs and great miracles taking place, he was constantly amazed.
> 
> Now when the apostles in Jerusalem heard that Samaria had received the word of God, they sent them Peter and John, who came down and prayed for them that they might receive the Holy Spirit. For He had not yet fallen upon any of them; they had simply been baptized in the name of the Lord Jesus. Then they began laying their hands on them, and they were receiving the Holy Spirit. Now when Simon saw that the Spirit was bestowed through the laying on of the apostles' hands, he offered them money, saying, "Give this authority to me as well, so that everyone on whom I lay my hands may receive the Holy Spirit." But Peter said to him, "May your silver perish with you, because you thought you could obtain the gift of God with money! You have no part or portion in this matter, for your heart is not right before God. Therefore repent of this wickedness of yours, and pray the Lord that, if possible, the intention of your heart may be forgiven you. For I see that you are in the gall of bitterness and in the bondage of iniquity." But Simon answered and said, "Pray to the Lord for me yourselves, so that nothing of what you have said may come upon me." (Acts 8:9--24)

Scripture does not explicitly designate Simon Magus as one who practiced *pharmakeia*, yet he well may have. It is not easy for us to be done with our lucrative past, so naturally Simon's temptation to continue profiting from manipulating the spiritual realm of secret things manifested itself immediately following his conversion. This temptation was also present in the church at large. Simon Magus was not a one-off, but representative of a larger danger among the people of God, and thus Scripture's New Testament condemnations of sorcery, whether the manipulation of the unseen world was referred to as *mageia* or *pharmakeia*.

Thus far, we have unpacked the nature of *pharmakeia* in the ancient world, focusing on its usage by *mageoi* and other occult figures. What remains, then, is to consider the specific instances of *pharmak*- words in Scripture and related documents, opening up the fact that "witchcraft" and "sorcery" don't give moderns a full enough picture of the sins being condemned.

Most of us have never known a sorcerer. Such figures remain within the realm of fairy tales or Disney movies. We think of the old man or woman with a hat, maybe with a magic wand, maybe standing over a cauldron, but of course we're sure such figures perished with the medieval world. Though the ancient *mageos* or *pharmakeus* did use spells and lurked in the shadows, they were far more common than we might think, with wide swaths of society employing their services. More to the point, *pharmakeia* included things we today do not think of as sorcery.

Given the universal importance of the fruitful womb in the life of man, few things were more subject to the desires to employ magic or occult control through *pharmakeia* than sex, marriage, conception, and childbirth---and this desire for control was both positive and negative. Women desired to possess a man as their husband or lover,[^178] women desired to conceive a child,[^179] women desired their child to be born safely; but women also desired a lover other than their husband,[^180] as well as the prevention of their own conception and birth of the children they were carrying in their womb. Further, evil women employed magic's potions and incantations for the purpose of destroying other women's marriages, conceptions, and safe childbirths.[^181] Thus *pharmakeia* was bound up with love, sex, and childbirth. In a world where the processes of life and death were recognized as obscure and under the gods' control, those who could manipulate the levers of such divine powers also dispensed the *pharmaka*.

These men and women, then, had a specialized, and often occult, trade. They were marginal figures bearing some resemblance to yesterday's medicine men or snake oil salesmen, or today's theosophists, practitioners of mindfulness and yoga, naturopathic and holistic doctors, and faith healers.

In the ancient world, those intent on preventing pregnancy or aborting their children purchased their potions from similar marginal figures. Statistics on this are unavailable, but sources indicate the number of people making use of these *pharmaka* was significant. We also know that, even in the church, converts to the Christian faith included mothers (and fathers) who had aborted their children.[^182] Luke records the conversion of Simon Magus, showing that the New Testament church did not just include former fornicators, idolaters, adulterers, effeminate, homosexuals, thieves, covetous, drunkards, revilers, and swindlers,[^183] but also *mageoi*. As there were *mageoi*, so the church also included those who formerly had employed the *mageoi*, and thus were tempted to continue to employ their services.

We have the historical record of Simon's temptation to continue his practice of magic, but we also have a New Testament record of the ongoing temptation of Christians to pay for those services, including *pharmaka* used to murder their children.

This explains Scripture's warnings not being limited to the practice of magic, generally, but also *pharmakeia*, specifically. New Christians had paid the so-called *pharmakoi*, but also doctors and midwives, all of whom commonly dispensed *pharmaka* for the purpose of killing preborn children. Following the practice of the pagans who were their neighbors, Christians made use of *pharmakeia*, and thus had to be warned against it by the Apostle.

But if with *pharmakeia* we only think of a wizard in a pointy hat and miss the fact that abortion is the reality that often underlies the use of *pharmakeia*, we do not fully grasp the weight of Scripture's condemnations. Consider Galatians 5:19--21:

> Now the deeds of the flesh are evident, which are: immorality [*porneia*], impurity [*akatharsia*], sensuality [*aselgeia*], idolatry [*eidōlolatria*], sorcery [*pharmakeia*], enmities, strife, jealousy, outbursts of anger, disputes, dissensions, factions, envying, drunkenness, carousing, and things like these, of which I forewarn you, just as I have forewarned you, that those who practice such things will not inherit the kingdom of God.

Here, the first three terms pertain to sexual immorality of various sorts. The next term, idolatry, also has here a likely sexual component, given that pagan temple worship was often associated with sexual immorality. Next is *pharmakeia*, followed by seven terms that do not pertain to sexual immorality, but rather to "relational" sins.

Note the clear pattern and order of these terms. Where does *pharmakeia* fit in? It doesn't fit with the "relational" sins mentioned, such as jealousy, wrath, and ambition. But keeping in mind *pharmakeia* was employed for contraceptive and abortifacient purposes, its presence next to sexual sins is natural, for then the Apostle here condemns, first, the general category of impurity (*porneia*), then the specific manifestations of that impurity (adultery and lasciviousness), then idolatry (almost always at the core of sexual sin); and finally, the use of contraceptive/abortifacient potions to destroy the evidence of these sins.

All the above opens up the nature of *pharmakeia*, and we now have some understanding why it is translated into English as "sorcery." Killing the little one bearing the image of God safely nestled in his mother's womb prevents the normal course of nature, and thus defies our Creator who Himself gives life, the womb, and safe delivery to His little ones.

Consider also Revelation 9:21:

> And they did not repent of their murders or their sorceries [*pharmakeia*] or their sexual immorality or their thefts.

Here again, note *pharmakeia* is placed immediately between "murders" and "sexual immorality." Compare Revelation 21:8 where again the *pharmakoi* are listed alongside "murderers," the "sexually immoral," and "idolaters."[^184]

Perhaps most revealing of the contraceptive and abortifacient nature of *pharmakeia* is evidence from the contemporaneous (AD 50--100) *Didache*. In its second chapter, this most ancient of the non-canonical documents of the church forbids a number of "grave sins":

> You shall not commit murder, you shall not commit adultery, you shall not commit pederasty, you shall not commit fornication [*porneuseis*], you shall not steal, you shall not practice magic [*mageuseis*], you shall not use potions [*pharmakeuseis*], you shall not murder a child by abortion [*phoneuseis teknon en phthora*], nor kill it after it is born [*gennēthen apokteneis*].[^185]

This passage is especially helpful because the terms we've been discussing are placed in close proximity, yet also distinguished. *Mageuseis*, "practice magic," refers to a broad array of occult practices. *Phoneuseis teknon en phthora* and *gennēthen apokteneis* in the last two clauses forbid, respectively, abortion and infanticide. But then, right between *mageuseis* and the mention of abortion and infanticide is *pharmakeuseis*. What does this mean?

It could be another condemnation of "sorcery" (i.e., restating *mageuseis*), yet no other sin is repeated in this list. There's little reason to take *pharmakeuseis* as synonymous with *mageuseis*, nor with the condemnations of abortion and infanticide that follow.

The better choice exegetically is to understand this reference to *pharmakeuseis* to be the condemnation of any dispensing or use of the agents of a *pharmakos* (denounced likewise in Revelation) for contraceptive/abortifacient purposes. Such agents would generally have been in an occult context, though *pharmakeuseis* here condemns *all* uses, whether occult or not. Here, we've translated it "use potions," and this is a good, broad translation. What it condemns would then include (1) chemical contraceptives, (2) abortion (whether chemical or surgical), and (3) incantations or other tools of an occult *pharmakos*.

This understanding gives insight into the *Didache*'s thought progression. Knowing that "practice magic" (*mageuseis*) could encompass giving of potions (or poisons), abortion, and infanticide, what follows *mageuseis* could express a progression of time: *pharmakeuseis* indicating the first attempt to destroy the child, *phoneuseis teknon en phthora* the abortifacient recourse when the *pharmaka* failed, and *gennēthen apokteneis* being the final solution. Or, the continuum could express the ancients' awareness of the little one's development: the broad, mysterious *pharmakeuseis* representing the uncertainty of conception and how *pharmakeia* functioned; *phoneuseis teknon en phthora* making it clear that what was at issue was flesh and blood, a *child* (*teknon*), and he was being *murdered*; and finally, *gennēthen apokteneis* showing the sin in all its nakedness, for the child had been *born*. As our awareness of our sin's severity grows, so does the iniquity if we follow through. The *Didache*'s progression, from magic to potions to abortion to infanticide, recognizes this.

Given how close the *Didache* is in date, vocabulary, and style to the New Testament, we should assume that the NT uses *pharmakeia* and related terms in a way similar to that found in the *Didache*. Thus when Scripture condemns the use of *pharmakeia*, it is not simply sorcery as we understand it that's being condemned, but the related use of contraceptive/abortifacient potions.

## Dealing with Common Justifications for Abortion

<div id="fninfo" data-fnstart="91"></div>

### Rape and Incest

Readers who consider themselves strongly "pro-life" may yet be uncomfortable with the complete repeal of legalized abortion because of concern for the well-being of women who are pregnant as a result of rape and incest.[^186] Should abortion be legal in these cases?

Even the discussion of these exceptional cases is dangerous. Pro-lifers have many scars they can show from times they've been foolish enough to condemn the killing of babies conceived in rape and incest. If they refused to modulate their position, the attack was vicious and left them tarred and feathered as an extremist, a monster.[^187] Questions fly: "Why should a woman have to bear the consequences of her violation? Isn't this validating the sin of the rapist? How can anyone countenance requiring a woman to gaze, day after day, at this child who is a living reminder of the wicked man who violated her?"

The objections are weighty, but let's bring them into the light of day and examine them.

First, the proportion of abortions due to rape or incest is miniscule. For example, in Germany, the percentage of abortions related to rape or incest is around 0.02 percent annually.[^188] In the United States, to the extent that such statistics are available,[^189] the numbers are similar: less than 0.5 percent are related to a prior rape.[^190] We remember the legal maxim that hard or exceptional cases make bad law when we realize how exceedingly rare abortions due to rape and incest actually are, comprising much less than 1 percent of abortions. Such hard cases should not be allowed to form our nation's laws on abortion.

But leaving the question of law to the side, are there good reasons not to kill the little one conceived by rape and incest?

First, a word of caution. Since this question is fraught with emotion issuing from some of the most painful circumstances of life, it's difficult to discuss without surrounding that discussion with pastoral care that is sensitive and ministers to readers the compassion of our Lord for the oppressed and those who suffer. We do work to demonstrate His compassion and tenderness, but we know our efforts will fail to satisfy the needs of readers---needs that are wholly legitimate.

Two things, then: First, please understand that this document is completely taken up with consideration of parts of life and death which have caused many readers great anguish. In many cases such persons are inconsolable separate from the comfort of the Holy Spirit. "In the midst of life, we live in death," as the *Book of Common Prayer* states in the committal service at graveside. Rape, incest, and abortion are each part of that death. So yes, like abortion itself, rape and incest cause their victims awful suffering, and we write in full awareness that reading this discussion of these things will add to the suffering of those harmed by these crimes. Given it is true those who have suffered rape or incest are innocent of the crime while those who have committed abortion are guilty of the crime, discussion of these crimes will for many be torment. Yet discuss we must---because all these things are a matter of truth and falsehood, righteousness and wickedness, life and death. It is not possible to proceed with any discussion of the wickedness of abortion, rape, and incest without faith that truth is glorious and needs no justification, whether its discovery and recognition lead to joy or pain. God has fashioned truth in such a way that it is indispensable to the healing of sin and the pain it causes, whether that sin is others' or our own.

Second, the church is our household of faith and we need her ministry and instruction particularly while considering the subject of this document. The world will be of little help to us, but the church of Jesus Christ will teach and clean and exhort and rebuke and encourage and comfort us as she has every generation since her birth at Pentecost. Considering and repenting of abortion is a work to be done in community.

We have no illusion our arguments here can both convince and console. Nevertheless, these arguments *must* be marshaled and presented to the church if her members are to repent and give themselves to the protection of mothers and their children. Making those arguments requires raising these painful matters of rape and incest because, over the past half century, no justification of the murder of little ones in their mother's womb has been more constant and effective than the supposed necessity of the deaths of babies conceived by rape and incest. So now, we turn to it, asking our readers' understanding for the necessity of our discussion being less than exhaustive.

To begin, then, note that the arguments against abortion made throughout this chapter also apply to abortion in cases of rape and incest. Any murder attacks the image of God He has placed in each child, regardless of the circumstances of that child's conception. Abortion is a crime against society, destroying the bonds of mutual obligation and fellowship we share, regardless of the circumstances of our conception. Any abortion destroys a human being---the greatest natural resource God has placed on His green earth. Any and every abortion has been universally condemned by church fathers through two millennia and is a heinous crime against nature, man, and God.

Beyond the above, to use the circumstances of the conception of a child as justification for the murder of that child is a denial of a fundamental principle of justice, that we are to protect the innocent and punish the guilty. Who is more guilty than the rapist, and who is more innocent than the unborn child?[^191] To kill an unborn child conceived in rape punishes that little one and her mother---not the rapist. Far from being a just and merciful alleviation of suffering, it multiplies the violence already surrounding this violent crime.

Many Christians are sympathetic to arguments in favor of aborting little ones conceived through rape and incest, but why? What is the nature of our vulnerability to this tactic of the abortionists?

There are several explanations for this vulnerability:

(1) As Christians, we feel intense pressure to state repeatedly that we share our culture's commitment to viewing rape as the highest, most horrible crime of violence against woman. It's as if we have to prove Christians are, in fact, concerned and respectful toward women, and never mind that all prior generations of Christians condemned rape as a heinous crime and subjected those committing it to the most severe penalties.[^192]

Never mind that all past generations of Christian fathers, husbands, and sons loved, cared for, and defended their mothers, wives, and daughters. Never mind the records across Christendom of their grief over the terrible, lifelong suffering of women who had been raped. Why is this not enough for us today? Christians feel the need to prove their respect for women by joining the mob's attack on the innocent child, executing that child for the crimes of her father. Have we forgotten God's words to Ezekiel?

> The person who sins will die. The son will not bear the punishment for the father's iniquity, nor will the father bear the punishment for the son's iniquity; the righteousness of the righteous will be upon himself, and the wickedness of the wicked will be upon himself. (Ezek. 18:20)

We have not progressed in our moral discernment and compassion above our fathers and mothers in the faith before us. Rather, showing ourselves attentive and concerned for the violence of rape inflicted on the mother by condoning the killing of her child conceived through that act is proof our moral discernment and compassion have decayed. Even if our concern were limited solely to the mother, and not the child, do we not recognize this child shares her mother's DNA---that in every sense of the word, she is her mother's child? The execution of the mother's child for the sins of the child's father is a more violent attack on womanhood than rape.

In his *City of God*, Saint Augustine speaks of the comfort women who are the victims of the violence of rape may take in their undefiled chastity. He continues:

> A woman who has been violated by the sin of another, and without any consent of her own, has no cause to put herself to death . . . for in that case she commits certain homicide [for] a crime which is . . . not her own.[^193]

If it is homicide for a mother to kill herself for the crime of another, it is also homicide for that mother to kill her baby for the crime of another. Certainly it seems harsh to warn a victim of rape against committing homicide, but this warning is needed. The temptations to utter despair and the crimes attendant upon such despair in the life of man and woman must be anticipated and warned against. These warnings are the fruit of our understanding, love, and compassion.

In our pastoral care, we must not have one eye on our reputation among worldlings and pagans, and another on God. Keep in mind what may be our Lord's most sober warning:

> Do not fear those who kill the body but are unable to kill the soul; but rather fear Him who is able to destroy both soul and body in hell. (Matt. 10:28)

Rape does terrible violence to the body and soul of the woman, but there is no crime more awful than murder, which Scripture demonstrates by revealing the place "murderers" will be cast on the Day of Judgment:

> But for the cowardly and unbelieving and abominable and murderers and immoral persons and sorcerers and idolaters and all liars, their part will be in the lake that burns with fire and brimstone, which is the second death. (Rev. 21:8)

The point is not that abortion is such an awful crime against man and God that it is beyond the mercy of God in Jesus Christ. No and never! The blood of Jesus doesn't cleanse us from little sins or some sins, but "all" sins. Right here, given the tendency we have to minimize the sin of murder by maximizing the sin of rape, let us hear the word of God concerning our tendency to deny our own sin and refuse to confess the evil we ourselves have done, and also our tendency to consign some sins and sinners to being beyond any forgiveness:

> If we say that we have fellowship with Him and yet walk in the darkness, we lie and do not practice the truth; but if we walk in the Light as He Himself is in the Light, we have fellowship with one another, and the blood of Jesus His Son cleanses us from all sin. If we say that we have no sin, we are deceiving ourselves and the truth is not in us. If we confess our sins, He is faithful and righteous to forgive us our sins and to cleanse us from all unrighteousness. (1 John 1:6--9)

(2) Another explanation for our vulnerability to arguments in defense of liberalized laws on abortion is that we can identify with the woman's suffering, but not the baby's. It is likely each of us knows a woman who has suffered this outrage. Our wife, our daughter, our mother. Those of us who are women can place ourselves in that situation; those of us who are men can sympathize to some extent because of our love for these women. Still, none of us can place ourselves in the womb with the unborn child. It is a hidden world unknown to us, and the child that lives in it for nine months is someone who cannot speak as her own advocate. So when the Deceiver comes to us and insinuates that the suffering of the woman takes precedence over the right of the unborn child to life, we're suckers. Our heart is bound up with the woman there in front of our eyes---not with the child who remains unseen and unheard. Thus we become guilty of the superficial judgment our Lord warns us about: "Do not judge according to the appearance, but judge with righteous judgment" (John 7:24).

(3) Another explanation for our vulnerability is our belief that it is unjust for us to suffer consequences for the sins of others. Increasingly, it is true that many of us think *grace* means freedom from consequences of any sin by anyone. But if going there is a bridge too far, we'll concede that Scripture teaches that *our own* sins have consequences. Samson and his libido. David and Bathsheba. Ananias and Sapphira. But bearing the consequences of *others'* sins? No way. The just God would never require that of anyone.

Yet He is just and He does require it. Scripture is full of such examples, from national and societal judgments (the Flood, the Canaanites, Israel, etc.) to sins whose punishment God visits upon families. This continues in our own day. When we are made late to work because of the traffic caused by a careless accident or a speeder. When the used car we bought turns out to have a dying engine because the seller never changed the oil. Sometimes it's more serious: When our father's coldness leaves us longing for affection. When we lose our home because of arson. Or even when we're injured because of a drunk driver. All through our lives, we suffer because of the sins of others. We may protest, arguing this is unjust; we may complain against God; but in the end, it's to no avail. No matter how big the consequence we think we've suffered, there's one that's far greater that every man has already suffered, and by God's decree: the imposition of God's curse upon each of us for our father Adam's sin. In light of this imputation of Adam's sin upon every woman and man, all our complaints of the injustice of the thing fall short.

So yes, the violation of a woman's soul and body at the hands of rape is a tragedy. It's a vile evil. It's a crime deserving of the harshest condemnation which ought to provoke our most tender compassion for its victim. But we may not conclude from this that we have a right to a life free from the consequences of others' sins. God disposes as He sees fit, and His arrangement of even the sins against us is done in His perfect will. He sees the end from the beginning. He also knows what each of us is able to endure the trials He sends our way (1 Cor. 10:13).

(4) Finally, we are vulnerable to arguments in favor of abortion in cases of rape and incest because we think large thoughts of our own justice, but small thoughts of God's ability to bring fruit out of suffering, not to mention His everlasting promise to bring every deed into the light at that great Day of Judgment.

Our thoughts and conceptions of justice are small and limited, but God's are perfect. He specializes in bringing light from darkness, life from death, and fruit from desolation. This is the testimony found across Scripture. We see it in the Garden where Adam's sin and condemnation bring with them the hope of future redemption through the seed of the woman. We see it in Joseph and his brothers, where the wickedness of his brothers leads to the sparing of God's people, but also the protection of the nation of Egypt from famine. As Joseph testifies, "God meant it for good" (Gen. 50:20).

Consider what is perhaps the most relevant case in Scripture which is one of the most sordid incidents in Scripture---the incest between Lot and his two daughters. Even in comparison to other sins in Scripture, this one stands out for its horror. It seems to us a filthy climax to Lot's descent, the final defilement of his body, name, and posterity, mating and producing children by lying with his own flesh and blood.

Yet that is not all of the story, for the account ends, not with Lot's nor his daughters' sin, but the fruit that resulted from that sin---in this case, the peoples of the Moabites and Ammonites that sprang from Lot's incestuous unions. Despite Lot's sin, despite his daughters' wickedness, God (as He does throughout Scripture) still grants them children who go on to become two great peoples.

"Some privilege!" the attentive reader of Scripture might say, for the Moabites and Ammonites were not God's chosen people, but Israel's enemies. But once again, this too is *not* the end of God's story. For out of the vile Moabites God was pleased to bring godly Ruth, as well as her great-grandson who was a man after God's own heart. His name was David, and from David's line our Lord Jesus Christ descended. We may think it undignified to have the bloodline of our Lord extend back through Lot's daughters and their incest, yet here we have another example of God confounding the wisdom of the wise. Faithless men view Lot's sin with despair. But in God's economy, nothing is wasted. He is the steward of suffering and habitually produces fruit from that suffering.

Back in 1971, countercultural icon and author of *One Flew Over the Cuckoo's Nest*, Ken Kesey, gave an interview to Paul Krassner, publisher and editor of the national alternative journal *The Realist*. During the interview, the subject of abortion was raised---specifically abortion in the case of rape:

> *Q. And yet, since you're against abortion, doesn't that put you in the position of saying that a girl or a woman must bear an unwanted child as punishment for ignorance or carelessness?*
> 
> A. In as I feel abortions to be probably the worst worm in the revolutionary philosophy, a worm bound in time to suck the righteousness and the life from the work we are engaged in, I want to take this slowly and carefully. . . .
> 
> . . .
> 
> Punishment of unwed mothers? Bullshit! Care of neither the old nor the young can be considered to be punishment for the able, not even the care of the un-dead old or the un-born young. These beings, regardless not only of race, creed and color but as well of size, situation or ability, must be treated as equals and their rights to life not only recognized but *defended*! Can they defend themselves?
> 
> You are you from conception, and that never changes no matter what physical changes your body takes. And the virile sport in the Mustang driving to work with his muscular forearm tanned and ready for a day's labor has *not one microgram more* right to his inalienable rights of life, liberty and the pursuit of happiness than has the three month's foetus riding in a sack of water or the vegetable rotting for twenty years in a gurney bed. Who's to know the value or extent of another's trip? How can we assume that the world through the windshield of that Mustang is any more rich or holy or even sane than the world before those pale blue eyes? How can abortion be anything but fascism again, back as a fad in a new intellectual garb with a new, and more helpless, victim?
> 
> I swear to you, Paul, that abortions are a terrible karmic bummer, and to support them---except in cases where it is a bona fide toss-up between the child and the mother's life---is to harbor a worm of discrepancy.
> 
> *Q. Well, that's really eloquent and mistypoo, but suppose Faye [Kesey's wife] were raped and became pregnant in the process?*
> 
> A. Nothing is changed. You don't plow under the corn because the seed was planted with a neighbor's shovel.[^194]

As moderns, we recoil at Kesey's terrible insensitivity, as we see it. Hearing him speak of the fruit of the rapist's sin horrifies us. How dare he speak of his wife's potential rape in such gross agricultural terms! How dare he attribute any blessing or fruit to rape!

As we ask our questions, it may become clear to us that our concern is not so much with life as it is with shame. The woman who suffers rape becomes covered with shame. She can't help herself. Her shame makes her want to die. Such shame requires something heavy. Something on the order of the sacrifice of her child. This shame cannot be healed or removed by talk of some hypothetical goodness or fruit proceeding from the rapist's violent and filthy ruination of her.

But shall we stop our train of thought long enough to consider that God's thoughts are not ours? That all of His attributes exist in perfect harmony, and thus there is no tension between the justice due the rapist and the justice due the mother and innocent child:

> The [Lord]{.smallcaps} has prepared everything for His purpose--- \
> even the wicked for the day of disaster. \
> (Prov. 16:4, HCSB)

The rapist has his coming day of reckoning, if not by the state performing its duty, then by God carrying out His prerogative. Meanwhile, both the rapist's crime and God's punishment of him will conform to *God's* purposes, and not our own.

This is hard for us to fathom. We comfort ourselves with the lie that such terrible evils are outside God's appointments. Actually, though, this is no comfort at all, for then we are left with unchecked evil and a powerless or compassionless God.

In the end, we must face the God Who Is---not the idol we make of Him in our own mind. This *true* God is never the author of sin,[^195] but neither is He a passive observer watching sin wreak its havoc. In His economy, the woman who suffers rape is not simply doomed to an interminable shame and victimhood from that moment onward. The God who forgives sin also heals shame, calling His redeemed ones to find their honor and glory in His adoption of them as His sons and daughters. He restores the years the locusts have eaten---and often that restoration comes in the form of new grain, new fruit, and new life brought about through others' sins against us.

This is a message of true compassion. It is not the compassion of the world, which postures itself as love for others while refusing to declare the truth. Rather, this is the true charity that mourns the indignity and outrage of rape and grieves with women and children, while also refusing to let their lives be consumed by it.

The true love that fully recognizes the terrible violation of woman such evil does will not be overcome by attacks upon God or the unborn little one, but only by the sustaining mercy of Christ. This true compassion will lead the sufferers to Christ. For Jesus knows what it is to be attacked, what it is to be innocent and violently abused, and what it is to commit His soul to the keeping of the One who is righteous. "With men this is impossible; but with God all things are possible" (Matt. 19:26).

### Health of the Mother

After all the other arguments above, the final accusation abortionists throw at pro-lifers often sounds something like this:

> You men are so fixated on women giving you as many babies as possible that you couldn't care less about their difficulties in pregnancy and childbirth! All you care about is babies and more babies. Even if her baby is killing her, you tell the mother she has to stay pregnant. She can't have an abortion even if it saves her life. She has to die so the baby can live. That's how insane you are!

Now maybe the many decades of our combined years in the anti-abortion movement aren't typical, but through those years we do not remember hearing any pro-lifer saying (or writing) that a mother must be told to die herself if a doctor tells her it's between her and her baby. Pro-lifers are quite reasonable and loving, and their love for babies is not greater than their love for mothers.

Anyhow, it's never going to be constructive during polemics with abortionists---speaking from the malice of their bloodguilt---for the Christian to try to have a rational discussion of various threats to a pregnant woman's health and the connection those threats may or may not have to the continuation of her pregnancy. For abortionists, this accusation is only a ploy. It's never a real argument.

Another thing to keep in mind is the tendency of abortionists to blur any distinction between mental and physical health and life. When they speak of "health of the mother," abortionists usually are referring to both the physical and emotional health of the mother. To them, both physical health concerns and mental health concerns are sufficient justification for killing the little ones.

Recall that this was the state of affairs prior to *Roe v. Wade*. At the time, abortion was largely legal for the purpose of protecting the emotional health of the mother---not just her physical health. One year prior to *Roe v. Wade*, back in 1972, abortion's death toll was already 586,760. What this shows is the limited protection our little neighbors have from death if the mother declares her emotional well-being is at stake.

If abortion were outlawed for reasons other than protection of the life of the mother, it's likely "life of the mother" would, in practice, be viewed expansively in its application in order to include threats to the mother's life due to mental health vulnerabilities, and many abortions would then be performed under these rubrics.

This is particularly so given the fact long known among medical professionals that no preborn child's death is necessary to save the life of his mother. Physicians both pro-life and pro-abortion have testified to this simple truth for decades now, and it has only become more true as those decades passed. Here's C. Everett Koop:

> Protection of the life of the mother as an excuse for an abortion is a smoke screen. In my 36 years in pediatric surgery I have never known of one instance where the child had to be aborted to save the mother's life.
> 
> When a woman is pregnant, her obstetrician takes on the care of two patients---the mother-to-be and the unborn baby. If, toward the end of the pregnancy complications arise that threaten the mother's health, he will take the child by inducing labor or performing a Caesarian section.
> 
> His intention is still to save the life of both the mother and the baby. . . . Because [the baby] has suddenly been taken out of the protective womb, it may encounter threats to its survival. The baby is never willfully destroyed because the mother's life is in danger.[^196]

On the pro-abortion side, father of Planned Parenthood Alan F. Guttmacher corroborates this understanding:

> Today it is possible for almost any patient to be brought through pregnancy alive, unless she suffers from a fatal illness such as cancer or leukemia, and, if so, abortion would be unlikely to prolong, much less save, life."[^197]

Decades ago, the evidence and testimony of both pro-life and pro-abortion physicians made it clear that mothers carrying their babies to term would not jeopardize the lives of their mothers regardless of the sickness or disease any mother contracted or was living with during her pregnancy. So the accusations of abortion promoters and supporters that pro-life men and women say such mothers have a duty to die to save the life of those children is a bald-faced lie. There are no such mothers. There are no such children.

Yet there are mothers who face decisions involving certain risk factors connected with their lives and the lives of their babies, and we have read testimonies of such mothers choosing to put off certain medical treatments needed for their terminal illnesses because those treatments posed a threat to their baby.[^198] These mothers have cried out to God for healing of their sickness so they can carry their little one to childbirth and life. Their doctor has explained that putting off treatment of their cancer, for instance, might hasten their death, but the mother refuses radiation, instead pleading with God for her own life and the life of her child. She has declined treatment rather than to risk harm to her child. She will speak of her love for her baby. She will remind those reading or listening how Jesus said no man has greater love than to lay down his life for a friend. She may recount how this statement of Jesus made the decision clear to her and her husband.

We ask ourselves if this is good or bad. Many things would have to be considered if one of us were to be faced with the same decision. The relative risk. The desire of one's husband. The number and ages of any children who would be left motherless. The counsel of the older women of the church, the pastor, and the elders. Whether the doctor was a Christian. Whether the baby was close enough to viability that holding out a couple weeks and taking her by Cesarean section would be an option, allowing radiation to start earlier. The list could go on.

Not one of us, though, would have the desire or claim the authority to take this life-and-death decision out of the mother and father's hands. Christians repeat our Lord's command to take up our cross and follow Him, but this is a far cry from one believer declaring to the pregnant Christian mother the specific cross she must take up is foregoing cancer treatment so that her unborn child will not be endangered by the radiation. None of us can imagine saying to such a Christian mother that her baby takes precedence over her, nor that foregoing radiation (for instance) is what Jesus means when He commands us to take up our cross for His sake. Rather, we would understand and agree with this mother if her treatment posed some level of risk to her baby, but she chose to proceed with that treatment.

The mother's and baby's lives are inextricably intertwined, and there are times when to save the mother's health and life is to save the baby's health and life. There are also times when treatments to save the mother's health and life pose an equal risk to herself and her baby, yet the decision will be made to proceed with that treatment recognizing that if the treatment ends up killing the child, this was in no way the intent of the physician or of his patient capable of full consent, the mother.[^199] They both knew he had two patients and everything was considered and done to protect the well-being of both patients, but in the end the second patient, despite their best efforts to keep it from happening, died. In this case, the physician, father, and mother can all take comfort from their vigilance to protect both the mother and her child, knowing the succeeding death of the child was neither their intent nor their fault. They acted wisely and by faith in God's care for both mother and child, and God's decree was that the mother would live and the child would die. The Lord giveth, the Lord taketh; blessed be the name of the Lord (Job 1:21).

This discussion emphasizes the necessity of reminding physicians and one another that when we treat a pregnant mother, our treatment inevitably treats her child also. Pharmaceutical corporations know this very well and are vigilant to warn physicians, pharmacists, and customers of the danger their products pose to babies in the womb of the mother ingesting those products. Everyone knows pregnant mothers should not smoke or drink if they desire to protect the little child in their womb. When a child is listening to her mother's songs, feeling her mother's movements, sensing her mother's joy and pain, eating her mother's food, sharing her mother's oxygen, and swimming in her mother's amniotic fluid, her health is inseparable from her mother's health.

The doctor who prescribes medicine or treatment for the mother knows this very well, being motivated to know it by the potential of a malpractice suit if she or he prescribes a drug or treatment which produces fetal anomalies in that child, leaving the child disabled when she enters this world.

Physicians also know it because, over the course of the 1970s, amniocentesis became the standard of care for pregnant mothers older than 35 years of age.[^200] This was due to their considerably higher risk of giving birth to children with Down syndrome or aneuploidy.

Today the physician must provide their patient with the options of amniocentesis, chorionic villus sampling, or more often cell-free fetal DNA screening,[^201] along with other fetal diagnostic procedures that protect the right of the parent (and yes, also the child) to exercise the option of termination of pregnancy in order to prevent what is legally referred to as "wrongful birth" and "wrongful life."

Malpractice suits are filed by both parents and children accusing physicians of neglecting to follow standards of care which would have made a diagnosis and termination of pregnancy possible, thus preventing the birth of a child of low quality of life because of a defect which might otherwise have been diagnosed in the womb.[^202] In 1990, over thirty years ago, fetal testing was so common that 200,000 pregnant women were subjected to amniocentesis procedures.

Let us confess our faith by stating that we who belong to Jesus Christ abominate this practice which now results in the aborting of over 90 percent of children with Down syndrome today in North America.[^203] Let us confess our faith by declaring that we Christians don't kill babies to protect ourselves from giving birth to a handicapped child. Christian physicians don't talk mothers into killing their baby in order to protect themselves from malpractice suits. In fact, no civilized person kills babies. What is the meaning of "civilization" and the "rule of law" when citizens protect their time and money by shedding the blood of their babies?

Abortionists see only one person, the mother, and so they kill her baby. They say it forthrightly, and often. Some of them deny the babies are persons. Some deny babies are alive. Sometimes they are brutally honest, saying the mother's right to abortion is absolute, and this is "whether or not it's a life!"[^204]

There will, as was pointed out above, be mothers who choose to reject treatment of their disease because the treatment poses a very serious danger to her preborn child. In such extraordinary cases, we acknowledge our Lord's declaration, "Greater love has no one than this, that one lay down his life for his friends" (John 15:13).

### Clinical Callousness

Before we move on, we want to give one pastoral caution concerning the medical professionals who care for us.

Babies and pregnancy are the times of greatest vulnerability for mothers, and also fathers (to some lesser extent). For this reason, when a physician or other medical authority (and yes, they are authorities) warns us we should consider aborting our child, it shakes us to our core. Sometimes the suggestion arises from a problematic ultrasound showing the little one might have this or that anomaly indicating some potentially serious genetic disorder. Other times it arises from a serious diagnosis of the mother herself made during her pregnancy which requires a treatment that could harm or kill the baby in her womb (as in the examples mentioned above).

Regardless of the reason for the suggestion or recommendation, the simple fact is that your professional healer has just suggested or recommended to you that you kill your child. Don't let the clinical tone of the suggestion throw you off guard, leaving you in shock so that you fail to react with the horror which you ought properly to feel and express. Prepare yourself beforehand so the medical professionals, who normally serve us so well, can have our help restoring their lost or attenuated instinct to protect mothers' loving solicitude towards their little ones, as well as the little ones themselves. Something like this might be said:

> What did you say? Did you really just suggest to me that I *kill* my *child*? Is my child not your patient also? Surely you weren't serious, were you? Are you so afraid of a malpractice suit that you have taken to saying such things? I'm so sorry for you. Go ahead and tell me what we can do about this problem, but don't you dare ever even in the slightest way suggest any solution to our problems that involves the death of the little one we both want to bring to term and deliver . . .

Something along those lines will be sufficient, and yes, it really will be helpful to many physicians who are only making the suggestion because it's a standard of practice, and not doing so can make them liable to a lawsuit if the child ends up being born with some congenital anomaly, or if carrying the little one to term contributes to the mother's death. Even if your physician reacts by sending you to another OB-GYN, rejoice that the Lord might have used you to reawaken her or his conscience, in time. Our social media generation needs to be reminded there are many things more horrible than relational or conversational awkwardness, or shame, or personally pronounced moral judgments.

Also remember that medical professionals are very limited in their knowledge, let alone ability to predict the future. If we hear the whistle of an artillery shell coming our way and are staring at mayhem all around us from previous shells that have rained down near us, it would be foolish not to take cover. But this is a far cry from reading an ultrasound and crying "wolf." Medical standards of practice might require a warning, but even as pastors, we can all recount times our sheep have come to us terror-stricken by the possible prognosis their OB-GYN just gave them, going on to suggest they consider terminating their pregnancy, after which it turned out to be a false alarm. Doctors might be required to give false alarms, but we are the children of the Great Physician for whom nothing is impossible.

Walking by faith includes pregnancy and childbirth. God loves our little ones more than we could ever love them, so even while they're still in the womb, practice entrusting them to Him.


[^96]: Augustine, *On the Trinity* 7.6.11.

[^97]: "*Roe v. Wade*: Its History and Impact," Planned Parenthood Federation of America, 2014, https://www.plannedparenthood.org/files/3013/9611/5870/Abortion_Roe_History.pdf.

[^98]: οὐ δώσω δὲ οὐδὲ φάρμακον οὐδενὶ αἰτηθεὶς θανάσιμον, οὐδὲ ὑφηγήσομαι συμβουλίην τοιήνδε: ὁμοίως δὲ οὐδὲ γυναικὶ πεσσὸν φθόριον δώσω. ἁγνῶς δὲ καὶ ὁσίως διατηρήσω βίον τὸν ἐμὸν καὶ τέχνην τὴν ἐμήν.

[^99]: Adam named his wife Eve, which means "living one" or "life-giver," "because she was the mother of all the living." Genesis 3:20.

[^100]: The reactions of many women on social media to the threatened overturning of *Roe v. Wade* illustrate this reality. For example, Twitter user \@Darlyn215 said on May 3, 2022, "You know what's so interesting? Women can't get themselves pregnant. It's men who cause abortions," accessed May 5, 2022, https://twitter.com/Darlyn215/status/1521595279077744641. Twitter user \@photogjoy said on May 4, 2022, "Let's force vasectomies on men who get women pregnant so the MAN has to pay the price as well," accessed May 5, 2022, https://twitter.com/photogjoy/status/1521822320628748288, emphasis original.

[^101]: "An Open Letter to State Lawmakers from America's Leading Pro-Life Organizations," May 12, 2022, https://www.nrlc.org/uploads/communications/051222coalitionlettertostates.pdf. Emphases original.

[^102]: 1 Kings 3:16--28.

[^103]: Mother Teresa, "Address to Commissioners of 200th General Assembly of the Presbyterian Church (USA), St. Louis, Missouri; June 7, 1988."

[^104]: Philip Ney, Claudia Sheils, and Marek Gajowy, "Post-Abortion Survivor Syndrome: Signs and Symptoms," *Southern Medical Journal* 99, no. 12 (December 2006): 1405--1406, https://doi.org/10.1097/01.smj.0000251372.56344.bf.

[^105]: "When they are able, from reliable evidence, to prove some fact of physical science, we shall show that it is not contrary to our Scripture. But when they produce from any of their books a theory contrary to Scripture, and therefore contrary to the catholic faith, either we shall have some ability to demonstrate that it is absolutely false, or at least we ourselves will hold it so without any shadow of a doubt. And so we will cling to our Mediator, 'in whom are hidden all the treasures of wisdom and knowledge,' that we will not be led astray by the glib talk of false philosophy or frightened by the superstition of false religion." Augustine, *Literal Commentary on Genesis* 1.21.41, trans. J. H. Taylor.

[^106]: Thus Augustine, on the question of the physical disposition of heaven: "But someone may ask: 'Is not Scripture opposed to those who hold that heaven is spherical, when it says "who stretches out heaven like a skin"?' Let it be opposed indeed if their statement is false. The truth is rather in what God reveals than in what groping men surmise. But if they are able to establish their doctrine with proofs that cannot be denied, we must show that this statement of Scripture about the skin is not opposed to the truth of their conclusions. . . . But if it is necessary, as it surely is, to interpret these two passages so that they are shown not to be contradictory but to be reconcilable, it is also necessary that both of these passages should not contradict the stories that may be supported by true evidence, by which heaven is said to be curved on all sides in the shape of a sphere, provide only that this is proved." *Literal Commentary on Genesis* 2.9.

[^107]: "It is admitted that theologians are not infallible, in the interpretation of Scripture. It may, therefore, happen in the future, as it has in the past, that interpretations of the Bible, long confidently received, must be modified or abandoned, to bring revelation into harmony with what God teaches in his works. This change of view as to the true meaning of the Bible may be a painful trial to the Church, but it does not in the least impair the authority of the Scriptures. They remain infallible; we are merely convicted of having mistaken their meaning." Charles Hodge, *Systematic Theology*, 3 vols. (1872--73; Eerdmans, 1982), 1:59.

[^108]: Indeed, because God is infallible in *all* His works and cannot err in His revelation of Himself, both natural and special revelation may be said to be infallible, but not any *interpretation* of those revelations.

[^109]: "Well, after all, it's living, isn't it? And if it's living, what is it if it's not a human being? A mouse? A dog? A monkey?" Richard John Neuhaus in an unpublished paper given at the Consultation on the Church and Abortion, sponsored by Presbyterians Pro-Life, Princeton Theological Seminary, February 28--29, 1992.

[^110]: See Job 10:8--12: "Your hands fashioned and made me altogether, and would You destroy me? Remember now, that You have made me as clay; and would You turn me into dust again? Did You not pour me out like milk and curdle me like cheese; clothe me with skin and flesh, and knit me together with bones and sinews? You have granted me life and lovingkindness; and Your care has preserved my spirit."

[^111]: John Paul II, *Evangelium Vitae*, March 25, 1995, §§ 60--61, https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_25031995_evangelium-vitae.html, quoting Sacred Congregation for the Doctrine of the Faith, *Declaration on Procured Abortion*, November 18, 1974, §§ 12--13, https://www.vatican.va/roman_curia/congregations/cfaith/documents/rc_con_cfaith_doc_19741118_declaration-abortion_en.html.

[^112]: The SLED acronym was developed by the Roman Catholic philosopher Stephen Schwarz in his 1990 book *The Moral Question of Abortion* (Loyola University Press).

[^113]: Re: sight, eye movements and reactions occur as early as 12 weeks. See Tryphena Humphrey, "Some Correlations between the Appearance of Human Fetal Reflexes and the Development of the Nervous System," in *Progress in Brain Research*, vol. 4, *Growth and Maturation of the Brain*, ed. Dominick P. Purpura and J. P. Schadé (Elsevier, 1964), 93--135, https://doi.org/10.1016/S0079-6123(08)61273-X.

    Re: hearing, see Christine Moon, Hugo Lagerkrantz, and Patricia Kuhl, "Language Experienced In Utero Affects Vowel Perception after Birth: A Two-Country Study," *Acta Paediatrica* 102, no. 2 (February 2013): 156--160, https://doi.org/10.1111/apa.12098; also Eino Partanen et al., "Learning-Induced Neural Plasticity of Speech Processing before Birth," in *Psychological and Cognitive Sciences* 110, no. 37 (August 26, 2013): 15145--15150, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3773755/.

    Re: pain, recent research has continually pushed back the developmental threshold at which the unborn are known to be able to feel pain. See, e.g., Stuart Derbyshire and John Bockmann, "Reconsidering Fetal Pain," *Journal of Medical Ethics* 46, no. 1 (2020): 3--6, http://dx.doi.org/10.1136/medethics-2019-105701. For other aspects of early fetal development, see Katrina Furth, *15 Facts at 15 Weeks*, On Science 3 (Arlington: Charlotte Lozier Institute, 2021), https://lozierinstitute.org/15-facts-at-15-weeks/.

[^114]: Linda Rodriguez McRobbie, "The Man in the Iron Lung," *The Guardian*, May 26, 2020, https://www.theguardian.com/society/2020/may/26/last-iron-lung-paul-alexander-polio-coronavirus.

[^115]: John Donne, *Devotions upon Emergent Occasions* (1624), ch. 17.

[^116]: Comments on Luke 10:30, trans. Jürgen von Hagen.

[^117]: Eugene Quay, "Justifiable Abortion," *The Georgetown Law Journal*, Winter 1960, 178. Quay, the founding editor of *The Georgetown Law Journal*, was a member of the American Law Institute whose work recommending legislative changes toward judicial reform were, at the time, being corrupted by a movement promoting the liberalization of state laws concerning abortion. "Justifiable Abortion" was his witness against this movement.

[^118]: John T. Noonan, "Restoring the Protection of Life to the Constitution," prepared statement in *Constitutional Amendments Relating to Abortion: Hearings Before the Subcommittee on the Constitution of the Committee on the Judiciary, United States Senate, Ninety-seventh Congress, First Session, on S.J. Res. 17, S.J. Res. 18, S.J. Res. 19, and S.J. Res. 110* (1983), 46.

[^119]: (William Morrow, 2005).

[^120]: Ibid., 137.

[^121]: Ibid., 138.

[^122]: Ibid., 139.

[^123]: Ibid., 138.

[^124]: Michael Giandrea and Shawn Sprague, "Estimating the U.S. Labor Share," *Monthly Labor Review*, U.S. Bureau of Labor Statistics, February 2017, https://doi.org/10.21916/mlr.2017.7.

[^125]: See "Labour Share of GDP, Comprising Wages and Social Protection Transfers," Sustainable Development Goals, United Nations Economic Commission for Europe, https://w3.unece.org/SDG/en/Indicator?id=30.

[^126]: All values are in US dollars.

[^127]: "Level of GDP Per Capita and Productivity," Organisation for Economic Co-operation and Development, https://stats.oecd.org/index.aspx?DataSetCode=PDB_LV.

[^128]: "Employment Status of the Civilian Noninstitutional Population by Age, Sex, and Race," Labor Force Statistics from the Current Population Survey, U.S. Bureau of Labor Statistics, https://www.bls.gov/cps/aa2019/cpsaat03.htm.

[^129]: Table 3 under "Access to Historical Data for the Tables of the Usual Weekly Earnings of Wage and Salary Workers," U.S. Bureau of Labor Statistics, https://www.bls.gov/webapps/legacy/cpswktab3.htm.

[^130]: Katherine Kortsmit et al., "Abortion Surveillance---United States, 2019," *Surveillance Summaries* 70, no. 9 (November 26, 2021): 1--29, CDC, https://www.cdc.gov/mmwr/volumes/70/ss/ss7009a1.htm.

[^131]: Credit Suisse Research Institute, *Global Wealth Report 2019*, 44.

[^132]: S. D. Mumford and E. Kessel, "Role of Abortion in Control of Global Population Growth," *Clinical Obstetrics and Gynecology* 13, no. 1 (March 1986):19--31.

[^133]: Max Kummerow, "Reproductive Biology of Abortion," The Overpopulation Project, January 13, 2019, https://overpopulation-project.com/reproductive-biology-of-abortion/.

[^134]: Donella Meadows et al., *The Limits to Growth* (Universe Books, 1972), http://www.donellameadows.org/wp-content/userfiles/Limits-to-Growth-digital-scan-version.pdf.

[^135]: Christof Rühl and Titus Erker, executive summary in "Oil Intensity: The Curiously Steady Decline of Oil in GDP," Center on Global Energy Policy at Columbia University SIPA, September 9, 2021, https://www.energypolicy.columbia.edu/research/report/oil-intensity-curiously-steady-decline-oil-gdp.

[^136]: FAO, IFAD, UNICEF, WFP and WHO, *The State of Food Security and Nutrition in the World 2020* (Rome: FAO, 2020), ch. 1, https://www.fao.org/3/ca9692en/online/ca9692en.html#chapter-1_1.

[^137]: To this point, embryos (i.e., embryos created via IVF) are transferred from one person to another under property law in the United States, denying them personhood.

[^138]: Daniel Kevles, "Eugenics and Human Rights," *The BMJ* 319 (August 14, 1999):435--438, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1127045/.

[^139]: Mother Teresa, "Notable and Quotable," *Wall Street Journal*, February 25, 1994, A14.

[^140]: Cf. John Locke, *Second Treatise of Government* 2.6: "The state of nature has a law of nature to govern it, which obliges every one: and reason, which is that law, teaches all mankind, who will but consult it, that being all equal and independent, no one ought to harm another in his life, health, liberty, or possessions: for men being all the workmanship of one omnipotent, and infinitely wise maker; all the servants of one sovereign master, sent into the world by his order, and about his business; they are his property, whose workmanship they are, made to last during his, not one another's pleasure: and being furnished with like faculties, sharing all in one community of nature, there cannot be supposed any such subordination among us, that may authorize us to destroy one another, as if we were made for one another's uses, as the inferior ranks of creatures are for our's. Every one, as he is bound to preserve himself, and not to quit his station wilfully, so by the like reason, when his own preservation comes not in competition, ought he, as much as he can, to preserve the rest of mankind, and may not, unless it be to do justice on an offender, take away, or impair the life, or what tends to the preservation of the life, the liberty, health, limb, or goods of another."

[^141]: *Black's Law Dictionary* 1324 (6th ed. 1990). Emphasis in original.

[^142]: 1 William Blackstone, *Commentaries* 129--130.

[^143]: "Quickening," *Bouvier's Law Dictionary*, vol. 3, 3rd ed. (West Publishing, 1914), 2784--2785.

[^144]: *Dobbs v. Jackson Women's Health Organization*, No. 19-1392, 2022 WL 2276808, at \*7 (US June 24, 2022). This quote is from pp. 5--6 of Justice Alito's opinion published in the slip opinion in the morning on June 24, 2022, accessed June 24, 2022, https://www.supremecourt.gov/opinions/21pdf/19-1392_6j37.pdf.

[^145]: For one of the best summaries of historical Jewish teaching on abortion, see J. David Bleich, "Abortion and Jewish Law," *New Perspectives on Human Abortion*, ed. Thomas Hilgers, Dennis Horan, and David Mall (Aletheia Books, 1981), 405--419.

[^146]: As noted earlier, it was a common practice for Roman fathers to abandon their infant children to die of exposure.

[^147]: Tacitus, *Histories* 5.5: "Yet they [the Jews] take care that their multitude grows; for indeed to kill any of their children is unspeakable, and they hold that the souls of those killed in battle or by penalty of death are immortal: hence their love of reproducing and their disregard for dying. They bury rather than burn their dead."

[^148]: Thus Josephus, *Against Appion* 2.202: "[The Law] mandates that they raise all the children, and forbids women either from aborting the seed or from destroying it; but if any [woman] should appear [to have done this], she would be a child murderer, having destroyed a soul and diminished the race."

[^149]: "Why Jews Oppose Abortion," *The Review of the News*, May 1, 1974, 1--6. Emphasis in the original.

[^150]: As quoted in Bill Moloney, "Jewish View," *National Right to Life News*, June 1979, 6.

[^151]: Jesus speaks of "joy that a human being has been born into the world," indicating that the human being exists prior to birth. For more on the biblical teaching of personhood prior to birth, see the next section of this paper, "The Testimony of Scripture."

[^152]: For more on this, see Daniel Schiff, "Evaluating Life," in *Abortion in Judaism* (Cambridge University Press, 2002), 27--57.

[^153]: "Ipsae quoque divites, ne per plures suum patrimonium dividatur, in utero proprios necant fetus, et parricidalibus succis in ipso genitali alvo pignora sui ventris exstinguunt, priusque aufertur vita quam tradatur. Quis docuit nisi homo filios abdicari?"

[^154]: "Aliquando eo usque pervenit haec libidinosa crudelitas vel libido crudelis, ut etiam sterilitatis venena procuret et si nihil valuerit, conceptos fetus aliquo modo intra viscera exstinguat ac fundat, volendo suam prolem prius interire quam vivere, aut si in utero iam vivebat, occidi ante quam nasci. Prorsus si ambo tales sunt, coniuges non sunt; et si ab initio tales fuerunt, non sibi per connubium, sed per stuprum potius convenerunt."

[^155]: *Lectures on Genesis Chapters 21--25*, ed. Jaroslav Pelikan, vol. 4 in *Luther's Works* (St. Louis: Concordia, 1955--1986), 304.

[^156]: Trans. Charles William Bingham (1852), in *Harmony of the Law*, vol. 3, The Ages Digital Library Commentary (Books for the Ages, 1998), 32.

[^157]: John Paul II, *Evangelium Vitae*, § 61.

[^158]: Peter Singer, *Practical Ethics* (Cambridge University Press, 1993), 136.

[^159]: Calvin, comments on John 18:28, *Commentary on the Gospel According to John*, vol. 2 trans. William Pringle (Wipf & Stock, 2021), 205.

[^160]: Psalms 119:73; 139:13.

[^161]: One biblical argument for this position is that "the pagan altars in the valley of Ben-Hinnom where children were sacrificed are also described as altars to Ba'al by the prophet Jeremiah." Caleb Strom, "Was Moloch Really Ba'al, the Ancient God Who Demanded Child Sacrifice?" Ancient Origins, February 10, 2019, https://www.ancient-origins.net/myths-legends-asia/identity-moloch-0011457. For more information, see the sources referenced Strom, as well as the references in the article on "Moloch" on Wikipedia, https://en.wikipedia.org/wiki/Moloch#References.

[^162]: "Ancient Carthaginians Really Did Sacrifice Their Children," News & Events, University of Oxford, January 23, 2014, https://www.ox.ac.uk/news/2014-01-23-ancient-carthaginians-really-did-sacrifice-their-children.

[^163]: Mary Elizabeth Williams, "So What If Abortion Ends Life?" *Salon*, January 23, 2013, https://www.salon.com/2013/01/23/so_what_if_abortion_ends_life/.

[^164]: October 4, 2010, https://www.huffpost.com/entry/harvest-rites-blood-for-b_b_746169.

[^165]: Cyril of Alexandria, *Catechetical Lectures* 12.25--26, trans. Edwin Hamilton Gifford.

[^166]: "And when men strive, and have smitten a pregnant woman, and her children have come out, and there is no mischief, he is certainly fined, as the husband of the woman doth lay upon him, and he hath given through the judges; and if there is mischief, then thou hast given life for life, eye for eye, tooth for tooth, hand for hand, foot for foot, burning for burning, wound for wound, stripe for stripe" (Young's Literal Translation).

    There has been much debate over the interpretation of this text. Perhaps the biggest question is how to understand the Hebrew here translated "mischief." Some modern scholars have even tried to make the case the text supports elective abortion. Evangelical scholars have responded by arguing "mischief" (Hebrew *\'āsôn*, [יצא]{dir="rtl"}) does not refer to miscarriage, but premature birth. Cf. U. Cassuto, *Commentary on the Book of Exodus* (Jerusalem Magnes, 1967), 275; H. W. House, "Miscarriage or Premature Birth: Additional Thoughts on Exodus 21:22--25," *Westminster Theological Journal* 41 (Fall 1978): 108--123; W. C. Kaiser, *Toward Old Testament Ethics* (Zondervan, 1983), 102--104, 168--172; also J. Calvin, *Commentary on the Four Last Books of Moses* (Baker, 1979); C. F. Keil and F. Delitzsch, *Exodus* (Eerdmans, n.d.). See also John Makujina, "The Semantics of [יצא]{dir="rtl"} in Exodus 21:22: Reassessing the Variables That Determine Meaning," *Bulletin for Biblical Research* 23, no. 3 (2013): 305--321.

    The interpretation held more broadly across history is "miscarriage." See Russell Fuller, "Exodus 21:22--23: The Miscarriage Interpretation and the Personhood of the Fetus," *Journal of the Evangelical Theological Society* 37, no. 2 (June 1994): 169--184; also Makujina.

    A second, related matter involves the LXX reading of this passage, which, instead of understanding the issue as one of "mischief" or "no mischief," distinguishes between a "formed" and "unformed" fetus. This distinction depends upon ancient opinions about ensoulment, and represents the interpretation of most of the church fathers. A majority of modern exegetes prefer the Hebrew Masoretic reading here, yet arguments in favor of the LXX's reading are substantial, and should not be dismissed out of hand in reference to the "formed" and "unformed" child. Cf. Stanley Isser, "Two Traditions: The Law of Exodus 21:22--23 Revisited," *The Catholic Biblical Quarterly* 52, no. 1: 30--45.

    Regardless of one's conclusions concerning the text's meanings and interpretations, Exodus 21:22--23 provides no support for elective abortion.

[^167]: See, e.g., Deuteronomy 12:31; 18:10; 2 Kings 16:3; 17:17; 17:31; 21:6; 2 Chronicles 28:3; 33:6; Jeremiah 7:31; 19:5; and Ezekiel 16:21; 20:26, 31; 23:37.

[^168]: Lawrence Stager and Samuel Wolff, "Child Sacrifice at Carthage---Religious Rite or Population Control?" *Biblical Archeology Review*, January/February 1984: 32--51. For a time scholars attempted to deny that child sacrifices to the gods really happened as reported, but new research published in the journal *Antiquity* leaves it beyond question, even suggesting that it might be one of the reasons the city was founded in the first place.

[^169]: The word comes, through French and Latin, from Greek *sardonios*, itself an alteration of Greek *sardinia*, associated with a plant from Sardinia. The ancients believed that eating this plant caused facial convulsions and led to death. See Stager and Wolff, 33.

[^170]: Translation by P. G. Mosca, *Child Sacrifice in Canaanite and Israelite Religion: A Study in Mulk and Molech*, PhD dissertation, Harvard University, 1975, 22, as quoted in Stager and Wolff, 33.

[^171]: *Apology* 9.24, from *Apology and De Spectaculis*, trans. T. R. Glover (Loeb Classical Library, 1931).

[^172]: Thus, for φαρμακεία, the Liddell, Scott, Jones Ancient Greek Lexicon gives "of abortifacients" as one definition, citing Soranus (1.59; fl. 1st/2nd century AD). By contrast, BDAG does not include this specific gloss for either *pharmakeia* or *pharmakon* despite Soranus having written within the New Testament time period and BDAG's inclusion of citations from several less significant medicinal writers. One might anticipate a correction of this oversight in future editions. See also Hippocrates, *Oath* 18--20: "Neither will I administer a poison [*pharmakon*] to anybody when asked to do so, nor will I suggest such a course. Similarly, I will not give to a woman a pessary to cause abortion."

[^173]: Riddle, *Eve's Herbs: A History of Contraception and Abortion in the West* (Harvard University Press, 1997).

[^174]: For an extended discussion of medicine as "art," and not simply "science," as well as a stunning essay on abortion, see Richard Selzer, *Mortal Lessons: Notes on the Art of Surgery* (Harcourt Brace & Co., 1974). Selzer was a second-generation physician and denied the existence of God.

[^175]: Precise data is absent, but a ballpark figure for the maternal mortality rate is between 0.5 and 2 percent.

[^176]: These and other terms were broad, overlapping, and often used interchangeably; see, e.g., Matthew Dickie, *Magic and Magicians in the Greco-Roman World* (Routledge, 2001), 34; but on the other hand, Richard Greenfield, "Magic and the Occult Sciences" in *The Cambridge Intellectual History of Byzantium* (Cambridge University Press, 2017), 220.

    Even a single term's meaning was often context dependent; cf. *magos* in the New Testament, which is used with reference to the *magi* of Matthew 2 as well as Simon the Magician in Acts 8. On balance, it is best to consider *magos*, *pharmakos*, etc., as related terms that sometimes retain their nuances~~---~~and indeed the standard lexica generally hold to this practice.

[^177]: Cf. Revelation 18:23.

[^178]: Cf. Alciphron, *Epistolae* 4.10.3; also Basil, *Letters* 188.8.

[^179]: Cf., among many others, Theophrastus, Περὶ φυτῶν ἱστορία 9.18.5.

[^180]: Cf. Euripides, *Hippolytus* 509--516.

[^181]: See, e.g., Apuleius, *Metamorphoses* 1.9ff. For more on reproductive spells, see also Jean-Jacques Aubert, "Threatened Wombs: Aspects of Ancient Uterine Magic," *Greek, Roman, and Byzantine Studies* 30, no. 3 (1989): 421--449.

[^182]: See Jerome, *Ad Eustochium* (*Letters* 22.13).

[^183]: 1 Corinthians 6:9--11.

[^184]: "But the cowardly, unbelieving, abominable, murderers, sexually immoral, sorcerers, idolaters, and all liars shall have their part in the lake which burns with fire and brimstone, which is the second death." Revelation 21:8.

[^185]: οὐ φονεύσεις, οὐ μοιχεύσεις, οὐ παιδοφθορήσεις, οὐ πορνεύσεις, οὐ κλέψεις, οὐ μαγεύσεις, οὐ φαρμακεύσεις, οὐ φονεύσεις τ́κνον ἐν φθορᾷ, οὐδὲ γεννηθὲν ἀποκτενεῖς. *Didache* 2.2.

[^186]: Although the crimes of rape and incest are distinct, the latter often involves the former, so we will mainly address rape.

[^187]: For instance, during a debate, Richard Mourdock, the 2012 US Senate candidate for Indiana, uttered the words, "I just struggled with it myself for a long time but I came to realize: Life is that gift from God that I think even if life begins in that horrible situation of rape, that it is something that God intended to happen." His confession of faith in God's sovereignty brought an abrupt end to his previously successful candidacy. See Kevin Robillard, "Buchanan: Mitt Romney Rejects 'Rape' Remark," *Politico*, October 24, 2012, http://www.politico.com/news/stories/1012/82808.html.

[^188]: See this report from the Gesundheitsberichterstattung des Bundes (Federal Health Monitoring System): https://www.gbe-bund.de:443/gbe/pkg_olap_tables.prc_archiv?p_indnr=240&p_archiv_id=1081842&p_sprache=E. Note as well that abortions related to the health of the mother make up less than 4 percent of the total, and this where health is defined broadly as physical and mental health, and a doctor must certify the threat in writing.

[^189]: In the United States, government agencies almost never require the keeping of data on abortions after rape or incest, or due to health concerns related to the mother. See Kortsmit et al., "Abortion Surveillance."

[^190]: According to a 2004 anonymous survey conducted by the Guttmacher Institute among 1,209 women who had aborted their children, less than 0.5 percent were related to rape, and 4 percent to the mother's health. See Lawrence Finer et al., "Reasons U.S. Women Have Abortions: Quantitative and Qualitative Perspectives," *Perspectives on Sexual and Reproductive Health* 37 (2005), no. 3: 110--118. Florida is exceptional among the states, providing an annual report on abortions which includes a statement of reasons given for the abortion. In 2020, 0.16 percent of abortions were related to rape and incest, 1.68 percent to the mother's physical health, and 1.88 percent to the mother's psychological health. See "Reported Induced Terminations of Pregnancy (ITOP) by Reason, by Trimester," 2020, https://ahca.myflorida.com/MCHQ/Central_Services/Training_Support/docs/TrimesterByReason_2020.pdf.

[^191]: We are not declaring the unborn child's absolute innocence here. In Psalm 51, David confesses he was "conceived in sin." Saying this, David was not referring to any sin of his father and mother in the circumstances of his conception, but to his own sin. David's confession of his own original sin from the moment of his conception is equally true of all men and women. In terms of relative innocence, though, the unborn child is the most innocent of all men.

    Still, in connection with the entirety of this paper, Calvin's comments on David's confession of guilt from his conception in the womb are instructive:

    > Interpreters have very properly rendered [the Hebrew] "hath conceived me." The expression intimates that we are cherished in sin from the first moment that we are in the womb. David, then, is here brought, by reflecting on one particular transgression, to cast a retrospective glance upon his whole past life, and to discover nothing but sin in it. . . . [David] refers to original sin with the view of aggravating his guilt, acknowledging that he had not contracted this or that sin for the first time lately, but had been born into the world with the seed of every iniquity.
    > 
    > The passage affords a striking testimony in proof of original sin entailed by Adam upon the whole human family. It not only teaches the doctrine, but may assist us in forming a correct idea of it. . . . The Bible, both in this and other places, clearly asserts that we are born in sin, and that it exists within us as a disease fixed in our nature. David does not charge it upon his parents, nor trace his crime to them, but . . . before the Divine tribunal, confesses that he was formed in sin, and that he was a transgressor ere he saw the light of this world. (Comments on Psalm 51:5, *Commentary on the Book of Psalms*, vol. 2, trans. James Anderson [Calvin Translation Society, 1846], 290)
    
    \ 

[^192]: Under the Mosaic Law, rape of a married woman was punishable by death (Deut. 22:22--23), and Western law has consistently punished rape with harsh penal sanctions.

[^193]: *City of God* 1.18: "Far be it from us to so misapply words. Let us rather draw this conclusion, that while the sanctity of the soul remains even when the body is violated, the sanctity of the body is not lost; and that, in like manner, the sanctity of the body is lost when the sanctity of the soul is violated, though the body itself remains intact. And therefore a woman who has been violated by the sin of another, and without any consent of her own, has no cause to put herself to death; much less has she cause to commit suicide in order to avoid such violation, for in that case she commits certain homicide to prevent a crime which is uncertain as yet, and not her own."

[^194]: "An Impolite Interview with Ken Kesey," *The Realist*, no. 90 (May/June 1971): 46--47, http://www.ep.tc/realist/90/46.html. Emphases original.

[^195]: Westminster Confession of Faith, 3.1, https://evangelpresbytery.com/westminster-confession-of-faith/#III.

[^196]: C. Everett Koop, interview with Dick Bohrer, *Moody Monthly*, May 1980, reprinted in Dick Bohrer, *Sell Your Homework: 24 Ways to Write What You Think*, lesson 8 ("The Speech Critique") (Glory Press Books, 2005), 17.

[^197]: "Abortion---Yesterday, Today, and Tomorrow," in *The Case for Legalized Abortion Now* (Diablo Press, 1967), 9.

[^198]: It is also worth noting that a 2015 study in the *New England Journal of Medicine* (*NEJM*) indicated that "Prenatal exposure to maternal cancer with or without treatment did not impair the cognitive, cardiac, or general development of children in early childhood." Frédéric Amant et al., "Pediatric Outcome after Maternal Cancer Diagnosed during Pregnancy," *NEJM* 373, no. 19: 1824--1834, https://www.nejm.org/doi/full/10.1056/NEJMoa1508913.

[^199]: It may not need to be said, but this is the very opposite of the mother paying for an abortion. This mother takes the life of her child, almost never to save her own life or health, but to keep her future plans and lifestyle intact and unhindered.

[^200]: "In the United States, the current [1995] standard of care in obstetrical practice is to offer either CVS or amniocentesis to women who will be greater than or equal to 35 years of age when they give birth . . ." Richard Olney et al., "Chorionic Villus Sampling and Amniocentesis: Recommendations for Prenatal Counseling," Morbidity and Mortality Weekly Report (MMWR), CDC, July 21, 1995, https://www.cdc.gov/mmwr/preview/mmwrhtml/00038393.htm.

[^201]: Laura Carlson and Neeta Vora, "Prenatal Diagnosis: Screening and Diagnostic Tools," *Obstetrics and Gynecology Clinics of North America* 44, no. 2 (June 2017): 245--256, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5548328/*.*

[^202]: For wrongful *birth*, see, as an example, Turpin v. Sortini, 31 Cal. 3d 220 (1982), https://law.justia.com/cases/california/supreme-court/3d/31/220.html. For wrongful *life*, see, as an example, Curlender v. Bio-Science Laboratories, 106 Cal. App. 3d 814 (1980), https://law.justia.com/cases/california/court-of-appeal/3d/106/811.html. In *Curlender*, the California appellate court found *Roe v. Wade* to be "of considerable importance in defining the parameters of 'wrongful-life' litigation," because of the Supreme Court's determination "that parents have a constitutionally protected right to obtain an abortion during the first trimester of pregnancy," at 820.

[^203]: Rebecca Lobo and Garnett Genuis, "Socially Repugnant or the Standard of Care: Is There a Distinction between Sex-Selective and Ability-Selective Abortion?" *Canadian Family Physician* 60, no. 3 (March 2014): 212--216, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3952749/.

[^204]: One of us participated in a debate over abortion at the General Assembly of the Presbyterian Church (USA) in which each side was asked to summarize the other side's position. He was asked to go first and summarized the abortionists' position by saying they felt any abortion is tragic, but there are times when the circumstances of a woman's pregnancy are so harmful to the woman that having an abortion is less tragic than the alternative. Further, that since it's unclear whether or not the unborn is a real human life, choosing to have an abortion can be the moral decision. With anger, the female abortion proponent, nearly shouting, said, "No!"

    The moderator responded, "No what? Are you saying this summary of your position isn't accurate?"

    She responded, "Yes! We are *not* saying it's *not* a life. We are saying the woman has a right to have an abortion *whether or not it's a life*!"
