## Abortion's Consequences

The destruction caused by the spread of abortion becomes more clear as we examine some of its additional consequences.

### Sex-Selective Abortion

Across South Asia, sex-selective abortion is now widespread. It was first practiced in South Korea, producing in certain cities a sex ratio at birth (SRB) of 125 boys to 100 girls.[^19] China copied the practice so that, now, a number of provinces have an SRB of 130 boys to 100 girls. Soon, the practice spread to India where several states now have an SRB of 120 boys to 100 girls. The National Library of Medicine of the National Institutes of Health gave the following report concerning China:

The SRB across the country for first-order births is 108, for second-order births it is 143 and for the (albeit rare) third-order births it is 157.[^20]

In 2012, Planned Parenthood's research arm, The Guttmacher Institute, reported:

The Chinese Academy of Social Sciences predicts that by 2020, China will have 30--40 million more boys and young men under age 20 than females of the same age. India, too, is facing a national crisis with its sex ratios. The Indian census does not publish sex ratios at birth, but rather child sex ratios, expressed as the number of females below age seven for every 1,000 males. The last four census surveys point to rapidly increasing disparities: The child sex ratio dropped from 962 (girls to 1,000 boys) in 1981 to 945 in 1991 to 927 in 2001, and according to the latest census, in 2011, the ratio decreased further, to 914.

. . . The northern Indian states of Haryana and Punjab are notorious for their exceedingly disparate ratios, at 830 and 846, respectively, with some districts dipping into the 770s.[^21]

*The Guardian* reports, "India is estimated to have 63 million fewer women since sex determination tests took off in the 1970s."[^22]

A decade ago, *The Economist* reported:

China alone stands to have as many unmarried young men---"bare branches," as they are known---as the entire population of young men in America.[^23]

More recently, *The Economist* did a piece on gendercide in the Caucasus states, especially Georgia, Azerbaijan, and Armenia:

But in Armenia and Azerbaijan more than 115 boys are born for every 100 girls and in Georgia the ratio is 120. These are bigger distortions than in India. In all three the figure has risen sharply since 1991. . . . In 2010, reckons Marc Michael of New York University's Abu Dhabi campus, the number of girls born was 10% lower than it would have been had the ratio been normal. The gap is second only to China's.[^24]

Enlightened Westerners condemn this killing of unborn girls for its "sexism." They are rightly horrified at the denial of the equality of the sexes it demonstrates. The image of God is the foundation of our personhood and is equally shared by man and woman, so any denial of woman's equal worth is an assault on God Himself.

Yet if we place this practice under scrutiny, it becomes clear something much worse than the denial of the equality of persons is motivating this gendercide. Consider feminist women who argue in defense of the right of women to have gender-selective abortions. In *Gendercide: The Implications of Sex Selection*, the late Mary Anne Warren, philosophy professor at San Francisco State University, argued against any legal prohibition of gender-selective abortion. Dedicating her book "To utopian feminists, who dream of alternative futures," Warren wrote:

I will argue that the objections to sex selection are insufficient to show that it is inherently immoral to preselect the sex of a child.[^25]

Speaking of the need to "resist prohibition" of gender-selective abortion in her chapter titled "The Case for Freedom of Choice," Warren writes:

There is great danger that the legal prohibition of sex selection would endanger other aspects of women's reproductive freedom \[including\] the right to choose abortion.[^26]

In her book's conclusion, Warren states:

We must not accept the argument that women who opt for sex selection \[abortion\] . . . are not making *real* choices.[^27]

Warren's foundational principle is women's self-determination. It must take precedence over the life of the unborn child. The liberation of women is of such importance and the ability to abort one's child is so central to that liberation that even the killing of unborn children based on their sex must be legitimated to serve this commitment. Women must have the right to kill any unborn child they do not want, even if the mother doesn't want that child because she's a girl.

This same underlying commitment is shared by all those who kill their unborn children. Regardless of why she is unwanted, an unwanted child is an unwanted child, and that's the end of it.

When we justify the murder of our little ones by talk of self-determination and our desires and goals being foiled by this baby in our womb, what does it really matter what those desires and goals are, so long as our ability to kill the child remains unimpeded? So, as to the sex-selective feticides of the East killing unborn baby girls particularly, the West has no reason to express concern or moral disapproval. Those in the West who declare that unwantedness of any sort justifies a mother killing her child have no basis to say the unwantedness of a child in the East is morally reprehensible. To each her own.

But really, did anyone anticipate the normalization of sex-selective abortion in India alone would result in 63 million sons unable to marry because their fathers and mothers murdered 63 million daughters?

### In Vitro Fertilization: Babies in the Fridge

A further consequence of the normalization of abortion is the growth of in vitro fertilization (IVF; literally, "fertilization in glass").[^28] This procedure removes eggs from a woman's ovaries to fertilize them with sperm outside the body in a laboratory dish.[^29] Normally, several eggs at a time are taken from the mother in order to fertilize them and have several children on hand from which to select the one or two who will be implanted in their mother's womb. Not every embryo will successfully attach himself to his mother's womb, so fertility clinic doctors make a habit of fertilizing several eggs at a time.[^30]

Those embryos not given the privilege of implantation in their mother's womb are cryogenically frozen and stored for usage later by their parents in another IVF cycle (if the child's sibling doesn't survive[^31] implantation), donated for scientific research (requiring the child's death), offered to another infertile couple, or simply destroyed.

Note here precisely what it is under discussion. IVF companies conceive image-bearers of God in a test tube, freeze them, make utilitarian calculations about how many babies they need, and so on.

In August 1989, world-renowned geneticist Jerome Lejeune testified in a Tennessee court concerning what he refers to as "little ones kept in the fridge." He opened up the ghoulish premises and procedures at the heart of the in vitro fertilization business. We quote extensively from Lejeune's testimony because of the close application of his testimony to those babies aborted at the same early stage of development through birth control. The human life that Dr. Lejeune testifies exists after conception is the same stage of embryonic life of those little ones prevented from attaching themselves to their mother's womb by IUDs and hormonal methods of birth control. Those babies imprisoned and killed by IVF procedures are the same age as those killed by IUDs and hormonal birth control.

The following is from Dr. Lejeune's court testimony:

Each of us has a unique beginning, the moment of conception. . . . As soon as the program is written on the DNA, there are twenty-three different pieces of program carried by the spermatozoa and there are twenty-three different homologous pieces carried by the ovum. As soon as the twenty-three chromosomes carried by the sperm encounter the twenty-three chromosomes carried by the ovum, the whole information necessary and sufficient to spell out all the characteristics of the new being is gathered. . . .

. . . Now, I know that there has been recent discussion of vocabulary, and I was very surprised two years ago that some of our British colleagues invented the term of pre-embryo. That does not exist, it has never existed. I was curious, and I went to the encyclopedia, to the French encyclopedia, the one I inherited from my great father so it was fifty years ago it was printed.

And at the term of embryo it was said: "The youngest form of a being," which is very clear and simple definition, and it stated: "it starts as one fertilized cell, (fertilized egg, which is called also zygote), and when the zygote splits in two cells, it is called a two-cell embryo. When it split in four it is called a four-cell embryo." Then it's very interesting because this terminology was accepted the world over for more than fifty years by all the specialists of the world, and we had no need at all of a sub-class which would be called a pre-embryo, because there is nothing before the embryo. Before an embryo there is a sperm and an egg, and that is it. And the sperm and an egg cannot be a pre-embryo because you cannot tell what embryo it will be, because you don't know what the sperm will go in what an egg \[*sic*\], but once it is made, you have got a zygote and when it divides it's an embryo and that's it. . . .

If we stop the process, if we slow down the movement of the molecules, we progressively come to a relative standstill, and when the embryo is frozen, these tiny human beings, they are very small, one millimeter and a half of a dimension, a sphere a millimeter and a half, you can put them in canisters by the thousands. And then with the due connotation, the fact of putting inside a 19 \[degree\] very chilly space, tiny human beings who are deprived of any liberty, of any movement, even they are deprived of time, (time is frozen for them), make them surviving, so to speak, in a suspended time, in a concentration can. It's not as hospitable and prepared to \[give\] life as would be the secret temple which is inside the female body that is a womb which is by far much better equipped physiologically, chemically, and I would say intellectually than our best laboratories for the development of a new human being. . . .

. . . There is no, no difficulty to understand that at the very beginning of life, the genetic information and the molecular structure of the egg, the spirit and the matter, the soul and the body must be that tightly intricated because it's a beginning of the new marvel that we call a human.

In response to the question, "What ethical considerations do you have about freezing?" Dr. Lejeune responded:

I think love is the contrary of chilly. Love is warmth, and life needs good temperature. So I would consider that the best we can do for early human beings is to have them in their normal shelter, not in the fridge.[^32]

It's natural to sympathize with those who desire to have children and are unable to do so naturally. In God's Word, there are a number of women who longed for children and mourned their empty wombs. In this connection, Scripture says repeatedly that it is God who opens and closes the womb.[^33] Yes, children are a gift from the Lord, but when God has closed the womb, is it right for those mourning their barren wombs to take matters into their own hands at the cost of most of their children conceived at IVF businesses being kept in a concentration can, or killed?[^34]

"You shall not murder" is true even if murdering will allow you, finally, to have a baby of your very own.

### Fetal Cell Lines: Cannibalization of Unborn Babies' Body Parts

A further consequence of the normalization of abortion is the global traffic in baby parts. This has been known and documented for a number of decades, although mostly in specialist literature. More recently, though, some of this trafficking has been brought to the attention of the broader population through the work of the Center for Medical Progress which received broad news coverage back in 2015 when they published videos of conversations they had with abortionists arranging the purchase of body parts from babies the abortionists had murdered. Then, more recently, because of Covid-19, there has been a surge in the discussion (limited mostly to Christians) of the use of fetal cell lines in the development and/or testing of vaccines.

Both appearances of public discussion of this horror received their fifteen minutes of attention, and were quickly gone. The roots of this horror go very deep, though, and those profiting from this business work to keep it hidden.

In 2015 *Nature* ran an article by Meredith Wadman titled "The Truth about Fetal Tissue Research," with the subheading, "The use of aborted fetal tissue has sparked controversy in the United States, but many scientists say it is essential for studies of HIV, development and more."[^35] Wadman explained the context for her article:

An explosive climate has surrounded US research with fetal tissues since July, when an anti-abortion group called the Center for Medical Progress in Irvine, California, released covertly filmed videos in which senior physicians from the Planned Parenthood Federation of America bluntly and dispassionately discussed their harvesting of fetal organs from abortions for use in research.[^36]

The article began:

Every month, Lishan Su receives a small test tube on ice from a company in California. In it is a piece of liver from a human fetus aborted at between 14 and 19 weeks of pregnancy.

Su and his staff at the University of North Carolina at Chapel Hill carefully grind the liver, centrifuge it and then extract and purify liver- and blood-forming stem cells. They inject the cells into the livers of newborn mice, and allow those mice to mature. The resulting animals are the only "humanized" mice with both functioning human liver and immune cells and, for Su, they are invaluable in his work on hepatitis B and C, allowing him to probe how the viruses evade the human immune system and cause chronic liver diseases.

"Using fetal tissue is not an easy choice, but so far there is no better choice," says Su, who has tried, and failed, to make a humanized mouse with other techniques. "Many, many biomedical researchers depend on fetal tissue research to really save human lives," he says. "And I think many of them feel the same way."[^37]

Medical research made great progress during the twentieth century, and the benefits have been remarkable. Yet the cost of this progress has often been the cannibalization of body parts of the unborn, as Wadman describes. Those opposing Covid vaccinations have described a part of this research to their constituents, explaining the development of these vaccines is dependent upon fetal cell lines largely derived from the bodies of babies killed through elective abortions. However, their explanations have been very limited concerning the origin, history, and present pervasive use of these cell lines.

Fetal cell lines go by esoteric names like HEK 293, WI-38, MRC-5, and Walvax-2. They are valued by scientists because of their ability to reproduce in great numbers while still being genetically and functionally normal, making them useful for a variety of purposes.[^38] They are developed from tissue---often the lungs---from aborted babies.

These cell lines have been under development since the 1960s, and the amount known about the aborted babies used to create them varies. Some of the babies whose tissue was used were aborted by the mother for psychological reasons. Other babies whose tissue was used were aborted for reasons that aren't known. It is possible some of these babies were not killed by elective, but rather spontaneous, abortions. Due to the research methodology, though, it's clear the vast majority of the babies died through elective abortions.[^39]

As mentioned above, it was the political ferment over Covid-19 vaccines that led to a discussion of these cell lines recently, largely among Christians. Vaccine development is one of the original-use cases for fetal cell lines. Rather than growing attenuated viruses in animal cells such as chicken eggs, it is beneficial that the environment these viruses replicate in is of human origin.[^40] This is nothing new, nor is it unique to Covid-19 vaccines.

The cell line called MRC-5 was developed in 1966 from the lung tissue of a 14-week-gestation male who was aborted for psychiatric reasons by a healthy 27-year-old mother.[^41] The MRC-5 cell line is broadly used for the production of vaccines used against diseases such as chickenpox, shingles, rabies, hepatitis A, and polio. A variety of other fetal cell lines have been used in the development of a variety of other vaccines, and such research is ongoing. For decades, without question or ethical opposition, Christians have used these vaccines for themselves and their children.

New cell lines continue to be created. One named Walvax-2, for example, was released in 2015 after four years of work. This cell line is an attempt to improve on other cell lines already in use for vaccine development in China. Walvax-2 "was derived from fetal lung tissue (similar to WI-38 and MRC-5) obtained from a 3-month old female fetus aborted because of the presence of a uterine scar from a previous Cesarean birth by a 27-year old healthy woman."[^42] Nine aborted children were used in the process, each carefully selected. Their parents gave what was purported to be a proper substitute for their baby's informed consent. The parents themselves had to be healthy and employed in careers that didn't involve any exposure to chemicals. The location of the abortion was prescribed so the "freshly aborted" body could be "immediately sent to the laboratory for the preparation of the cells."[^43] The method of abortion was also specified: in order to protect the baby's body from harm during the process of his birth, labor was to be induced by breaking the mother's water.

Given the emphasis on speed and freshness of tissue, it is not cynical to ask whether these babies were truly deceased before their lungs were removed from their bodies. If these babies were living while their tissue was taken, this would be consistent with many precedents documented in the pages of the literature of the fetal medical research industry.

Still, vaccine research and development is merely one small area of medical research and product development that depends upon the ongoing supply of tissue and body parts harvested from living little ones ripped from their mother's womb.

Alvin Wong, MD, describes the many uses of the fetal cell line HEK 293:

The human embryonic kidney (HEK) 293 cell line is widely used in laboratory research. HEK 293 was derived from the kidney cells of a human embryo, as its name denotes. A student or fellow involved in life sciences research would almost inevitably encounter this cell line in the course of his work. A common use for it is in the field of gene therapy, where it is used to propagate adenovirus. Adenovirus is a common vehicle used to deliver experimental genes. There are also other derivatives of HEK 293 used in this field.[^44]

For several reasons, the fetal cell line HEK 293 is a special case. First, both researchers who developed this line have stated they have no knowledge whether the unborn baby they used died from a spontaneous or elective abortion.[^45] This might be the only cell line where this information is *not* known.

HEK 293 is also unique because it has been "immortalized," meaning the cells can keep undergoing division without losing their useful properties. This makes the cells less useful for vaccine development, but they are widely used in other categories of research. As Dr. Wong indicated, HEK 293 is so widely used it's unlikely any student or researcher can avoid it. But beyond students and researchers, it's practically impossible for the average person to avoid benefiting from HEK 293 research in his day-to-day life.

Christian, stop and think about this. If we're going to battle against abortion and its surrounding industries, we must count the cost. Certainly many will declare us enemies of women's dignity and value, but those involved in science will also denounce us, saying, "You're going to hinder medical research everyone benefits from, often in ways that protect human lives!" Are we prepared to respond, "Yes, our resolve is firm. It is more important to defend babies' lives than to defend the availability of their body parts for research and development, even if those body parts are used in the development of lifesaving procedures and products."

Can Christians really sustain one more accusation of being "against science"? Having delved deeply into the literature of this grisly practice and trade in fetal parts beyond the limited area of the development of cell lines, we assure readers we have avoided recording here the most awful acts imaginable committed against some of these little ones. These crimes have been documented for many decades now, even in the pages of our own US government publications,[^46] and we will not elaborate here other than to say the church has no excuse for how long our eyes have been blind. Pro-life is as pro-life does, and pro-lifers have only done what is obvious---what smacks us in the face and stays there mocking us.

The recent popular exercise of Christian conscience in opposing the relationship of abortion to fetal cell lines has been selective. Covid vaccines were fortuitous in allowing some to raise the issue of the cannibalization of our unborn children's bodies for Covid vaccines specifically, but this present awakening appears to have been quite limited in its scope. It has not matured into any parallel awakening of Christian conscience in the abuses of unborn children's bodies (not related to cell lines) which are ubiquitous in the developed world and have been for decades.

Many opposed Covid vaccinations, saying, "Fetal cells have been used to develop and test these vaccines, and I'll have no part of it." This led to the assumption that Covid vaccines were unusual in this regard, representing a new tyranny extending into our lives by requiring this participation in abortion's bloodshed.

Now, though, we have presented a larger picture demonstrating that Covid vaccines are a small aspect of medical and corporate scientific dependence on the body parts of aborted babies. Whether we know or admit it, we participate.

In retrospect, the internal logic of the thing is inevitable. With the slaughter of babies in the billions, why not salvage some value by utilizing body parts as the little one's non-consensual donations to the well-being of the larger human community? As some medical ethicists might put it, "Do these little ones not have a duty to contribute their own legacy to our social contract? Ought we not to assume they would affirm their own moral obligation to make some small contribution to the lives of others?"[^47]

During the half century that has passed since *Roe v. Wade*, God's people have learned the intense difficulty of reversing this bloody decision. It has been a long, hard political battle with almost none of us anticipating this late victory recently gained here in 2022.

Yet now, with the reversal of *Roe v. Wade*, we come to recognize the relative insignificance of this reversal for the protection of our little ones. It seems likely the majority of abortions will continue unabated as chemical abortions in the first weeks and days of life predominate. Thus, faced with the now-present reality of a post-*Roe* world, we have died to the previously widely held conviction that *Roe v. Wade*'s reversal would restore protection under the rule of law to preborn babies. This conviction has proved to be as illusory as any parallel hope that the reversal of *Roe v. Wade* would also bring an end to the trafficking in body parts on which modern medical research is dependent.

The genocide of the preborn has become so integral to Western society that it's hard to conceptualize a path forward that would provide any substantive hope of bringing it to an end. Across the developed world, society has become dependent upon the systematic extinction of all preborn life judged to be inconvenient. Add to this our medical-industrial complex's dependence on the bodies of this holocaust's victims for many of the raw materials needed for their research and development, and the near impossibility of restoring the protection of every child's right to life, liberty, and the pursuit of happiness from the moment of conception becomes clear.

Repentance and reform are always difficult, though, and we must confess publicly that this world was created by the God who is truth, and truth is its own justification.

Now then, to make any claim to democracy is to make a parallel claim to the value of each individual. Do each of these little ones robbed of life while nestled safely in the body of their mother not have a right to be born, to live, to work, to study, to play, to laugh, to cry, to marry, to have their own children; and as they die, to leave an inheritance to their grandchildren?

Yet here we are, the Great American Empire spreading democracy around the world while robbing these little ones of every one of their human rights. The little ones don't even get a vote on the use of their leftover body parts by medical science and product development.

All of the ghoulish trafficking and research happen behind laboratories' closed doors, so it's easy for us to claim ignorance, trotting out a modicum of knowledge only when it is useful politically, to further some other more expedient end. Are we wrong, then, to force the church to see the extent of this horror? Would it not be better to allow our brothers and sisters in Christ to continue to live in ignorance, or at least plausible deniability?

Surely not. It is the duty of God's servants to tell the whole bloody truth. Until we see this truth, we will never know what is being done to our little neighbors, and our love will never extend to these particular "least of these" of our Lord. The traders in the body parts of preborn babies might think they're getting away with it---and humanly speaking they are. But across Scripture, God speaks the same truths He spoke to the prophet Ezekiel:

The iniquity of the house of Israel and Judah is very, very great, and the land is filled with blood and the city is full of perversion; for they say, "The [Lord]{.smallcaps} has forsaken the land, and the [Lord]{.smallcaps} does not see!" But as for Me, My eye will have no pity nor will I spare, but I will bring their conduct upon their heads. (Ezek. 9:9--10)

The bloodshed associated simply with researchers' constant need for fetal body parts runs so deep, and is so pervasive, that readers may wish us to be specific in our guidance here, providing particular steps we should take to begin to oppose it. But here, we think it best to refrain from doing so.

Remember, fetal research encompasses a very broad sphere of scientific investigation involving far more than the development of cell lines. Keep in mind also that in this more encompassing area we are referring to as "fetal research," the church at large is very limited in its understanding. As God's people are taught and grow in our knowledge of this evil, consciences will be awakened to the multifaceted nature of this thorny issue and choose this or that method of defending these lives too. Likely there will be those who decide they will not allow any vaccinations in their family, whether for children or adults, whether for diseases similar to polio or to this year's flu. Others will decide to work toward the growth of scientific research that displaces the continued need for dependence on present cell lines for valuable testing and research. Many voices will produce a variety of places of conscience and witness, as God leads each of us.

But wherever this or that person or congregation chooses to stand, every effort must be taken to avoid making that standing place a test of orthodoxy or Christian faith. We must avoid such division and schism. Where one conscience has been awakened and pricked on such matters, there is also the potential for judging another conscience that does not share that person's precise convictions. And of course, we know that every man thinks every other man should share his convictions, so on an issue with such weight as the bodies of little babies, the possibility of censoriousness is great.

The firestorm in the church over Covid has recently shown the great potential for schism over secondary and tertiary matters, but it has also shown that a variety of Christian responses can be within the bounds of Scripture and according to godly principles.[^48] For example, on the question of vaccines and fetal research, Cardinal Ratzinger's letter on the use of vaccines prepared from cells derived from aborted babies shows but one way of approaching the topic in a careful and Christian way.[^49] Other such evaluations could and should be written, and it is our hope that God through His Spirit grants the church an increasing knowledge and wisdom on how to address these matters with courage, wisdom, and unity.