# Applications

We now turn from the historical context, development, and spread of abortion, as well as its condemnation by nature, church history, common law, and Scripture, to the pressing question of what should be done by the church today to repent of this evil, and how God's people are to work toward restoring the liberties and freedoms of our most vulnerable and innocent neighbors. What shall we do to work toward repentance and the end of abortion?

## The Duty of Civil Authorities

<div id="fninfo" data-fnstart="1"></div>

It's easy to summarize the duty of civil authorities in response to abortion, particularly in light of the Supreme Court's reversal of *Roe v. Wade*: They must stop it. They must forbid it by law, then punish those who break the law. They must protect and defend those God has placed under their care. They must fear and honor God by recognizing His image in every man, woman, and child. God has ordained them to punish evil and reward good. And concerning those who murder unborn children specifically, the civil authority must obey God's command, "Whoever sheds man's blood, by man his blood shall be shed, for in the image of God He made man" (Gen. 9:6).

These things are easy to write and speak, but difficult to do. Still, as with all duties commanded by God, governing with justice will yield its fruit of peace and righteousness; it will bring on both the ruler and those he rules God's approval and blessing.

### The Civil Ruler and God's Law

In Romans 13, the Apostle Paul presents the clearest, most direct declaration of the civil magistrate's duties:

> Every person is to be in subjection to the governing authorities. For there is no authority except from God, and those which exist are established by God. Therefore whoever resists authority has opposed the ordinance of God; and they who have opposed will receive condemnation upon themselves. For rulers are not a cause of fear for good behavior, but for evil. Do you want to have no fear of authority? Do what is good and you will have praise from the same; for it is a minister of God to you for good. But if you do what is evil, be afraid; for it does not bear the sword for nothing; for it is a minister of God, an avenger who brings wrath on the one who practices evil. Therefore it is necessary to be in subjection, not only because of wrath, but also for conscience' sake. For because of this you also pay taxes, for rulers are servants of God, devoting themselves to this very thing. Render to all what is due them: tax to whom tax is due; custom to whom custom; fear to whom fear; honor to whom honor. (Rom. 13:1--7)

Note what is said about governing authorities:

1.  They are from God.
2.  They are appointed by God.
3.  They carry out the ordinances of God.
4.  They are a terror, not to good, but to evil.
5.  They are God's ministers for good.
6.  They are avenging ministers of God to bring God's wrath on those who do evil.
7.  They are to be supported by us through taxes, customs, fear, and honor.

These statements are true of every civil magistrate no matter his particular bailiwick. The degree and scope of implementation will differ according to the office he holds. The president of the United States has a much larger sphere to govern than a city's mayor or a county councilor, yet the essence of their duties is the same. We may encapsulate these truths by focusing on the magistrate as a minister of God. In common parlance, we think of "minister" as synonymous with "pastor," but the latter is simply one species of the former.

The analogy is instructive. The pastor is a minister of God's ordinances too, but the ordinances he is to enforce are of a spiritual sort since God has delegated him authority over His church. God has not delegated him the sword, but rather the keys of His spiritual kingdom; and, in that connection, the administration of the sacraments by which the boundaries of His kingdom are made visible.

The civil ruler is a minister of God's ordinances also---but those pertaining to public life. God has granted him the ministry of authority over the public sphere of law, government, and justice. God has delegated him the sword to enforce the laws that govern his sphere. Further, those laws are not, ultimately, his own, since they flow from the eternal law of God:

> I am not now speaking of the observance of the law of nature and of the divine law, or of the law of nations; observance of these is binding upon all kings . . .[^205]

The civil ruler has authority to promulgate and administer the law, but he also has been delegated by God's authority to enforce that law through punishment. This is what Scripture refers to when it designates him an "avenger" of evil, referencing the sword that he bears. Not only does he have the ability, authority, and right to punish evil; he has the *duty* to do so. This is part of the ministry he has received from God, and he may not lawfully divest himself of it.

Moreover, the obligation of the civil ruler to enforce God's law is inseparable from his duty to discern who is violating the law. As with rulers of other spheres, the civil ruler must discern good from evil. Some understanding of good and evil can be gained from natural law, but full knowledge can only come from divine revelation:

> Yet undoubtedly the revealed law is (humanly speaking) of infinitely more authority than what we generally call the natural law. Because one is the law of nature, expressly declared so to be by God himself; the other is only what, by the assistance of human reason, we imagine to be that law. If we could be as certain of the latter as we are of the former, both would have an equal authority; but, till then, they can never be put in any competition together.
> 
> Upon these two foundations, the law of nature and the law of revelation, depend all human laws; that is to say, no human laws should be suffered to contradict these.[^206]

Enforcing and administering the laws also has reciprocal elements. Just as the Seventh Commandment does not simply forbid adultery, but also enjoins love and fidelity toward one's wife,[^207] so also the ruler's obligation to punish evil requires him to promote good. The ruler who cultivates good relations with foreign nations but refuses to commit arms to stopping an invasion is in violation of his duty. The city councilor who encourages citizens to vote but does not punish voter fraud is a failure.

Similarly, concerning abortion, the civil magistrate must understand he is a minister of God's command that those who shed the blood of man shall suffer the same. He must bear the sword of God's wrath against the one who murders His image-bearers, carrying out His sentence of death. The ruler's own background, history, opinions, sentiments, compunctions, feelings, and so on are, in one sense, immaterial. As with any other murder, the injunction against child murder comes from the Chief Lawgiver, and each subordinate lawgiver He has established has a duty to carry out the law established by His authority.

Neither the law nor the authority is, in fact, the minister's own; they are delegated to him for a specific function which is, in its negative dimension, to stop the evil of child murder. In its positive dimension, he is commanded to do all he can to value, honor, and care for the life of mankind as God has ordained and established it under His rule.

Thus the civil authority is required by God to defend the unborn by criminalizing abortion to the end that our little ones may be restored to the protection of the rule of law. In enforcing laws against mothers killing their babies, the civil ruler must beware of the temptation to profess he has more tenderness and compassion than God Himself. In America, our civil authorities formerly forbade abortion. Those laws must be restored.

In doing so, the overturning of *Roe* is a necessary and long-desired step. But, as we said earlier, joy in the downfall of *Roe* must not blind Christians to what is glaringly absent in the majority opinion of *Dobbs*: the recognition of the personhood of the unborn child. It is well for us to argue on the basis of federalism that the national government may not force abortion on the states, on the basis of strict constructionism that no constitutional right to abortion exists, or on the basis of originalism that the founders envisioned no such right---but all such arguments pale before the foundational issue: that, by God's decree, no man may lawfully destroy the image of God placed in man. So long as we in our laws continue to see originalism as the only proper basis for opposing abortion, we fall short of God's requirements. We act as Constitutionalists but not as Christians. May the end of *Roe* be only the *first* step in restoring God's rule of law to our nation.

Moreover, it will not be enough merely to restore pre-*Roe* legal frameworks. At that time, the law was inconsistent in its application. State and local laws permitted exceptions while not making those who procured abortions liable for the crime of murder. Even those who performed abortions were not punished for murder. The Supreme Court in *Roe v. Wade* noticed this inconsistency and decided this abolished the argument that preborn children are persons with due process afforded to them in the Constitution. The court said:

> When Texas urges that a fetus is entitled to Fourteenth Amendment protection as a person, it faces a dilemma. Neither in Texas nor in any other State are all abortions prohibited. Despite broad proscription, an exception always exists. The exception contained in Art. 1196, for an abortion procured or attempted by medical advice for the purpose of saving the life of the mother, is typical. But if the fetus is a person who is not to be deprived of life without due process of law, and if the mother's condition is the sole determinant, does not the Texas exception appear to be out of line with the Amendment's command?
> 
> There are other inconsistencies between Fourteenth Amendment status and the typical abortion statute. It has already been pointed out . . . that in Texas the woman is not a principal or an accomplice with respect to an abortion upon her. If the fetus is a person, why is the woman not a principal or an accomplice? Further, the penalty for criminal abortion specified by Art. 1195 is significantly less than the maximum penalty for murder prescribed by Art. 1257 of the Texas Penal Code. If the fetus is a person, may the penalties be different?

A preborn baby *is* a person, and just as civil magistrates should work to overthrow all laws and policies that allow and promote abortion, they must do so with God's law as their standard. Abortion is murder according to God and should be treated as such by the civil magistrate.

Such a commitment to the law would not simply deter this great evil, but it would also serve a teaching function much needed now when it has become a habit to speak and think of little babies as "wanted" or "unwanted," "planned" or "unplanned"; when it has become our habit to dehumanize these little ones by referring to them as "fetuses," "fetal tissue," and "the products of conception."

Another element of this teaching work has already begun in some states. When a child's life ended in miscarriage or stillbirth, for many years the "fetus" was disposed of by hospitals and doctors. In fact, mothers and fathers were often forbidden by law from taking their dead child to bury and mourn. Such laws teach falsely that unborn children are not human beings, and that their loss is nothing to mourn. Recently, however, in some places the law now requires doctors and hospitals to offer mothers and fathers the opportunity to take their child's body, regardless of how old or young he may have been.[^208] Laws such as this remind everybody involved that a miscarriage or stillbirth is not simply the loss of "fetal tissue," but the death of a child.

From conception, every little one created by God bears His image and likeness, so that to shed his blood is to destroy God's glory in him. Child-killing is an act of warfare against God Himself, and the civil ruler is required by God to execute His wrath upon all those committing this awful crime.

### Keeping Our Eye on the Ball: Understanding the Dangers of Incrementalism

Civil magistrates must also be attentive to the current context of abortion, noting where their action is most needed. Presently, as we have noted, pro-lifers' and anti-abortionists' attention is fixed on surgical abortion. It is assumed that success on the surgical front will be a substantive victory toward the suppression of abortion overall. And, to be sure, we rejoice in the present decline of surgical abortions. It is God's blessing that, as technologies such as ultrasound shove our noses in the gore of our surgical child murders, many citizens and rulers could no longer countenance such an obvious moral monstrosity. Reforming our infant holocaust must start somewhere, so it is good there is some movement in the laws of our land outlawing a few of the more horrendous parts of this bloodshed. It is also good for the ghouls of Planned Parenthood and the National Abortion Rights Action League to see progress in laws against abortion, and to have a growing fear that society will condemn, outlaw, and punish their bloodlust.

On the other hand, while it is true that politics is the art of the possible, the people of God must let our voices be heard when pro-life legislation is proposed and passed which forestalls the abolition of abortion. We must fight against this bloodshed until all those profiting from it personally, financially, and politically are brought down from power and the lives of our little ones are brought back under the law's protection; until all the institutional forces protecting this bloodshed repent or yield up their authority in an unconditional surrender.

Laws outlawing this or that more limited aspect of our baby holocaust can be harmful if they diminish our zeal in opposing this holocaust itself. Incrementalism can have unintended consequences that are harmful to the larger goal. Eating away at the edges of our bloodletting may become a sort of medieval morality play that confirms our feelings of moral superiority while demoralizing us so we take no larger step towards the entire outlawing of abortion.

Today, the overturning of *Roe* is a prime example of both the benefits and the limits of incrementalism. On the one hand, *Roe* was birthed in a long twilight of gradual compromises and defeats. It represented not the initial salvo from the Evil One against the unborn, but rather the culmination of decay in our marriages, churches, and societies for some one hundred years previous. And so, as *Roe* happened by incremental decay, so its downfall happened by gradual progress. Much of this has been noted in this document. The awakening of the (Protestant) Christian conscience. The development of ultrasound technology. The political awakening of Christians and their recognition of abortion as a bedrock issue. The pushing of laws to restrict abortion. The attempt to close abortion "clinics" by creative means. The election of presidents committed to appointing SCOTUS justices who would overturn *Roe*. For reasons known only to Himself, God chose to bring *Roe* down, not suddenly, but by the gradual work of faithful Christians.

Yet gradual success brings with it its own dangers. Having toiled for so long to achieve even a small victory, we rest on our laurels and take our ease. Having crossed the Jordan and defeated Jericho, we content ourselves with the land already taken by our fathers, and fail to achieve the victories and gain the ground given us by the Lord. And when a man with faith challenges us to fulfill the mission we've been given, we think him foolish. We mistake faithlessness for prudence, sloth for judiciousness, and think God incapable of working if not according to our conceptions. Faced with Goliaths on every bloody front, we quash the Davids in our midst, calling their zeal presumption and their courage recklessness.

Then, too, success tempts us to think more highly of ourselves than we ought. We become enamored with our wisdom, our strategies, our understanding of the body politic, our compassion for women, and so on---forgetting that the One who has called us to fight abortion is the same One whose thoughts are far above our own:

> Do you not know? Have you not heard?
> The Everlasting God, the [Lord]{.smallcaps}, the Creator of the ends of the earth
> Does not become weary or tired.
> His understanding is inscrutable.
> (Isa. 40:28)

There are also practical matters to consider. In particular, the civil authority should consider that anti-abortion bills that are limited in scope can have unintended consequences. Remember that the law is a teaching mechanism. As noted earlier, one unintended consequence of the pro-life focus on surgical abortions---say, for instance, twenty-week abortion bans and heartbeat bills---is that abortion moves to younger ages not impacted by these laws. An exclusive focus on surgical abortions may well entrench the murder of children at increasingly younger ages---ages it is more difficult to marshal political opposition to.

Worst of all, victory on one front can cause us to redefine the command and counsel of God. Having labored for many years against the most obvious symbol of abortion in our land, we begin to confine God's commands to it. Unable in our strength to abolish abortion completely, we satisfy ourselves that overturning *Roe* is surely enough work, and surely will please God enough. And in so doing, we circumscribe the law of God, justifying ourselves by our paltry works and omitting what we cannot achieve:

> Woe to you, scribes and Pharisees, hypocrites! For you tithe mint and dill and cummin, and have neglected the weightier provisions of the law: justice and mercy and faithfulness; but these are the things you should have done without neglecting the others. (Matt. 23:23)

Indeed, our tendency to focus on the less painful parts of reform is obvious. For example, observe how pro-lifers focus almost exclusively on surgical abortions. For a number of reasons, it's much more difficult to oppose and pass laws against chemical abortions, yet chemical abortions (what abortionists refer to as "medication abortions") are now the majority of abortions. It may be possible to focus on some aspects of chemical abortions without outlawing them entirely at first, but we must be honest with our arguments, never misleading the babies' murderers to the end that they think they can manipulate the Christian vote and retain their authority by occasionally fiddling around the edges of this ongoing slaughter. In all cases, we must be clear that the Christian conscience is principled---not pragmatic; and that its driving principle can never be stated either personally or in legal code as anything less than "Whoever sheds man's blood, by man his blood shall be shed, for in the image of God He made man."

Thus, to the extent that *Roe* is now overturned and some aspects of law concerning preborn human life return to pre-*Roe* frameworks, we should be glad, and should take stock of the means that led to this success. Yet we may never content ourselves by seeing *Roe* as the limit of our opposition to abortion. Its undoing is something that we *ought to have done*, but we may not leave *undone* the work of abolishing the countless remaining manifestations of abortion. IUDs, RU-486, Plan B, hormonal birth control---all these remain and are growing, and they are an enemy as deadly and entangled with us as *Roe* ever was.

Christians must therefore not regard any victory in the battle as the end of the war. Even with *Roe* overturned, no state has yet completely banned abortion (Oklahoma has come closest), and children younger than six weeks will continue to be killed even in states where abortion is curtailed. A generation ago, godly Christians might have seen overturning *Roe* as the final goal in ending abortion, but the truth has now become clearer. The end of *Roe* is not the end of abortion, nor even the beginning of the end, but rather---perhaps---the end of the beginning.[^209]

### Zeal Tempered by Knowledge: Prudent Policies

Scripture demonstrates that zeal for God's law and character is a constant feature of civil authorities who are praiseworthy. One is hard-pressed to find Scripture ever condemning a man for zeal for God's glory. Yet zeal alone doth not a just ruler make. Zeal must be tempered by knowledge:

> For I testify about them that they have a zeal for God, but not in accordance with knowledge. (Rom. 10:2)

Our Lord Himself warned against undertaking a task we lack the resources to complete:

> For which one of you, when he wants to build a tower, does not first sit down and calculate the cost to see if he has enough to complete it? Otherwise, when he has laid a foundation and is not able to finish, all who observe it begin to ridicule him, saying, "This man began to build and was not able to finish." Or what king, when he sets out to meet another king in battle, will not first sit down and consider whether he is strong enough with ten thousand men to encounter the one coming against him with twenty thousand? Or else, while the other is still far away, he sends a delegation and asks for terms of peace. (Luke 14:28--32)

Assembling resources, developing strategies and tactics, assessing our opponent's resources, strategies, and tactics, and carefully considering possible collateral damage---in all these things we must temper our zeal with knowledge. Civil authorities willing to join this battle must consider not just the ultimate goal of abolishing abortion, but the means and resources God has supplied. We must evaluate the condition our fellow Christians' hearts with respect to abortion. Do those we must depend upon in this battle---our brothers and sisters in Christ---truly understand the nature of this killing in all its sordid details? Do they have the will to call their neighbors and rulers to repentance, or are they aiming simply at repeating shibboleths of the pro-life movement?

We see the sort of hostilities and dangers we will face from fellow believers as we read the history of the kings of Israel. Beginning with Solomon, Scripture records a relentless decline in the faithfulness of God's people, and this decline was represented and led by Israel's faithless and wicked kings. We have already noted some of the worst of these: Manasseh was the king of God's covenant people when he led them in sacrificing their little covenant children to the demon god of Molech.

Yet Israel was also led by godly kings such as Jehoshaphat, Hezekiah, and Josiah. The hearts of these men were toward God, and thus they sought to end the gross wickedness of their predecessors and the people they ruled.

It is noteworthy that Scripture is not absolutist toward even these godly kings, but faithfully documents both the good and evil of their leadership:

> He [Jehoshaphat] walked in the way of his father Asa and did not depart from it, doing right in the sight of the [Lord]{.smallcaps}. The high places, however, were not removed; the people had not yet directed their hearts to the God of their fathers. (2 Chron. 20:32--33)

This is the refrain of many a righteous king: he "did what was right in the sight of the [Lord]{.smallcaps}," yet "the high places were not taken away." In this and many similar passages, the Holy Spirit does not tell us *why* they were not taken away. We can imagine any number of reasons. The king had no desire himself to remove the high places. Or maybe he wanted to, but it was inexpedient or politically impossible. Maybe his advisors opposed him in it. It could well be that he was worried what his queen would think (à la Solomon).

In one sense, the reason doesn't matter; it was evil that the high places remained, and this was a blot on the soul of the king and his nation. Yet note how this failure is not the focus of the summary of the king's life.[^210] It's important enough to mention, but does not dominate. It is possible to read this as a direct condemnation of the king, yet also possible to read it as more an assessment of the spiritual state of the nation and the attending realities.

So why were the high places not removed? Well, in Jehoshaphat's case, we're told why: "The people had not directed their hearts to the God of their fathers." Certainly, they ought to have; but they hadn't. They were not yet at that point in their repentance.

Our nation and its bloodshed are much like this. We have kings and rulers who resemble the kings of Israel who worshiped the true God without tearing down the idols and high places. Some of our rulers are devoted to abortion's bloodshed, while others are apathetic. Some rulers oppose abortion's bloodshed, but do so timidly. Only a very few have shown zeal in working to bring this genocide to an end.

Depending upon which sort of rulers we are governed by, we can see a variety of strategies and intentions motivating this or that policy initiative or law restricting abortion. One ruler supports an anti-abortion initiative for his own political advantage; another does so because he has some commitment to morality; and yet another because he truly fears God and honors His moral law. Still, this and similar leadership motivated by any even minimal desire to end abortion that leads to fewer infants being killed is something to rejoice over. And if we do have a ruler who fears God, we can rejoice all the more.

Recognize, though, that having the blessing of being governed by a ruler who fears God and trembles at the bloodshed of babies does not make the way forward totally clear. Even then, not all those who fear God and pray for the abolition of abortion will see strategy and tactics in the same way.

What some promote as a daring sortie testifying to faith and zeal will be condemned by others as a Pyrrhic victory that will result, not in less bloodshed, but more, because the zealot did not take into account all the factors: the probable response of the watching world, the stiffening of resolve on the part of godless rulers, or the effect of their action on the people of God themselves. Every calculation of how many babies will be saved each year when, by God's power, abortion has finally been criminalized, must be accompanied by a parallel calculation of how many babies will be lost. Remember, politics is the art of the possible. Our principled and absolute opposition to all abortion must not give birth to zeal without knowledge which causes even more bloodshed of the preborn.

With this in mind, civil rulers must temper zeal with wisdom from on high. We must sympathize with them in the difficulty of their decisions, praying that God will give them wisdom. In whatever station and with whatever gifting God has given them, civil rulers should work toward stopping abortion as quickly and as completely as possible. In some cases (e.g., as has been done with *Roe v. Wade*), this will mean supporting a law directly challenging a decision, policy, or law that upholds abortion in our land. In other cases, prudence may require a ruler to prioritize a strategy offering the most long-term benefits for ending the bloodshed. This may cause him to expend more energy on a bill or policy less direct in its challenge to abortion because he believes doing so has more potential to hamper the bloodshed in the future. Remember that *Roe v. Wade* did not draw its legal foundation from blunt preestablished "rights" to abortion, but from the subtle expansions of rights of "privacy" that had wound their way through earlier decisions such as *Griswold v. Connecticut*. The direct attack is not always the best path to victory. All that glitters is not gold.

For all the above reasons we renew our commitment to the truth that it is not the office of the church to dictate exactly how the civil magistrate must do his work. If complete abolition of abortion is not politically feasible in a given polity at a given time, it is still godly for the civil authority to save as many lives as possible through efforts short of complete abolition---always keeping firmly in mind that complete abolition is God's decretive standard and must remain the ruler's final objective.

### The Accountability of Civil Rulers

Thus we remind every ruler that he will face accountability for how he has stewarded his authority from God. Some of his accountability will be to higher magistrates and some to those who elected him.

Nevertheless, his final accounting will be to God. He will give account to God for how he fulfilled his duty to punish evil and reward good. He will not be judged according to what he or his subjects think is evil or good, but according to what God's moral law declares evil and good. Whether he acknowledges it or not, the day is quickly coming when he will stand at the bar of the Almighty, and on that day no excuses will avail for his refusals to carry out the duties of his God-ordained station.

Every civil ruler will be judged by God for honoring or abandoning the defense of life, and especially the defense of lives weak or powerless because they live at the margins of society. This is the most fundamental God-given duty of a civil magistrate. In other ways, a particular ruler's administration of law might be commendable: he may have lowered taxes, cleaned out corporate corruption, balanced the budget, conserved natural resources, reduced government tyranny, and enhanced religious freedom across his domain; yet if he has turned a blind eye to the bloodshed of those living at the margins of his domain and not striven to bring it to an end, his administration has failed at the most basic duty God has delegated to him. The bloodguilt must be removed from the land, and he is the one charged by God with the responsibility of doing so.

Knowing God's requirements, yet being aware of our own inability, we are tempted to make only token efforts, only perfunctory attempts we know will accomplish little. Concerning abortion, we all have observed how often politicians play games with the lives of these little ones. Not having the courage to stand on principle, politicians run on being "pro-life"; they write pro-life commitments into their party platforms, then spend almost none of their political capital defending the little ones. Announcing that they are "pro-life" is a political ruse more for getting out the vote and raising campaign contributions than for ending abortion. For this reason, those who oppose abortion commonly lament, "Fool me once, shame on you. Fool me twice, shame on me. Fool me three times, I'm a Republican."

Still, despite all the promises our rulers have left unfulfilled, knowing our God's arm is mighty in behalf of the widow, the orphan, and the sojourner in our midst, by faith we rejoice in the sure and certain truth that God sees, God knows, and will bring every deed into judgment.

Apathy, half measures, and unfaithfulness are not exclusive to rulers, of course; they are common to man. Yet Scripture is clear that with authority comes greater accountability. The Apostle James warned teachers, "Let not many of you become teachers, . . . knowing that as such we will incur a stricter judgment" (James 3:1). If our teachers will be judged by God more strictly, what of His judgment of civil rulers whose raison d'être is judgment and punishment? Of all offices in God's economy, the civil ruler is the only one given expansive powers of temporal and physical penalties. He is the only one given the power of the sword, the only one authorized to compel financial support, the only one authorized to make war. God has made him steward of great power and authority, and has directed him to use it to serve and protect his citizens. The civil authority must fear God and His judgment:

> And the Lord said, "Who then is the faithful and sensible steward, whom his master will put in charge of his servants, to give them their rations at the proper time? Blessed is that slave whom his master finds so doing when he comes. Truly I say to you that he will put him in charge of all his possessions. But if that slave says in his heart, 'My master will be a long time in coming,' and begins to beat the slaves, both men and women, and to eat and drink and get drunk; the master of that slave will come on a day when he does not expect him and at an hour he does not know, and will cut him in pieces, and assign him a place with the unbelievers. And that slave who knew his master's will and did not get ready or act in accord with his will, will receive many lashes, but the one who did not know it, and committed deeds worthy of a flogging, will receive but few. From everyone who has been given much, much will be required; and to whom they entrusted much, of him they will ask all the more." (Luke 12:42--48)

Hearing this high calling might cause any man to despair. Seeing the corruption of their own hearts and the corruption of those under their authority, many rulers have thrown in the towel. Yet those suffering this temptation should remember that, though God is perfectly just and holy, He also knows His sons are not. He knows our frame and remembers that we are dust (Ps. 103:14).

Yes, this is the command given by Jesus: "You are to be perfect, as your heavenly Father is perfect" (Matt. 5:48). God doesn't dream or wish we were perfect in our exercise of authority: He commands us to be so. His standards are perfection. This is a fundamental gospel truth because the hopelessness of perfection in ourselves and our subjects causes us to despair of ourselves and live by faith in Jesus Christ, the Savior of the whole world to whom God the Father has delegated all authority in heaven and on earth (Matt. 28:18).

So then, we are to honor and keep His commandments, but we do so by faith in the Lordship of Jesus Christ, knowing that this faith has already overcome the world, making His commandments not grievous to us:

> For this is the love of God, that we keep His commandments; and His commandments are not burdensome. For whatever is born of God overcomes the world; and this is the victory that has overcome the world---our faith. (1 John 5:3--4)

This work of governing requires wisdom, care, and the ministry of the Holy Spirit. No ruler, nor any one of us, is sufficient for these things (2 Cor. 2:16), and it is only through the power of God and the fellowship of His church that any ruler may hope to honor God, particularly in his defense of the unborn. That defense may or may not result in great and epic advances against the evil of abortion, but no better epitaph for a magistrate's efforts could be given than this one given by our Lord: "She has done what she could" (Mark 14:8).

## The Duty of Church Authorities

<div id="fninfo" data-fnstart="7"></div>

### The Church and Abortion: Success Followed by Failure

In *Moby Dick*, Herman Melville makes the simple observation, "The pulpit leads the world." He adds, "Yes, the world's a ship on its passage out, and not a voyage complete; and the pulpit is its prow."[^211] Jesus said He would build His church, and He promised the gates of hell would not prevail against her.

The Christian church is always to be on the offensive. After His resurrection, our Lord declared, "All authority has been given to me in heaven and on earth." It is His---not our own---authority we carry to the ends of the earth, teaching all men to do what He has commanded. We are His church militant.

God delegated the keys of His kingdom to the officers of His church. Thus pastors and elders lead the world through the proclamation of His Word, yes, but also through their exercise of these keys in their practice of church discipline. Immediately following our Lord's ascension, the power and authority of the King of kings and Lord of lords was carried by the church and her officers across the Roman Empire.

The New Testament church was born and grew in a world of infanticide, abortion, and fruitlessness. Through the pulpit, then, the early church proclaimed and practiced the protection of the weak and vulnerable, as well as the restoration of fruitfulness to the marriage bed. The church rescued unwanted, exposed infants left to die in the garbage heaps of Roman cities. The church protected the aged and infirm. As the church spread through Asia Minor, North Africa, and the Roman Empire, obedience to God's law spread. Contraception dwindled and abortion became unthinkable. Church fathers did not cease condemning the slaughter of the preborn, as well as all attempts to remove fruitfulness from marriage. Even when the church adopted unbiblical views of sex and celibacy, it did not alter its witness to these basic divine truths concerning procreation and the wickedness of abortion.

It is a terrible tragedy, then, that it was the twentieth-century church and her officers who led the West into the legalization and widespread practice first, of birth control and contraception, and then abortion. It was the early part of the twentieth century when the first major denomination announced that artificial birth control was an acceptable practice.

In August of 1930, breaking with all Christendom, the officers of the Anglican Church announced at their decennial Lambeth Conference their repudiation of their historic condemnation of intentional prevention of pregnancy.[^212] A few months later, the Federal Council of Churches followed suit, endorsing "the careful and restrained use of contraceptives by married people."[^213]

Those unaware of the uniform condemnation of contraception and abortion by Christendom will find instructive this March 22, 1931, editorial by the *Washington Post* written in response to the Anglican pronouncement:

> It is impossible to reconcile the doctrine of the divine institution of marriage with any modernistic plan for the mechanical regulation or suppression of human birth. The church must either reject the plain teachings of the Bible or reject schemes for the "scientific" production of human souls. Carried to its logical conclusion, the committee's report if carried into effect would sound the death-knell of marriage as a holy institution, by establishing degrading practices which would encourage indiscriminate immorality. The suggestion that the use of legalized contraceptives would be "careful and restrained" is preposterous.[^214]

The Anglicans' reversal was not in response to some new discovery in the Bible or any advancement in theological understanding. Rather, it seems evident the change of doctrinal standards followed the practice of the pastors in their own lives.

For instance, an actuarial survey of the professional and upper classes in the UK during 1875 showed clergymen had an average of 5.2 children.[^215] This was on par with the UK's national average. Yet when the 1911 census was taken, this figure had dropped to 2.8 children. Meanwhile, the national average remained at 3.7. Two decades before announcing their change in doctrine, the men of the pulpit had already changed their practice so that, inevitably, their personal practices changed their preaching.

To return to the *Washington Post*, it was only a matter of time until the Anglican bishops' talking point "careful and restrained" vanished, just as Planned Parenthood, the Religious Coalition for Abortion Rights, and the National Abortion Rights Action League's talking point about keeping abortion "safe, legal, and rare" has also vanished. It took a mere thirty years for the "careful and restrained use" of contraception to give way to the National Council of Churches' full embrace of abortion. It was February 23, 1961, when the National Council of Churches endorsed abortion---twelve years before the Supreme Court legalized infant murder in 1973.

Ten years after *Roe v. Wade*, the Presbyterian Church (USA) declared abortion "an act of faithfulness before God":

> Protestants have long affirmed the use of contraception as a responsible exercise of stewardship of life. To prevent pregnancy when it is not desired is to be a responsible steward of human life. However, in the exceptional case in which a woman is pregnant and judges that it would be irresponsible to bring a child into the world, given the limitations of her situation, it can be an act of faithfulness before God to intervene in the natural process of pregnancy and terminate it.[^216]

In 1970, three years prior to the Supreme Court's *Roe v. Wade* ruling, the Baptist Sunday School Board (now known as Lifeway) conducted a poll which found that 70 percent of Southern Baptist pastors supported abortion to protect, not just the physical health of a mother, but also her mental health; and that 64 percent of Southern Baptist pastors supported abortion in the case of a fetal disability. One year later (1971), the Southern Baptist Convention (the largest Protestant denomination in the US) at their annual national meeting passed a resolution stating:

> We call upon Southern Baptists to work for legislation that will allow the possibility of abortion under such conditions as rape, incest, clear evidence of fetal deformity, and carefully ascertained evidence of the likelihood of damage to the emotional, mental, and physical health of the mother.[^217]

Two years later, a poll conducted by the *Baptist Standard* found that 90 percent of Texas Baptists believed their state's abortion laws were too restrictive. Here again, the pulpit led the world, removing moral censures against the slaughter of little ones in the womb. The world followed the church's leadership, and one year later the Supreme Court issued its bloody decree.

In subsequent years, the Southern Baptist Convention went through a "conservative resurgence," and by God's grace moved back from its former advocacy of abortion. Yet the damage had been done.

Today, we have some hope that opinion polls within conservative Christian denominations would not resemble those of the 1970s. There are many pastors faithfully working to awaken Southern Baptists' consciences to the horror of the slaughter of children. We appreciate this work in any denomination, and yet still today the most conservative Christian churches and congregations neglect or even refuse to give the souls under their charge biblical moral instruction concerning these matters.

For example, in 2019, the Pew Research Center analyzed nearly 50,000 sermons shared online by more than 6,000 US churches during the second quarter of the year, and they found that abortion was mentioned in only 4 percent of those sermons. Pew Research noted that, even when abortion was mentioned, it was rarely the focus of the sermon:

> When sermons are broken into smaller segments of 250 words (the median sermon runs 5,502 words), three-quarters of all sermons that mention abortion do so in just one segment. As a result, only 1% of all sermons across the whole database discuss abortion in more than one segment.[^218]

Given pastors' avoidance of these matters, it's no surprise researchers find more than 4 out of 10 women who have had an abortion are churchgoers,[^219] nor is it any surprise 54 percent of members of the Presbyterian Church in America believe abortion should be legal.[^220]

### The Church's Bloodguilt

We, the people of God, must confess our bloodguilt. As it was with Israel and Judah in the times of the Old Testament prophets, the people of God today have our children's blood on our hands.

We don't know how many of their lives we have sacrificed, and we're relieved not to know. At times we have used methods of birth control which have an abortifacient agency knowing full well we were doing so. At other times we have assuaged our consciences by telling ourselves we'll never know whether our method of birth control killed our child; and anyhow, it's more likely our birth control prevented conception than that it killed any little one God had created and placed in our wife's womb. We dampen down our consciences with self-talk of risk being an everyday part of life. It was not our intent to kill our little one. Surely any bloodshed we commit from a desire to provide our already-born children a college education and greater socioeconomic stability justifies any risk we take with our birth control.

It must be stated clearly that, among the people of God, the bloodguilt doesn't rest on fathers and mothers alone, but also physicians, nurses, and pharmacists who are brothers and sisters in Christ and who neglected to inform us that our birth control has an abortifacient agency. Among the people of God, many physicians, nurses, and pharmacists answered our questions with equivocations and lies concerning the medical choices they helped us make.

Listen to this command given by God to His covenant people, noting His warning against their pleading ignorance:

> Then the [Lord]{.smallcaps} spoke to Moses, saying, "You shall also say to the sons of Israel:
> 
> 'Any man from the sons of Israel or from the aliens sojourning in Israel who gives any of his offspring to Molech, shall surely be put to death; the people of the land shall stone him with stones. I will also set My face against that man and will cut him off from among his people, because he has given some of his offspring to Molech, so as to defile My sanctuary and to profane My holy name. If the people of the land, however, should ever disregard that man when he gives any of his offspring to Molech, so as not to put him to death, then I Myself will set My face against that man and against his family, and I will cut off from among their people both him and all those who play the harlot after him, by playing the harlot after Molech.'" (Lev. 20:1--5)

Bloodguilt is everywhere among God's people in the Western world today, especially here in North America where there still remains such a treasure of Christian faith and witness. Having been given much, our guilt is that much greater. God commanded Moses to warn His people against child slaughter. Who warns the people of God today?

God has set apart pastors and other church officers to preach and teach His Word today. In connection with intimate matters related to women and their life-givingness, it is the particular calling of our congregation's "older women" to instruct the women of the church in these life-and-death matters. Older women are called to teach godliness to the congregation's younger women; and specifically to teach the younger women to "love their children."[^221]

Would it not be the most basic fulfillment of this calling for older women to warn young brides and mothers against the horror of child sacrifice practiced all around us by the pagans? Yes, pastors must give this instruction and provide these warnings in premarital counseling also; but how can an older woman of God instruct a younger woman to love her children without warning her not to kill her children?

It is good and right for our older women to teach the younger women to read the Bible and pray, to keep a rein on their irritation at their little ones and not lash out in anger at them, to respect their husbands, to read the Bible to their little ones, to be patient with a child who is difficult to nurse, and so on. But does their obligation to lead the younger women of God not include speaking to them about the sanctity of the marriage bed and its fruit?

In the final analysis, though, none among the people of God have greater responsibility for the pervasiveness of the bloodshed of our children than the shepherds of Christ's church. The Apostle Paul testified to those he had shepherded in Ephesus that none of their "blood" was on his "hands." How had he acquitted himself of any bloodguilt?

> For I did not shrink from declaring to you the whole purpose of God. (Acts 20:27)

Today, pastors shrink and run from declaring to their sheep the whole counsel of God concerning sexuality, marriage, and God's blessing of children. Pastors have not warned their sheep against subverting God's purpose in the womb by shedding the blood of those children He Himself has placed there. Pastors in their pulpits, in their offices during marital and premarital counseling, and in every part of church life---as well as elders, deacons, and older women in their congregations---are neither teaching nor warning their sheep against the wiles of the Evil One who loves death, particularly the death of little ones who have just been created by our heavenly Father.

It's an awful truth that those we worship with who are marked by the sign of God's covenant continue to do obeisance to the pagans' demon gods of choice, self-determination, convenience, academic degrees, wealth, comfort, and a whole host of other idols, even joining them in their child sacrifices. God blesses us, entrusting the womb of our wives with new life for the propagation of His godly seed,[^222] and Christian wives leave His worship, drive home with their husband and children, eat dinner, and later go up to their bathroom and murder this little blessing He's given.

Do God's prophets warn them against this sin?

No. As in the days of the prophet Isaiah, so in our own day:

> His watchmen are blind, \
> All of them know nothing. \
> All of them are mute dogs unable to bark, \
> Dreamers lying down, who love to slumber; \
> And the dogs are greedy, they are not satisfied. \
> And they are shepherds who have no understanding; \
> They have all turned to their own way, \
> Each one to his unjust gain, to the last one. \
> "Come," they say, "let us get wine, and let us drink heavily of strong drink; \
> And tomorrow will be like today, only more so." \
> (Isa. 56:10--12)

Within the church today, God makes husband and wife one for the propagation of a godly seed; He blesses the husband and wife by creating a child in the womb of the wife; and we respond by practicing pregnancy prevention using hormones that regularly kill a child God has created and sent to us as His blessing.

Thus God's covenant people today commit the same sin as God's covenant people in the time of Manasseh and Solomon. Where is our King Josiah whose reform included forbidding and stopping the child sacrifices practiced by God's people?

> He [Josiah] also defiled Topheth, which is in the valley of the son of Hinnom, that no man might make his son or his daughter pass through the fire for Molech. (2 Kings 23:10)

### The Necessity of Repentance

Repentance is the only path back to the grace of God, but how shall pastors lead this repentance?

First, repentance must be preached. As they stand in their pulpits proclaiming God's Word, God's servants must not avert their eyes from the most helpless of lambs being taken away to the slaughter. Remember our Lord's parable of the religious leaders who walked past the victim lying injured in the road?

God has called us to rescue those being led away to death; to hold back those who are staggering to the slaughter (Prov. 24:11). Will our shepherds continue to close their eyes to the blood that stains the ground of our villages, cities, states, and nations? Will our shepherds continue to pretend they don't know about these deaths of the lambs of their flock?

Nothing is hidden from God, and He will repay according to what has been done and left undone, what pastors have said and left unsaid. From the ground, the blood of these little ones cries out to Him.

This is not a political issue, nor should pastors relegate the defense of these littles ones to a single pro-life Sunday each January. Nor should pastors preach as if the abortions are all done "out there" by others---and only at Planned Parenthood's clinics. One Sunday each year with condemnation only of outsiders is a betrayal of the pastoral office.

Shepherds must repent of their self-censorship which arises from a desire to avoid offending their people. The souls under the care of shepherds are sheep. Sheep must be taught and rebuked and led to confession of their sins by faithful shepherds watching over their souls, regardless of whether their sheep want to be rebuked and called to repentance.

If the response is that some things are impolite to speak of in mixed company, keep in mind that eternity and judgment are drawing near. How could it ever be impolite for men who are shepherds to call women to repentance for murdering their children---nor any less their husbands who are eager for, and complicit in, their decisions?

Women pay for abortion procedures and drugs. Some of our own mothers, wives, and daughters have committed abortion. Women we love and are called to instruct and protect should not lack shepherds who will speak truthfully, leading them into a biblical understanding and a true spiritual remorse for what they have done. Women who have committed abortions need the wounding of God's law so they may confess their crimes, and by faith alongside David, find forgiveness and have the joy of their salvation restored to them:

> Deliver me from bloodguiltiness, O God, the God of my salvation; \
> Then my tongue will joyfully sing of Your righteousness. \
> (Ps. 51:14)

In all the work of the pastor, he must keep this warning in mind:

> Now as for you, son of man, I have appointed you a watchman for the house of Israel; so you will hear a message from My mouth and give them warning from Me. When I say to the wicked, "O wicked man, you will surely die," and you do not speak to warn the wicked from his way, that wicked man shall die in his iniquity, but his blood I will require from your hand. But if you on your part warn a wicked man to turn from his way and he does not turn from his way, he will die in his iniquity, but you have delivered your life. (Ezek. 33:7--9)

True gospel ministry never consists of God's yes without His no.

### The Church's Public Witness against the Killing

As our Lord said, it was God who "from the beginning made them male and female" (Matt. 19:4). Sex is a station assigned each of us by God. We have no individuality that is not marked by God's call of each of us to the station of either man or woman. We cannot live by faith without doing so as men and women who, by faith, fulfill our sex biblically.

Given the pervasive rebellion of individuals today repudiating God's creation of each person as man or woman, the beginning of repentance and the first steps of faith will often be defined within the church by men and women rediscovering, learning to love, and fulfilling their God-given sexuality. One certain and joyful side effect of such a resurgence of biblical sexuality is that pastors who preach and teach with application to men as men and women as women will lead the way toward the abolition of abortion.

When pastors lead their people to rejoice in their God-given sexuality and to desire a godly seed (Mal. 2:15), this will awaken the consciences of the people of God to the horror of abortion's slaughter. Pastors who are fearful of the reaction of their sheep, and thus inclined to avoid serving as the instruments of this sexual awakening, may take encouragement and be strengthened by the Apostle Paul's exhortation: "Speak and exhort with all authority. Let no one disregard you" (Titus 2:15).

Men and women of God who discover the blessing of manhood and womanhood, marital love, and children will also certainly come to realize the wickedness of abortion and express a desire to witness against this great evil. This is particularly true of women who, prior to coming to faith or a truly biblical understanding of the blessing of unborn life, have aborted their little ones. Naturally, those who have repented of their own abortions will desire to find women considering abortion and awaken these women to the beauty of life and the terrible sin of killing our Lord's little ones, truly "the least of these":

> But when the Son of Man comes in His glory, and all the angels with Him, then He will sit on His glorious throne. All the nations will be gathered before Him; and He will separate them from one another, as the shepherd separates the sheep from the goats; and He will put the sheep on His right, and the goats on the left.
> 
> Then the King will say to those on His right, "Come, you who are blessed of My Father, inherit the kingdom prepared for you from the foundation of the world. For I was hungry, and you gave Me something to eat; I was thirsty, and you gave Me something to drink; I was a stranger, and you invited Me in; naked, and you clothed Me; I was sick, and you visited Me; I was in prison, and you came to Me." Then the righteous will answer Him, "Lord, when did we see You hungry, and feed You, or thirsty, and give You something to drink? And when did we see You a stranger, and invite You in, or naked, and clothe You? When did we see You sick, or in prison, and come to You?" The King will answer and say to them, "Truly I say to you, to the extent that you did it to one of these brothers of Mine, even the least of them, you did it to Me."
> 
> Then He will also say to those on His left, "Depart from Me, accursed ones, into the eternal fire which has been prepared for the devil and his angels; for I was hungry, and you gave Me nothing to eat; I was thirsty, and you gave Me nothing to drink; I was a stranger, and you did not invite Me in; naked, and you did not clothe Me; sick, and in prison, and you did not visit Me." Then they themselves also will answer, "Lord, when did we see You hungry, or thirsty, or a stranger, or naked, or sick, or in prison, and did not take care of You?" Then He will answer them, "Truly I say to you, to the extent that you did not do it to one of the least of these, you did not do it to Me." These will go away into eternal punishment, but the righteous into eternal life. (Matt. 25:31--46)

Men too, discovering not only the blessing of manhood and womanhood, marital love, and children, but also their manly biblical duty[^223] to protect the lives woman presents the race, will ask how they can help restrain and end this bloodshed. It is right for men and women to ask these questions and seek to stand up against the slaughter of the unborn. We will all seek to love and protect the least of these, and the officers of Christ's church will be called upon to give wise counsel concerning how to best witness against this horror.

While not every church is located within driving distance of a surgical abortion "clinic," many are, and it is a work of justice and love to go and bear witness against the bloodletting as those inside their mother's wombs are being led to the slaughter. Even though pharmacies dispensing murderous drugs are fast becoming the primary battleground, the abortuary remains a place of bloodshed, and there are Christian men and women who will desire to present a Christian witness there. This work should be supported by the wise counsel of their church officers. Examining how best to undertake this work is particularly necessary given the physical, legal, and spiritual dangers that attend any Christian witness at these killing places.

Other ways and places to witness against the bloodshed are best considered under the wise counsel of those officers congregants have vowed submission to. This is no light matter and should not be entered into unadvisedly. Standing against the massive murder of our little ones, though, is righteous, and where the officers of a particular church are uninterested in preaching against it as well as supporting public anti-abortion witness by their counsel and presence, it remains a Christian duty which will weigh heavy on the consciences of God's faithful. It is no sin for them to commend their conscience to God by such public witness.

Some churches will decide to witness against abortion publicly outside the abortuary on its killing days. Some will have no abortuary to provide sidewalk counseling to and may choose to picket their local supermarket pharmacies. Other churches will go together with fellow believers of neighboring congregations to picket the city's United Way offices where the community's charitable contributions are used to support Planned Parenthood. Some churches will call their members to attend county and city council hearings related to the zoning and support of the killing places. Other congregations will have pastors, elders, and deacons gifted for open-air preaching who will ask their people to come and support that preaching outside the abortuaries, pharmacies, and supermarkets, or at the county courthouse and inside the state capital.

Some churches will focus on social media forms of witness. Other churches will join together to write a doctrinal witness and teaching tool similar to this one that can be shared among their denominational churches, officers, and members. Other churches will start and support crisis pregnancy ministries, or provide financial support to couples in the congregation who adopt children---or embryos left in the "concentration can" of in vitro businesses.[^224]

Churches may provide an effective witness against abortion in countless ways. What is important is to be creative in providing men and women opportunities to speak up in defense of these little ones created by God; and, where possible, to provide this witness under the wise counsel and direction of the shepherds God has provided us in His church.

For Christians to undertake calling those killing their children to repentance is a gospel witness, not merely a political demonstration. But as we bear this witness, church members and officers must exercise caution and wisdom in this work, guarding against schism and division among God's people, as well as any needless scandal in the wider community.

Still, it must be said that any witness against the slaughter will inevitably give rise to scandal among those covered in blood and unwilling to repent. Truth is often scandalous, particularly when it exposes the bloodshed of the innocents. The mere fact of scandal in the community attendant to the church's witness against abortion may be the most clear evidence of the effectiveness of that witness.

In addition, all churches can and should be regularly praying for the end of abortion. Prayer doesn't take the place of these other forms of action but prayer itself is not passive. It is one of the main weapons of warfare that Jesus has given us. In sacred Scripture, the prayers of God's people are described as rising to the heavens like a pleasing aroma of incense. The fire of this incense is then hurled back to the earth in God's judgment on the enemies of Christ.[^225] Christ hears the cry of those who suffer, and He is the great Defender of the orphan. Churches should not forget the power of prayer, and they should pray for God's mercy on little ones and judgment upon those who oppress them without repentance.

Remember that the church, God's house, is to be a house of prayer for the nations (Isa. 56:7). The Apostle Paul instructed the church to offer entreaties *and* prayers, petitions *and* thanksgivings, on behalf of all people including those in civil authority (1 Tim. 2:1--2). Surely, the little children in the womb are among those who are of the nations that we ought to pray on behalf of. Prayer and thanksgiving for these children and their mothers ought to be a normal part of the intercessory work of the church. Pray that God would turn the hearts of the fathers and mothers toward their children. Pray that God would move the hearts of our civil authorities. Pray that all our efforts to bear witness will be used by God for His glory, the souls of mothers, and the lives of the preborn.

### Instructing the Civil Magistrate

Pastors are not simply called to shepherd God's flock. That is their primary call, but by that call they are also responsible to serve as God's servants commissioned to proclaim His law and gospel to the nations. Pastors today are God's servants, the prophets.

The gospel of Jesus Christ always and necessarily proclaims God's law. Calling men to repent and believe is no private Christian work, and this is our Lord's Great Commission:

> All authority has been given to Me in heaven and on earth. Go therefore and make disciples of all the nations, baptizing them in the name of the Father and the Son and the Holy Spirit, teaching them to observe all that I commanded you; and lo, I am with you always, even to the end of the age. (Matt. 28:18--20)

Add to this statement our Lord's call to His followers to be His witnesses to the world:

> You are the salt of the earth; but if the salt has become tasteless, how can it be made salty again? It is no longer good for anything, except to be thrown out and trampled under foot by men.
> 
> You are the light of the world. A city set on a hill cannot be hidden; nor does anyone light a lamp and put it under a basket, but on the lampstand, and it gives light to all who are in the house. Let your light shine before men in such a way that they may see your good works, and glorify your Father who is in heaven.
> 
> Do not think that I came to abolish the Law or the Prophets; I did not come to abolish but to fulfill. For truly I say to you, until heaven and earth pass away, not the smallest letter or stroke shall pass from the Law until all is accomplished. (Matt. 5:13--18)

Christian pastors are to heed and obey our Lord's order that we make disciples of "all nations," that we be "the salt of the earth," that we remain "salty," that we provide "the light of the world," and that we serve as His "city on a hill" which "cannot be hidden." We are not to hide our light under a basket, but to lift it up on a lampstand for all to see.

The Apostle Paul is simply reiterating these commands, emphasizing this responsibility of pastors and their congregations to serve as witnesses to our wicked world when he writes to Timothy that the Christian church is "the pillar and support of the truth" (1 Tim. 3:15).

When pastors censor themselves, justifying it by talk of "being gospel-centered" or pontificating on "two-kingdom theology," we betray our calling. When we are silent, refusing to expose and condemn the bloodlust and slaughter we are drowning in today, we betray our commission. Why would anyone repent of abortion who has not been confronted with God's terrible condemnations of child sacrifice?

Understanding why we are petrified to proclaim those condemnations is not difficult.

Given how intensely the state supports the bloodshed of our little ones, it's important to say that Christians' prophetic witness against abortion must begin with proclaiming the truth to the rich, powerful, and strong, particularly the civil magistrate. Yes, it is true that ministers are church---not civil---authorities. It is true some pastors suffer the temptation to focus on the political realm to the neglect of their calling to feed and guard their flock. Yet God's prophets must not use this first priority as an excuse for abandoning their prophetic calling. We are to call all men---including especially civil authorities---to repentance.

Pierre Viret, a minister in Calvin's company of pastors, put it this way:

> Just as ministers are not bound to do what pertains to rulers and magistrates, so on the other hand if they do not sound the word, and do not speak to the rulers and magistrates with all frankness according to their calling, they will be guilty of grave guilt. For they would then be included in the number of dumb dogs which Isaiah speaks of. For their office requires them to call the rulers and magistrates to do their duty according to the Law of God.[^226]

The historic church has always proclaimed God's law to civil magistrates. John Calvin addressed his *Institutes of the Christian Religion* to the civil magistrate. Luther was relentless in challenging the princes of Germany. A thousand years earlier, John Chrysostom enraged the empress with his rebukes of her luxurious lifestyle, and was exiled for his work. The early church apologists directed their works to the civil magistrates, calling them to repent and believe on Jesus Christ.

Here, church fathers are only following the biblical example. The Old Testament prophets rebuked kings to their faces, both Israelite and gentile kings. These same prophets proclaimed the coming salvation of the nations in the time of the New Covenant, foretelling that kings would be nursing maids to the church. Psalm 2 explicitly commands rulers to "kiss the Son," warning of the consequences if they refused.

Do we remember that John the Baptist lost his head for rebuking the civil ruler, Herod, for violating God's law? Jesus told His disciples they would stand before kings, and so they did, preaching to civil authorities, some of whom were converted. There was the proconsul Sergius Paulus (Acts 13) and Dionysius the Areopagite (Acts 17). The book of Acts concludes with Paul's journey to the capital of the Roman Empire, leaving the reader with the anticipation of his encounter with its leaders. Even Theophilus, the man addressed by Luke in both his gospel and the book of Acts*,* is thought by some to have been a civil magistrate.

It involves no admixture or denial of the discrete nature of the two kingdoms to command civil rulers in God's name to punish abortion as a fundamental violation of God's law. It's an old tactic here in the United States to maintain the canard of the separation of church and state in order to silence those prophesying against injustice and oppression. Both ecclesiastical and civil rulers are agreed that the church should shut up.

Here in the United States, this is nothing new. Note this lament by President Lincoln:

> You say that you think slavery is wrong, but you denounce all attempts to restrain it. Is there anything else that you think wrong, that you are not willing to deal with as a wrong? Why are you so careful, so tender of this one wrong and no other? You will not let us *do* a single thing as if it was wrong; there is no place where you will allow it to be even *called* wrong! We must not call it wrong . . . in politics because that is bringing morality into politics, and we must not call it wrong in the pulpit because that is bringing politics into religion . . . and there is no single place, according to you, where this wrong thing can be properly called wrong![^227]

Pastors are not to allow God's prophetic words to be gagged in the public square. Right there at the heart of our towns and cities, pastors are to preach against the evils of our day, condemning those evils as well as civil magistrates who live by them electorally. Of course pastors must not abandon their flock to become political hacks. And yes, this is a danger when the sheep feel impotent in the face of pagan culture warriors and desire that a champion be raised up representing their side. Many pastors choose to be their flock's hero rather than their shepherd. It is enticing, and shepherds must resist this temptation.

Still, pastors have a duty to serve as prophets to the civil rulers. They can only fulfill their duty to rule by the law of God if they heard that law proclaimed.

### The Civil Authority and the Power of the Keys

This responsibility is even more imperative when, as is so often the case here in North America, the civil ruler is a Christian who has vowed submission to his shepherds and sits with the people of God each week under the preaching of God's Word, then communing with them at the Table of our Lord. In such cases, pastors must preach and teach this ruler; but if he refuses to honor his shepherds calling him to submission to God's law, they must exercise the tools of discipline given them by God. Civil rulers who bow the knee to Molech and refuse admonitions and rebukes concerning their promotion of bloody sacrifices to demons must, in time, be barred from the Lord's Table. No one who is complicit and unrepentant in spilling the blood of the innocent should be allowed to continue to commune with God's people. He is not discerning the body and blood of our Lord.

### Walking alongside Our Sheep in the Death of the Unborn

Finally, pastors testify against abortion by being tender with those in their flock who have lost their little ones. Despite improvements in technology, the death of children in utero is still a regular sadness felt by many of our sheep. Yet, too often, God's people do not know how to grieve the loss of the unborn, because pastors, church officers, and the older women of the church have not been examples to them in these things, nor instructed them. In light of the massive numbers of abortions the past half century, as well as the dwindling love of fruitfulness within the church the past full century now, it's no surprise the church has grown insensitive to the grief of mothers, fathers, and children mourning the deaths of their unborn and stillborn babies.

Families should not be left to suffer this grief hidden and alone. Shepherds and their wives can lead the way in helping and comforting those who grieve the deaths of our lambs. Shepherds and their wives can lead the way, showing the flock the beauty and relief of mourning these little ones with the eyes of faith fixed on the resurrection of Jesus Christ. King David himself taught us how to do so, mourning the loss of his little one (2 Sam. 12:23).

A number of our modern practices surrounding death are unhelpful in this regard. Our forced cheerful and happy-clappy posture toward death today inside and outside the church is a betrayal of the Fall and its awful consequences which seek to drown us in grief and sadness. Mutual conspiracies to deny death's terrible weight are no good.

The church should be led back to our former heavy and truthful liturgies of death and mourning testifying to our hope in the resurrection of our Lord. These liturgies will be so helpful directing families in their grief (over the deaths of adults *or* babies), and this is particularly the case following the loss of their little child---when it does seem awkward to grieve someone so very tiny whom we have never seen.

This leadership of the pastor and church will be particularly helpful to mothers who have carried these little ones and known them intimately, sometimes for a full nine months; who with great expectation have been singing to them, praying for them, talking to them, and naming them. We provide a safe place for the mother and father's grief when we give a homily, pray, sing, and help bury their lambs at the end of funerals and committal services.

It is not absurd to have a funeral for a child. It is not foolishly sentimental to bury him. It is not wrong to love him before he has lived outside his mother's womb.

God's flock needs shepherds who will join the ewes in grieving over their little lost lambs. It will be difficult to know precisely when and how to provide such ministry in this or that circumstance and with this or that family. Immediately questions will come up concerning what age to begin, and whether or not to have any service if there is no body to bury. These questions will need pastoral sensitivity and the guidance of the Holy Spirit.

What is crucial, though, is that the church recover the uniquely Christian way of life and death. Pastors who lead that recovery will be blessed by the deepening love and trust of their sheep---particularly the mothers. But more, these pastors will have the supreme good of the approval of our Chief Shepherd.

## The Duty of Individuals

<div id="fninfo" data-fnstart="24"></div>

> For if God . . . did not spare the ancient world, but preserved Noah, a preacher of righteousness, with seven others, when He brought a flood upon the world of the ungodly . . . (2 Pet. 2:4, 5)

Have we followed Noah, preaching righteousness against the bloodguilt we live amidst? Or rather, have we participated ourselves in the wickedness by paying for a surgical abortion, encouraging or sympathizing with others who have paid for one, or using an abortifacient drug regimen or hormonal birth control?

God's hatred of the bloodshed of innocents is repeated many places in Scripture, but the shedding of the blood of one's own little ones is a particular horror. There is no more terrible pollution of the land:

> They even sacrificed their sons and their daughters to the demons, \
> And shed innocent blood, \
> The blood of their sons and their daughters, \
> Whom they sacrificed to the idols of Canaan; \
> And the land was polluted with the blood. \
> (Ps. 106:37--38)

At its core, abortion is an act of idolatry. Sacrificing one's own children must necessarily be the most intensely religious act. Sacrificing one's own child is the bloody confession of faith in demons. It is a denial of faith in the only true God who closes and opens the womb. It is a denial of faith in God's provision for His own and the blessings He sends them. It is a final irreversible declaration concerning one's own child that God is wrong in His creation.

But prior to this horror, what can be said about lust? Lust permeates the Christian church and home, the Christian computer and phone. Christian men and women tend their idols, consuming the naked flesh of strangers. God will judge us for this.

Many reading this paper have somberly nodded along up to this point, reassuring ourselves of our innocence. We haven't killed our own children. We've protected them. We haven't paid for an abortion. We haven't committed adultery. We haven't even used the Pill. But even in such cases, we lack knowledge of our own lust and the ways it contributes to the sin of abortion among the idolatrous objects of that lust.

We also lack understanding of our responsibility for our neighbors. We may object that we can't be held accountable for what wicked men and women do, but responding this way, we demonstrate our normal thought process is the denial we are our neighbor's keeper. Do we not feel the weight of the example Noah should be to us today in his preaching of righteousness to his own neighbors?

Abortion is the violation of the Sixth Commandment, "Thou shalt not kill." The Westminster Larger Catechism expounds on what this commandment requires of us positively:

> All careful studies, and lawful endeavors, to preserve the life of ourselves and others by resisting all thoughts and purposes, subduing all passions, and avoiding all occasions, temptations, and practices, which tend to the unjust taking away the life of any; . . . just defense thereof against violence . . . ; comforting and succoring the distressed, and protecting and defending the innocent.[^228]

God deals with men representationally and corporately. God judges nations for the sins prevalent among them. Even if there are people of God today who have not participated directly in the sin of abortion, we cannot claim clean hands and hearts. We live in a nation committed to the bloodshed of children, and God is just to judge our nation corporately, showering His holy wrath upon us all.

When the day comes when God's judgment falls upon the bloodshed of our nations, will there be men of God among us we have seen and heard stand and preach as righteous Noah preached righteousness to his own generation?

### Male Leadership in Fighting Abortion

In modern discussions of abortion, it is not uncommon to hear the claim that men should keep silent on the issue. Since men can't get pregnant, the argument goes, the issue doesn't pertain to them. Abortion is a deeply personal issue for women, and men have no right to tell women what to do with their bodies.

To the contrary, murder is everyone's business---particularly men. It is the nature of the male of the species to guard and protect life. Men are the first ones we expect to step up and protect a woman who is being beaten, a child who is being slapped around, a black man with a rogue law enforcement officer kneeling on his neck, a mentally handicapped person who is being mocked, or a homeless person being beaten up by a gang of punks. In the same way, it is men we expect to step up and protect little babies from being aborted. It is a glorious fulfillment of his nature for the male of the species to do so.

But what about when women oppose them doing so? What if even pro-life women try to shush men working to defend the babies, saying things like:

- No woman about to have an abortion is going to listen to any man's warnings.
- Men don't understand the difficulties women face during pregnancy. Let *us* do the talking.

One of us made a habit of picketing a Planned Parenthood abortuary in his city with his young daughters some years back, and one day an angry woman from the abortion side of things walked up to him and, having asked if he was married and where his wife was ("at home taking care of our other children"), she rebuked him: "You should go home and take care of the children yourself, and let your wife do the picketing!"

Initially, the man thought, "That's a good point. Why am I here, and not my wife?" But almost as quickly, the truth of God's creation order hit him and he responded to her, "Defending life is the man's job. My wife is home taking care of our other children, and that's what God has called her to do."

Readers likely are shuddering. Was this man trying to be as offensive as he possibly could be? Why on earth would he take such a volatile situation as an opportunity to start an argument with the woman over what men should do and what women should do? It was only going to infuriate the woman, and how does that help?

It's interesting, then, to record here that his response left the woman nonplussed. It didn't anger her more, but it seemed to take the edge off her anger. She was silent for some seconds, seemingly wondering what to say. Then she uttered something like "Oh" almost under her breath, and wandered back inside.

Who was it who raised this matter of what is man's and what is woman's work? It wasn't the pro-life man, but the pro-abortion woman. The man simply answered her question by calmly testifying to the biblical truth that God has called man to defend women and children.

In truth, such arguments are not peculiar to the work opposing abortion. They permeate life today in the home, church, and society. Men are told not to take leadership of anyone but themselves, and even in their leadership of themselves, men are warned to submit to the women of their lives so they will be kept from their naturally bad inclinations and desires. Never mind women's equally bad inclinations and desires---we're talking men here, and everyone knows they're a piece of work.

It may well be true that, given our track record, men today lack any moral authority. And certainly Christians should not ignore strategic concerns. But shall we turn from our distinctly male calling to defend the vulnerable and rescue the perishing? Remember righteous Job's description of his own godliness:

> I delivered the poor who cried for help, \
> And the orphan who had no helper. \
> The blessing of the one ready to perish came upon me, \
> And I made the widow's heart sing for joy. \
> I put on righteousness, and it clothed me; \
> My justice was like a robe and a turban. \
> I was eyes to the blind \
> And feet to the lame. \
> I was a father to the needy, \
> And I investigated the case which I did not know. \
> I broke the jaws of the wicked \
> And snatched the prey from his teeth. \
> (Job 29:12--17)

The duty of man is clear. God's fatherhood is written into human society. That fatherhood is present from the individual household up to the kingdom, from the newly married husband up to the king or president. God places men in authority and holds men accountable for themselves and for those they are in authority over. Just as God dealt with Adam and Eve, so He continues to deal with us today. Yes, being made equally in the image and likeness of God, women are moral agents alongside men, but as Adam was responsible for Eve and the race in his Fall, so God to this day still requires each man to answer for those under his care, starting with his wife and children. The husband and father is to guard and protect his wife and children. The first chapters of Genesis could not reveal and demonstrate this fundamental truth of God's creation order with greater clarity.

> Deliver those who are being taken away to death, \
> And those who are staggering to slaughter, Oh hold them back. \
> If you say, "See, we did not know this," \
> Does He not consider it who weighs the hearts? \
> And does He not know it who keeps your soul? \
> And will He not render to man according to his work? \
> (Prov. 24:12)

Consider the understanding of our fathers who fought, bled and died to win and defend life. They knew it was the man's job, though the cost was great. Will we honor those men, putting wreaths on their tombs while refusing to protect lives today?

Men must recognize the slaughter of the little ones is no "women's issue." It is a justice issue. It is a murder issue, and bloodguilt hangs in the balance.

Of course, we do not deny women can and should also be Christian witnesses standing against abortion. Yet Christian men have the greater duty. Christian men must lead the opposition to this great wickedness.

### Christian Witness at the Killing Places

One weakness of the church in our time is the tendency believers have to think godliness simply consists of keeping our own hands clean. Note our habit of focusing on the first half of the following command given by the Apostle Paul to the church in Ephesus, while neglecting the second half:

> Do not participate in the unfruitful deeds of darkness, but instead even expose them. (Eph. 5:11)

It is not enough to avoid the unfruitful deeds of darkness. We must also expose them, which is quite costly by comparison. Naming the sin of abortion "murder," "child sacrifice," "slaughter," "genocide," and a "holocaust" elicits hostile responses such as:

> *Don't you dare tell me what I can and can't do with my own body!*

> *Jesus said judge not lest you be judged. I thought you were a Christian!*

> *Keep your religion out of politics.*

> *Why don't you shut your mouth!*

It's possible to hide while keeping oneself from wickedness personally, but it's not possible to hide while exposing wickedness. Yet the God's command is not simply to have nothing to do with the unfruitful deeds of darkness, but rather to expose them.

So how do we do this? What are we to do as individuals living in this bloodthirsty land? How can we expose this shameful deed of abortion done in darkness? How do we awake the sleepers and help them arise from the dead (Eph. 5:14)? These are difficult questions, and the application will necessarily differ country by country, state by state, city by city, church by church, and person by person.

Some of us live in red states, some blue states. Some congregations have an abortuary in their city, some don't. Some churches have a strong ethnic or denominational commitment to fruitfulness which trains husbands and wives to accept however many children God blesses them with, while other churches made up of a more transient membership and lacking a strong ethnic element are largely middle-class families intent on limiting their fruitfulness. Their priority is not fruitfulness, but a superior education and the socioeconomic improvement of their family. Obviously, the first sort of family will need little exhortation to turn away from killing their children while the second will be sorely tempted so that witness against the bloodshed of infants will necessarily begin within the church herself.

Outside of the church, each locale has unique factors that inoculate the populace at large against abortion; or oppositely, promote it. Some of our cities and towns are within the former manufacturing centers with a heavy Roman Catholic presence, while other cities and towns live in the shadow of large research universities. Some of us work in the fields of medicine, education, and law, and we see thunderheads on the horizon. We easily anticipate special challenges coming toward us which will likely jeopardize our ability to work in our current job field. We know there are growing ethical conflicts that may soon become unavoidable. In fact, it is a simple and necessary observation that some fellow believers are set apart to bear heavy responsibility in the fight, while others are not.

Again, it is imperative that we make gentle and charitable assessments of brothers and sisters in Christ as we head into the future conflict over abortion, but also a host of other moral and ethical conflicts resulting from the wickedness of our cultural repudiation of Christendom and resultant reversion to paganism. We may have two physicians in our congregation, one working in trauma and emergency care and the other in obstetrics and gynecology, and one of them will soon be denied hospital privileges while the other will continue to work in that same hospital. One of our lawyers might practice family law and find herself brought up before the state bar association's legal ethics committee while another has a practice in probate law and is able to avoid most ethical conflicts.

Context is a much-abused word in mainstream evangelical culture, but context does matter----personal, familial, educational, provincial, spiritual, and otherwise. We do not forget that one of the most important personal contexts of all is our own particular weaknesses, temptations, and sins. For example, some men may not be fit to protest at an abortuary because they are hotheaded. Some men are guilty of sexual sins which open their public protest against abortion up to charges of hypocrisy from their wife, children, church, or the community at large. Some women who have suffered sexual abuse might be cautioned to stay away from the scene of our present holocaust, since it might be too harmful to them emotionally. Some women have had many abortions, and having come to faith in Christ and repented, they might be particularly effective in public protests, while other women who mourn their inability to have any children thus far might be tempted to sinful anger and bitterness.

Showing up at the killing fields and protesting remains a fundamental way of protecting those without a voice. Asking the counsel of their pastors and elders, Christians ought to consider whether they are called to this ministry. The weapons we have from God are powerful for tearing down strongholds so that when Christians show up at the killing fields, darkness is put on notice and sometimes individual children are saved from death.

Those who do become engaged in public ministry at these killing places need to be aware of the dangers. While we are promised the gates of hell will not prevail against the church, this does not mean the church and her people will not suffer the hatred and attack of pagans drowning in their bloodlust. Exposing the deeds of darkness is always a dangerous work.

Other dangers arise, not from others, but ourselves---dangers such as pharisaism, spiritual pride, bitterness, and parading our righteous deeds on social media. We must not become proud in our work of public witness. But for the grace of God, we would be the ones walking into the abortuary.

We particularly need to avoid giving ourselves over to disappointment. People will reject our plea, leaving us vulnerable to becoming jaded. We will want every member of our church to show up and protest with us, and when they don't, we will be tempted to condemn those who, in our judgment, have no good reason for their absence.

Whatever form of witness we choose, we must keep in mind that the abortion "clinic" is no longer the main place of killing. Today, that place is hidden. The evil deed is done in complete privacy. It is done silently there behind the bathroom door of our homes---and not just the homes of worldlings, but also our own homes and the homes of our brothers and sisters in Christ. Today, our child sacrifices are done in our own homes so that no one will know when we commit our murders. No one ever catches a glimpse of the lifeless bodies of little ones murdered by their mothers there at home.

Often these murders are hidden by the mother even from her own husband---the little one's father. We mention protesting outside pharmacies alongside protesting outside Planned Parenthood abortuaries because of the prevalence of over-the-counter drugs in killing our unborn children today. Increasingly, the main killing place is an individual woman's conscience and her bathroom. Exposing this darkness requires entirely different tactics than the tactics used for decades in protests outside surgical abortuaries.

As the battlefield shifts, we need to do the work of informing ourselves and others concerning the abortifacient agencies of what are falsely labeled "contraceptives." Not simply the obviously abortifacient mifepristone-and-misoprostol regimen, but stealth agents such as the Pill and Plan B. We need not present ourselves as one more internet expert. It's enough for us to know and communicate the basics to others, taking special care to counteract the lies of the media and medical professionals who assure women that their drugs are *absolutely not* abortifacients.

As we do this work, we should speak from humility, remembering Scripture's warning that "we all stumble in many ways" (James 3:2).

### Christian Witness on the Job

In opposing abortion in our individual callings, the tactics we use must be tuned to the present context. Increasingly, the movement of abortion from surgical and public to chemical and private will require a retooling of our methods. Some older methods of witness may still have some utility, but others will no longer be useful. Still, each calling has its own unique contributions to make.

We need pro-life state legislators, particularly as *Roe v. Wade* is overturned and the battle is returned to each state. We need physicians who will warn their patients against abortifacient drugs. We need pharmacists who will inform their customers. We need physicians, physician's assistants, nurses, and pharmacists who will decline any involvement in the bloody trade in poisons that kill the preborn child; who will declare to their ethics committee that, still at this late date, they retain medicine's historic commitment to the Hippocratic Oath:

> Neither will I administer a poison [*pharmakon*] to anybody when asked to do so, nor will I suggest such a course. Similarly, I will not give to a woman a pessary to cause abortion.

We need judges who use every tool at their disposal to end this genocide perpetrated against the little ones. We need writers to produce *Uncle Tom's Cabin* for the unborn. We need artists to depict the horror visually. We need musicians to compose songs[^229] and symphonies[^230] lamenting our lost little ones. We need drivers to transport needy mothers to their ultrasound. We need carpenters, drywallers, and painters to build homes for poor families.

We need soldiers in every last job and calling who will fight using the weapons of God:

> For though we walk in the flesh, we do not war according to the flesh, for the weapons of our warfare are not of the flesh, but divinely powerful for the destruction of fortresses. We are destroying speculations and every lofty thing raised up against the knowledge of God, and we are taking every thought captive to the obedience of Christ. (2 Cor. 10:3--5)

### Christian Witness in the Public Square

The Old Testament repeatedly records God's people giving themselves to bloodshed, particularly through child sacrifice. If 1 and 2 Corinthians teach us anything, it is the vulnerability of God's people to the temptation to ape the culture around them, making the sins of their pagan neighbors their own sins also.

What a betrayal of our Lord Jesus who resisted Satan's temptations to go along to get along. To "fit in." God commands us to be "blameless and innocent, children of God above repraoch in the midst of a crooked and perverse generation, among whom [we] shine as lights in the world" (Phil. 2:15). Our citizenship is not here on earth, but above in heaven. Fixing our eyes on our Lord and setting ourselves on pilgrimage to His heavenlies, we will no longer fear man, nor will we be ashamed of Him and His words. With respect to this gross and bloody horror of baby killing, we'll be intransigent in our opposition to the act itself, as well as to those covered in its blood. Fearing God, we will not fear man:

> Abortion and euthanasia are . . . crimes which no human law can claim to legitimize. There is no obligation in conscience to obey such laws; instead there is a grave and clear obligation to oppose them by conscientious objection. From the very beginnings of the Church, the apostolic preaching reminded Christians of their duty to obey legitimately constituted public authorities (cf. Rom. 13:1--7; 1 Pet. 2:13--14), but at the same time it firmly warned that "we must obey God rather than men" (Acts 5:29). In the Old Testament, precisely in regard to threats against life, we find a significant example of resistance to the unjust command of those in authority. After Pharaoh ordered the killing of all newborn males, the Hebrew midwives refused. "They did not do as the king of Egypt commanded them, but let the male children live" (Exod. 1:17). But the ultimate reason for their action should be noted: "the midwives feared God." It is precisely from obedience to God---to whom alone is due that fear which is acknowledgment of his absolute sovereignty---that the strength and the courage to resist unjust human laws are born. It is the strength and the courage of those prepared even to be imprisoned or put to the sword, in the certainty that this is what makes for "the endurance and faith of the saints" (Rev. 13:10).
> 
> In the case of an intrinsically unjust law, such as a law permitting abortion or euthanasia, it is therefore never licit to obey it, or to "take part in a propaganda campaign in favour of such a law, or vote for it."[^231]

Still, recognizing our subordinate earthly citizenship, we must call our elected officials to defend life by stopping any and all abortions. Further, we must vote accordingly. Further still, as citizens of a democratic republic, we have obligations past generations of Christians did not have, most notably the obligation to create and advance policies through our elected representatives. This is a tool ancient Israel did not possess, nor did God's people possess it under the reigns of Herod or Nero. With democracy comes individual responsibilities. The bloody condition of our Union came about not through hostile foreign takeovers, but hostile domestic betrayals of God's law and our Constitution by our elected officials. Harry Blackmun wrote the abominable ruling in *Roe v. Wade*, but it was two Republican presidents, Dwight Eisenhower and Richard Nixon, who promoted him to the Supreme Court of the United States, while Christians stood by, either unaware or in support.

Yet the awakening of the (especially Protestant) Christian conscience did bear political fruit. It was Republican president Ronald Reagan who initiated the "Mexico City" policy prohibiting taxpayer money from funding abortions overseas. And it was also Ronald Reagan who nominated Antonin Scalia to the Court, and subsequent Republican presidents' appointments which have resulted in SCOTUS being willing to impair or overturn *Roe*: Clarence Thomas (George H. W. Bush); Samuel Alito (George W. Bush); and Neil Gorsuch, Brett Kavanaugh, and Amy Coney Barrett (Donald Trump).[^232] Indeed, attacking *Roe* by reclaiming the courts is a strategy born over forty years ago,[^233] which only now has borne its most visible fruit---and it has largely been Christian electoral calculus that has made that strategy bear fruit. So votes do matter, and though politics must never be our final hope, the Christian who neglects his democratic responsibilities abdicates his authority delegated him by God.

For centuries, Scripture was the bedrock of Christendom's rule of law, such that there was broad agreement concerning that law's fundamentals, and those fundamentals transcended political sectarianism. The heart of those fundamentals was the law's duty to protect the vulnerable---those at the margins of society because of poverty, handicap, age, race, or lack of citizenship.

That time is gone. The Democratic party now holds as its most sacred principles its commitments to promote sodomy, to deny God's creation of male and female; and, worst of all, its bloodthirsty pursuit of the death of preborn children, even to the point of rabidly demanding this slaughter be subsidized by every last taxpayer.[^234] Back in 1973, a third of Democrats opposed abortion, but now, pro-life Democrats are extinct.

This is not to extol the Republican party. Republicans did not begin to oppose abortion until the 1980s, and still today, many who vote Republican deny the preborn have any right to life under our Constitution. Yet if hypocrisy is the tribute vice pays to virtue,[^235] we must honor this tribute the Republican party keeps paying to the law of God by producing party platforms which claim to be "pro-life."

How do Christians determine who gets their vote?

Read *World* magazine, emails from Friday Fax[^236] and National Right to Life, Personhood Alliance, Operation Save America, and/or Catholic Vote. Read the blog posts and listen to the podcasts of orthodox Protestant pastors and elders. Read news from a variety of sources, including mainstream media. (Reading mainstream media will keep us informed concerning our enemies' strategies, a highly effective form of espionage.) Vote in every election you're eligible for, and vote knowing which candidates are determined to end our present genocidal holocaust. Don't vote for a county dogcatcher if she's not pro-life.

Get rid of judges who traffic in the blood of infants. And if, like us, you have a hard time keeping up on the various candidates, find a brother or sister in Christ who has kept up, and circulate their recommendations within the body of Christ.

Once the election is over and our rulers have taken office, bear witness in behalf of the little ones at times set aside for the public to address their rulers. There are Christians in some cities who have worked to get their local government to pass sanctuary laws that abolish abortion in their city. State legislators, too, provide times for meeting with their constituents. Allow your children to write their state legislators, respectfully requesting that they outlaw abortion.

Indeed, much good work has been done recently at the state level. Legislators in states such as Texas, Mississippi, and (most notably) Oklahoma have done good work in bringing down *Roe* and striving to end legal abortion. If you're in a state that hasn't done so, push for this to happen in writing, through calls, and at the ballot box. And if you are in a state that's taken even small steps in this direction, thank your officials who have had a part; and keep encouraging them to press on. Remember the downfall of *Roe* represents only the beginning of the work.

Some of us will even run for office. Yet our purpose here is not to outline every way in which a Christian can meet his obligation as a citizen, but rather, to exhort Christians to do what is good and right for each of us in our own particular situation.

### What about the Babies of Pagans?

Some Christians speak and write, suggesting Christians chill out over the pagans aborting their own babies, and should just concern themselves with not killing their own children. But this is, in fact, what pagans have always done.

Brothers and sisters, let us not commit the sin of Cain. We *are* our brother's keeper.

True, we must not participate in the unfruitful works of darkness, but the godly alternative to this is not to withdraw from society, but to expose those deeds and to reprove those committing them. Do we really feel no compassion and recognize no obligation to rescue those little ones being murdered?

Like Job, we are to take responsibility for "widows and orphans in their distress" (James 1:27). The Apostle James places this injunction upon us, and it is not simply widows of the Christian community he is referring to. His day was similar to our own. Men and women were killing children without any slightest remorse. This was the context in which the church became known for saving the baby girls exposed on the hillsides---girls born to the very pagans who persecuted the Christians rescuing their little ones.

Why such concern among the early Christians? Didn't they realize their actions failed any cost-benefit analysis? Didn't they know demography was on their side because they were the ones allowing their children to be born and live? Didn't they know the future belonged to Christians?

Yes, but they also remembered their heavenly Father sends rain upon both the just and the unjust. The children of pagans are not simply objects of punishment, but fellow men made in the image of God. They are children of His hand (Acts 17:28), and therefore proper objects of Christian compassion.

We must never turn a blind eye to the slaughter of the preborn, especially those who belong to the pagans around us. They too bear the image and likeness of God. They are our neighbors, and we are commanded to love our neighbors as we love ourselves.

### Dedication to Life in the Face of Congenital Anomalies and Disabilities

Information from diagnostic testing for birth defects and genetic abnormalities is often a blessing. It helps fathers and mothers prepare spiritually and mentally to care for their child and allows nurses and doctors to spring into action upon the child's birth. Yet, because of the heartless ease with which life is disposed of today, it is the general expectation that hardship will be avoided at any cost so that positive tests often lead parents to kill their child. This tendency is particularly awful when we consider that the best diagnostic methods---maternal blood screens,[^237] fetal echocardiogram, ultrasound, chorionic villus sampling,[^238] and amniocentesis[^239]---often give false positives.[^240]

When a fetal anomaly is predicted, fathers and mothers face immense pressure to "terminate the pregnancy." The very fear of caring for a child with structural or genetic abnormalities may lead to the temptation to kill the child. Add the counsel of parents, friends, and doctors to that fear, and many parents become convinced killing their child is the only humane option. No one's reminding them how often the results of the screening tests are wrong.

Even if diagnoses could be made with 100 percent accuracy and a particular diagnosis is troublesome, is it not a fundamental of Christian faith that each child in the womb is God's creation? The presence of an extra or mutated chromosome, the lack of a limb or an eye, the deformity of an organ or blood cells---none of these eviscerate any son or daughter of the image and likeness of God.

The real question is whether or not we are willing to accept from God both prosperity and adversity (Eccles. 7:14). Whether we recognize it is God who sends us handicaps and deformities:

> Who has made man's mouth? Or who makes him mute or deaf, or seeing or blind? Is it not I, the [Lord]{.smallcaps}? (Exod. 4:11)

Any defect of any child does not in any slightest way negate the image of God in him, nor does it negate his absolute right to be defended against those determined to kill him. The difficulties of our lives do not justify murder, whether that murder is committed by ourselves or another.

## Two Challenges

<div id="fninfo" data-fnstart="37"></div>

As we draw to an end, two challenges before us need to be examined. In both cases, the difficulty of our task of calling God's people to repentance over abortion may lead us to throw up our hands with despair, turning aside from the work because we had not counted the cost or difficulty of that task beforehand. These two challenges then need to be clarified so we may be wise in carrying out our prophetic work.

### Challenge 1: Restoring Our Depleted Understanding of the Image of God in Man

Watching the selectivity of moderns choosing their objects of compassion, the Christian soon comes to the necessary conclusion that compassion now is based on feelings, and those feelings are awakened only by finding oneself identifying with a victim personally. The compassion of moderns is reserved for those who tug on their heartstrings, and wokeism is our parading those heartstrings.

This superficiality of modern compassion is the center of our inability to awaken the people of God to the horror of murdering our little ones by means of hormonal birth control. The two-day-old child is hard for anyone to feel empathy towards,[^241] so he awakens no one's compassion. What we're left with, then, is the objective fact of his bearing the image of God. This is his ironclad claim to life, but this doctrinal truth does not tug heartstrings.

Can it really be true that, concerning bloodshed, the church today has turned from truth to feelings?

Again, if 1 and 2 Corinthians teach us anything, it is that the church is never immune to the sins of the surrounding culture, and this is particularly true concerning the bloodshed of innocents. The Lutheran Church in the time of the Third Reich and the Evangelical Christians of Rwanda in the time of their genocide mark this truth with an exclamation point. So today, the selectivity of our compassion and concern for life has reached a level best described as lunacy.

Stop for a second and think about the laws protecting dolphins and the eggs of bald eagles. Think about the national outpourings of anguish over whether or not the newborn panda bear at this or that zoo will survive. Think about the regular headlines and pictures of cats trapped in trees, and firefighters' attempts to rescue them. Think about the compassion of social justice warriors opposing racism and human trafficking and the effect of climate change on unborn generations.

There is no end to the masses' riots of indignation and demands for government action on behalf of Mother Nature, almost every sort of animal, and endless oppressed people groups. Many never stop shouting down others over these things. The parading of one's moral superiority in such matters may well be the central theme of social media. The discovery of a new people group or species suffering some new, heretofore unrecognized, injustice is a vein of riches greater than any found during the Klondike Gold Rush.

But why do these waves of discovery of injustice and compassion toward a succession of victims never extend to the unborn? Even among Christians whose compassion does extend to the unborn killed surgically later in pregnancy, why does this compassion for *some* preborn not continue backwards to the little one trying to implant in her mother's womb shortly after conception? Surely she deserves some small benefit from our much-ballyhooed tenderness for the weak and oppressed?

Once we have the wisdom to question the eliciting of our compassion today, and its relevance to our battle against abortion, the answer becomes clear. Preborn children don't tug at our heartstrings because their existence is hidden in the secret places, seen only by the God who created them. The mother can't see or feel these little ones in her body. Often she kills them before she is able to establish that they exist.

She has unprotected sex, she's forty and wondering if she may give birth to a child with Down syndrome, so just to be safe, she takes an ECP. The mother is a junior in college and has a boyfriend she expects to marry, but they're living together and both are Christians, so they make provision for their flesh by getting on the Pill. The pastor's daughter gets drunk with the son of an elder at a party one night and they copulate. The next morning, though, filled with horror, the daughter runs to the Kroger pharmacy and asks the pharmacist for the morning-after pill. The deacon and his wife already have five children and have decided they can't afford a Christian education for those five if they have any more, so she pays her OB-GYN to insert an IUD.

In each of these cases, there's plausible deniability of any knowledge of pregnancy, so the act of hormonal birth control seems morally unremarkable. Note that word "seems." Add to this the small percentage of the abortifacient agency of hormonal methods of birth control, and it's no wonder the people of God feel no pangs of conscience when they use these methods. "Everything in life involves risk," they say.

However, move the timeline forward: the mother's period is late, she feels sick to her stomach and takes a pregnancy test and it's positive. See then how that mother reacts to a casual offer of a smoke or her girlfriends getting together for drinks or her family telling her to take a ride on the roller coaster at King's Island. This woman has turned into a whole different person called "mother," so no thank you, no thank you, and thank you very much---but no. Move the timeline forward a few weeks more after the baby has woken this mother up with shifting and kicking her womb, and try again the smoke, the drink, or the roller coaster. Oh my, there is nothing and no one more intense than a mother whose newborn has quickened. She is hardwired to die protecting her little one now.

What has changed?

The mother knows she has a baby now, and she has bonded with that baby physically and emotionally. In other words, her perceptions of the life God has created within her are acute, and they tug at every one of her heartstrings. This is her precious child!

But was the child precious before the pregnancy test? Before he moved and kicked? To put it another way, is the child's life and claim on his mother's protection a function of her personal perceptions of his value? Or is it the simple fact of God's creation of this little one in His own image?

Every Christian knows the truth. Man's value is not a function of his ability to elicit empathy or sympathy from others, but the prior fact of his creation by God who, at the moment of conception, placed within him His own image and likeness. Thus as we have said repeatedly, this little one's murder is prohibited by God because this little one is His image-bearer.

It's understandable that pagans who flip all God's distinctions upside down would feel no guilt over killing babies they have not yet bonded with physically or emotionally. It's even understandable that they would be able to descend to that level of hell where they feel no guilt over killing their own babies *after* quickening. Such women are dead in their trespasses and sins and need to be born again by the Holy Spirit, that they might be horrified at their sin and flee to Jesus' blood and righteousness.

But Christians? What do we say to women of God and their husbands who feel no guilt over practicing birth control that has an abortifacient agency in the first days of life?

Several passages come to mind:

> And do not be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what the will of God is, that which is good and acceptable and perfect. (Rom. 12:2)

> For He who said, "Do not commit adultery," also said, "Do not commit murder." Now if you do not commit adultery, but do commit murder, you have become a transgressor of the law. (James 2:11)

> Do not participate in the unfruitful deeds of darkness, but instead even expose them; for it is disgraceful even to speak of the things which are done by them in secret. But all things become visible when they are exposed by the light, for everything that becomes visible is light. For this reason it says,
> 
> "Awake, sleeper,
> And arise from the dead,
> And Christ will shine on you."
> (Eph. 5:11--14)

Note that command, "expose them." This is one of the major purposes of this document---to open up the sin of this violation of the Sixth Commandment, including opening up the sad truth that worldlings have no slightest qualms over the morality of killing living beings they can't see or feel who are incapable of eliciting any slightest empathy or sympathy from them.

Living in this culture of death, Christians need this great sin exposed to us also. We must have the degraded state of our empathy and compassion demonstrated to us. We must be reminded of the image of God in man---particularly that image in the little man or woman in our womb struggling to attach himself or herself there in order to receive his mother's protection and nurture.

Until the image of God in teeny-weeny babies is exposed once more by the light of the Word of God, there will be no repentance within the church over our ubiquitous and incessant killing of our God-given sons and daughters. We may not see any quick restoration of our ability to see and recognize and cherish His image, but this objective fact must lead us to repentance and set us free from our bloodshed.

This truth of the image of God in man from the moment of conception must be taught repeatedly, fervently, and with all authority. No other truth will do.

### Challenge 2: Maintaining the Unity of the Body of Christ

The second problem we face in leading the church to repent of abortion is schism. Among the people of God within His church, calls to repentance are always divisive. How much more so, then, when we are called to repent of the sacrifice of our unborn children to the idols of our hearts. Naturally, the response will often be hostility. Brothers and sisters in Christ will accuse this call to repentance of being divisive within the church.

It's always been true that some whose consciences are tender repent, while some with consciences that are seared or hardened refuse and attack those who preach to them. Our Lord spoke this tender lament:

> Jerusalem, Jerusalem, who kills the prophets and stones those who are sent to her! How often I wanted to gather your children together, the way a hen gathers her chicks under her wings, and you were unwilling. Behold, your house is being left to you desolate! (Matt. 23:37--38)

During His week of passion, our Lord prayed for His people that we would be one as He and His Father are One. He said our unity would show the world His Father had sent Him (John 17:21). Much is at stake with the unity of the body of Christ, but this unity is not a simple or straightforward thing.

Five centuries ago, the Protestant reformers sought to restore the gospel of regeneration in the power of the Holy Spirit to the Christian church. The response of Rome to the reformers who condemned the selling of indulgences was to threaten their lives, then excommunicate them. Rome's priests never stopped condemning the reformers for schism, and the reformers never stopped defending themselves against this charge.

Similarly, one century ago, J. Gresham Machen strongly condemned the denial of the gospel and many fundamental doctrines of Scripture by missionaries and church officers of his time. Calling for the restoration of biblical Christianity to the church and God's sheep, he wrote his classic *Christianity and Liberalism*, whose call for division is resident in that very title. His message was that the liberalism of the Presbyterian church at the time was a different religion than Christianity, and that the church must separate from liberals who called themselves Christians.

Much of the church's history in North America across the twentieth century is simply the outworking of Machen's clarion call for reform implemented in mission after mission, denomination after denomination, church after church, carried in waves across the continent in city, town, and village. In time, those dividing from liberals came to be known broadly as "Evangelicals," regardless of their denominational or doctrinal affiliation, and those liberals who refused to repent were cut off.

The reigning religious authorities of the time accused these reformers of schism, but were they truly schismatics? Who was responsible for the division of the church at the time of the Reformation? Rome, or reformers such as Martin Luther and John Calvin? Who caused schism in the battle over liberalism? The liberal pastors and seminary professors of the Presbyterian church, or J. Gresham Machen whom they condemned and defrocked?

In Galatians, the Apostle Paul did not hesitate to divide the church by his denouncements and anathemas against those within the church calling for the Gentiles to be circumcised. If we believe Paul did so under his apostolic authority and his words here are inspired by the Holy Spirit, we acknowledge the rightness of his divisive statements such as:

> I am amazed that you are so quickly deserting Him who called you by the grace of Christ, for a different gospel; which is really not another; only there are some who are disturbing you and want to distort the gospel of Christ. But even if we, or an angel from heaven, should preach to you a gospel contrary to what we have preached to you, he is to be accursed! As we have said before, so I say again now, if any man is preaching to you a gospel contrary to what you received, he is to be accursed! (Gal. 1:6--9)

Strong words, those, and they are fully justified by what is at stake, which was the preaching of a different gospel which was no gospel at all. If the people of God in the church of Galatia allowed themselves to be circumcised, they were turning aside and following preachers the Apostle Paul said were to be damned.

There are many other places in Scripture where God's servants called for division from false preachers and prophets, and they did so not because they were seeking to please their listeners and readers, but because they loved the unity of the bride of Christ and knew the false teachers' assaults on the purity of the doctrine of salvation was destroying that unity. John the Baptist, Jesus, the Apostle Paul, Luther, Calvin, Bucer, Knox, and Machen are all alike in this.

We must grow in our discernment concerning the nature of the church's unity, so that we can distinguish between reformers and schismatics. After all, every schismatic claims to be a reformer. The Judaizers of the New Testament church preached another gospel as restorationists, as prophets, as the only men truly concerned for the unity of the body of Christ. They said they had to preach circumcision in order to restore unity in God's truth among God's people.

There are no false prophets, false apostles, false preachers, or false shepherds dividing the church with false doctrine who neglect to claim they are the true healers of Christ's body, restoring the unity of ages past through what in truth is their schism.

First then, the unity of the church is protected by distinguishing between true shepherds and false shepherds, the true church and the false church. Any work of reform must be recognized as an effort, not at division of the true church, but the reform of this church. The church reformed must always continue pursuing that reformation.

Those who condemn the exposure of false ethics and doctrine because of the divisive nature of that exposure must keep in mind John Calvin's warning:

> "Peace" is certainly a pleasing word; but cursed is the peace that is obtained at so great a cost that there is lost to us the doctrine of Christ, by which alone we grow together into a godly and holy unity.[^242]

There is a godly unity, but also an ungodly unity. What ought we to call that unity that defends the practice of hormonal birth control by denying the image of God in the unborn present from the moment of conception? What ought we to call that unity that condemns those who call for repentance in this matter, claiming they are schismatic?

This brings us to another consideration, though, which must be thought through carefully.

The Apostle Paul condemned those false preachers who called for the Gentile believers to be circumcised, and he sought to expel them from the body of Christ, but at the same time he also condemned the division in the body of Christ over meat sacrificed to idols. This second division over meat was a matter of "weaker" and "stronger brothers," and while making it clear that one group was "stronger," he nevertheless commanded both sides to "accept one another." It was not that there was no truth in the matter, but that this doctrinal disagreement was not to divide the people of God.

There have been innumerable divisions in the history of the church of a similar nature, where one group is properly called "strong" and the other "weak." Is the division between those who do and those who do not use hormonal birth control of such a nature that it is right to label those who condemn these early methods of birth control "weaker brothers" and those who use them "stronger brothers"? Maybe it's unfair to word it that way? Maybe it should be left up to the individual church or family whether to label those who repent of hormonal birth control "weaker" or "stronger"?

As we come to the end of this document, it is obvious those who have adopted this call to the church to repent of abortion do not believe abortion is properly spoken of as a secondary or tertiary matter in which Christians should agree to disagree. Abortion is a matter of life and death, and not the life and death of dolphins or cats or the murderer on death row, but the life and death of our own precious sons and daughters made in the image and likeness of God.

In this connection, keep in mind God's command to the sons of Israel not to "play the harlot" with those sacrificing their children to Molech by disregarding this heinous crime committed by their neighbors. Keep in mind His warning that the penalty of this disregard will be His cutting them off from the people of God:

> If the people of the land, however, should ever disregard that man when he gives any of his offspring to Molech, so as not to put him to death, then I Myself will set My face against that man and against his family, and I will cut off from among their people both him and all those who play the harlot after him, by playing the harlot after Molech. (Lev. 20:4--5)

But what if, as in Solomon's time, the people of God have become inured to the horror and wickedness of child sacrifice? Is this not the case today, and does this necessitate the same sort of radical act Ezra commanded when he demanded the Jewish husbands cast out their idolatrous pagan wives?

In other words, should the church divide over abortion? Should the church divide over surgical abortion? Should the church divide over late-first-trimester abortion by mifepristone and misoprostol? Should the church divide over early-first-trimester abortion through IUDs and other hormonal methods of birth control?

Is there a simple answer to this question? Those who have adopted this paper do not speak with apostolic authority. We are not familiar with every cultural context of those who will read it, and we do not know the condition and vulnerabilities of each church that readers are members of. In one sense, we believe the division of denominations and churches over abortion is necessary, yet the challenge is in the details, so we make no overarching claim about how and when that division should be accomplished.

There are many questions related to this division that require great wisdom in pastoral application. Is there a member of the church who is paid for performing abortions? Is there someone in the congregation who works for United Way or Planned Parenthood? Is there a representative serving in state government who has voted in favor of lifting restrictions on hormonal birth control methods, approving their distribution on the internet and over-the-counter in pharmacies? Is there an engaged couple who tell the pastor during their premarital counseling that they plan to use a hormonal method of birth control for the first couple of years so they can save up a down payment on a house? So they can minister in a Muslim part of the world without worrying about having a child? Is there an ER physician or physician's assistant who is required to care for rape victims by providing them an ECP? Is there a public school teacher who is responsible to teach a sex education module which presents drugs with an abortifacient agency as "contraceptives" which "do not cause an abortion"?

The list of such challenges to any simple call for church division over abortion could be multiplied, going on for pages. The meaning of the Sixth Commandment is clearly opened and explained in many doctrinal statements of the church adopted over many centuries since the Reformation, one helpful example being the Westminster Larger Catechism cited above. Even the penalty for breaking the Sixth Commandment and the divine rationale for that penalty is recorded in Scripture concisely and precisely. We have worked hard to make it clear how abortion in all its forms is a violation of this Sixth Commandment, and that Scripture, church history, and genetics speak in unison concerning this violation.

Still, the pastoral instruction, preaching, and application of these truths to God's flock and sheep never may disregard our necessary commitment to uphold the purity of God's truth while also seeking the peace of Christ's church. Sometimes division is the necessary tool of restoring the church's peace. Sometimes not. Making this determination is not something pastors, deacons, elders (and the older women of the church who teach the younger women under the authority of those officers) may avoid. We must not shirk this responsibility. We must have faith and make pastoral decisions in light of the coming judgment of our Chief Shepherd. Jesus calls each of us to lead in such a way that we can join the Apostle Paul in stating to our sheep that we have none of their blood on our hands (Acts 20:26).

It is undeniable that even the most biblical of churches today living in the midst of this growing holocaust are unfaithful in condemning all the forms of abortion practiced in our congregations. This must end, and it must end now! Pastors must preach and teach against abortion in all its forms, doing so with love and patience, but also authority and boldness.

On the other hand, each of us will have our own way and timing of turning the ship of the church towards this repentance, but difference in timing and method must not lead us to condemn those also committed to calling for repentance from this bloodshed.

We may put it this way: the pursuit of the church's repentance over abortion is an act of love for God and our neighbor, and that love should be obvious, even and especially when it divides those who claim the name of Christ. This is not an impossible goal. Let us give ourselves to it.

## The End of Abortion: Reclaiming God's Blessing of Fruitfulness

<div id="fninfo" data-fnstart="39"></div>

And so, many thousands of words later, we bring this jeremiad against the slaughter of children to a conclusion. What will be the end of abortion? God alone will most certainly bring about the end of abortion, but when and how will He do so?

We believe in the power of God to end oppression and bloodshed. Those of us alive at the time of the fall of the Soviet Union remember well how astounding this great change was to the entire world. Many heroic men had been laboring to this end, but no one anywhere predicted what happened, and the shock was heard around the world. Christians rejoiced in this wonderful act of God, even though, in retrospect, the crumbling of the foundations was clarified so that natural causes seemed sufficient for the explanation. But natural causes are never the whole, and not even most, of the story in the eternal conflict between good and evil, life and death.

Having surveyed this monstrous genocidal holocaust, we wonder what work we can do to hasten its demise. Preaching, prayer, and our own repentance are the first things we give ourselves to. There's no question that, here as always, we wrestle not with "flesh and blood, but against the rulers, against the powers, against the world forces of this darkness, against the spiritual forces of wickedness in the heavenly places" (Eph. 6:12).

The Evil One never ceases in his attack upon little ones. Hating and seeking to destroy life, he inspired Pharaoh to slaughter the Hebrew baby boys. He led generations of the people of God in both kingdoms of Israel and Judah to sacrifice their little ones to Molech. He led Herod to murder all the sons of Bethlehem born within two years of our Lord. Then, finally, we have this prophecy given through the Apostle John, recorded in Revelation 12:

> A great sign appeared in heaven: a woman clothed with the sun, and the moon under her feet, and on her head a crown of twelve stars; and she was with child; and she cried out, being in labor and in pain to give birth.
> 
> Then another sign appeared in heaven: and behold, a great red dragon having seven heads and ten horns, and on his heads were seven diadems. And his tail swept away a third of the stars of heaven and threw them to the earth. And the dragon stood before the woman who was about to give birth, so that when she gave birth he might devour her child.
> 
> And she gave birth to a son, a male child, who is to rule all the nations with a rod of iron; and her child was caught up to God and to His throne. Then the woman fled into the wilderness where she had a place prepared by God, so that there she would be nourished for one thousand two hundred and sixty days.
> 
> And there was war in heaven, Michael and his angels waging war with the dragon. The dragon and his angels waged war, and they were not strong enough, and there was no longer a place found for them in heaven. And the great dragon was thrown down, the serpent of old who is called the devil and Satan, who deceives the whole world; he was thrown down to the earth, and his angels were thrown down with him. Then I heard a loud voice in heaven, saying,
> 
> "Now the salvation, and the power, and the kingdom of our God and the authority of His Christ have come, for the accuser of our brethren has been thrown down, he who accuses them before our God day and night. And they overcame him because of the blood of the Lamb and because of the word of their testimony, and they did not love their life even when faced with death. For this reason, rejoice, O heavens and you who dwell in them. Woe to the earth and the sea, because the devil has come down to you, having great wrath, knowing that he has only a short time."
> 
> And when the dragon saw that he was thrown down to the earth, he persecuted the woman who gave birth to the male child. But the two wings of the great eagle were given to the woman, so that she could fly into the wilderness to her place, where she was nourished for a time and times and half a time, from the presence of the serpent. And the serpent poured water like a river out of his mouth after the woman, so that he might cause her to be swept away with the flood. But the earth helped the woman, and the earth opened its mouth and drank up the river which the dragon poured out of his mouth. So the dragon was enraged with the woman, and went off to make war with the rest of her children, who keep the commandments of God and hold to the testimony of Jesus.

What a terrible account of the Evil One's attempt to destroy our Savior and His mother, but what a wonderful account of God's justice and mercy, throwing him down and protecting our Lord, as well as His mother in the moment of her womanly vulnerability and labor as life-giver!

Satan is forevermore standing before woman in childbirth, seeking to devour the precious life of her child. Yet God is seated on His throne, building His kingdom generation after generation to the very end, with victory sure and certain. We must note the glorious theme of the miraculous births of little ones predestined to be the servants and saviors of His plan of salvation.

Think of the promise He made to Abraham and Sarah fulfilled in the miraculous conception and birth of Isaac. Think of His miraculous protection of the infant Moses. Think of His promise to Zacharias and Elizabeth fulfilled in the miraculous conception and birth of John the Baptist. Remember the response of the blessed Virgin Mary when she was told she would give birth to the Savior of her people. In innocence, she responded, "How can this be, since I am a virgin?"

> The angel answered and said to her, "The Holy Spirit will come upon you, and the power of the Most High will overshadow you; and for that reason the holy Child shall be called the Son of God." (Luke 1:34--35)

Mothers giving birth to saviors promised and protected by God is a central theme of salvation history. This history never denigrates or dismisses women's work and contribution to that history. Surely it is in large part these accounts of God's work in and through women's life-givingnesss that have borne the fruit of the equality of women and men which, among the world's religions and ideologies, is uniquely Christian.

Then also, we remember our Lord's promise concerning these little ones, whose mothers look on and listen with joy. Note the men. Note the children. Meditate on the response of the women present:

> Then some children were brought to Him so that He might lay His hands on them and pray; and the disciples rebuked them. But Jesus said, "Let the children alone, and do not hinder them from coming to Me; for the kingdom of heaven belongs to such as these." After laying His hands on them, He departed from there. (Matt. 19:13--15)

This document can be understood as our work seeking to restore the beauty of womanhood and childbirth to the church, because without that restoration, no negative attempt to expose and oppose the bloodshed of babies will get any purchase among us, let alone the pagans.

Necessarily so, much of this statement has been negatively focused. We have spent much time showing God's no---His condemnation of abortion, His judgments upon bloodshed, and our own sin that has brought it about. We have labored to show the need to speak truly about this evil, from our courts, our pulpits, and now from our own lips as men and women claiming Christ's name. We have shown why "pro-life" must never be defined so as to exclude or hide "anti-abortion."

But we have also shown that God's commandments are always reciprocal. Where God says yes to something, He also says no to its opposite. When God forbids something, He encourages its opposite. And so must we. The opposite of abortion is childbearing. It is painful, but it is life-giving. The opposite of death is life, and as God creates life, so we must love life. But not simply generic "life," but this and that newborn child and this and that preborn child, back to the moment of his or her conception. And as we shall see below, even before his conception.

God has made His world fruitful. Fruitfulness is creation's DNA.

We see the early spring bulbs. We gaze on snowdrops bursting through the snow in their glee for spring. We see the roses full of color, changing in shade with the temperature, so full of petals they can't hold themselves up. We see the apple and peach trees so laden with fruit that they can't bring it all to harvest. And then there are the animals that fill our world. The cardinals outside our windows, diligently pecking through the snow to find their food. The coyotes we hear at night, glorifying God by the howls they share one with another. And the tenderness and delicacy of newborn kittens, full of unchecked curiosity and jaunty in their play.

Today, it's commonplace to talk of how best to conserve this life. We understand that proper conservation involves not just stopping threats to creation, but also working positively to undo the damage done. We know that if the wolves on Isle Royale are lost because of man's mismanagement, repairing the problem may involve reestablishing them. That if the fish are depleted in our waters because our effluent is full of hormones from the Pill, we must not only purify the waters but also replenish the fish. And that repairing land whose soil is eroded because of clear-cutting involves not just stopping the harvesting, but reforesting it. Caring for creation means not just stopping its destruction, but promoting its prosperity---its fruitfulness.

The same is true concerning abortion. Ending abortion means not just hating abortion but loving the life God gives us as His blessing. We have shown how the civil magistrate must have a commitment to this, in fostering and protecting the lives of those he rules. We have seen how pastors and elders and churchmen as a whole must pursue this, in both disciplining the sins of those under their care and also encouraging them towards obedience in caring for children, born and preborn. And so, we conclude by exhorting each of us to rekindle our commitment to gratitude toward God for every one of His blessings.

Consider the wonder and privilege He has bestowed on woman to bring into this world children made in His own image and likeness. Let our love for woman as God made her fire our hatred of snuffing out those lives He blesses her with---and also those of us privileged to be her husband and lover through all the days, months, and years of her self-sacrifice as the mother of all the living. We are to be romanced and inspired by the fruitfulness God placed at the heart of all His creation, glorying particularly in woman's gift of this fruitfulness to us all.

Being moralists, it is tempting to think negatively. Strangely, as hard as it is for many of us to speak God's no publicly, we sometimes have no difficulty allowing it to be the extent of how we define our faithfulness, and this is particularly so concerning abortion. After all, we reassure ourselves that we have been firm where it counts. We've stood outside of the abortuary and condemned the ghoulish "escorts" leading women into the killing chamber to kill her child. We linger on Facebook, ready and waiting to thunder against the wickedness of child murder. We relish every opportunity to prove our intellectual acumen and godliness by dispatching all the craven arguments of postmodern pagans in support of the slaughter of the innocents. We have rebuked our congressmen, calling down God's wrath on him for his hatred of life. We declare that we won't vote for him. Pompously, we denounce our governor publicly, informing him that he has no claim to authority because he hasn't shut down Planned Parenthood's "clinics."[^243]

And yet, does our defense of the babies extend to embracing them?

Yes, this is the canard every escort shouts at us: "If you love babies so much, why don't you try *having* one!" they yell derisively at godly men walking the sidewalk with signs that say "Love life!"

Sure, they're hardhearted and scornful, but their mocking presents us an opportunity for self-examination. Do we love children, or do we simply love our own moral superiority? This is the question every preacher knows too well. Sure, I warn the people of God against sin and am faithful to preach against abortion, but do I love my neighbor? Do I love life?

> If I speak with the tongues of men and of angels, but do not have love, I have become a noisy gong or a clanging cymbal. If I have the gift of prophecy . . . but do not have love, I am nothing. (1 Cor. 13:1--2)

The last fifty years of Evangelicalism have been so soft, so cloyingly sentimental, so opposed to any proclamation of God's judgment, that our repentance from these things has not been easy to do ourselves, nor to call others to. Proclaiming God's no as well as His yes, we are tempted to reassure ourselves that we practice and preach repentance, and thus are superior to those who do not. Opposing abortion is so seductive to the growth of spiritual pride, but love casts out pride. Love leads us to give ourselves to vulnerability and self-sacrifice.

Are we willing to become childlike? Remember Jesus' words: "Truly I say to you, whoever does not receive the kingdom of God like a child will not enter it at all" (Mark 10:15).

Protecting life without loving life is absurd. Protecting children without loving and coming to resemble them in childlike faith falls short of the kingdom of God. The godly love life and children.

"Well, of course," we say, "a more obvious truth has never been written."

Then, if it's so easy, why did the people of God in Israel and Judah sacrifice their sons and daughters? Why do we ourselves sacrifice our own sons and daughters?

The reason Scripture commands Christians to love is that it is very difficult. Were it easy, the commands would not be so constant across the New Testament. Let us recognize that the core of child murder is a desire not to be inconvenienced by the burdens of another. Lovelessness is the seedbed of child sacrifice, although this lovelessness is strengthened by our resolve not to allow ourselves to become the subject of God's sovereignty in creating life within us and within our wife. Lovelessness combined with rebellion against God's sovereignty and a refusal to thank God for His creation and gift of life are a toxic triad that corrupts many of our marriages and families. We have even passed these sins on to the next generations.

Our precious children see and hear how often we think and speak of them as an inconvenience to us. Maybe it's when our daughter comes in while we're writing about the evil of abortion and the precious gift of life, and she asks us to look at her drawing. Maybe it's when our son interrupts our train of thought, wanting to tell us (in never-ending detail) about the snowman he just made outside. Maybe it's when we can't take that vacation to Europe we'd like because the airfare for seven is as ridiculous as having seven children in the first place in our modern dissipated world. How would we manage traveling across countries devoid of children with our own brood needing potty breaks and diaper stops every hour?[^244]

Or think of how knowledgeable your children are of your irritation at God for His blessings of little ones. You wanted to finish that degree, but couldn't because you had to provide for that new mother and baby---and you have made no effort to hide or put to death your continuing bitterness and the lethargy in your fatherhood and leadership. You resent the fact that you couldn't take that high-paying job because it would have left you no time for your children, and your children live with the awareness that they are a perpetual pain to you. Your five-year plan was perfectly on track, but then your fifth or sixth child was born with special needs and you take no joy in him.

Is it any wonder that our wives hanker after jobs and more spending money and the positive affirmation they receive working outside the home where their bosses and coworkers never stop telling them how great a gadget inventor and gadget maker and gadget marketer and gadget seller and gadget improver and gadget-maker human resources manager they are? Is there any better way to kill our wife's femininity, motherly instinct, and life-givingness than daily displaying our bitterness at the burden of the children she has presented us? Woman is made by God to be the glory of man. Why join the world in trashing her glory?

Our negative reactions and bitterness at the outpouring of life God sends us as His blessing are obvious to all, and our wives are acutely and painfully sensitive to it. By the will of our Father, even men and women as evil as we are have been given the gift of new life, both spiritually and physically. He has allowed us to share our lives with those born from our own bodies, sharing our own genes, and often sharing our interests and hobbies also. He has privileged us to take part in the propagation of the human race and the calling of men into His kingdom---two of the profoundest mysteries of existence. Yet we are ungrateful. Often we loathe our tiresome duties toward our children. We even commit murder in our hearts as we wickedly wish that God had never given us these blessings.

Truthfully, how different are we from worldlings who kill their children? By God's grace, His Spirit keeps us from going *that* far, although often we think the same thoughts, have the same motivations, display the same ingratitude. Brothers and sisters, as sons and daughters of our heavenly Father, this must not be. It is these sins of our hearts we must recognize, bring captive to the power of the Holy Spirit, repent of, and destroy. At the core of ending abortion is not just *opposing* those who would kill children, but *becoming* those who welcome and love them---which begins by loving our wife as *mother*, as *life-giver*, as *Eve*.

Loving children and motherhood includes loving the children we haven't yet been given. On the surface, this statement may sound like nonsense. How can we love a child we haven't been blessed with? How can we have affection for someone whose face we haven't seen, whose personality is yet unknown, whose habits and quirks and even sins are (as Melville put it) a lipless, unfeatured blank to us?[^245] How can we love children God has not blessed us with yet; children He has not yet created?

The question itself reveals part of the problem: we think highly of our thoughts, and lowly of God's. We live in an age that prizes empiricism and scientific discovery, and we are self-assured in our understanding of what life is and how it begins. Ultrasounds and DNA research *have* been instrumental in reinforcing the truth that life begins at conception, but pro-lifers celebrating and using these tools to defend little ones must not fall into thinking we have unveiled the mysteries of life's beginnings.

We can love our wife's womanly fecundity and her future children even while God has not yet granted her any child. Is this not the meaning of Otis Redding singing, "When a man loves a woman"? Woman is life. Woman is fruitfulness. Woman is fecundity and this cannot be separated from her being. The love of a man for his woman is not simply love of her personhood, but love of her womanhood which will ache with longing until it is satisfied by God's gift of a child.

In God's economy, our unborn children who are the coming fruit of our lovemaking *do* exist. The same Psalmist who tells us we're formed *in* our mother's womb goes on to speak of things even more mysterious:

> My frame was not hidden from You, \
> When I was made in secret, \
> And skillfully wrought in the depths of the earth; \
> Your eyes have seen my unformed substance; \
> And in Your book were all written \
> The days that were ordained for me, \
> When as yet there was not one of them. \
> (Ps. 139:15--16)

There are, indeed, more things in heaven and earth than are dreamt of in our philosophy. When we begin to preen ourselves on our understanding of biology, we must remember Scripture records that Levi gave the tithe to Melchizedek while he was still in the loins of Abraham:

> And, so to speak, through Abraham even Levi, who received tithes, paid tithes, for he was still in the loins of his father when Melchizedek met him. (Heb. 7:9)

And the Apostle Paul tells us a perhaps even greater mystery: God the Father "chose us in [Christ] before the foundation of the world" (Eph. 1:4)!

Remember that several of our church fathers speak of killing a child before he exists[^246]---and they were not ignorant of the law of non-contradiction. Still today, it is a great mystery when and how soul and body are joined together by God. Deep truths are open, and infinity is finite, to God.[^247] It is no absurdity to talk of cherishing our wife's fecundity, her life-givingness and the coming little ones we hope and pray for, while we have not yet heard or seen them. This is the center of man loving woman.

Pornography's eroticism is woman's life-giving body parts put on display for men who hate life, who hate fruitfulness. The world is full of men incapable of loving woman as woman. Refusing the responsibility and celebration at the heart of true manhood, these men remain dead in their trespasses and sins, giving themselves over to their infantile desires and lusts, and dying with little or no seed. Their particular taste in erotic images might differ from the sodomites, but the essence of sodomy is sex denuded of fertility; it is sex robbed of life-givingness. One may use one's wife for such lust, or one may use another man, but the essence of the thing is identical. What's love got to do with it? What's woman got to do with it? What's life got to do with it?

So now, again: Do we love life? Do we love that life not yet placed in the wombs of our wives? In faith we may do so. By faith we love what He has promised to give us according to His will. We not only hate the murder of children, but we also agree with the Psalmist that they are a heritage from the Lord. That the fruit of the womb is His reward, and that God is pleased to give good things to His children.

And so, for our part, we commit ourselves to loving children past, present, and future, trusting God with the fruitfulness of our marriage beds. We choose faith for the lives God gives us as His blessings, welcoming not just some of the lives He sends in a timely way, but also those He sends in what we might think an untimely way.

And when we choose to offer our fruitfulness to God as Christians before the twentieth century did, we do so fully aware of how many of our fellow believers will mock us; or worse, will accuse us of being Quiverfullists who are ignorant, presumptuous, foolish, patriarchal, and irresponsible. They will tell one another that our motivation is pride.

Brothers in Christ may characterize us as legalists who think God requires us to have as many children as possible. They will never understand the truth that we have simply become committed to loving life, and that this love has led us to openness to God blessing our lovemaking as He chooses, by faith receiving with joy all the fruit He may bestow on it. No, nothing so joyful will cloud the judgments of the loveless and coldhearted Christian who speaks of childbearing (and even abortion) as merely a question of stewardship.[^248] Fellow Christians will say we are in bondage to some law of multiplication of the species that will grow our tribe and take us to a higher level of heaven, and we're sure we'll have more crowns there. They'll claim we believe God requires us to have as many children as possible.

Truth is, though, that we believe the Lord opens and closes the womb. This is our joy, our faith, and we love trusting God with all His blessings. When the advocates of abortion scream "My body, my choice," we smile, noting that unless we recognize our bodies as His, our choices are nothing but slavery. The freedom to abort is nothing but bondage to the devil. It is only when we *choose* to abandon our claims to autonomy that we have freedom to be the fathers and mothers God has made us to be. Those the Son makes free are free indeed (John 8:36).

Of course our love of life runs utterly against the grain of our culture---particularly the culture of Evangelicalism. And it's not that we can't come up with a host of reasons why we should avoid fruitfulness: Until both husband and wife get their degrees, a child would be inconvenient. Our house is too small for another child. More than one child per bedroom is irresponsible. Our wife frets over the future, and we would not be a servant-leader if we neglected her fears. Our husband's single income isn't sufficient to feed another mouth. We need to get a job. Our parents already think we're irresponsible, and another child would just confirm their judgment.

In fact, we're just as good at coming up with reasons to shut down our fruitfulness as all our friends who stopped at two. (And yes, we know some couples have valid reasons for stopping there.) Nevertheless, for the vast majority of us, our problem is not an excess of prudence, but a deficit of faith and the love that flows from it. Sure, everyone around us thinks three or four children is the outer limit of sanity. How can parents of five provide music lessons? How can they have their kids in sports? How will they be able to send their children to college, let alone graduate school? How will they pay for each of their daughters' weddings?

Some of these expenses are unlike the others, but the point is clear. These judgments of what fathers and mothers need to give their children are not a function of what pleases God and will lead to our children's godliness, but what our peers see as the minimal obligations parents have to their sons and daughters. Here as everywhere, "The Christian ideal has not been tried and found wanting. It has been found difficult; and left untried."[^249]

The doubts and fears of fathers and mothers are nothing new. Every generation of Christians faces them. In fact, a good case can be made that the doubts and fears of past generations were far more substantive than our own. In a world where food was self-produced, they had to be concerned whether there would be enough food to go around come winter and spring. Whether God would provide summer rains this year after last year's drought. Whether locusts would swarm in and destroy their crops.

In a world without Walmart, Goodwill, and eBay---a world where clothing was ten times the relative cost of clothing today---they didn't know if they could afford to clothe their children. Technological and economic development have put so many of these fears to rest, today, yet we manufacture new ones like whether or not we can afford a piano or guitar for our musically gifted children, a kit for our budding soccer player, private school tuition, or college tuition for all of them.

To those of little faith, the Christian family's resources are always a fixed pie, with each new child depleting the share of those who came before. Whereas anyone who has grown up in a large family, or any father and mother blessed by God with one, knows this is a lie. To those of little faith, every last act of faith is way too costly and must be carefully weighed by those who understand that judiciousness is next to godliness.

What if we trusted God? What if we truly believed the promise of Romans 8:28, that God is ultimately causing all things to work together for good to those who love God---including antibiotics, vaccines, farming techniques that massively increase yield, NICU advancements, and on and on. God's providence has made it much easier to fulfill the command to be fruitful and multiply, and yet we balk. Does God still rule His world? He has orchestrated many, many technological mercies in this world so that the church might grow with godly seed to the praise of His glory. With all the benefits and blessings He's given us in the modern world, can we not still rest upon the same promises our fathers and mothers in the faith did?

> For this reason I say to you, do not be worried about your life, as to what you will eat or what you will drink; nor for your body, as to what you will put on. Is not life more than food, and the body more than clothing? Look at the birds of the air, that they do not sow, nor reap nor gather into barns, and yet your heavenly Father feeds them. Are you not worth much more than they? And who of you by being worried can add a single hour to his life? And why are you worried about clothing? Observe how the lilies of the field grow; they do not toil nor do they spin, yet I say to you that not even Solomon in all his glory clothed himself like one of these. But if God so clothes the grass of the field, which is alive today and tomorrow is thrown into the furnace, will He not much more clothe you? You of little faith! Do not worry then, saying, "What will we eat?" or "What will we drink?" or "What will we wear for clothing?" For the Gentiles eagerly seek all these things; for your heavenly Father knows that you need all these things. But seek first His kingdom and His righteousness, and all these things will be added to you.
> 
> So do not worry about tomorrow; for tomorrow will care for itself. Each day has enough trouble of its own. (Matt. 6:25--34)

Early Christians knew these promises, and took them to heart. Their world was filled with sin: with child abuse and neglect, abortion, exposure, and infanticide; with poverty, rampant injustice and oppression, and terrible cruelty. Life expectancy was around 40, and more than half their children and mothers died in childbirth. Persecution was constant. There were many physical and spiritual threats to their children. The greatest minds and philosophers of their time had concluded it was better not to bring children into a world of such difficulty, cruelty, and bloodshed. There was a pervasive cynicism about marriage, children, and family, and it caused Greco-Roman birth rates to plummet even as standards of living improved. Their world was our world.

But their response was not ours. Amid a Roman population in decline, the population of Christians was on the increase.[^250] In the face of realities that, to the natural mind, argued for moderation, the church fathers became, if anything, *more* adamant against abortion and contraception. And as the Christian population increased, demographic change continued. The Christians who had more children became the Christians who loved more children, and the Christians who loved more children sought to ensure that the children of their persecutors were cared for as well. This continued throughout periods of war, famine, and persecution.

Finally, in God's good providence, the magistrates themselves began to change. But it took time and went in fits and starts. It would be glorious to imagine that, when Constantine marked Rome with the cross, abortion was done and gone, but the reality was messy. Abortion's demise proceeded by gradual steps of law. First to be proscribed was abortion that deprived a husband of offspring.[^251] Then came banning of child exposure and infanticide.[^252]

Finally, some 450 years after our Lord sanctified childbirth by His incarnation, Emperor Leo banned abortion outright.[^253] Yes, the legal end of abortion was brought about through wars, politics, protests, prayers, and schemes,[^254] but all of it was the providence of God, and He worked through simple Christians who loved their children, and who rescued and adopted babies left to die on the hillsides. In doing so, they heaped coals of fire on the heads of their enemies (Rom. 12:20).

This is our hope. It is the hope that has undergirded countless Christians working to protect the widow, the fatherless, and the unborn, ever since the Evil One set his sights on them. It is the hope that has carried us through the dark days of *Griswold*, *Roe*, and *Casey*, knowing that the cause of righteousness proceeds in fits and starts. It is the hope that gives meaning to every small act of courage: every man who refuses to kill his child to hide his sin; every woman who chooses to let her little one live despite the cost to her reputation, her relationship with her parents, or her career prospects; every downtrodden protestor who stands alone in the rain with nothing to show for it; and every legislator or magistrate who defends the unborn at the cost of his own position. And it is the hope that must abide even with the downfall of *Roe*, since only this hope can sustain the pro-life struggle in the terra incognita of a post-*Roe* landscape.

We have spent much time and many words unpacking the wicked state of our land. We have shown how, to our utter shame, we the people of God have also given ourselves to the bloodshed of our infants. We have recounted God's condemnation of abortion writ large across creation and throughout Scripture and church history. We have begun to open up what we can do to end the bloodshed---as magistrates, churchmen, and men and women of God.

Finally, though, our hope for the end of abortion isn't a matter of historical insight, proper argument, or wise application. The only end of abortion will be born through the preaching of the gospel of Jesus Christ which alone produces the fruit of repentance. This repentance must begin within the church of the Living God, but it will not end until it has spread throughout the earth.

This repentance from abortion is no abstract thing. It will be a living, breathing reality that is produced in the power of the Holy Spirit, and it will lay claim to every part of our lives, most especially our marriages and lovemaking. It seems almost unfathomable that God graces man with His very image and likeness. It seems unfathomable that, despite Adam's sin and our own multiplied transgressions adding to it, our heavenly Father continues to shower both the righteous and unrighteous with the gift of life, with the gift of children---the fruit of our lovemaking.

This extravagance from God should never be taken for granted or despised. He owes us death and hell, and shall we despise His gifts of love and life? Do we hear His warning?

> Do not be deceived, my beloved brethren. Every good thing given and every perfect gift is from above, coming down from the Father of lights, with whom there is no variation or shifting shadow. In the exercise of His will He brought us forth by the word of truth, so that we would be a kind of first fruits among His creatures. (James 1:16--18)

We are a kind of first fruits sent down from above by our heavenly Father. He has blessed His creation with such endless fruitfulness! Let us commit ourselves to being the instruments of His fruitfulness. Let us propagate a godly seed to serve in His courts of praise, giving Him glory forevermore.

Yes, doing so will require sacrifice. But the reality of sacrifice is built into creation. Into the little strawberry plants, which even in their first year will try to produce as much fruit as they can, stunting their own growth. Into the apple or peach tree which will bear so much fruit that their branches, laden with fruit, will break and fall. Into the salmon of Alaska, which travel a thousand miles upstream, expending all their energy to lay their eggs and then die. Of course, also, into our wonderful wives, who will endure the indignities of pregnancy, the pains of labor, the resulting stretch marks and varicose veins and bouts of depression, and on and on---who, in infinite ways, die so their child (*our* child) may live.

The cross is unavoidable. The only question is who will bear it and to what end. Will the cross be borne by fathers and mothers who sacrifice time, labor, money, and convenience---and in the mother's case, even their own bodies---so our children may live? Or, oppositely, will fathers and mothers demand the cross be carried by their children? Will fathers and mothers demand of their children their death, without even asking them if they're willing? Will fathers and mothers demand of their sons and daughters this last measure of devotion, which they hope will enable them to live an unencumbered life, not bothered by their children's needs, free to pile up wealth and possessions with no thought for anyone's needs but their own?

Will we call these little ones to die for us, or will we die for them? Every man and woman ever conceived has faced this choice, and each answer reveals to the watching world faith or unbelief in the King of kings and Lord of lords.

When God's people are fruitful, bearing, loving, and disciplining our own and others' children (through adoption), we testify to our rulers as well as the watching world of the kindness, mercy, and love of the heavenly Father. When we respond to ridicule not with cynicism or anger but by entrusting ourselves to Him who judges righteously (1 Pet. 2:23), we follow the Apostle in showing our gentleness to all men, knowing "the Lord is near" (Phil. 4:5). When our pastors and elders condemn oppression and injustice, particularly that terrible injustice of the murder of little ones awaiting birth, we tread the path our own fathers and mothers trod two millennia ago, thus changing the Roman Empire.

It will not happen overnight. *Roe* stood for half a century, and its debris is everywhere. But abortion *will* in God's time be brought down; and so let us here declare it simply: to embrace the fruit of the womb is to prove ourselves true sons of our heavenly Father. To care for the soul of every little one is to see in that life the image of God Himself and of our Lord, made man for us. And to love children, ours and our neighbors', is not to burden the world, but to exercise godly care by tending to our own corner of it. Or, as J. R. R. Tolkien put it:

> It is not our part to master all the tides of the world, but to do what is in us for the succour of those years wherein we are set, uprooting the evil in the fields that we know, so that those who live after may have clean earth to till.[^255]

This, then, is our hope. That our pastors and elders, legislators and magistrates, will lead us toward repentance and a return to God and His law. That as our own hearts bear new life, so we as fathers and mothers will have the blessing of the fruit of the womb that is the Lord's reward. And that, day by day, this joy will provoke our neighbors to jealousy---our repentance leading theirs, so that, finally, our eyes may see the day when this mighty scourge of evil shall speedily pass away.

Until that day, we persevere in hope---not a hope of chimera or fancy, but of faith and certainty, that when abortion is all past and the blood of Abel altogether purged, it will be by the sovereign hand of the Almighty as He turns our hearts once again to repentance.

The final verse of the Old Testament proclaims the wonderful fruit of this repentance:

> He will restore the hearts of the fathers to their children and the hearts of the children to their fathers, so that I will not come and smite the land with a curse. (Mal. 4:6)

Even so, come, Lord Jesus.


[^205]: Hugo Grotius, *De Jure Belli ac Pacis Libri Tres*, 121 (1.3.16).

[^206]: 1 William Blackstone, *Commentaries* \*42.

[^207]: See Westminster Larger Catechism, question 138, https://evangelpresbytery.com/westminster-larger-catechism/#Law.

[^208]: See, e.g., Indiana Code § 16-21-11-4, which recognizes parents' right to determine final disposition of the body of their little one lost to miscarriage.

[^209]: See Winston Churchill, in a 1942 speech commenting on the battle of El Alamein. "Autumn 1942 (Age 68)," International Churchill Society, March 12, 2015, https://winstonchurchill.org/the-life-of-churchill/war-leader/1940-1942/autumn-1942-age-68/.

[^210]: It may also be instructive that, in each such case, the words shift from active to passive voice: the deeds of the king (for good or for ill) are expressed in active voice, while the persistence of the high places is shifted into passive voice ("were not taken away"). This may represent a lower-level criticism of the king.

[^211]: Herman Melville, *Moby Dick*, ch. 8.

[^212]: See Resolution 15 from The Lambeth Conference, 1930, Anglican Communion, https://www.anglicancommunion.org/resources/document-library/lambeth-conference/1930/resolution-15-the-life-and-witness-of-the-christian-community-marriage.aspx.

[^213]: "Protestants Endorse Birth Control," *Birth Control Review* 15, no. 4 (April 1931): 102.

[^214]: Quoted in Howard Kainz, "Failing to Connect the Dots on Contraception," *First Things*, February 8, 2012, https://www.firstthings.com/web-exclusives/2012/02/gop-fails-to-connect-the-dots-on-contraception.

[^215]: As reported by Richard Soloway, *Birth Control and the Population Question in England, 1877--1930* (University of North Carolina Press, 1982), 103.

[^216]: "Covenant and Creation: Theological Reflections on Contraception and Abortion," report delivered to the 195th General Assembly (1983) of the Presbyterian Church (USA), 17. The GA received this report and adopted its policy statements and recommendations.

[^217]: David Roach, "How Southern Baptists Became Pro-Life," *Baptist Press*, January 16, 2015, https://www.baptistpress.com/resource-library/news/how-southern-baptists-became-pro-life/.

[^218]: Dennis Quinn, "Few U.S. Sermons Mention Abortion, Though Discussion Varies by Religious Affiliation and Congregation Size," Pew Research Center, April 29, 2020, https://www.pewresearch.org/fact-tank/2020/04/29/few-u-s-sermons-mention-abortion-though-discussion-varies-by-religious-affiliation-and-congregation-size/.

[^219]: Lisa Cannon Green, "Survey: Women Go Silently from Church to Abortion Clinic," Focus on the Family, August 17, 2021, https://www.focusonthefamily.com/pro-life/survey-women-go-silently-from-church-to-abortion-clinic/.

[^220]: David Masci, "American Religious Groups Vary Widely in Their Views of Abortion," Pew Research Center, January 22, 2018, https://www.pewresearch.org/fact-tank/2018/01/22/american-religious-groups-vary-widely-in-their-views-of-abortion/.

[^221]: "Older women likewise are to be reverent in their behavior, not malicious gossips nor enslaved to much wine, teaching what is good, so that they may encourage the young women to love their husbands, to love their children, to be sensible, pure, workers at home, kind, being subject to their own husbands, so that the word of God will not be dishonored." Titus 2:3--5.

[^222]: "But not one has done so who has a remnant of the Spirit. And what did that one do while he was seeking a godly offspring? Take heed then to your spirit, and let no one deal treacherously against the wife of your youth." Malachi 2:15.

[^223]: For more, see "Man's Duty to Protect Woman," Majority Report of the Presbyterian Church in America's General Assembly Ad Interim Study Committee on Women in the Military, 2001, https://www.pcahistory.org/pca/studies/01-278.html.

[^224]: For more information on embryo adoption, see the website of the National Embryo Donation Center, https://www.embryodonation.org/; or the website of Nightlight Christian Adoption's "Snowflakes" program, https://nightlight.org/snowflakes-embryo-adoption-donation/.

[^225]: See Revelation 8.

[^226]: Pierre Viret, *The Christian and the Magistrate: Roles, Responsibilities, and Jurisdictions*, trans. R. A. Sheats (Psalm 78 Ministries, 2015), ch. 7, Kindle.

[^227]: Speech at New Haven, Connecticut, March 6, 1860, *Collected Works of Abraham Lincoln*, vol. 4 (University of Michigan Digital Library Production Services, 2001), 21, http://name.umdl.umich.edu/lincoln4. Emphases original.

[^228]: Westminster Larger Catechism, question 135.

[^229]: See Michael Card's 1984 song, "Spirit of the Age":
    
    > I thought that I heard crying coming through my door. \
    Was it Rachel weeping for her sons who were no more? \
    Could it have been the babies crying for themselves, \
    Never understanding that they died for someone else?
    >
    > A voice is heard of weeping and of wailing. \
    History speaks of it on every page: \
    Of innocent and helpless little babies, \
    Offerings to the spirit of the age.
    >
    > No way of understanding this sad and painful sign; \
    Whenever Satan rears his head, there comes a tragic time. \
    If he could crush the cradle, then that would stop the cross; \
    He knew that once the Light was born, his every hope was lost.
    >
    > Now every age has heard it, this voice that speaks from hell: \
    "Sacrifice your children and for you it will be well." \
    The subtle serpent's lying, his dark and ruthless rage; \
    Behold, it is revealed to be the spirit of the age.
    >
    > Soon all the ones who seemed to die for nothing \
    Will stand beside the Ancient of Days. \
    With joy we'll see that Infant from a manger \
    Come and crush the spirit of the age.
    
    \ 

[^230]: One example of such is David DeBoor Canfield's "Sighs and Sorrows," Sonata No. 2 for Violin and Piano (1987; rev. 2010), a work protesting abortion.

[^231]: John Paul II, *Evangelium Vitae*, § 73. The concluding quote is from *Declaration on Procured Abortion*, § 22.

[^232]: On the other hand, Republican presidents have also been responsible for a number of disappointments on abortion: e.g., Sandra Day O'Conner, Anthony Kennedy, and David Souter.

[^233]: As but one example, the Federalist Society, an organization that advocates for originalism in constitutional interpretation, was founded in 1982. In recent elections, Republican candidates (especially Donald Trump) have made a cornerstone of their platform a commitment to choosing judges that are approved by the Federalist Society.

[^234]: From the 2020 Democratic party platform:

    > We believe unequivocally, like the majority of Americans, that every woman should be able to access high-quality reproductive health care services, including safe and legal abortion. We will repeal the Title X domestic gag rule and restore federal funding for Planned Parenthood, which provides vital preventive and reproductive health care for millions of people, especially low-income people, and people of color, and LGBTQ+ people, including in underserved areas.
    >
    > Democrats oppose and will fight to overturn federal and state laws that create barriers to reproductive health and rights. We will repeal the Hyde Amendment, and protect and codify the right to reproductive freedom.
    
    "Achieving Universal, Affordable, Quality Health Care," Democrats.org, accessed June 21, 2022, https://democrats.org/where-we-stand/party-platform/achieving-universal-affordable-quality-health-care/.

[^235]: François de La Rochefoucauld, *Maxims*, no. 218.

[^236]: This publication is by the Center for Family and Human Rights, covering life and social policy issues at the United Nations and other international entities.

[^237]: These analyze fetal DNA in the mother's bloodstream.

[^238]: A piece of the placenta is removed and tested.

[^239]: Amniotic fluid from the area surrounding the baby is withdrawn and tested.

[^240]: Maternal blood tests are frequently used to screen for Down syndrome, trisomy 18 and trisomy 13. The Mayo Clinic reports that 15 percent of women receive a false negative and 5 percent receive a false positive for Down syndrome ("First Trimester Screening," Mayo Clinic, https://www.mayoclinic.org/tests-procedures/first-trimester-screening/about/pac-20394169). More recently, these non-invasive prenatal screenings (NIPS) have been used for other genetic micro-deletions. A 2017 study concluded that the false positive rate for the detection of some of the micro-deletion syndromes could be as high as 90 percent (Henna Advani et al., "Challenges in Non-invasive Prenatal Screening for Sub-chromosomal Copy Number Variations Using Cell-Free DNA," *Prenatal Diagnosis* 37, no. 11 [November 2017]: 1067--1075, https://doi.org/10.1002/pd.5161). Even the *New York Times* found this news troubling (Sarah Kliff and Aatish Bhatia, "When They Warn of Rare Disorders, These Prenatal Tests Are Usually Wrong," *The Upshot* (blog), *New York Times*, January 1, 2022, https://www.nytimes.com/2022/01/01/upshot/pregnancy-birth-genetic-testing.html). A 2014 study in France determined that ultrasounds yielded a false positive rate of 8.8 percent and a misclassification rate of 9.2 percent (Anne Debost-Legrand et al., "False Positive Morphologic Diagnoses at the Anomaly Scan: Marginal or Real Problem, A Population-Based Cohort Study," *BMC Pregnancy and Childbirth* 14, art. no. 112, March 24, 2014, https://doi.org/10.1186/1471-2393-14-112). Chorionic villus sampling (CVS) and amniocentesis are generally recommended only after an abnormality is indicated by means of less invasive maternal blood tests or ultrasounds. Neither of these methods is foolproof: "A false positive rate was reported to be 3.6% for early amniocentesis and 8% for mid-trimester amniocentesis" (Zarko Alfirevic, Faris Mujezinovic, and Karin Sundberg, "Amniocentesis and Chorionic Villus Sampling for Prenatal Diagnosis," *Cochrane Database of Systematic Reviews* 2003, no. 3, https://doi.org/10.1002/14651858.CD003252). Both CVS and amniocentesis can lead to the death of the baby in the womb; for pregnant women at least 35 years old, the risk of the baby dying from amniocentesis is the same as the risk of the child having, for example, Down syndrome (Susan Pauker and Stephen Pauker, "Prenatal Diagnosis---Why Is 35 a Magic Number?" *NEJM* 330, no. 16 [April 21, 1994]: 1151--1152, https://doi.org/10.1056/nejm199404213301610). For CVS the rate of the baby dying after the procedure was around 2.5 percent (Laird Jackson et al., "A Randomized Comparison of Transcervical and Transabdominal Chorionic-Villus Sampling," *NEJM* 327, no. 9 [August 27, 1992]: 594--598, https://doi.org/10.1056/NEJM199208273270903).

[^241]: We are aware this concept of "empathy" has become controversial in some parts of the church recently. No question false empathy is abroad and social media is the perfect breeding ground. While conceding that the word can be abused, the abuse of a thing does not invalidate its proper use. The *Oxford English Dictionary* defines "empathy" as "the ability to understand and share the feelings of another." Thus empathy is a critical component of the character of Christian charity:

    > For we do not have a high priest who cannot sympathize with our weaknesses, but One who has been tempted in all things as we are, yet without sin. (Heb. 4:15)

    > When Jesus therefore saw her weeping, and the Jews who came with her also weeping, He was deeply moved in spirit and was troubled, and said, "Where have you laid him?" They said to Him, "Lord, come and see." Jesus wept. (John 11:33--35)

    > And if one member suffers, all the members suffer with it; if one member is honored, all the members rejoice with it. (1 Cor. 12:26)

    \ 

[^242]: John Calvin, comments on Acts 15:2, *The Acts of the Apostles 14--28*, trans. John W. Fraser, ed. David W. Torrance and Thomas F. Torrance (Eerdmans, 1995), 27.

[^243]: A clinic, properly called, is a place where the healing arts are practiced---not a place presided over by an executioner of the innocent and defenseless. From the *Online Etymology Dictionary*: "1620s, 'bedridden person, one confined to his bed by sickness,' from French *clinique* (17c.), from Latin *clinicus* 'physician that visits patients in their beds,' from Greek *klinike* (*techne*) '(practice) at the sickbed,' from *klinikos* 'of the bed,' from *kline* 'bed, couch, that on which one lies,' from suffixed form of PIE root *klei*- 'to lean.'" Accessed April 10, 2022, https://www.etymonline.com/word/clinic.

[^244]: A note of encouragement on this. One married couple of our congregation traveled across Europe a couple years ago with a brood of four, ages 1, 2, 6, and 8. They reported: "We walked out of our Airbnb as a family of 6, and a very old Italian woman looked at our kids and her eyes filled with tears and she said, 'Bella! Bella! Bella familia!' On more than one occasion we had waiters go out of their way to serve us because they were so thrilled that we were out and about with so many small children. The Italians were smitten, and even the French were accommodating to an extreme."

[^245]: Herman Melville, *Moby Dick*, ch. 134.

[^246]: Cf., e.g., Augustine, *On Marriage and Concupiscence* 1.15.17 (AD 419--420): "Indeed, sometimes this lustful cruelty or cruel lust [*libidinosa crudelitas vel libido crudelis*] extends so far that it obtains poisons of sterility [*sterilitatis venena*]; and, if nothing else works, [it] snuffs out and breaks up by some means the offspring conceived in the womb, preferring its own offspring to perish before it lives [*prius interire quam vivere*]; or, if it was already living in the womb, to be killed before being born [*occidi antequam nasci*]."

    Cf. also John Chrysostom (AD 391): "Why do you sow where the field is eager to destroy the fruit, where there are medicines of sterility? Where there is murder before birth? You do not even let a harlot remain only a harlot, but you make her a murderess as well. . . . Indeed, it is something worse than murder, and I do not know what to call it; for she does not kill what is formed but prevents its formation. What then? Do you condemn the gift of God and fight with his [natural] laws? . . . Yet such turpitude . . . the matter still seems indifferent to many men---even to many men having wives. In this indifference of the married men there is greater evil filth; for then poisons are prepared, not against the womb of a prostitute, but against your injured wife. Against her are these innumerable tricks." *Homilies on Romans* 24, trans. J. Walker, J. Sheppard, and H. Browne.

[^247]: "Far be it, then, from us to doubt that all number is known to Him 'whose understanding,' according to the Psalmist, 'is infinite.' The infinity of number, though there be no numbering of infinite numbers, is yet not incomprehensible by Him whose understanding is infinite. And thus, if everything which is comprehended is defined or made finite by the comprehension of him who knows it, then all infinity is in some ineffable way made finite to God, for it is comprehensible by His knowledge. Wherefore, if the infinity of numbers cannot be infinite to the knowledge of God, by which it is comprehended, what are we poor creatures that we should presume to fix limits to His knowledge, and say that unless the same temporal thing be repeated by the same periodic revolutions, God cannot either foreknow His creatures that He may make them, or know them when He has made them? God, whose knowledge is simply manifold, and uniform in its variety, comprehends all incomprehensibles with so incomprehensible a comprehension, that though He willed always to make His later works novel and unlike what went before them, He could not produce them without order and foresight, nor conceive them suddenly, but by His eternal foreknowledge." *City of God* 12.18, trans. Marcus Dods.

[^248]: One of us recalls an elder telling him that the wife of one of the staff members of the church had just found out she was pregnant. He said the staff member had come to him asking what they should do, since his wife had been on some medication that might have harmed the child and they were fearful. The elder explained he'd suggested the staff member consider abortion, explaining to his pastor, "I consider abortion a matter of stewardship."

[^249]: G. K Chesterton, "The Unfinished Temple," ch. 5 in *What's Wrong with the World*, https://www.gutenberg.org/files/1717/1717-h/1717-h.htm.

[^250]: Hard data on Roman fertility in general, let alone Christian Roman fertility, is lacking. But Stark, *The Rise of Christianity: A Sociologist Reconsiders History* (Princeton University Press, 1996), 122--128, considering the available evidence, lays out a compelling argument for a healthy increase in the Christian fertility rate in the late Roman world, pointing in particular to the following advantages held by Christians in comparison to pagans: (1) abhorrence of abortion and infanticide, (2) objections to contraception, (3) a positive view of marriage (even in cases of mixed marriage), and (4) a high percentage of women of childbearing age. There is also some testimony from primary sources of the time. Noting this, Stark comments, "Differential fertility was taken as fact by the ancients," and quotes Minucius Felix approvingly: "Day by day the number of us is increased [because of] [our] fair mode of life" (122).

[^251]: Put in place by Emperor Septimius Severus (193--211): "A woman who intentionally induces an abortion is to be sentenced by the Governor to temporary exile; for it can be considered dishonorable for a woman to defraud a husband of his children with impunity." *Digesta* 47.11.4*.*

[^252]: Particularly under Theodosius II (408--450): "If anyone commit the crime of killing an infant, this evil shall constitute a capital offense." *Codex Theodosianus* 9.14.1.

[^253]: "Two laws have been enacted, one against a woman who, through dislike to her husband, takes pains to produce an abortion upon herself, and accomplishes the death of her unborn child, and another enacted against the husband requiring him to repudiate a woman who has been guilty of such an outrage." Leo later says that such a woman "has committed a crime which is an outrage . . . against Nature." *The New Constitutions of the Emperor Leo* 31, trans. S. P. Scott, https://droitromain.univ-grenoble-alpes.fr/Anglica/NL31_Scott.htm.

[^254]: This does not mean that the practice of abortion ended immediately, of course. Indeed, child murder was apparently slow to decline. Law, as all else, is bound by God's decrees, but law cannot in itself change hearts.

[^255]: J. R. R. Tolkien, "The Last Debate," ch. 9 in bk. 1 of *The Lord of the Rings: The Return of the King*.