# Epilogue {-}

A valiant warrior for the faith who never ceased opposing abortion and all evils metastasizing from it was lost to the battle back in 2009. He was the late Richard John Neuhaus, and a few months before his death, he presented the concluding message of the 2008 annual convention of National Right to Life.

He ended his speech with these words:

> We do not know, we do not need to know, how the battle for the dignity of the human person will be resolved. God knows, and that is enough. As Mother Teresa of Calcutta and saints beyond numbering have taught us, our task is not to be successful but to be faithful. Yet in that faithfulness is the lively hope of success. We are the stronger because we are unburdened by delusions. We know that in a sinful world, far short of the promised Kingdom of God, there will always be great evils. The principalities and powers will continue to rage, but they will not prevail.
> 
> In the midst of the encroaching darkness of the culture of death, we have heard the voice of Him who said, "In the world you will have trouble. But fear not, I have overcome the world." Because He has overcome, we shall overcome. We do not know when; we do not know how. God knows, and that is enough. We know the justice of our cause, we trust in the faithfulness of His promise, and therefore we shall not weary, we shall not rest.
> 
> Whether, in this great contest between the culture of life and the culture of death, we were recruited many years ago or whether we were recruited only yesterday, we have been recruited for the duration. We go from this convention refreshed in our resolve to fight the good fight. We go from this convention trusting in the words of the prophet Isaiah that "they who wait upon the Lord will renew their strength, they will mount up with wings like eagles, they will run and not be weary, they will walk and not be faint."
> 
> The journey has been long, and there are miles and miles to go. But from this convention the word is carried to every neighborhood, every house of worship, every congressional office, every state house, every precinct of this our beloved country---from this convention the word is carried that, until every human being created in the image and likeness of God---no matter how small or how weak, no matter how old or how burdensome---until every human being created in the image and likeness of God is protected in law and cared for in life, we shall not weary, we shall not rest. And, in this the great human rights struggle of our time and all times, we shall overcome.[^256]


[^256]: Richard John Neuhaus, "We Shall Not Weary, We Shall Not Rest," speech given at the conclusion of the 2008 annual convention of National Right to Life, July 5, 2008, as published on July 11, 2008, in *First Things*, https://www.firstthings.com/web-exclusives/2008/07/we-shall-not-weary-we-shall-not-rest.