## The Church's Response to Abortion

Back in the fifties when what was called "birth control" was first normalized in conjunction with the change of definition of "conception" and "life," this change in definitions had the inevitable result of allowing abortion to throw off its guilt and shame. Christians and pagans together grew used to employing birth control technology to prevent children so that, as surgical abortions came forward and began to increase in frequency, Christians were desensitized. The horror of doctors taking money to cut apart and remove infants from their mother's womb didn't register among the people whose practice of birth control depended upon conception not being conception and life not being life.

As pointed out earlier, the explosion of surgical abortions preceded 1973's *Roe v. Wade* decision. Nevertheless, *Roe v. Wade* threw the door open in a way the previous laws of the fifty states had not done.

### Protestants and Whatever Happened to the Human Race?

How did the church respond to *Roe v. Wade*?

Roman Catholics didn't waver in their longstanding, historical opposition to contraception and abortion, but Protestants---including Evangelicals---simply accepted *Roe v. Wade* as the law of the land. The Supreme Court was the standing civil authority and Evangelicals believed God required them to honor this Supreme Court ruling.

Undoubtedly some readers survey the contemporary disrespect for authority, and particularly the opposition to surgical abortion which is now so characteristic of conservative Protestant churches in North America, and have trouble believing the same disrespect and opposition to the Supreme Court's *Roe v. Wade* ruling was not present in 1973 and years following.

In the wake of *Roe v. Wade*, it's a tragic fact that Evangelicals were silent and compliant. This can be demonstrated in many ways, but the most obvious way is the national barnstorming tour of C. Everett Koop and Francis Schaeffer showing their films and giving lectures based on their jointly authored book *Whatever Happened to the Human Race?*

It wasn't until 1979 that Koop and Schaeffer toured the country's major cities calling attendees to wake up to the horrors of surgical abortions, and their attendees were exclusively Evangelicals. At the time, Koop (later to become surgeon general under President Reagan) and Schaeffer complained to their Denver audience[^50] that they had contacted fifteen or so Evangelical leaders in Wheaton, inviting them to attend their Chicago series, but none of them had been willing to come. This, they explained, was one more proof of the lack of concern over abortion on the part of Evangelicals, and particularly Evangelical leaders.

Nevertheless, Koop and Schaeffer were respected within Evangelicalism's rank and file, and their prophetic witness of 1979 single-handedly woke Evangelicalism up so that conservative Protestant Christians still today view opposition to abortion as a fundamental part of Christian ethics.[^51] Since 1979, therefore, pro-life commitments have been a fundamental component of Christian political witness and action.

But notice that *Roe v. Wade* was issued in 1973, and Koop and Schaeffer did not publish their book and give their lectures until 1979---six years later.

### Pro-Life Protestants and the Growth of Chemical Abortions

It is God's kindness that the conservative Protestant church has mostly been firm in her opposition to abortion since 1979, but that opposition has been focused almost exclusively on surgical abortion. More recently, there has been some opposition to later chemical abortions that are committed up until the tenth week of pregnancy by means of the drugs mifepristone (RU-486) and misoprostol, but the pro-life commitments and witness which grew out of Koop and Schaeffer's witness never matured into opposition to abortifacient birth control methods not involving surgery or mifepristone and misoprostol.

Even as we write, IUDs and hormonal birth control methods like the Pill continue to be widely used by conservative Protestants who consider themselves pro-life. Most of them remain oblivious to the abortifacient nature of their hormonal methods and IUDs.

Meanwhile, surgical abortions are in decline and chemical abortions have taken over.

In 2019, one medical journal co-sponsored by The Faculty of Sexual & Reproductive Healthcare of the Royal College of Obstetricians & Gynaecologists estimated "medication (or medical) abortion accounts for at least half of all abortions in the majority of countries."[^52] Again, keep in mind that this estimate excludes the abortion of little ones by birth control methods that have an agency preventing the child's implantation in his mother's womb. When the Royal College's obstetricians and gynecologists speak of "medication abortions," they are only referring to later abortions committed by means of the drugs mifepristone and misoprostol up through ten weeks of gestation.

Remember that the scientific and medical communities redefined "conception" and "life" in order to normalize the mid-century birth control pill known to have an abortifacient agency. Largely by means of these redefinitions almost sixty years ago, the word "abortion" has never been associated with the Pill, the IUD, or any other hormonal birth control.

Within the broader pro-life community, there has been some opposition to later-term mifepristone and misoprostol abortions. Some have recognized the peculiar danger of these drugs due to the perception that they are a kinder, gentler way of killing than scalpels and suction machines. But what about the abortifacient agency of IUDs and hormonal drugs and devices? Shouldn't our pro-life witness be consistent?

The child conceived by his father's fertilization of his mother's egg takes six or seven days to wend his way to his mother's uterus and attach himself to her uterine wall. Rightly understood, chemical abortions are not just mifepristone and misoprostol given later in pregnancy, but they include IUDs and drugs that obstruct the child's attachment to the wall of the uterus, denying him the nurture and protection of his mother's womb.

Note carefully: the deaths of children caused by IUDs, by early birth control methods with a hormonal component, by later birth control methods utilizing mifepristone and misoprostol, and by surgical abortions all break the Sixth Commandment. But all these killings are not equally visible and felt.

The blood, body parts, and shame of surgical abortions are hard to hide, but it's easy to hide the tiny little ones killed by IUDs and the Pill. Thus with surgical abortion's decline, the emotional and spiritual toll of abortion has grown increasingly hidden.

Unlike the death-camp victims of World War II, aborted babies who are also the victims of genocide have not been liberated, and their pictures have not been taken. No holocaust museum recounts their chemical tortures and deaths. As abortions continue to move toward the first weeks of pregnancy and the chemical removal of the child, it will become ever more difficult to see and oppose this bloodletting. Mothers will hide their murders at home, inside their wombs, and this secrecy will make it exceedingly difficult to protect the little victims in any court of law.

Nevertheless, God sees these murders, and all the blood will be brought to His bar of justice. It will not remain hidden:

They even sacrificed their sons and their daughters to the demons,

And shed innocent blood,

The blood of their sons and their daughters,

Whom they sacrificed to the idols of Canaan;

And the land was polluted with the blood.

Thus they became unclean in their practices,

And played the harlot in their deeds.

Therefore the anger of the [Lord]{.smallcaps} was kindled against His people . . .

(Ps. 106:37--40)