## The Truth about Hormonal Birth Control

To come to some awareness of the scale of this bloodshed, we must reckon with the many abortions caused specifically by IUDs and hormonal birth control. This is a very difficult question for many Christians today. How can the default birth control methods used by Christians within the church for the past seventy years be called into question? Surely the medical establishment (and particularly Christians who are a part of that establishment) would have warned us if their birth control methods were aborting our children, right? Is the goal here simply to condemn all forms of birth control? Are the authors of this document Roman Catholic?

Good questions, and no, your authors are not condemning all use of birth control. Although we believe most practices of birth control today are not morally justified, there are occasions where pregnancy prevention is justified, and in such cases there are methods of pregnancy prevention which are truly and only pregnancy prevention---that is, which are truly contraceptive. Which is to say, there are methods of preventing pregnancy that prevent conception rather than preventing implantation. There are methods of pregnancy prevention that do not have any abortifacient agency and do not kill children. Sadly, these methods do not include some of the most common methods of birth control used today.

### IUDs, the Pill, and the Prevention of Implantation

Among the 61 percent of women in the United States between the ages of 15 and 49 using some method of pregnancy prevention in 2019, close to half (27 percent of the same demographic) employed methods with an abortifacient agency.[^53] IUDs and all hormonal birth control methods include a significant agency of preventing a very young child from attaching himself to the wall of the uterus. For a few days the little one lives, but then he is denied the nurture and protection of his mother's womb, and this kills him.

The official and scientific sources confirming this are endless, and have been for generations. For this reason scientific and medical authorities changed the definition of conception in the 1960s, as documented above.

This subterfuge enabled them to declare that IUDs and hormonal birth control methods are *absolutely not* abortifacients. This subterfuge enabled our obstetricians and gynecologists also to redefine the beginning of life as implantation---not fertilization. Because of this deception, these forms of birth control have been embraced by an unknowing public for nearly sixty years now. And through these years, our obstetricians, gynecologists, and pharmacists, Christian and pagan alike, have been assuring us there's no danger of the products they prescribe killing our little ones.

The project is larger than denying these little ones are living human beings. This denial requires a prior denial that IUDs and hormonal methods of birth control have any agency at all of preventing implantation. Christians and pagans have thus become allies, joining together in opposing and obstructing woman's wonderful nature decreed by God as "the mother of the living" and "life-giver."[^54]

Some would claim it doesn't really matter if a woman's method of birth control prevents the little one from attaching himself to his mother's womb so long as the prevention of implantation is not the primary agency of the mother's choice of birth control. The risk is small and neither her doctor nor her pharmacist are selling her drugs with the intent to kill her babies. Their intent is simply to help their client interrupt her normal cycle; or, failing that, to help the woman's body to attack her husband's sperm so it is unable to fertilize any egg that happens to make it down her fallopian tubes. They go on to point out that all of life has risks, and this risk of killing the little one is reasonable given the large benefit of preventing the birth of another "unwanted child," or a child who would harm the chances of his siblings going to college.

Thus what Hannah Arendt referred to as the banality of evil[^55] continues into the twenty-first century, although Jews and "useless eaters" are no longer the intended victims. Lately, the victims are our own sons and daughters. If, over the course of twenty or thirty years of fertility, killing a few of her children is the cost of one mother limiting her painful pregnancies and childbirth, and minimizing the burden of raising a child to adulthood---it's a small price to pay for such a significant relief.

Of course, it's neither the mother nor her husband paying any price, but rather their dead sons and daughters. It cost these little ones their lives. They didn't live a life of slavery. They were murdered in the womb before they saw the light of day or took a breath.

It would be preferable not to have to discuss the pragmatic and callous rationalizations Christians employ to justify their murder of their unborn children, but such rationalizations are common within the church. Men and women today style themselves sensitive to the suffering of others, but unborn children haven't made the cut. Christian men and women assure one another that compassion is their highest commitment, but let's look carefully at this fruit of our compassion.

We sympathize with sisters in Christ fearful of being overwhelmed by scads of children. We sympathize with Christian mothers of a certain age fearful of giving birth to a child with a genetic defect. We sympathize with Christian mothers who are tired of being pregnant and want to "get on with life." We sympathize with Christian mothers who want to defer having their own biological children so they can adopt others' unwanted children. We sympathize with women who suffer debilitating pain from conditions, such as endometriosis, whose doctors prescribe the Pill to relieve that pain. We sympathize with Christian mothers who give all these reasons for using abortifacient methods of birth control.

Of course, all of us should have and express sympathy in such situations, but that sympathy must issue from a compassion that is true, not false. How do we recognize false sympathy and compassion?

False compassion has no patience for truth. It brushes it aside. Concerning conception and the life of the preborn, false compassion expresses sympathy to the mother who is visible while leaving the child who is not present alone in his vulnerability, invisibility, and silence.

Having compassion is godly, but only if that compassion is godly, which necessarily means only if that compassion is truthful. Yes, we are called by God to have compassion on women bearing these burdens and having such a desire, but that compassion must always be expressed to the mother for both her life and the lives of her babies. In our day of cheap sentiments spread through social media by emoticons, Christians should balk at the whole mess, understanding how costly true compassion is, and having the unerring ability to see where it needs to be defended.

Flannery O'Connor, that great southern author who had such an unerring instinct for the ways original sin twists our lives, compared the tenderness of past ages to the tenderness of our own age:

. . . now, we govern by tenderness. It is a tenderness which, long since cut off from the person of Christ, is wrapped in theory. When tenderness is detached from the source of tenderness, its logical outcome is terror. It ends in forced-labor camps and in the fumes of the gas chamber.[^56]

Our tender sympathies have borne the fruit of infant slaughter. We must face it.

Princeton ethicist Paul Ramsey pointed out that a deer hunter is guilty of manslaughter if he finds himself wondering what that movement is in the underbrush, but goes ahead and pulls the trigger, and kills a man. The law requires the hunter to wait to shoot until he's established his target is not a man. Man is the most precious of all God's creatures,[^57] and thus it is a criminal act to take unnecessary risks of shedding his blood. He alone bears God's image and likeness. Even a minute or two old, he is known and precious in God's sight.

In light of this basic moral principle, we stop and consider the fact that hormonal methods of birth control have an agency of preventing the little one from availing himself of the nurture and protection of his mother's womb. This fact is scientifically incontrovertible. Over the years, there have been some Christians who have tried to deny it, but the testimony of secular scholars, physicians, and pharmaceutical firms is nearly unanimous: IUDs and hormonal methods of birth control have an undeniable abortifacient agency.[^58]

Taking hormonal methods, specifically, the simplest search of the web returns page after page from pharmaceutical firms, non-profits working to limit world population, and healthcare information sites, all matter-of-factly stating their agency of preventing implantation. Such statements vary in terminology, but here are typical examples.

Here is an excerpt from an article on the website of the National Center for Biotechnology Information of the National Institutes of Health:

The hormones in contraceptives don't only prevent ovulation. Some also prevent fertilized eggs from implanting into the womb.[^59]

The American Society for Reproductive Medicine publishes ReproductiveFacts.org, where they ask the question, "How do hormonal contraceptives work?" Here is their answer:

Hormonal contraceptives contain a progestin (progesterone medicine) with or without an estrogen. . . . These two hormones together, or the progestin alone, work in several ways to prevent a pregnancy:

-   They can prevent ovulation (the release of an egg).

-   They make the mucus around the cervix (mouth of the womb) thicker so that sperm cannot enter the uterus (womb).

-   They make the lining of the uterus (womb) thinner to prevent a fertilized egg from attaching itself.[^60]

The following is from the University of Michigan Health website:[^61]

+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Method**                | **How it prevents pregnancy**                                                                                                              |
+===========================+============================================================================================================================================+
| Hormonal                  | -   Prevents ovulation                                                                                                                     |
|                           |                                                                                                                                            |
|                           | -   Thickens mucus at the cervix so sperm cannot pass through                                                                              |
|                           |                                                                                                                                            |
|                           | -   Changes the environment of the uterus and fallopian tubes to prevent fertilization and to prevent implantation if fertilization occurs |
+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Intrauterine device (IUD) | -   There are two types of IUDs (hormonal and copper). Both types may work by preventing:                                                  |
|                           |                                                                                                                                            |
|                           |     -   Fertilization of the egg.                                                                                                          |
|                           |                                                                                                                                            |
|                           |     -   Implantation in the uterus.                                                                                                        |
+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+

Similar documentation is spread across the web. One prominent example is an online course in human embryology developed by the prestigious Swiss universities of Fribourg, Lausanne, and Bern. In their module 6.5, we read:

Contraception can take place on three different levels: preventing oocytes from meeting sperm cells, hindering ovulation, \[or\] hindering fertilization or the implantation of the fertilized oocyte.[^62]

The embryology course's supplementary link goes on to specify this concerning hormonal birth control:

They transform the uterine endometrium so it becomes pseudoatrophic, thereby making an implantation practically impossible, should an ovulation and fertilization take place.[^63]

They describe the *primary* abortifacient agency of the IUD:

With an intra-uterine device (IUD) a double function is involved: firstly, implantation is hindered and, secondly, sperm cells are immobilized.

Some researchers are working to prove this abortifacient agency of the IUD is minor or absent, as shown by a recent (2020) study published in *Nature*'s *Scientific Reports*.[^64] Relias Media cites one of the study's authors, Karen Smith-McCune:

We always assumed, from the 1980s on, that the IUD was preventing implantation, but that's never been proven.[^65]

Consider carefully this long-held assumption. It was the cover for governmental, scientific, and medical authorities to promote, prescribe, sell, and insert IUDs for decades, all the while knowing their IUDs were abortifacients.

Smith-McCune goes on to report her study found hormone-releasing IUDs indeed caused inflammation of the uterine wall, but copper-releasing IUDs did not. From this Smith-McCune concludes copper-releasing IUDs do not prevent implantation. Her conclusion, however, is logically wrong; copper-releasing IUDs might have other effects preventing implantation consistent with the traditional assumption. The authors indirectly admit the weakness of their conclusion, calling it a "suggestion." In a matter of life and death, why would serious researchers content themselves with suggestions? Smith-McCune seeks to answer that question:

I think the results present a counterargument to resistance to the IUD. Policymakers who are resistant to IUD use can take our data as evidence that strongly suggests it is not preventing implantation.

Note in her statement the distinction between hormonal and copper-releasing IUDs has conveniently disappeared. Moreover, note this is not science. The study is catering to political interests intent on breaking down political resistance against the use of IUDs based on moral grounds.

Furthermore, Smith-McCune's suggestion cannot account for the fact that IUDs, whether copper or hormonal, are over 99 percent effective as "emergency contraception" for up to five days after intercourse, just like the morning-after pill.[^66]

Now then, once more: What follower of Jesus Christ is satisfied with assurances that his chances of killing his child are small, with suggestions that some IUDs might work differently than others? Remember that all he and his wife must do to avoid killing their child is refuse to use the IUD and other hormonal forms of birth control.

It's understandable for worldlings to be dismissive of such violations of the Sixth Commandment, but Christians? Have we forgotten the warning of the Apostle John concerning "murderers," that they "will be in the lake that burns with fire and brimstone, which is the second death" (Rev. 21:8)? Is God's commandment, "Whoever sheds man's blood, by man his blood shall be shed" (Gen. 9:6), limited to babies we allow to be born? Babies we allow to attach themselves to their mother's womb?

Those who hate God and His moral law are unconcerned about such matters, but are we not God's people? Have we not heard His warnings that He hates those who shed the blood of innocents? Are babies anyone's enemies? Do we not welcome and rejoice in His precious gift of life? Do we not join our forefathers in giving Him praise and thanks for opening the womb of our mothers and wives?

### The Significance of Our Lord's Incarnation

One of the most beautiful things about recovering the personhood of the embryo created by God and only a couple days old is that we recover the beauty and wonder of the incarnation of our Lord Jesus. When we sing, "Lo, He abhors not the Virgin's womb,"[^67] our thoughts naturally turn to a visible baby bump and Jesus residing there with blessed Mary resting her hands on her womb, radiating her love to the Son of God. Which is to say, who thinks of our Lord's incarnation when it was but a day or two old?

The King of Glory through whom the stars were formed, and the earth holds together yet today, dignified the embryonic life of each of us by living that life Himself. This is amazing and must surely instruct us concerning reverence due the embryonic life He still creates and places in woman, the life-giver. We may callously dismiss this life, but we do so forgetting the Son of Man was Himself a mere second old, and was that very second fully Man and fully God. Would we dare to deny His Personhood the millisecond after the Holy Spirit came upon Mary and she became pregnant with the Savior of the world? And if we would not deny His Personhood at that moment, why would we deny any baby's personhood whom Jesus Himself brothered by His own conception?

Theologian Thomas F. Torrance writes:

The Son of God became a human being for us in the womb of the Virgin Mary, bone of our bone and flesh of our flesh. He became what we are. Think of the importance of the incarnation, then, for our understanding of and regard for the unborn child. Every child in the womb has been brothered by the Lord Jesus. In becoming a human being for us, he also became an embryo for the sake of all embryos, and for our Christian understanding of the being, nature and status in God's eyes of the unborn child. So, to take no thought, or no proper thought, for the unborn child is to have no proper thought of Jesus himself as our Lord and Savior or to appreciate his relation as the incarnate Creator to every human being.[^68]

Consider this account written by the physician Luke, found in the first chapter of his gospel. There we read that the angel Gabriel told the Virgin Mary:

Do not be afraid, Mary; for you have found favor with God. And behold, you will conceive in your womb and bear a son, and you shall name Him Jesus.

The angel tells Mary, "you will conceive in your womb." She hasn't yet conceived, but at some point in the future, she "will."

Mary asked how this could be, since she was a virgin. The angel explained:

The Holy Spirit will come upon you, and the power of the Most High will overshadow you; and for that reason the holy Child shall be called the Son of God.

At some point in the future, the Holy Spirit "will come upon" her, and "the power of the Most High will overshadow" her. Again, at some point in the future these things "will" be accomplished. It's as certain as every word of God, but its accomplishment is not yet. The holy Child "shall" be called.

Jesus will be fully man, but is not yet. The prophecy has been given, but it has not yet been fulfilled. His taking on manhood through His conception is still in the future.

Then Gabriel strengthens Mary's faith:

And behold, even your relative Elizabeth has also conceived a son in her old age; and she who was called barren is now in her sixth month. For nothing will be impossible with God.

After this shocking announcement that her relative Elizabeth has miraculously conceived and is in her sixth month, we read Mary declaring her submission to God's will, after which the angel Gabriel leaves her.

Then what?

Now at this time Mary arose and went in a hurry to the hill country, to a city of Judah, and entered the house of Zacharias and greeted Elizabeth.

We aren't told where Elizabeth and her husband Zacharias lived---only that it was a city of Judah in "the hill country." We're also told as soon as the angel left her, Mary arose and "went in a hurry" there. When did the Holy Spirit come upon her, and the power of the Most High overshadow her, so that the embryonic Savior indwelt her? Sometime between Gabriel's announcement that she would (future tense) become pregnant and her arrival and entry to Elizabeth's house there in the hill country. How do we know she was pregnant when she arrived?

Because of this account of her arrival, also by the beloved physician Luke:

When Elizabeth heard Mary's greeting, the baby leaped in her womb; and Elizabeth was filled with the Holy Spirit. And she cried out with a loud voice and said, "Blessed are you among women, and blessed is the fruit of your womb! And how has it happened to me, that the mother of my Lord would come to me? For behold, when the sound of your greeting reached my ears, the baby leaped in my womb for joy."[^69]

There it is: "blessed is the fruit of your womb!" Mary is now pregnant. She is now bearing fruit. She is now "the mother" of our Lord.

How old is our Lord at this moment?

Our best guess is somewhere around a week of age. We're not sure Mary left to visit Elizabeth the same day she received the prophecy. She may have left a day or two later. What we do know is that as the angel Gabriel left her, it was "at this time" that she "arose" and "went in a hurry." Various guesses are made about the town Mary traveled to and its distance. If we accept church tradition, the village was Ein Karem, about eighty miles from Nazareth, so it took Mary about a week to get there.

If our Lord took up His embryonic residence in Mary's womb immediately upon Gabriel's departure, right as Mary began hurrying to Elizabeth's home, Jesus was likely somewhere between seven and ten days old. If Mary conceived our Lord halfway through her journey, Jesus was likely somewhere between three and seven days old.

Stop and consider that little ones normally take five or six days to implant themselves on the wall of their mother's uterus. It's possible then, and maybe even likely, that as His mother traveled, Jesus did also, moving towards the rest, safety, and nourishment of attachment to Mary's womb.

Jesus brothered us at conception. Not any time later. Not at implantation. Not at quickening. Not at birth. His conception, no less than His implantation, quickening, and birth, redeemed our own conception, no less than our own implantation, quickening, and birth.

There is no place for the follower of Jesus Christ to kill any human being at any stage of life which He, our Lord Jesus, blessed by living it with and for us. No Christian kills an embryo any more than he or she kills a newborn baby with Down syndrome or an elderly parent who's had a stroke.

We protect the weak and vulnerable. We do not kill them.