## The Body Count

Coming face to face with the lies and bloodshed, we can't help seeking to quantify the slaughter around us. What is a truthful estimate of the number of little ones we have sacrificed through abortion since the 1950s and '60s?

As Christians and pro-lifers in general have tried to come to terms with the slaughter of the twentieth and twenty-first centuries, it's become commonplace to speak in terms of large figures that boggle the mind, but even the most informed pro-lifers today speak only of "millions" of babies lost. Anything larger seems needlessly inflammatory, and "billions"? Surely not . . .

Let's take a count of the victims of our bloodshed.

### Surgical and Chemical Abortions

Back in 1999, Planned Parenthood's research arm, the Guttmacher Institute, published "The Incidence of Abortion Worldwide," in which they stated, "Worldwide, about one-fourth of the approximately 180 million pregnancies known to occur each year are resolved by abortion."[^70] At the time, this would have been 0.75 percent of the world's population killed each year, but this was decades ago.

Acknowledging the growth of abortions worldwide across the past twenty years, a 2020 article in *The Lancet* estimated that between 2015 and 2019 the yearly average of abortion victims had increased to 73 million---0.98 percent of the world's population.[^71] At this rate, it takes thirteen and a half years to reach a billion. Meanwhile, keep in mind that abortions have been common in Russia and Eastern Europe since the early fifties, and the United States since the seventies.

China is unique due to their longtime enforcement of population control. From 1980 through 2016, the Chinese government worked to reduce their nation's birth rate by limiting most married couples to one child.[^72] They enforced this policy by forcibly aborting mothers' babies[^73] so that, from the adoption of China's one-child policy in 1980 through the government's repeal of the policy on January 1, 2016,[^74] China's Health Ministry revealed it had done 336 million abortions.[^75] During those years alone, China committed one-third of a billion abortions.

From statistics compiled over the years, the Guttmacher Institute now places the number of babies murdered at 1.6 billion (and no, they don't call it "murder"). Yet if we examine this abortion count more deeply, it becomes clear the Guttmacher Institute's numbers are still drastically underreported.

### Accounting for Hormonal Birth Control and IUDs

Recall how prevalent hormonal birth control methods are across the world and that one of their agencies is preventing implantation. How many deaths of little ones due to this agency of hormonal methods have occurred in the world since 1950? Let us consider all hormonal methods including pills, injectables, implants, IUDs, and emergency contraceptive pills (ECPs).

To enforce its one-child policy, not only has China engaged in forced abortion, but government authorities have implanted IUDs in their nation's women so that, as the *New York Times* reports, "from 1980 to 2014, according to official statistics, 324 million Chinese women were fitted with IUDs."[^76] Those 324 million IUDs prevented countless births by obstructing little ones from attaching themselves to their mother's womb. What was the death toll in China?

But beyond China and IUDs, recall how prevalent hormonal birth control methods are across the world. Can we estimate how many women lost their babies through these birth control methods since their normalization in the 1960s?

Because current and hard data is not available on these questions, we must take recourse to some estimates to get an idea of the order of magnitude we should think about. Let's start with the Pill. In 1999, Dr. William F. Colliton reported data from the Guttmacher Institute indicating that 10.4 million women were using the Pill in the US.[^77] Based on 28-day cycles and a 14 percent chance of an ovulation occurring for women taking the Pill, this would imply 18.95 million exposures to pregnancy per year. Taking into account the likelihood of spontaneous abortions, Dr. Colliton estimated that the number of abortions induced by the Pill making the womb less hospitable for fertilized eggs to between 1.1 million and 1.9 million per year. He also reported a more cautious estimate based on a 20 percent fecundity rate that put the number of Pill-induced abortions to between 0.1 million and 1.6 million per year.

More recent CDC data indicate that currently about 10.2 million women in the US take the Pill.[^78] Based on a pregnancy rate of 85 percent for women using no birth control and 9 percent for women using the Pill, 76 percent of these 10.2 million, or 7.7 million would have become pregnant in a given year had they not used the Pill nor any other birth control method.[^79] Given that the Pill reduces the frequency of ovulation by 57.4 percent to 98.75 percent,[^80] the loss of births due to the reduction of ovulation frequency would be between 4.4 million and 7.6 million. If the remaining losses of births are caused by the abortifacient effect of the Pill, the number of induced abortions would be between 0.97 million and 3.3 million. This corresponds to between 0.0095 and 0.33 Pill-induced abortions per woman taking the Pill every year. This means that a woman using the Pill runs the risk of unknowingly killing one of her children between once in three years and once in one hundred years.

According to United Nations data, 152.1 million women of childbearing age around the world were taking the Pill in 2018.[^81] Applying the US estimate, the number of Pill-induced abortions would range between 1.4 million and 50.2 million annually. We emphasize again that these are rough estimates only. But they clearly show us that we are looking at a large phenomenon. Keep in mind that we are here talking only about the Pill. We have not included other hormone-based birth control methods such as injectables, implants, and IUDs which, in 2019, the UN estimated at 10 percent of the 60 percent of women of childbearing age employing "any method" of birth control. Nor does this estimate include ECPs (morning-after pills).[^82]

Considering all IUDs (inert, copper, and hormonal), each has post-fertilization effects preventing pregnancies.[^83] These work by preventing the fertilized egg access to the endometrium, prohibiting the little one's attachment there. Stanford and Micolajczyk estimate that the post-fertilization effects of inert IUDs inhibit implantation in 99.1 percent of all cases of fertilized eggs. For copper and hormonal IUDs their estimates vary between 99.1 percent to 99.5 percent and 99.8 percent to 99.95 percent, respectively. Thus the post-fertilization effects are very powerful, and they must be, given the relatively large rate of fertilizations per cycle (15.6 percent for inert IUDs, 4.1 percent to 8.1 percent for copper IUDs, and 14 percent for hormonal IUDs) on the one hand, and the low rate of pregnancies of women wearing IUDs on the other. The authors estimate that 0.72 to 1.97 fertilized eggs fail to implant per woman wearing inert IUDs per year. For copper and hormonal IUDs, the corresponding numbers are 0.19 to 1.04 and 0.19 to 1.82, respectively. That is, women wearing copper IUDs are likely to effectively abort a child between once a year and once every five years. Women wearing hormonal IUDs are likely to abort a child between every 6.6 months and every five years.

According to UN data released in 2019, 8.3 percent of the 74.7 million women of childbearing age in the US (6.2 million women) were using IUDs of some kind.[^84] Taking the above numbers, the implied annual loss of fertilized eggs (little ones bearing the image of God) due to the post-fertilization effects of IUDs in the United States alone would be between 1.18 million (if all IUDs were copper and the low estimate prevails) and 12.2 million (if all IUDs were inert and the high estimate prevails).

Let us reiterate that these estimates are the number of lives lost in the US each year merely from the abortifacient agency of IUDs, and that no estimates of the death toll from prevention of implantation after conception are ever included in any organization's reports of numbers of abortions. Their statistics are only the number of babies killed after those babies have survived through implantation.

### Accounting for In Vitro Fertilization

Now consider the death toll from IVF.[^85] Here, the true cost of human life in this process is again hidden by definitions of conception and the use of medical jargon, but the Human Fertilisation & Embryology Authority (HFEA), an organization in the United Kingdom that is responsible for regulating the practice of IVF throughout the UK, reported to Parliament that from August 1, 1991, to December 31, 2011, 3,546,818 embryos were created. Of these, 1,714,570 were "discarded," i.e., thrown away like trash (whether because they died in the lab, or for reasons of quality, or for reasons of eugenics, the report does not say). Meanwhile, 5,876 embryos were frozen with the intent to give them to research (a sentence of death), while 841,396 were frozen for future use. Only 1,388,443 of the created embryos from this period were "transferred" to a womb, thus creating a pregnancy.[^86] For a nearly coterminous period---1991 to June 30, 2010---the HFEA reported that 101,605 embryos were given for research---again, a sentence of death.[^87] When we put the numbers together from these slightly diverging time periods of embryos discarded or given for research, the death toll for this twenty-year period comes to 1,816,175. But this death toll is not yet complete, as we will see.

According to the 2012 annual report of the HFEA, "In the UK, 224,196 babies were born after IVF treatment between 1991 and 2011."[^88] Subtracting the number of babies born from the number of embryos transferred to a woman's womb, we see that 1,164,247 embryos died during pregnancy.[^89] This plus the previous death toll gives us 2,980,422 dead little ones. Simplifying this data, the numbers indicate that for every one baby born via IVF in the UK between 1991 and 2011, roughly sixteen embryos were created. Of these sixteen, nine were "discarded," five died during pregnancy, one was frozen, and one was born.

Getting an exact number of how many children have been sacrificed and placed in "concentration cans" worldwide through IVF is difficult. In 2018, the International Committee for Monitoring Assisted Reproductive Technology reported that more than 8 million IVF children had been born since IVF's introduction in 1978.[^90] When we consider that the UK's practice of IVF is very well-regulated in comparison to, for instance, that of the United States,[^91] it is hard to accept a ratio of one child born to sixteen children created, or a ratio of one child born to fourteen children dead, as a realistic ratio for the entire world---the actual ratio is likely to be significantly worse. But accepting it for the sake of an estimate, we find that 8 million IVF children born means that 128 million IVF children were created, 112 million were killed outright or died, and another 8 million were frozen to await one fate or another. That makes 120 million children conceived through IVF who were not born, from 1978 through 2018.

### The Total

Based on the reporting of *The Lancet* that abortions worldwide have increased to 73 million (0.98 of current world population) per year, and assuming the accuracy of the Guttmacher Institute's statistics on world abortions presently totaling 1.6 billion, we conclude that, by 2027, the little ones slaughtered after their survival of implantation will be greater than 2 billion.

Now stop and consider how many little ones aren't included in *The Lancet* and Guttmacher Institute totals. How many babies have been frozen or killed through in vitro fertilization? How many babies have been killed by IUDs preventing their implantation? How many babies have been killed by mothers using the 255 forms of hormonal birth control sold by pharmaceutical firms and reviewed on Drugs.com?[^92]