## Conclusion: Genocide

To summarize, the twentieth century has seen mankind keep descending down into the moral abyss of bloodshed which started with world wars, moved to world wars targeting civilians, then to governments targeting their own countrymen; and finally, to fathers and mothers waging war against their own sons and daughters. At each stage of these changes in the method and scale of the killing, the number of deaths multiplied so that, now, the death toll of our war on unborn babies dwarfs the combined death tolls of all these previous bloodsheds. Mankind today has turned inward against himself, devouring his own offspring.

How do we reckon with such unspeakable horrors? Are there words able to convey such savagery? Are there texts of Scripture revealing the Almighty's hatred of such wickedness and the certainty of His coming judgment of those who have committed such crimes?

Living in a day puffed up with the pride over its concern for what it speaks of as "basic" or "fundamental" human rights, we must puncture this pride with such firm conviction and will that those who hear us may never lie to themselves again concerning their pursuit of "social justice" or "compassion," nor of their being in any way righteous because of any stand they have taken against systemic evils. A good beginning to the destruction of this pride can be accomplished by applying a label to the slaughter of the unborn which has been avoided before this present time.

From Greek *genos* ("birth, race, kind") and Latin *caedere* ("kill"), this word has long been used to refer to the slaughter of a group distinguished by ethnicity or nationality. Age, though, is a parallel category to race and ethnicity. Further, unborn children are, in fact, distinguished by specific physical characteristics, being housed and protected within their mothers' wombs. From here on out, we must make it a habit of speaking of the intentional destruction of unborn children as *genocide*.

Some might cavil that there is no widespread targeting of unborn children *in toto*, but rather only those children in specific circumstances. But even granting the premises of such a wicked counterargument does not nullify the argument we make here. Genocide does not require the intention to kill *all* members of the *genos*, but only the intentional targeting and killing of members of that class *as such*.[^93] Note this resolution by the UN General Assembly back in 1946, whose concepts became cornerstones of international law regarding genocide:

Genocide is a denial of the right of existence of entire human groups, as homicide is the denial of the right to live of individual human beings; such denial of the right of existence shocks the conscience of mankind, results in great losses to humanity in the form of cultural and other contributions represented by these human groups, and is contrary to moral law and the spirit and aims of the United Nations.[^94]

The cornerstone of child murder today is a denial of unborn babies' right to existence. It "shocks the conscience" of those consciences not yet deadened to it. It causes unthinkable "losses to humanity" in the potential it snuffs out, and it is certainly contrary to the moral law of God.

This is genocide, and we, the people of God, must acknowledge our complicity and participation in it.

No doubt Asia's long history of the bloodshed of its children is a consequence of the East's commitment to false religion across thousands of years. But let us examine the West.

Within the pagan idolatry of the ancient Roman Empire there was no question of the absolute authority of the father of the household over the life and death of his children. Called *patria potestas*, this power enabled fathers to throw their children on the hillsides, exposed there to die. This was the context of the New Testament church as it grew in its first few centuries, and in time the witness---the salt and light of the church---first caused these little ones who were the cast-offs from pagan idolatry to be rescued and adopted by Christians, then caused this horror to be outlawed as Christendom displaced the immoralities of paganism.

For most of the past two thousand years, Christendom has been identified by this same love and protection of the weak and defenseless---particularly children. Now though, we find the West hell-bent on flipping every godly commitment of Christendom upside down, starting with its former protection of those on the margins of society. Nor have we ever been as hell-bent on this reversal as in our return to the slaughter of children. The slaughter of children pervasive across our world today could not possibly be more of a rejection of the Christian faith.

What is the moral responsibility of the church in this?

Christians know the truth that life begins with conception. God blesses a husband and his wife with the fruit of the womb and that fruit bears His own image and likeness from the moment of conception. From that point forward, all the little one needs is his mother's womb. Christians know (or have no excuse for not knowing) that we kill that little one when we obstruct his implantation. (And those who claim ignorance are helped by this present document, which is part of its purpose.) Christians must never lie about murder. Christians must never dissimulate about bloodshed. Christians must move heaven and earth to avoid placing a stumbling block in the path of just one of our Lord's little ones.

So now, how do God's people stand in the presence of God and worship Him given a death toll for abortions this past century that is surely in the billions? Given that our ground is saturated by blood?

Do not defile yourselves with any of these things; for by all these the nations are defiled, which I am casting out before you. For the land is defiled; therefore I visit the punishment of its iniquity upon it, and the land vomits out its inhabitants. (Lev. 18:24--25)

So you shall not pollute the land where you are; for blood defiles the land, and no atonement can be made for the land, for the blood that is shed on it, except by the blood of him who shed it. Therefore do not defile the land which you inhabit, in the midst of which I dwell; for I the [Lord]{.smallcaps} dwell among the children of Israel. (Num. 35:33--34)

As we live and God's patience remains, we may repent; and repent we must. It is our prayer that, through this paper, all of us who belong to God will turn and rend our garments and throw ashes on our heads in repentance.

In this section we have opened up our bloodlust. Now, we must hear again the decrees of God against it, found both in His Word and in nature as created by the Word Himself. As churchmen, as magistrates, and as men, what must we do to repent of this wickedness so that God may see fit to renew our minds and hearts, restoring to us and our children His law, His perfections, and His love for little ones?

May God, who alone hath the power, inscribe these teachings on the hearts of those who hold sway over the Christian world. May He grant to them a mind possessing knowledge of divine and human law, and having ever before it the reflection that it hath been chosen as a servant for the rule of man, the living thing most dear to God.[^95]