# Chapter 2. Abortion's Assault upon God's Character and Law

Our purpose here is not to provide an exhaustive treatment of the moral issues surrounding abortion. Such a work would fill volumes. Yet in the spirit of saying *something* so that we be not silent,[^96] we provide here some limited accounting of the moral harm caused by abortion. Any of these examples of abortion's moral harm is sufficient to demonstrate to tender Christian consciences the wickedness of abortion. Taken together, these examples expose the monstrosity of this sin.

## A. Moral Arguments

From birth to death, every man knows that to kill another man is a crime against man and God. Scripture and history provide irrefutable evidence that God has written this law on every man's heart. This testimony of man's conscience is ineffaceable. Indeed, even the national, state, and local battles fought over abortion during the twentieth and twenty-first centuries bear witness to the testimony of the Spirit of God against this form of murder. Despite the corruption of man's fallen nature, the horrors of this crime against the little ones cry out against us.

### Overthrowing Our Creator's Command against Murder

To murder has always been a great wickedness. From Creation, all races, nations, and societies have recognized that, if any crimes exist, murder is the most fundamental. Abortion is no exception.

### Denial of the Right to Life

Abortion denies the most fundamental right God has given man, which is the right to live. For centuries, arguments have raged over the nature and extent of man's right to live, and in what judicial cases man forfeits that right. What has been undeniable under the rule of law of the Western world is that no individual may decide whether another lives or dies. That prerogative is one owned solely by God and those institutions to whom He delegates the sword in the exercise of justice.

Yet in 1973---and quite suddenly---the Supreme Court of the United States declared the laws against murder by abortion null and void---laws which were, at the time, written on the books of almost every state of the Union. Planned Parenthood records the change enforced by *Roe v. Wade* this way:

*Roe* has come to be known as the case that legalized abortion nationwide. At the time the decision was handed down, nearly all states outlawed abortion except to save a woman's life or for limited reasons such as preserving the woman's health, or instances of rape, incest, or fetal anomaly. *Roe* rendered these laws unconstitutional.[^97]

This federal reversal of states' laws was unprecedented and led to an embarrassing dilemma among physicians. Sadly, like most Americans of the time, the medical establishment raised no outcry over the newly invented right of mothers to kill their babies. Now that this right had been created, the question remained: Who would carry out these murders?

At that time, the nation's physicians had been initiated into the practice of medicine by taking the Hippocratic Oath, part of which read:

I shall never give a deadly drug (*pharmakon*) to anyone if asked, nor shall I recommend such counsel; and likewise I shall not give a woman a pessary for an abortion.

With purity and in accordance with divine law I will keep my life and my art.[^98]

The Hippocratic Oath originated two and a half millennia ago, and it represented the most basic commitments of physicians in their practice of the healing arts. So, when *Roe v. Wade*'s new mandate came down, it raised the question whether physicians would continue to honor their oath. Or, would they begin to accept money in payment for "causing an abortion"?

There was never any significant debate. Doctors across our nation began to break their oath and take money from mothers seeking doctors' assistance in killing their little ones. To clean up the mess, the Hippocratic Oath was sometimes edited and sometimes removed from physicians' initiation rites.

### The Removal of Woman's Moral Agency

Abortion also required the diminishment of woman's moral agency. At the heart of personhood is individual responsibility for one's own deeds. The rule of law flows from this individual moral agency. Whether in the workplace, government, church, or family, the rule of law holds every man and woman accountable for his actions. The roofer is accountable to put on a roof that doesn't leak. The lawyer is accountable to provide his client truthful counsel. The judge is accountable to issue just judgments that do not abandon the meek and lowly to oppression by the sleek, rich, and educated. The pastor is accountable to keep his sheep's blood off his hands by speaking to them precisely what God commands.

Concerning moral agency, feminism had long argued that male authority diminished female responsibility. Feminists declared it would only be when male authority was brought to an end that women would possess full personhood equal to men, and thus bear the full weight of the consequences of their actions. They must be granted self-determination and freedom to choose. Only when this equality was established could women be said to have the same moral agency as men. These themes are constant across feminist and pro-abortion literature of the past fifty years.

When feminists promoted abortion, though, they set this claim aside. No mother was to be judged for procuring the murder of her child.

Today, the male authority that God established when He created Adam first, then Eve, has been repudiated, and yet it is notable that mothers who pay doctors to murder their little ones are viewed as the victims of their boyfriends, husbands, fathers, or a patriarchal society. If there is any moral judgment involved in any abortion, it is the condemnation of bad men who force good women to kill their children. Society is condemned for robbing women of power and self-determination, forcing them to commit bloodshed in order to establish their power and self-determination. Personhood begins with freedom of choice, and what freedom of choice do women have if they are unable to rid their own bodies of these parasites clinging to their wombs? In fact, the ability to choose abortion is said to be central to women's self-determination. Women cannot truly be free and equal until they are granted this fundamental freedom of choice. Feminists demand that their sex's life-givingness[^99] must be subject to the mother's choice whether or not to allow this life God has placed in her to continue. This is necessary to establish women's equality and personhood.

This is the grotesque reasoning feminists have used to reduce mothers to the very status they had previously condemned. In order to gain moral agency on a par with men, feminists demanded women be granted the right to kill their children. And yet, if women exercised this right, they were to bear no guilt for it. Rather, they must be judged to have killed their children under compulsion. They are free of any responsibility for the murder of their little ones they paid to have killed.

But when guilt is denied, repentance is also denied. What is purportedly done from respect for women results in barring women from confessing their sin to the holy God and receiving forgiveness through the mercy and love of God in Jesus Christ. If women commit no crime subject to man's law when they kill their babies, the only logical conclusion is that women who kill their babies commit no sin subject to God's law either.

Women must not seek God's forgiveness for shedding the blood of the children God gave them as His blessing, and the civil authorities must enact no laws testifying to their maternal bloodguilt. The woman has, in effect, become what the feminists feared: a non-agent, functioning only as the victim of male figures in her life, denied any responsibility for her own actions.[^100]

Yet why should this be so? After all, the man who beats his wife or children is responsible for the harm and suffering he causes the members of his household. Equally so the woman who beats her husband or children: she too is responsible for the harm and suffering she causes her intimate family members. If a father rapes or murders one of his children, no prosecutor, court, judge, or jury will hesitate to punish him for his crimes. Equally so the mother who rapes or murders one of her children: any just society will demand her trial and punishment, and the judicial system will carry out this difficult work.

Why, then, have eighty-three pro-life leaders of national and state organizations issued a press release opposing any laws to "punish" mothers who kill their preborn children? Their press release was issued in the weeks following *Politico*'s leak of Justice Alito's draft opinion in *Dobbs v. Jackson Women's Health Organization*, and it was drafted and signed by the leaders of organizations including the Ethics and Religious Liberty Commission of the Southern Baptist Convention, the US Conference of Catholic Bishops, Americans United for Life, the Faith & Freedom Coalition, Life Issues Institute, the National Association of Pro-Life Nurses, and the National Right to Life. The letter reads:

**Women are victims of abortion and require our compassion and support** . . .

**As national and state pro-life organizations, representing tens of millions of pro-life men, women, and children across the country, let us be clear: We state unequivocally that we do not support any measure seeking to criminalize or punish women and we stand firmly opposed to include such penalties in legislation.** . . .

We understand better than anyone else the desire to punish the purveyors of abortion who act callously and without regard to the dignity of human life. But turning women who have abortions into criminals **[is not the way.]{.underline}**[^101]

While it is true women and men other than the baby's mother usually share the bloodguilt of the murder of the preborn, it remains hard to fathom this denial of the moral agency of the women who most often are the ones who actually pay for the drugs or surgery to kill their baby. Wise Solomon recognized the mother who wanted the baby dead to be the evil moral agent in the dispute, and penalized her for it.[^102] Was Solomon wrong?

How have we come to think so lightly of the minds, consciences, and souls of women, that we issue statements absolving them of any responsibility for their murder of their own children? Do these pro-life leaders claim to speak for God in their dispensing this public absolution to mothers who have aborted their preborn children?

No murder is hidden from God. Every one of us will soon give an accounting for our bloodguilt on that Final Day of Judgment, when the secrets of all men will be revealed before the Great Judge Eternal. It is of the essence of the gospel message preached by John the Baptist, Jesus Christ, the Apostles, and every gospel witness down through two millennia of church history to "flee the wrath to come." How then can those professing faith in Jesus issue public statements that women who have murdered their preborn children are merely "victims of abortion" who "require our compassion and support," and that they are adamantly opposed to any law which would declare these women "criminals"?

To be sure, these post-*Roe* days will require wisdom in the writing and debate over states' abortion legislation. No two states are alike, and civil authorities of each state will bear the responsibility of decisions concerning who should be held accountable for the shedding of these little ones' blood, as well as how, when, and in what way. Given a particular state's demography, it may be wise not to use the force of law against mothers who buy the murder of their preborn children. Nevertheless, no follower of Jesus Christ should ever declare moral or criminal absolution concerning such mothers. God will judge us, and it is no kindness for any leader to declare that those bearing bloodguilt are only "victims" of this abortion they have purchased, and that no one should "punish" them.

On the other hand, assuming such pro-life leaders are successful in their attempts to stave off any criminalization or punishment of mothers who abort their little ones, the truth always held precious by the church of Jesus Christ remains with us today---to proclaim repentance for the forgiveness of this sin too, as also every other form of wickedness:

\[Jesus\] said to them, "Thus it is written, that the Christ would suffer and rise again from the dead the third day, and that repentance for forgiveness of sins would be proclaimed in His name to all the nations. (Luke 24:46--47)

The path forward from the bloodguilt of abortion is not claiming victimhood and denying one's moral agency, but acknowledging our guilt and fleeing to the cross of Jesus Christ for His forgiveness. Those of us who love Jesus have done the same (and continue to do so daily) and will welcome you into the household of faith, the church of the Living God.

### The Death of the Conscience

Mother Teresa of Calcutta used to say there are two deaths in every abortion:

The mother herself kills, destroys, murders her own child. Created by God Himself for greater things: to love and to be loved. Created in the image of God. Created to be His presence in the world today. I mean destroying. And in killing that living reality of the tenderness of God's love, the mother kills two: the child and her (own) conscience. For life she will know she has murdered her own child with her own decision.[^103]

God's moral law is written on each man's heart so that our conscience testifies to each of us what ought and ought not to be done. When women and men act against their conscience, particularly on an issue of such gravity, they sear their conscience and leave it on life support.

Despite all the supposed evidence denying the suffering of mothers who choose abortion, the murderess bears her guilt and shame for the rest of her life. Grievous (and often, repeated) sin of this nature can so harm the conscience that it ceases to function. Such a woman has lost not only her child, but God's gift of knowing what sin she has committed. For herself, her family, and her society, this grave evil gives birth to grave consequences among all those who know and love her. They may not know the cause of her moral disease, but they suffer it along with her. As one example, the children she chooses to give birth to end up being her *wanted* children, and they too suffer guilt and shame, sometimes called "post-abortion survivor syndrome."[^104]

We must not allow our bloodlust to fool us:

Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap. For he that soweth to his flesh shall of the flesh reap corruption; but he that soweth to the Spirit shall of the Spirit reap life everlasting. (Gal. 6:7--8, KJV)

## B. Natural Law Arguments

All creation declares abortion's ingratitude and rebellion against our Creator. But men make science their god and mock God's truths, so we are tempted to retreat within the walls of special revelation, consigning the natural world and its scientific investigation as a pagan domain. This is a grave mistake. Natural revelation is a key part of knowing and understanding God. God's book of nature helps us to know *what* He has done and *how* He works among us. Indeed, Scripture itself teaches us to ask, "Does not even nature itself teach you?" (1 Cor. 11:14).

Those truths proclaimed by nature must not be abandoned in favor of those truths revealed by Scripture.[^105] Nature is a handmaid to Scripture. It too reveals the character of God, at times in areas Scripture does not. Sacred Scripture is infallible, yet not all texts of Scripture are spoken with equal clarity; where Scripture is unclear, the book of nature helps us evaluate what interpretations of God's Word are most sound.[^106] Some of our fallible understandings of Scripture need refinement by nature.[^107] Properly understood, natural revelation cannot contradict special revelation.[^108] Any conflict between natural and special revelation, then, is due to some error in our interpretation of either (or both).

Conversely, when both of God's spheres of revelation address a matter, we do well to take special heed. Thus we here state that our condemnation of abortion is not only based on God's written moral law, but also God's book of nature. Together they bear unanimous testimony against the monstrosity of this crime.

[]{#_Toc106897061 .anchor}Man as Unique Creation

Scientific research shows that, from the moment of conception, the unborn child possesses all the genetic information that distinguishes him from any other created species or being. The unborn child conceived in his mother is not a tree, monkey, or tumor.[^109] He is a human being bearing the image of God with forty-six chromosomes and the DNA that sets him apart from the rest of creation. He is demonstrably different from either his father or mother, with DNA drawn from both of them. He is a unique human being.

As detailed earlier, physicians have tried to change the definition of *conception* from fertilization to successful implantation in the mother's womb. But this change makes a mockery of science and reason. The safe attachment of the child to his mother's womb does not change him in any way. There is no scientific or rational reason why implantation should define the beginning of life or qualify that life for protection. It is true that, from implantation, the little one's reliance on his mother for nourishment increases, but this increase does not bear on his right of protection. Indeed, such an argument contradicts one typical argument for abortion "rights"---namely, that one person dependent on another is *less* deserving of protections and rights. What a callous response to the interrelatedness of life, and specifically the charity God commands between us in light of His charity toward us!

[]{#_Toc106897062 .anchor}Personhood from the Beginning

If, for the sake of argument, we grant that the personhood of the human embryo is not yet proven to exist at fertilization, arguments based on this irrational supposition still fall flat. For, in order to justify the moral rectitude of abortion at any point, one would need to establish that there is no possibility of the abortion killing a person. Yet it is impossible to demonstrate the newly conceived embryo lacks personhood. Indeed, all the evidence is to the contrary.

Again, if for the sake of argument we were to accept this irrational premise, it would immediately leave us asking at what stage of later embryonic development personhood is acquired? At what stage does what is not man somehow become man?

The irrationality of this project is clear to everyone who has not allowed himself to become a bloody ideologue. This little one is a living human being when he emerges from his mother's womb because he is a living being at the moment when his life *qua* human begins---always and forevermore at conception.

Yes, we can muddy the waters by raising abstract, speculative questions on ensoulment, personhood, or quickening, desperately working to deny that conception is the beginning of life. But why such intensity in our efforts to deny protection to these little ones? The truth is, throughout history, men (often with better intentions than our own) have discussed the mystery of how and when our heavenly Father "ensouls" an infant. Many of the church fathers wrote extensively on the matter, yet their opinions were never settled matters of dogma, in large part because Scripture does not directly address the topic.[^110] Nor did these theories cause the slightest hesitation in their condemning abortion as a grave sin from the moment of conception. In *Evangelium Vitae,* John Paul II puts it directly:

Some people try to justify abortion by claiming that the result of conception, at least up to a certain number of days, cannot yet be considered a personal human life. But in fact, "from the time that the ovum is fertilized, a life is begun which is neither that of the father nor the mother; it is rather the life of a new human being with his own growth. It would never be made human if it were not human already. . . ."

Furthermore, what is at stake is so important that, from the standpoint of moral obligation, the mere probability that a human person is involved would suffice to justify an absolutely clear prohibition of any intervention aimed at killing a human embryo. Precisely for this reason, over and above all scientific debates . . . , the Church has always taught and continues to teach that the result of human procreation, from the first moment of its existence, must be guaranteed that unconditional respect which is morally due to the human being in his or her totality and unity as body and spirit.[^111]

The church has always taught and continues to teach that abortion is the direct assault upon the providence and authority of God, our Creator.

[]{#_Toc106897063 .anchor}SLED Arguments

Many of the arguments employed by advocates of abortion can be divided into four categories referred to by the acronym SLED, referring to the Size, Level of development, Environment, and Degree of dependency of the preborn child.[^112]

1.  *Size:* Some argue abortion is justified because these little ones are beyond our view. It is permissible to kill the little one because he is too small to see hidden inside his mother's womb.

> Yet God's creation is full of small organisms and many of them have the protection of law and the sympathy of society, such as the world's smallest primate and smallest marine mammal. Shall we justify the killing of these organisms because of their size? On the contrary, it is much more grievous to destroy these little ones because of how tiny and defenseless they are. Only a monster would argue that the smaller and weaker the baby, the less claim that baby has on our protection.

2.  *Level of development:* Some argue the limitations of the child during his early development make it permissible to kill him. The unborn child can't feel pain, can't think, isn't self-aware, and is not yet sentient, so we may kill him.

> Yet science is proving the little one's sensitivity to his environment at younger and younger stages of his life in the womb.[^113] The limitations of development are irrelevant. One's right to life is not dependent on one's capacities to enjoy life or assert his personhood. Children or adults who suffer sickness, wounds, or genetic anomalies which leave them with limited capacities have as much claim to society's protection as those with no such limitations, both outside and inside the womb.

3.  *Environment:* Some argue the environment in which the unborn child exists invalidates his right to be considered human. Since the unborn child doesn't, for example, breathe air, he is sufficiently "other" so that he deserves no protection.

> Of course, the same argument would never be made concerning residents of the South Pole or the International Space Station. Neither of those locations can sustain life naturally without the provision of extraordinarily complicated and costly artificial supports. The same can be said concerning victims of polio who have, for decades, continued to live only by the support of an iron lung.[^114]

4.  *Degree of dependence:* Some argue the unborn child's dependence upon his mother undermines his right to the protection of his life.

> This argument is especially pernicious, for it strikes at the heart of one of the principal blessings God has ordained in human society, which is our interdependence. God has woven interdependence across His creation: the tree and soil, the citizen and ruler, the husband and wife, teacher and student, doctor and patient; and most preciously, mother and child.
>
> No man is an island.[^115] No man is independent. By arguing that dependence diminishes value, this argument also targets the handicapped, the elderly, the sick, the infirm, and anyone who depends on another for nourishment and care. This is the trajectory of the pro-abortion argument. This world of callous disregard for the weak and defenseless must be rejected.

[]{#_Toc106897064 .anchor}C. Societal Arguments

[]{#_Toc106897065 .anchor}Man as Social Being

God has ordained men to live, not to themselves, but in bonds of fellowship one with another, so that when one suffers, all suffer. This has been seen more clearly in recent days as the negative effects of isolation because of Covid have continued to make themselves known. As Calvin put it:

The human race has been joined together by a sacred link of community. . . . They are all next to \[*or*, neighbors to\] one another. To be our next \[neighbor\], it is enough for someone to exist as a human being, for we do not have the right to destroy our common nature.[^116]

Not coincidentally, the account of the first assault on God's gift of life committed by Cain, who murdered his brother Abel, records Cain's justification: "Am I my brother's keeper?" Cain was denying his obligation to love his neighbor. The answer implied by Cain given his question is, "No, I am not my brother's keeper." This is the heartless answer implicit in every violation of the second table of God's moral law: we are not our neighbor's keeper. No violation of neighbor-keeping, of loving our neighbor as we love ourselves, is more fundamental than robbing our neighbor of his very life.

God's condemnation of the manslayer Cain demonstrates the wickedness of Cain's self-justification. We are in fact our neighbor's keeper, and this sacred duty declared by God has governed all subsequent human society. By God's design, society is a fellowship of His image-bearers. Men are bound together in this mutuality. We have a large degree of freedom, yet that freedom is defined by the moral law requiring that we love and defend our neighbor.

Notwithstanding the corruption of man by Adam's Fall, human societies throughout history and across the world have enacted statutes against murder. From the Code of Hammurabi to the law codes of Draco and Solon to the Roman Twelve Tables to the laws of the Zhou Dynasty and the three constitutional principles of the Han Dynasty, man's societies have recognized that murder destroys the foundation of the consent under which men live together bound by law; and that, left unchecked, murder leads to disarray, anarchy, and ruin:

Protecting the life of the unborn child has been a major concern of the earliest laws known to us. It has continued to be an object of law-making in every subsequent civilization which has contributed to our own because it springs from a universal feeling which in the past has ceased to move men only when a nation was in decay.[^117]

When anyone kills another man (even himself) with whom we are bound in union, it is not a "personal decision," or a "reproductive choice," but an offense against all. And so it is with the unborn:

A choice cannot be private which affects another's life. The child in the womb has blood and brains, a respiratory system, a circulatory system, a urinary system that are not those of his or her mother. The child in the womb is not the property of his or her parent. The body of the child in the womb is not that of his or her parent. Sexuality may be private, reproduction may be private, but the taking of the life of the unborn cannot be private. It is a social act. Multiplied by 1 million times a year, it is a social act amounting to atrocity.[^118]

[]{#_Toc106897066 .anchor}The Loss of Potential

Much has been made in recent years of man's squandering of the earth's natural resources. But the resource with the most potential for the betterment and sustainability of human society is neither geological nor ecological, but anthropological. Man is the ultimate resource created by God, called by Him to "subdue" the rest of His creation.

God commanded us to subdue creation, and man's obedience to this command has been responsible for every advancement in law, medicine, politics, and art. Even conservation comes through man managing creation towards the betterment of mankind and the prosperity of the rest of creation.

Abortion, birth control, and contraception attack man's potential to bless all creation in this and other ways. To refuse God's blessings of children is to steal from future generations the benefits He has ordained we bequeath them. The loss of each child by that murder of abortion is the loss of immeasurable blessings which otherwise would rain down from heaven on our descendants. Perhaps that child would have been the next Jonas Salk, curing not polio, but cancer. Perhaps that child would have been the next Bach. The next Da Vinci? The next Martin Luther? The next George Washington Carver? The next Edison? Or even the next Fred Rogers?

Each of these men blessed multiple generations through those gifts God gave them. Are we not grateful their parents did not kill them? Are we not grateful they were conceived and born during a time when their societies still forbade mothers killing their unborn children?

[]{#_Toc106897067 .anchor}Economic Considerations

In their 2005 book *Freakonomics*,[^119] Steven D. Levitt and Stephen J. Dubner argued that the liberalization of abortion led to a significant reduction in the crime rate. Empirically, their argument was based on the observation that the crime rate in states that allowed abortion fell some fifteen years after the new legislation came into effect. Specifically, Levitt and Dubner argue that *Roe v. Wade* was the cause of the drop in crime rates in the early 1990s. The argument is simple and cynical: *Roe v. Wade* made abortions cheaper so that abortions became affordable to low-income women. Unwanted children of low-income mothers are more likely to be criminals later in life.[^120] Hence the benefit of *Roe v. Wade* is fewer criminals, fewer prison inmates, and thus a fiscal gain to society.

Apart from the fact that any correlation spanning over fifteen years is necessarily tenuous because there are a multitude of intervening factors that need to be controlled for, it is also completely inappropriate for the issue at hand. Levitt and Dubner say that "one study has shown that the typical child who went unborn in the early years of legalized abortion would have been 50 percent more likely to live in poverty" and in a single parent home.[^121] They do not indicate where that study was published. They go on, citing "another study \[that\] has shown that low maternal education is the single most powerful factor leading to criminality \[of the child\]."[^122] They don't bother telling the reader where this study was published and by whom. Did Levitt and Dubner make it up? Maybe. We don't know. In any case, two "studies" with no references and no explanation of data or methodology cannot be used to justify the deaths of some 750,000 human beings in the first year after *Roe v. Wade*.[^123] Far from being serious economists, Levitt and Dubner wrote a book to amuse their readers and themselves with absurd statements and they amused themselves with the deaths of millions of children.

Levitt and Dubner's argument is also flawed because abortion occurs not only among low-income classes. They would have had to show that after *Roe v. Wade*, abortions occurred *primarily* in low-income families. Yet we know that they occur in all income groups. We also know that abortions often cause mental harm---the treatment of which must be counted against what Levitt and Dubner seem to perceive as a fiscal benefit to US society.

How then should we look at the economic implications of abortion? For every economy today, it remains true that human beings contribute the most to economic well-being. In the US, the labor share (i.e., the percentage of annual value added that accrues to workers and proprietors as compensation for their work) is around 60 percent.[^124] It is slightly higher on average in the twenty most important economies of the world (the G20).[^125] This implies that every aborted child inflicts an economic damage on the US economy in the form of lost income.

Can we estimate that damage?

We begin by noting that the average productivity of an American is annual GDP per employed person, which was \$131,812[^126] in 2019.[^127] (We use data for 2019, since these are not affected by the Covid pandemic.) Next we calculate his or her average years in the workforce by multiplying Americans' years of age by their age-specific participation rates, i.e., the percentage of Americans in that age group being in the workforce.[^128] Then we multiply their years in the workforce by their age-dependent productivity, assuming that Americans' relative productivity over the life-cycle is reflected by relative weekly earnings over the life-cycle.[^129] Finally, we take the present value over their lifetimes; that is, we sum up their average productivity over the ages of their lifetime and discount the values after their first entry into the workforce. We assume an annual real (i.e., inflation-adjusted) interest rate of 4 percent, which is realistic for the US economy. This yields an estimate of average lifetime productivity and, therefore, an estimate of the economic loss to the US economy from aborting a child.

This number is 14.5 times the annual GDP per employed person, or \$1.91 million. This is the loss of economic wealth the US economy incurs due to an abortion in 2019. Take this times the number of aborted per year, which was 629,898 in 2019 according to CDC data,[^130] and you have the estimated economic cost of abortion. The result is a loss of wealth due to abortions in 2019 of \$1.2 trillion, roughly 1.1 percent of total household wealth in the US in 2019,[^131] or 5.6 percent of annual economic output in 2019. Clearly, abortion inflicts a serious economic damage on the US economy.

The discount factor obviously plays a large role in these calculations. In the above calculations, we assumed that there is no productivity growth over the lifetime of a person born today. This is clearly unrealistic in light of past evidence. Productivity growth effectively reduces the annual discount rate. If productivity grows at an average rate of 1 percent over the lifetime of the individual (conservative estimate), the relevant real interest rate falls to 3 percent and his lifetime production is 17.9 times annual production. The discounted value of an individual's lifetime production would be \$2.36 million.

Some people object to this, arguing that abortion is necessary to keep overpopulation in check. For example, Mumford and Kessel argued in 1986 that developed countries needed to maintain an abortion rate of 201 to 500 per 1,000 live births to keep their population growth rates close to 1 percent or less.[^132] Max Kummerow claims that opposition to abortion is today's equivalent of the Roman Catholic Church forcing Galileo to recant his claim that the earth revolves around the sun (which, incidentally, never happened).[^133] Kummerow argues that abortion should be regarded as a valid instrument of keeping population growth in check, which, he proposes, is necessary to assure that mankind does not deplete Earth's resources.

Such arguments seem plausible, but lack economic substance. Kummerow refers to the (in)famous "Meadows Report," published as *The Limits to Growth* by the think tank Club of Rome in 1972, as well as its update published in 2004.[^134] Both reports argue that unless mankind manages to reduce population growth by all means, the current economic system will collapse. The original report predicted that collapse would occur around 2010. It also predicted that the world would run out of crude oil by that time. Neither one has happened.

Why not? Because the authors of these and similar reports are engineers who do not understand economics. The economics of resource depletion is that when resources become scarce, their prices increase and this creates incentives in a variety of directions: economizing on the use of these resources, increasing the use of recycled materials, investing in new technologies to detect and exploit resource deposits. Today, the estimated time to deplete currently known crude oil deposits at current extraction rates is about forty to fifty years from now, very similar to what the 1972 report foresaw. In the developed world, the oil intensity of economic production, measured in terms of barrels of crude oil per \$1,000 of GDP, has declined by 56 percent since 1973.[^135] Because of the "green revolution," the development of more productive rice plants and other grains, there is no food scarcity in principle on earth today. The world's food supply in terms of calories per day per capita has increased by 34 percent between 1947 and 2018. Today's level of 2,928 calories well exceeds the daily need per person of 1,800 calories calculated by the Food and Agricultural Organization (FAO), a branch of the United Nations. Still, the FAO estimates that some 690 million people globally, or 8.9 percent of the world's population suffer from chronic hunger today.[^136] But they do so because they lack *access* to food, not because food itself is lacking. Human greed and hatred toward other human beings are the causes of hunger. This goes right to the heart of the Christian faith: 690 million people starve from a lack of brotherly love.

Overpopulation is not the problem. In fact, given today's state of agricultural productivity, the world could sustain a population larger by 62 percent. Even the wildest population forecasts do not foresee such an increase. Population growth rates have long been falling. To the best of our knowledge, the world's population will reach 10 billion by 2050 and then first stagnate and finally decline.

Obviously, then, abortion is not required to keep population growth in check and prevent a global hunger crisis. Ultimately, killing a baby is the most explicit expression of denying him access to food and all other parts of the comforts of life. Call it greed and hatred, if you wish. An economic rationale for abortion simply does not exist.

[]{#_Toc106897068 .anchor}Devaluing One Devalues All

In modern society, the rights of the underprivileged are top government priorities. Every good citizen will champion the unique gifts that these groups bring to society as a whole. Why does this not hold true for those being murdered in their mother's wombs? Why does society not hear their voices too? To speak bluntly about the hypocrisy, the very voices that vociferously condemn any slightest insensitivity toward the underprivileged are the same voices that aggressively promote the continuance of our slaughter of the unborn. The same voices known for denouncing the slightest indifference toward the plight of other underrepresented ethnic, racial, or socioeconomic minorities show not the slightest concern for that most underrepresented of all minorities, the unborn.

Keep in mind that devaluing the rights of others is a slippery slope. Those protections found in the United States Constitution are predicated on God's creation of men equal in His sight. Abortion denies this truth that is fundamental to the rule of law. Abortion disenfranchises an entire category of unrepresented across our society, consigning them to death. Our nation's fathers in past generations declared their slaves to be worth only three-fifths of other men in representation.[^137] As unjust as our past laws were, though, today we have decayed to such a morally degraded state that we say the unborn are worth nothing at all. Early twentieth-century laws were enacted to prevent "deficient" people from "breeding."[^138] Today, we have enacted laws denying the unborn birth itself.

How can any society that denies the rights of its unborn claim to value the rights of any other class of vulnerable persons? What madness is it that drives a society to protect a host of special people groups while decreeing the wholesale slaughter of its own children? Any society that refuses to defend its innocent and defenseless babies highlights the high hypocrisy of every other social justice it preens itself over. If unborn children are devalued, every other group is as well, and so are we all. Mother Teresa speaks truly:

America needs no words from me to see how your decision in *Roe v. Wade* has deformed a great nation. The so-called right to abortion has pitted mothers against their children and women against men. It has sown violence and discord at the heart of the most intimate human relationships. It has aggravated the derogation of the father's role in an increasingly fatherless society. It has portrayed the greatest of gifts---a child---as a competitor, an intrusion, and an inconvenience. It has nominally accorded mothers unfettered dominion over the independent lives of their physically dependent sons and daughters. And, in granting this unconscionable power, it has exposed many women to unjust and selfish demands from their husbands or other sexual partners. Human rights are not a privilege conferred by government. They are every human being's entitlement by virtue of his humanity. The right to life does not depend, and must not be declared to be, contingent on the pleasure of anyone else, not even a parent or a sovereign.[^139]

[]{#_Toc106897069 .anchor}The History and Destruction of the Unborn's "Right to Life" in the West

Today, any discussion of man's interaction with his fellow man in society introduces the notion of rights. This is true above all on the matter of laws, mores, and customs protecting unborn babies from being killed. For several hundred years now, Christian philosophers and theorists have recognized that God, as Creator and the Source of all political equity and liberty, has given man as the crown of His creation certain rights that flow from his identity as the crown of God's creation and possessor of the *imago Dei*. Chief among these is a right to life.[^140]

Yet a Christian must tread carefully here. In the last two hundred years here in the West, and with amazing speed in the late twentieth and early twenty-first centuries, rights have proliferated. Almost everything is declared a right: healthcare, housing, food security, education, euthanasia---even access to the internet. Perhaps compensating for the lack of substance to such claims, people declare almost anything desired a fundamental human right. With such a plethora of rights, the meaning of human rights has depreciated socially and morally.

Thirty years ago, an American legal dictionary defined "right" fairly accurately as follows:

As a noun, and taken in the *concrete* sense, a power, privilege, faculty, or demand, inherent in one person and incident upon another. Rights are defined generally as "powers of free action." And the primal rights pertaining to men are enjoyed by human beings purely as such, being grounded in personality, and existing antecedently to their recognition in positive law. But leaving the abstract moral sphere, and giving to the term juristic content, a "right" is well defined as "a capacity residing in one man of controlling, with the assent and assistance of the state, the actions of others."[^141]

This is a useful rendering of the meaning in several respects. First, one man's right always implies another man's corresponding duty. Second, not all rights are of equal importance. Third, natural rights (referred to in the definition as "primal") exist independently of and prior to recognition in man's law. In other words, man's law does not create or grant such rights; man's law can only discern and enforce them. Fourth, a man may invoke the state to vindicate his right against another man.

This meaning applies perfectly to the right to life. First, a man is obligated to avoid taking the life of another man unless justified by self-defense, just war, or the exercise of capital punishment. Second, the right to life is of paramount importance. Without life, it is impossible to exercise any other right. Third, God gives a man life, and thus a right to life that civil authorities must recognize and faithfully secure. In other words, civil authorities do not grant and cannot withdraw (unless justified) a man's right to life. Fourth, a man can invoke the power of the state to secure his life against harm from another man.

In the formulation of the American Declaration of Independence, government is instituted to secure a man's basic rights, including his right to life: "all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness. That to secure these rights, Governments are instituted among Men . . ."

We must recognize that a government itself violates the right to life when, having the ability to do so, it refuses to secure any man's life from dangers. When civil authorities neglect their duty to protect life on a mass scale over a long period, they nearly forfeit their reason for existence. Government, because of its obligation to defend the oppressed from the predator, shares culpability when it refuses to protect the unborn. It is not simply a matter of one private individual committing harm against another private individual. Some civil authorities themselves will be judged by God for their active sin of commission in legitimating abortion as lawful; other civil authorities will be judged for their sins of omission in failing to protect vulnerable unborn lives.

The Fifth Amendment to the US Constitution (ratified in 1791) protects the right to life: "No person shall be . . . deprived of life, liberty, or property, without due process of law." The Fourteenth Amendment (ratified in 1868) similarly protects the right to life from deprivation by the State: "nor shall any State deprive any person of life, liberty, or property, without due process of law."

British common law recognized an unborn child's right to life at quickening:

I. The right of personal security consists in a person's legal and uninterrupted enjoyment of his life, his limbs, his body, his health, and his reputation.

> 1\. Life is the immediate gift of God, a right inherent by nature in every individual; and it begins in contemplation of law as soon as an infant is able to stir in the mother's womb. For if a woman is quick with child, and by a potion or otherwise, killeth it in her womb; or if any one beat her, whereby the child dieth in her body, and she is delivered of a dead child; this, though not murder, was by the ancient law homicide or manslaughter. But the modern law doth not look upon this offence in quite so atrocious a light, but merely as a heinous misdemeanor.[^142]

Medical science and knowledge advanced in the 1800s, making it impossible to cavil that life begins at any time other than at conception. These advancements also included the introduction of anesthesia and instruments to make childbirth safer and less agonizing. The American Medical Association led the effort to strengthen legal protections of the preborn through state statutes codified in the mid- to late-1800s. These protections expanded the civil authority's criminalization of abortion to include the killing of the preborn before quickening---at any time after the moment of conception. These laws also punished the advertising and use of abortifacient drugs, which to that point had been advertised in many newspapers and kept for sale by local druggists in a wink-wink, under-the-counter manner. This progress in protection of preborn life was in keeping with the general acknowledgment that the common law had defects which needed correction.

*Bouvier's Law Dictionary*, a then-respected law dictionary published in its third revision in 1914, indicates that the legal profession had modernized (in the best sense of the word) its formerly antiquated and ignorant understanding of the beginning of a preborn infant's life. In other words, the legal profession had rejected that life began at "quickening":

It was formerly supposed that either the child was not alive until the time of quickening, or that it had acquired some new kind of existence that it did not possess before: hence the presumption of law that dates the life of the child from that time \[i.e., quickening\].

The child is, in truth, alive from the first moment of conception, and, according to its age and state of development, has different modes of manifesting its life, and, during a portion of the period of gestation, by its motion. By the growth of the embryo, the womb is enlarged until it becomes of too great a size to be contained in the pelvis, it then rises to the abdomen, when the motion of the foetus is for the first time felt.

Quickening as indicating a distinct point in the existence of the foetus has no foundation in physiology: for it arises merely from the relation which the organs of gestation bear to the parts that surround them; it may take place early or late, according to the condition of these different parts, but not from any inherent vitality for the first time manifested by the foetus.[^143]

In the latter third of the twentieth century, *Griswold v. Connecticut*, *Roe v. Wade*, and *Doe v. Bolton* abolished these legal protections through what one Supreme Court Justice White (dissenting in *Roe v. Wade*) called a "raw exercise of judicial power." Thus judicial fiat established the mother as sole arbiter of her preborn child's life. Ignoring over a hundred years of scientific knowledge and medical advancements, the Supreme Court's abortion opinions were a retrograde movement back to a more primitive and barbaric (if not sophistical and self-interested) belief about the beginning of life.

Now, in 2022, in God's kind providence the unexpected has come to pass, as a majority of the Supreme Court in *Dobbs v. Jackson Women's Health Organization* has finally recognized what has been patently obvious to all: the penumbras of *Roe* were a legal fiction designed to grant the murder of children the protection of law, and such judicial inventions should not be allowed to stand as precedent. Without question, the overturning of *Roe* is a victory to those who have fought for years to remove this stench of legal manipulation from the books.Writing for the majority, Justice Alito speaks truly:

We hold that *Roe* and *Case*y must be overruled. The Constitution makes no reference to abortion, and no such right is implicitly protected by any constitutional provision. . . .

. . . *Roe*'s defenders characterize the abortion right as similar to the rights recognized in past decisions involving matters such as intimate sexual relations, contraception, and marriage, but abortion is fundamentally different, as both *Roe* and *Casey* acknowledged, because it destroys what those decisions called "fetal life" and what the law now before us describes as an "unborn human being."

. . . *Roe* was egregiously wrong from the start. Its reasoning was exceptionally weak, and the decision has had damaging consequences.[^144]

That *Roe* has been overturned is a victory. Yet this victory must not blind Christians to what is glaringly absent in the majority opinion of *Dobbs*: the recognition of the personhood of the unborn child. Omission of this was perhaps understandable in previous ages, but as has been detailed here, the last two hundred years of scientific progress and discovery has rendered this failure inexcusable. *Dobbs* may result in repealing some of the barbarism on blatant display for the last fifty years, but it leaves us still inferior to even our recent forefathers in recognizing the personhood bestowed by God on every human being made in His image.

[]{#_Toc106897070 .anchor}D. The Witness of the Church

As Protestants, we hold that only the testimony of Scripture is infallible. Yet not all areas of Scripture are equally clear, so there has been significant variation in many areas of doctrine across the history of the church. But on the matter of abortion, this has not been so. For over two thousand years, there has been unanimity in declaring abortion a grave evil and crime.

Long before God became flesh and dwelt among us, God's people abominated abortion.[^145] Among the Jews, it was offensive, and indeed the Jews were famous for their hostility to both exposure[^146] and abortion.[^147] As was true with the later church fathers, there was debate and discussion on matters related to ensoulment and quickening, but deliberate abortion was considered a violation of the law of God, and an affront to the sanctity of life.[^148] Former chief justice of the Supreme Rabbinical Court of America, Rabbi Marvin S. Antelman, offers this summary:

All major religions have their parochial and their universal aspects, and the problem of abortion is *not* a parochial one. It is of universal morality, and it is neither a Catholic problem, nor a Jewish problem, nor a Protestant problem. It involves the killing of a human being, an act forbidden by *universal* commandment.[^149]

Similarly, Chief Rabbi Dr. Immanuel Jakobovits of the United Kingdom explains Jewish thinking on the value of human life:

Jewish law sees every human life as having the sanctity of intrinsic and infinite worth. One life has as much value as one hundred or one thousand; you cannot multiply infinity and you cannot divide it. So every human being has an identical worth and is identically worth saving.[^150]

This care for the life of the unborn is precisely what we witness in the Jewish world recorded by the gospels. We see the affirmation of the agency of John the Baptist in the womb of Elizabeth, and her reaction thereto testifying to her son's personhood (Luke 1:41--45). We see the great care taken by Joseph and Mary for our Lord, which perfectly accords with a culture that affirmed the preciousness of life. We see the revulsion of the Apostle Matthew who, through the Holy Spirit, exposes Herod's murder of the innocents with no hint that it could ever be excusable (Matt. 2:16--18). And we see in our Lord's words the care for the unborn and the recognition of their personhood (John 16:21).[^151]

With the development of the New Testament church, some of the defining features that had marked God's people began to change. With the abrogation of Old Testament ceremonial law and the expansion of faith and the covenant people to the Gentiles, many of the old distinguishing marks between God's chosen people and the rest of the world became obsolete. In such an environment, one might anticipate the stringency of earlier Judaic condemnations of abortion would be softened, or fall by the wayside.

What happened was just the opposite. Christian condemnations of abortion intensified beyond earlier Jewish ones. The Jews had focused on abortion as a crime against man, but Christians came to speak of abortion as a crime against God. Where Jewish rabbis had refrained from according status to the unborn, even carving out exceptions where abortion might be permitted,[^152] Christians were adamant, speaking in absolute terms concerning its evil.

Opposition to abortion had previously been a feature of close-knit Jewish communities, but with the new Christian church crossing national boundaries, the rejection of abortion no longer remained an ethnic distinctive. It was now a fundamental moral commitment of the new, burgeoning, multiethnic Christian church. Jewish opprobrium towards abortion and the exposure of infants was common across the Roman Empire, but this opprobrium focused on their own communities. It was not so with the Christians. It was no longer enough for God's people to condemn abortion and exposure as unworthy of the covenant community, but now the Christian church opposed these murders even among the pagans---in rhetoric, in policy, and eventually in law. Most importantly, Christians rescued these little ones exposed by their pagan parents, taking them from the hillsides into their homes and adopting them as their own children. This act of Christian compassion was well-known across the Empire. It was a defining mark of these first Christians.

It is not surprising, then, that during the Apostolic Age and immediately thereafter, we find clear prohibitions of abortion in the writings of church fathers:

You shalt not murder a child by abortion, nor kill that which is begotten. (*Didache* 2.2, AD 50--100)

You shall not murder a child by abortion, nor in turn shall you kill him after it is born. (*Letter of Barnabas* 19, AD 80--130)

All of life could proceed according to nature for us if we exert power over our desires from the beginning and do not by evil devices and schemes kill the human offspring, designed by divine forethought and intention. For those women who, to cover their immorality, use abortifacient drugs \[*phthoriois pharmakois*\] that expel the matter entirely dead, abort along with the embryo their own affection for mankind. (Clement, *The Tutor* 2.10.96.1, c. AD 198)

But for us \[Christians\], since homicide has once for all been forbidden, it is not permitted to pull apart even what has been conceived in the womb. . . . Prevention of birth is hastened homicide; nor does it matter whether one tears away a life that has been born or pulls apart one in the midst of birth. He who will be a man is a man already: for indeed the entire fruit exists already in the seed. (Tertullian, *Defense of the Christians Against the Heathen* 9, c. AD 197)

Therefore the fetus is a human being in the womb from the time that its form is complete. For also the law of Moses judges abortion worthy of penalties, given there exist already the rudiments of a man, since to him is already allotted the condition of life and death when he is assigned to his fate---even though, by still living within the mother, he shares his fate for the most part with her. (Tertullian, *A Treatise on the Soul* 37, AD 208--212)

When a woman has with intentionality destroyed (*phtheirasa*) a fetus, she is held to be guilty of murder. No fastidious distinction (*akribologia*) between "completely formed" and "unformed" exists with us. For in this case not only the child about to be born will be vindicated, but also the woman herself who plotted against herself: inasmuch in most cases women perish from such attempts. And there is added to this also a second murder, the destruction (*phthora*) of the embryo---at least as far as the purpose of those who dare these things. (Basil, *Letter to Amphilocus on the Canons* 188.2, fourth century AD)

Also, the rich themselves, lest their inheritance be divided among many, kill their own offspring in the womb, and by parricidal liquids they snuff out the children of the womb in the genital organs themselves---and life is taken away before it be imparted. Who except man has taught us how to renounce our own sons? (Ambrose, *Hexameron* 5.18.58, AD 386--390)[^153]

You shall not use magic. You shall not use potions; for He says, You shall not permit witches \[*lit.*, potionists\] to live. You shall not slay your child by abortion, nor kill that which is begotten; for everything that has been formed and has received a soul from God shall be avenged if slain, as unjustly destroyed. (*Apostolic Constitutions* 7.1.3, AD 375--380)

Some, when they know they have conceived through wickedness, turn to abortive drugs; often, when they too have themselves perished, they are brought to the lower world guilty of three crimes: suicide, adultery against Christ, and parricide of their unborn child (Jerome, *Letters* 22.13, c. AD 384)

Indeed, sometimes this lustful cruelty or cruel lust \[*libidinosa crudelitas vel libido crudelis*\] extends so far that it obtains poisons of sterility \[*sterilitatis venena*\]; and, if nothing else works, \[it\] snuffs out and breaks up by some means the offspring conceived in the womb, preferring its own offspring to perish before it lives \[*prius interire quam vivere*\]; or, if it was already living in the womb, to be killed before being born \[*occidi antequam nasci*\]. (Augustine, *On Marriage and Concupiscence* 1.17 \[15\], AD 419--420)[^154]

Over a millennium later, the Protestant reformers repeated this condemnation of abortion---always a distinctive mark of Christian morality and charity:

How great, therefore, the wickedness of human nature is! How many girls there are who prevent conception and kill and expel tender fetuses, although procreation is the work of God! Indeed, some spouses who marry and live together in a respectable manner have various ends in mind, but rarely children. The God who declares that we are to be fruitful and multiply regards it as a great evil when human beings destroy their offspring. (Martin Luther, comments on Gen. 25:1--4)[^155]

The foetus, though enclosed in the womb of its mother, is already a human being, and it is almost a monstrous crime to rob it of the life which it has not yet begun to enjoy. If it seems more horrible to kill a man in his own house than in a field, because a man's house is his place of most secure refuge, it ought surely to be deemed more atrocious to destroy a foetus in the womb before it has come to light. (John Calvin, comments on Exod. 21:22ff.)[^156]

From ancient times down to the present day, the position of the church across all its branches---Roman Catholic, Orthodox, and Protestant---has been adamant and unchanging: abortion in all its manifestations is a grave, unspeakable evil:

Throughout Christianity's two thousand year history, this same doctrine of condemning all direct abortions has been constantly taught by the Fathers of the Church and by her Pastors and Doctors. Even scientific and philosophical discussions about the precise moment of the infusion of the spiritual soul have never given rise to any hesitation about the moral condemnation of abortion.[^157]

[]{#_Toc106897071 .anchor}E. The Testimony of Scripture

Leaving all other arguments to the side, Scripture's authority is absolute. Scripture is not the word of man, but the Word of God. We must submit our judgments concerning abortion to Scripture, where the duty of God's people to uphold His image placed in mankind is everywhere revealed, both implicitly and explicitly.

[]{#_Toc106897072 .anchor}Imago Dei

We begin with the doctrine from which flows the clearest condemnation of abortion. God created man in His own image:

Then God said, "Let Us make man in Our image, according to Our likeness; and let them rule over the fish of the sea and over the birds of the sky and over the cattle and over all the earth, and over every creeping thing that creeps on the earth." God created man in His own image, in the image of God He created him; male and female He created them. God blessed them; and God said to them, "Be fruitful and multiply, and fill the earth, and subdue it; and rule over the fish of the sea and over the birds of the sky and over every living thing that moves on the earth." (Gen. 1:26--28)

While all creation proclaims God's glory, the singularity of man is clearly stated to be that he alone---both male and female---bears the *imago Dei*. None of the rest of God's creatures bear His image and likeness, and although we may argue concerning the precise meaning of "image" and "likeness," God doesn't leave us guessing as to its central significance in life-and-death matters.

We find this significance stated in connection with Scripture's second mention of man bearing God's image and likeness in Genesis 9:

And God blessed Noah and his sons and said to them, "Be fruitful and multiply, and fill the earth. The fear of you and the terror of you will be on every beast of the earth and on every bird of the sky; with everything that creeps on the ground, and all the fish of the sea, into your hand they are given. Every moving thing that is alive shall be food for you; I give all to you, as I gave the green plant. Only you shall not eat flesh with its life, that is, its blood. Surely I will require your lifeblood; from every beast I will require it. And from every man, from every man's brother I will require the life of man.

> "Whoever sheds man's blood,
>
> By man his blood shall be shed,
>
> For in the image of God
>
> He made man.
>
> "As for you, be fruitful and multiply;
>
> Populate the earth abundantly and multiply in it."
>
> (Gen. 9:1--7)

Today, intellectuals, philosophers, and scientists (as well as some pastors and theologians) join together in assuring man that God is not his Maker, and he need not fear returning to God for judgment following his death. They contradict Scripture's declaration, "It is He who hath made us, and not we ourselves" (Ps. 100:3). From their fervid religious commitment to evolution, they declare the opposite: "It is not He who hath made us, but we ourselves."

Abortion is the godless pagans' most terrible violation of nature, but this violation didn't start with abortion. It began with their denial that God created all things, and that man as male and female is the crown of His creation. Consider the ways the text above from Genesis 9 teaches this truth and could not be more contrary to the spirit of our age.

First, through Noah, God commands the race He named "man" (Hebrew *adam*) to "be fruitful, and multiply, and fill the earth." Not just "be fruitful," but "multiply." Not just "multiply," but "fill the earth." This series of commands is then repeated at the end of the passage.

Man is God's priority on His earth, and He goes on to make man's primacy more clear by declaring, as a blessing, that man will strike "fear" and be a "terror" to all other creatures. This is God's doing, and therefore it is good. Then He makes it even more clear by stating to man concerning all other creatures of His creation, "into your hand they are given."

He adds that, just like plants, animals are His gift to man for food, and that man is free to kill the creatures, whereas the creatures are forbidden to kill man: "Surely I will require your lifeblood; from every beast I will require it."

Then, not only animals are forbidden to kill man, but man himself is forbidden to kill man. Why? Because man is God's image-bearer:

Whoever sheds man's blood,

By man his blood shall be shed,

For in the image of God

He made man.

Flip this upside down and we have the spirit of our age. Man's population must decline. Man must discipline his fecundity so that his numbers on the earth stop expanding and begin to contract. Rather than subduing the earth and its creatures, man must subdue his multiplication because his multiplication is unsustainable. Man must not rule creation. Such anthropocentric thinking is not creation-keeping, but creation-destroying.

Contradicting God, the spirit of our age declares nature must not serve man, but man must serve nature. It declares there is no distinction in principle between man and animal, and thus the high priest of paganism, Princeton ethicist Peter Singer, writes:

My suggestion, then, is that we accord the fetus no higher moral status than we give to a nonhuman animal at a similar level of rationality, self-consciousness, awareness, capacity to feel and so on. Because no fetus is a person, no fetus has the same claim to life as a person. Until a fetus has some capacity for conscious experience, an abortion terminates an existence that is---considered as it is and not in terms of its potential---more like that of a plant than of a sentient animal like a dog or a cow.[^158]

We see how deeply this rebellion against God has infiltrated the church in any number of ways, but note particularly how many believers choose dogs and cats over children. Also note how many Christians today decline to eat the very animals God gave us to eat when He declared, they "shall be food for you." Of course, Christians who are vegans and vegetarians are eager to reassure other believers this is only their preference---not their principle. But note how meatlessness grows in the church even as Singer promotes his ethical anarchy---and then the entire world prattles on about cruelty to animals and free-range chickens. Five centuries ago, Calvin made this observation which is still true:

It is usual with hypocrites to reckon it a greater crime to kill a flea than to kill a man.[^159]

Given this flipping of God's order of creation, it should surprise no one that we've also flipped capital punishment upside down. God commands that murderers be executed because murder destroys an image-bearer. Today, though, man outlaws the execution of murderers. Today, it's murderers who awaken the compassion of men and women. Murderers are protected from execution while innocent babies are abandoned.

The various Green advocates of sustainability have repudiated God as the Creator of the universe, and have thus inevitably denied man's dignity as the crown of God's creation. These pagans have replaced the truths of God with the worship of creation, ushering back into Christendom the very idolatries and sexual perversions condemned by the Apostle Paul in the first chapter of his letter to the church in Rome. Refusing to honor and give thanks to their Creator, pagans are turned over by God to the same unimaginable horrors that led God to command the sons of Israel to wipe out the Canaanites of the Promised Land.

The image of God marks man's whole being, body and soul. Thus to kill a man is to destroy God's image in that man, and thus openly defy the God who placed it there. To kill a man or woman, boy or girl, is wrong not only because of the harm done to the individual, but also because of the assault upon God. When one man murders another, it is an act of war against God. God declares the shedding of innocent blood pollutes the land and must be avenged by the execution of the manslayer:

So you shall not pollute the land in which you are; for blood pollutes the land and no expiation can be made for the land for the blood that is shed on it, except by the blood of him who shed it. You shall not defile the land in which you live. (Num. 35:33--34)

[]{#_Toc106897073 .anchor}"Your Hands Formed Me"

God is Creator, and every child conceived reveals the purposeful and formative hand of God in His design.[^160] Scientific advancement has done much to open up the astonishing nature of conception, yet this ought not cause us to be materialists in our understanding, supposing that new life can be explained simply in terms of sperm, egg, DNA, mitosis, and so on. To be sure, our Lord shows us His glory through these means, but He also fashions each child in invisible, spiritual, and unfathomable ways:

Just as you do not know the path of the wind and how bones are formed in the womb of the pregnant woman, so you do not know the activity of God who makes all things. (Eccles. 11:5)

Abortion is an assault on this secret and divine creation. It takes the greatest mystery in our lives, the creation of life, and destroys it. It takes one of God's greatest mercies to sinful man and mocks it. It is an extolling of death, and thus a denial of God. God creates life. Satan hates and destroys life.

[]{#_Toc106897074 .anchor}Woman as Life-Giver

The gift of procreation was only given to man when God created woman. As companion to Adam, she was to be a help meet (fitting or suitable) for him, and central to that suitability for man is woman's gift of bringing life into the world. When Adam named her "Eve" ("living one," or "life-giver"), this was not merely descriptive, but prescriptive:

Now the man called his wife's name Eve, because she was the mother of all the living. (Gen. 3:20)

Now the man had relations with his wife Eve, and she conceived and gave birth to Cain, and she said, "I have gotten a manchild with the help of the [Lord]{.smallcaps}." (Gen. 4:1)

God created man in His own image, in the image of God He created him; male and female He created them. God blessed them; and God said to them, "Be fruitful and multiply, and fill the earth, and subdue it." (Gen. 1:27--28)

Life-giving is fundamental to the mission of woman. God is pleased to bring life into this world through her:

For as the woman originates from the man, so also the man has his birth through the woman; and all things originate from God. (1 Cor. 11:12)

Life-giving is woman's highest calling and most noble purpose. This is not to say woman's only value is her ability to give life. Many women are single. Many married women have not had their wombs opened by God. Nevertheless, to declare that God created woman's physiology, nature, and being as life-giver is no abuse of women who are childless. It is simply to state what is the doctrine of Scripture and has been obvious to all men everywhere across the ages. Moreover, this blessing of God will continue to be obvious both in Scripture and nature until our Lord returns. We may strive against it and seek to twist and deform our sisters, daughters, and wives until their lives are a visible effort to deny this truth, but nature and nature's God will have the victory.
