# Endnotes

test

[^1]: https://evangel.pressbooks.com. The BCO includes a Directory for Worship by which we govern our worship (https://evangel.pressbooks.com/chapter/preface-to-the-directory/).

[^2]: https://evangel.pressbooks.com/chapter/28-declaration-of-doctrine-and-policies-concerning-sexuality/.

[^3]: https://evangelpresbytery.com/wp-content/uploads/2020/06/STATEMENT-ON-SPHERE-AUTHORITY-WORSHIP-AND-COVID-19-QUARANTINES.pdf.

[^4]: https://evangelpresbytery.com/wp-content/uploads/2021/10/Conscience-and-COVID-19-Vaccine-Mandates_Evangel-Presbytery.pdf.

[^5]: https://www.sovereignkingchurch.com/.

[^6]: *Dobbs v. Jackson Women's Health Organization*, No. 19-1392 (US June 24, 2022).

[^7]: This usage of "man" as a gender inclusive will be constant in this document. God Himself named our race (both male and female together) "man" (Hebrew *adam*) after the male of the species (Genesis 5:2). The usage of "man" to refer to both male and female of the species therefore honors God's naming in a way the more common "human," "human being," "humanity," "humankind," and "person" obscure.

[^8]: Jonathan Bearak et al., "Unintended Pregnancy and Abortion by Income, Region, and the Legal Status of Abortion: Estimates from a Comprehensive Model for 1990--2019," *The Lancet Global Health* 8, no. 9 (September 1, 2020): e1152--e1161, https://doi.org/10.1016/S2214-109X(20)30315-6.

[^9]: *The Effects of Strategic Bombing on German Morale*, The United States Strategic Bombing Survey (Morale Division, May 1947), 1:7--8, https://isr.umich.edu/wp-content/uploads/historicPublications/Effects_300\_.PDF.

[^10]: Aleksandr Solzhenitsyn, *The Gulag Archipelago*, trans. Thomas P. Whitney (HarperCollins, 2007), 1:174.

[^11]: Hosea 4:2.

[^12]: Note the use of the term "birth control" for what would almost always be labeled "contraception" across scientific and medical literature. In our usage, "contraception" will refer only to methods of birth control which actually prevent conception, defined as the fertilization of the egg producing an embryo. On the other hand, "birth control" will include contraceptive agents and methods, but also abortifacient agents and methods which, properly speaking, do not prevent conception, but the little one's implantation, development to full term, and birth.

[^13]: See testimony of Dr. Jerome Lejeune in *Davis v. Davis*, as reproduced in pt. 1 of *A Symphony of the Preborn Child* (National Association for the Advancement of Preborn Children, 1989), 18, https://naapc.org/wp-content/uploads/2010/05/symphony.pdf. We will quote extensively from Dr. Lejeune's testimony when addressing in vitro fertilization below.

[^14]: "When Human Life Begins," American College of Pediatricians, March 2017, https://acpeds.org/position-statements/when-human-life-begins.

[^15]: Bent Böving, "Implantation Mechanisms," ch. 7 in *Mechanisms Concerned with Conception*, ed. C. G. Hartman (MacMillan, 1963), 386.

[^16]: The American College of Obstetricians and Gynecologists (ACOG) Committee on Terminology, "Terms Used in Reference to The Fetus," *Terminology Bulletin*, no. 1 (September 1965): 1. For more on this change, see https://acpeds.org/position-statements/when-human-life-begins.

[^17]: Bernard Nathanson and Richard Ostling, *Aborting America* (Doubleday, 1979), 193.

[^18]: Willard Cates Jr., David Grimes, and Kenneth Schulz, "The Public Health Impact of Legal Abortion: 30 Years Later," *Perspectives on Sexual and Reproductive Health* 35, no. 1 (January/February 2003): 25--28, https://doi.org/10.1363/3502503.

[^19]: Therese Hesketh, Li Lu, and Zhu Wei Xing, "The Consequences of Son Preference and Sex-Selective Abortion in China and Other Asian Countries," *Canadian Medical Association Journal* 183, no. 12 (September 6, 2011): 1374--1377, https://doi.org/10.1503/cmaj.101368.

[^20]: Ibid., 1375.

[^21]: Sneha Barot, "A Problem-and-Solution Mismatch: Son Preference and Sex-Selective Abortion Bans," *Guttmacher Policy Review* 15, no. 2 (2012): 19, https://www.guttmacher.org/gpr/2012/05/problem-and-solution-mismatch-son-preference-and-sex-selective-abortion-bans.

[^22]: Amrit Dhillon, "Selective Abortion in India Could Lead to 6.8m Fewer Girls Being Born by 2030," *The Guardian*, August 21, 2020, https://www.theguardian.com/global-development/2020/aug/21/selective-abortion-in-india-could-lead-to-68m-fewer-girls-being-born-by-2030.

[^23]: "Gendercide," *The Economist*, March 4, 2010, https://www.economist.com/leaders/2010/03/04/gendercide.

[^24]: "Gendercide in the Caucasus: Sex-Selective Abortion," *The Economist*, September 21, 2013, https://www.economist.com/europe/2013/09/21/gendercide-in-the-caucasus.

[^25]: Mary Anne Warren, *Gendercide: The Implications of Sex Selection* (Rowman & Allanheld, 1985), 5. Warren is slippery in stating specific arguments, but her book is a defense of gender-selective feticide.

[^26]: Ibid., 183.

[^27]: Ibid., 197. Emphasis original.

[^28]: See European Society of Human Reproduction and Embryology (ESHRE), "More Than 8 Million Babies Born from IVF Since the World's First in 1978," *Science Daily*, July 3, 2018, https://www.sciencedaily.com/releases/2018/07/180703084127.htm.

[^29]: "In vitro fertilization (IVF)," Mayo Clinic, https://www.mayoclinic.org/tests-procedures/in-vitro-fertilization/about/pac-20384716.

[^30]: Ibid.

[^31]: Notably, even the scientific literature refers to embryos' ability to *survive* the freeze-thaw cycle. Ibid.

[^32]: Lejeune, in *A Symphony of the Preborn Child*, 14, 18, 19--20, 24, 26.

[^33]: See Genesis 20:18; 29:31; 1 Samuel 1:6; Psalm 127:3; Isaiah 66:9; among others. From Eve, to Sarah, to Rachel, Hannah, and so on, Scripture is full of instances proclaiming that God opens the womb. And conversely, it also teaches that God closes the womb: e.g., Abimelech's household, Rachel, Hannah, etc.

[^34]: The authors know of a couple who used IVF to produce a number of embryos. Determined to use each of them, they delivered multiple sets of twins and singles. Eight years after their last pregnancy, they were convicted that the final two embryos were still in limbo. So at the age of 42, with a house already quite full of children, the wife was implanted with the final embryos and brought two more souls into the world.

[^35]: Meredith Wadman, "The Truth about Fetal Tissue Research," *Nature* 528, December 10, 2015, https://doi.org/10.1038/528178a.

[^36]: Ibid., 179.

[^37]: Ibid., 178.

[^38]: For a discussion of biotherapeutic proteins manufactured in different cell lines, including HEK 293 cells and their derivatives, see Jennifer Dumont et al., "Human Cell Lines for Biopharmaceutical Manufacturing: History, Status, and Future Perspectives," *Critical Reviews in Biotechnology* 36, no. 6 (November 2016): 1110--1122, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5152558/. There are other cell lines developed from cancerous cells that also replicate themselves in great numbers but have whatever genetic/functional changes that made them cancerous.

[^39]: "Fetal Tissue Research: Focus on the Science and Not the Politics," *The Lancet Respiratory Medicine* 7, no. 8, June 24, 2019, https://doi.org/10.1016/S2213-2600(19)30222-X.

[^40]: "The primary cell lines, which are obtained from animals, introduce potentially risky exogenous agents. In contrast, human diploid cell strains (HDCSs), acquired from embryos or other tissue cells of human origin, possess identical chromosome sets that are free of all known adventitious agents." Bo Ma et al., "Characteristics and Viral Propagation Properties of a New Human Diploid Cell Line, Walvax-2, and Its Suitability as a Candidate Cell Substrate for Vaccine Production," *Human Vaccines & Immunotherapeutics* 11, no. 4 (2015): 999, https://doi.org/10.1080/21645515.2015.1009811.

[^41]: See AG05965-D, "Fibroblast from Skin, Lung," product from Coriell Institute for Medical Research, https://catalog.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=AG05965-D.

[^42]: Bo Ma et al., 999.

[^43]: Ibid., 1006.

[^44]: Alvin Wong, "The Ethics of HEK 293," *The National Catholic Bioethics Quarterly* 6, no. 3 (Autumn 2006): 473--474, https://doi.org/10.5840/ncbq20066331.

[^45]: See Frank Graham, whose work was responsible for the first transformation of the fetal cells into a perpetual line: "Abortion was illegal in the Netherlands until 1984 except to save the life of the mother. Consequently I have always assumed that the HEK cells used by the Leiden lab must have derived from a therapeutic abortion." Ivan Couronne, "How Fetal Cells From the 1970s Power Medical Innovation Today," *Courthouse News Service*, October 20, 2020, https://www.courthousenews.com/how-fetal-cells-from-the-1970s-power-medical-innovation-today/. See also Alex Van der Eb, in whose lab Dr. Graham worked: "The fetus, as far as I can remember was completely normal. Nothing was wrong. The reasons for the abortion were unknown to me. I probably knew it at that time, but it got lost, all this information." Vaccines and Related Biological Products Advisory Committee, Advisory Committee Meeting, May 16, 2001, transcript by Neal R. Gross, United States of America Food and Drug Administration Center for Biologics Evaluation and Research 81, https://wayback.archive-it.org/7993/20170404095417/https:/www.fda.gov/ohrms/dockets/ac/01/transcripts/3750t1_01.pdf.

[^46]: For more, see U.S. Department of Health, Education, and Welfare, "Appendix: Research on the Fetus," The National Commission for the Protection of Human Subjects of Biomedical and Behavioral Research (1976), https://archive.org/details/researchonfetusa00unit/page/n3/mode/2up.

[^47]: Readers might gasp at this argument, thinking it can't possibly be what anyone would write or say. Your writers, though, have read a significant amount in the literature of medical ethics dealing with the question whether preborn babies are proper subjects of experimentation and can be surmised to have given their informed consent, and this summary is accurate.

[^48]: For more on this issue, a helpful place to start is Evangel Presbytery, "Conscience and COVID-19 Vaccine Mandates: In Defense of Sphere Authority," October 8, 2021, https://evangelpresbytery.com/wp-content/uploads/2021/10/Conscience-and-COVID-19-Vaccine-Mandates_Evangel-Presbytery.pdf. See also Evangel Presbytery, "Statement on Sphere Authority, Worship, and COVID-19 Quarantines," June 2020, https://evangelpresbytery.com/wp-content/uploads/2020/06/STATEMENT-ON-SPHERE-AUTHORITY-WORSHIP-AND-COVID-19-QUARANTINES.pdf.

[^49]: Cardinal Elio Sgreccia wrote a public letter to Mrs. Debra L. Vinnedge, June 9, 2005, which included a study on vaccinating children with vaccines prepared using cell lines derived from aborted human fetuses that concluded as follows:

    there is a grave responsibility to use alternative vaccines and to make a conscientious objection with regard to those which have moral problems;

    as regards the vaccines without an alternative, the need to contest so that others may be prepared must be reaffirmed, as should be the lawfulness of using the former in the meantime insomuch as is necessary in order to avoid a serious risk not only for one's own children but also, and perhaps more specifically, for the health conditions of the population as a whole---especially for pregnant women;

    the lawfulness of the use of these vaccines should not be misinterpreted as a declaration of the lawfulness of their production, marketing and use, but is to be understood as being a passive material cooperation and, in its mildest and remotest sense, also active, morally justified as an *extrema ratio* due to the necessity to provide for the good of one's children and of the people who come in contact with the children (pregnant women);

    such cooperation occurs in a context of moral coercion of the conscience of parents, who are forced to choose to act against their conscience or otherwise, to put the health of their children and of the population as a whole at risk. This is an unjust alternative choice, which must be eliminated as soon as possible.

    Accessed at https://www.immunize.org/talking-about-vaccines/vaticandocument.htm. The study was later published as "Pontifical Academy for Life Statement: Moral Reflections on Vaccines Prepared from Cells Derived from Aborted Human Foetuses," *The Linacre Quarterly* 86, no. 2--3 (May--August 2019): 182--187, https://doi.org/10.1177/0024363919855896.

[^50]: One of our authors was present there in Denver and heard Schaeffer's lament.

[^51]: In *First Things* back in 1998, Richard John Neuhaus commented on the influence of Koop and Shaeffer's book and film series: "Through his films and lectures, Schaeffer dramatically posed the question of what was becoming of the human race and almost single-handedly alerted evangelicals to the significance of the abortion debate. He did not use the language of John Paul II about 'the culture of death' versus 'the culture of life,' but that was the gist of his message, and his effective delivery of that message was a critical factor in bringing about the ever-growing alliance between evangelicals and Catholics in the great cultural tasks of our time. As our evangelical friends do not usually say, *Requiescat in pace*." "A Tacit Admission of Defeat: The Public Square," *First Things* 82, April 1998, 60--75.

[^52]: Anna Popinchalk and Gilda Sedgh, "Trends in the Method and Gestational Age of Abortion in High-Income Countries," *BMJ Sexual & Reproductive Health* 45, no. 2 (April 2019): 95--103, https://doi.org/10.1136/bmjsrh-2018-200149.

[^53]: "Contraceptive Use by Method 2019: Data Booklet," United Nations Department of Economic and Social Affairs (United Nations, 2019), 22, https://www.un.org/development/desa/pd/sites/www.un.org.development.desa.pd/files/files/documents/2020/Jan/un_2019_contraceptiveusebymethod_databooklet.pdf.

[^54]: In Genesis 3:20, Adam names the woman Eve (Hebrew **חַוָּה**, *ḥaûâ*), which literally means "living," "living one," or "life-giver." The Holy Spirit tells us that Adam named her this "because she was the mother of all the living."

[^55]: Thomas White, "What Did Hannah Arendt Really Mean by the Banality of Evil?" *Aeon*, April 23, 2018, https://aeon.co/ideas/what-did-hannah-arendt-really-mean-by-the-banality-of-evil.

[^56]: Flannery O'Connor, *Mystery and Manners: Occasional Prose* (Farrar, Straus, and Giroux, 1969), 226--228.

[^57]: "Are not two sparrows sold for a cent? And yet not one of them will fall to the ground apart from your Father. But the very hairs of your head are all numbered. So do not fear; you are more valuable than many sparrows." Matthew 10:29--31.

[^58]: Here is a helpful summary of some Christian physicians' efforts to deny hormonal birth control methods are abortifacient, followed by documentation of their errors: Randy Alcorn, *Does the Birth Control Pill Cause Abortions?*, 11th edition (Eternal Perspective Ministries, 2011), https://www.epm.org/static/uploads/downloads/bcpill.pdf.

[^59]: Institute for Quality and Efficiency in Health Care, "Contraception: Hormonal Contraceptives," InformedHealth.org, updated June 29, 2017, https://www.ncbi.nlm.nih.gov/books/NBK441576/.

[^60]: "Hormonal Contraception," English Fact Sheets & Info Booklets, ReproductiveFacts.org, American Society of Reproductive Medicine, accessed June 23, 2022, https://www.reproductivefacts.org/news-and-publications/patient-fact-sheets-and-booklets/documents/fact-sheets-and-info-booklets/hormonal-contraception/.

[^61]: "How Birth Control Methods Prevent Pregnancy," University of Michigan Health, accessed June 23, 2022, https://www.umwomenshealth.org/health-library/tb1025.

[^62]: "Contraception Methods That Hinder Implantation," embryology.ch (Online course in embryology for medical students), Universities of Fribourg, Lausanne and Bern (Switzerland), accessed June 23, 2022, https://embryology.ch/en/embryogenese/implantation/contraception-methods/introduction.html. Note here, as everywhere in the literature, that "hindering . . . the implantation of the fertilized oocyte" is labeled "contraception."

[^63]: https://embryology.ch/en/embryogenese/implantation/popup/contracep.html.

[^64]: Karen Smith-McCune et al., "Differential Effects of the Hormonal and Copper Intrauterine Device on the Endometrial Transcriptome," *Scientific Reports* 10, art. no. 6888 (2020), https://doi.org/10.1038/s41598-020-63798-8.

[^65]: "Study: Copper IUDs Do Not Appear to Prevent Implantation or Increase HIV Risk," Relias Media, July 1, 2020, https://www.reliasmedia.com/articles/146320-study-copper-iuds-do-not-appear-to-prevent-implantation-or-increase-hiv-risk.

[^66]: "IUD," Planned Parenthood, accessed June 23, 2022, https://www.plannedparenthood.org/learn/birth-control/iud.

[^67]: God of God, Light of Light;

    Lo, He abhors not the Virgin's womb;

    Very God, begotten, not created . . .

    John Francis Wade (attr.), "O Come All Ye Faithful" (1751), trans. Frederick Oakeley (1841).

[^68]: Thomas F. Torrance, "The Being and Nature of the Unborn Child," address given at the Presbyterians Pro-Life General Assembly Luncheon, 212th General Assembly of the Presbyterian Church (USA), June 25, 2000 (Glen Lorien Books, 2000), 4--5, http://www.togetherforadoption.org/wp-content/media/Torrance-paper-on-the-Unborn.pdf.

[^69]: Luke 1:30ff.

[^70]: Stanley Henshaw, Susheela Singh and Taylor Haas, "The Incidence of Abortion Worldwide," *International Perspectives on Sexual and Reproductive Health* 25, January 1999, 30--38, https://www.guttmacher.org/journals/ipsrh/1999/01/incidence-abortion-worldwide.

[^71]: Bearak et al.

[^72]: China's policy applied to cities, but the countryside and some ethnic minorities were granted exceptions.

[^73]: Ma Jian, "China's Barbaric One-Child Policy," *The Guardian*, May 6, 2013, https://www.theguardian.com/books/2013/may/06/chinas-barbaric-one-child-policy.

[^74]: The policy allowed for a second child in more rural areas and among certain ethnic minorities if a couple's first child was female.

[^75]: Tom Strode, "China: 40 Years; 336 Million Abortions," *The Baptist Messenger*, March 28, 2013, https://www.mydigitalpublication.com/display_article.php?id=1358181&view=152240.

[^76]: Sui-Lee Wee, "After One-Child Policy, Outrage at China's Offer to Remove IUDs," *New York Times*, January 7, 2017, https://www.nytimes.com/2017/01/07/world/asia/after-one-child-policy-outrage-at-chinas-offer-to-remove-iuds.html.

[^77]: William F. Colliton, "Birth Control Pill: Abortifacient and Contraceptive," *The Linacre Quarterly* 66, no. 4, art. 2, https://epublications.marquette.edu/lnq/vol66/iss4/2/.

[^78]: "Current Contraceptive Status Among Women Aged 15--49: United States, 2017--2019," NCHS Data Brief No. 388 (October 2020), https://www.cdc.gov/nchs/products/databriefs/db388.htm.

[^79]: James Trussell, "Contraceptive Failure in the United States," *Contraception* 83, no. 5 (May 2011): 397--404, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3638209/. See also "How Effective Is Contraception at Preventing Pregnancy?" NHS, last reviewed April 17, 2020, https://www.nhs.uk/conditions/contraception/how-effective-contraception/.

[^80]: Ian Milsom and Tjeerd Korver, "Ovulation Incidence with Oral Contraceptives: A Literature Review," *Journal of Family Planning and Reproductive Health Care* 34, no. 4 (October 2008): 237--246, https://doi.org/10.1783/147118908786000451.

[^81]: UN, "Contraceptive Use by Method 2019: Data Booklet," 15.

[^82]: Practice of birth control in Europe and North America among 246,000,000 women 15--49, by percentages: any method 58.2, female sterilization 6.3, male sterilization 2.5, pill 17.8, injectable 1.1, implant 1.1, IUD 7.9, male condom 14.6, rhythm 1.4, withdrawal 4.1, other methods 1.4. Ibid.

[^83]: Joseph Stanford and Rafael Micolajczyk, "Mechanisms of Action of Intrauterine Devices: Update and Estimation of Postfertilization Effects," *American Journal of Obstetrics & Gynecology* 187, no. 6 (December 2002): 1699--1708.

[^84]: UN, "Contraceptive Use by Method 2019: Data Booklet," 22.

[^85]: See, among others, "1.5 Million Embryos Killed through IVF Since 1991 in Britain," *LifeSiteNews*, July 27, 2011, https://www.lifesitenews.com/news/15-million-embryos-killed-through-ivf-since-1991-in-britain/.

[^86]: *Hansard*, HL Debates, vol. 742, January 8, 2013, cols. WA22--WA26, https://publications.parliament.uk/pa/ld201213/ldhansrd/text/130108w0001.htm#column_WA26.

[^87]: *Hansard*, HL Debates, vol. 729, July 20, 2011, cols. WA305--WA308, https://publications.parliament.uk/pa/ld201011/ldhansrd/text/110720w0001.htm#column_WA305. It is not certain whether the HFEA refers to the entirety of 1991 in this report, or the period beginning August 1, 1991.

[^88]: "Fertility Treatment in 2012: Trends and Figures," HFEA, https://www.hfea.gov.uk/media/2080/hfea-fertility-trends-2012.pdf. Again, it is not certain whether the HFEA refers to the entirety of 1991, or the period beginning August 1, 1991.

[^89]: This number does not account for embryos that became twins or triplets.

[^90]: ESHRE, "More Than 8 Million Babies."

[^91]: See, e.g., "The Fertility Center Regulation Crisis in the United States" Peiffer Wolf Carr and Kane (law firm), August 7, 2019, https://peifferwolf.com/wp-content/uploads/2020/01/PWCK_Fertility-Center-Regulation-Crisis-Issue-Briefer_FINAL.pdf.

[^92]: "Medications for Birth Control (Contraception)," Drugs.com, accessed June 23, 2022, https://www.drugs.com/condition/contraception.html.

[^93]: Stalin's plan was not to kill all Ukrainians worldwide, nor were the Turks intent on killing all Armenians across the world. Yet their crimes, as well as many other similar ones, have always been condemned as genocide.

[^94]:  UN General Assembly, Resolution 96(I), The Crime of Genocide, A/RES/96-I (December 11, 1946), https://documents-dds-ny.un.org/doc/RESOLUTION/GEN/NR0/033/47/img/NR003347.pdf?OpenElement.

[^95]: Hugo Grotius, *De Jure Belli ac Pacis Libri Tres* (1646), trans. Francis W. Kelsey, Carnegie Classics of International Law, ed. James Brown Scott, vol. 2 (Oxford: Clarendon Press, 1925), 862 (3.25.8).

[^96]: Augustine, *On the Trinity* 7.6.11.

[^97]: "*Roe v. Wade*: Its History and Impact," Planned Parenthood Federation of America, 2014, https://www.plannedparenthood.org/files/3013/9611/5870/Abortion_Roe_History.pdf.

[^98]: οὐ δώσω δὲ οὐδὲ φάρμακον οὐδενὶ αἰτηθεὶς θανάσιμον, οὐδὲ ὑφηγήσομαι συμβουλίην τοιήνδε: ὁμοίως δὲ οὐδὲ γυναικὶ πεσσὸν φθόριον δώσω. ἁγνῶς δὲ καὶ ὁσίως διατηρήσω βίον τὸν ἐμὸν καὶ τέχνην τὴν ἐμήν.

[^99]: Adam named his wife Eve, which means "living one" or "life-giver," "because she was the mother of all the living." Genesis 3:20.

[^100]: The reactions of many women on social media to the threatened overturning of *Roe v. Wade* illustrate this reality. For example, Twitter user \@Darlyn215 said on May 3, 2022, "You know what's so interesting? Women can't get themselves pregnant. It's men who cause abortions," accessed May 5, 2022, https://twitter.com/Darlyn215/status/1521595279077744641. Twitter user \@photogjoy said on May 4, 2022, "Let's force vasectomies on men who get women pregnant so the MAN has to pay the price as well," accessed May 5, 2022, https://twitter.com/photogjoy/status/1521822320628748288, emphasis original.

[^101]: "An Open Letter to State Lawmakers from America's Leading Pro-Life Organizations," May 12, 2022, https://www.nrlc.org/uploads/communications/051222coalitionlettertostates.pdf. Emphases original.

[^102]: 1 Kings 3:16--28.

[^103]: Mother Teresa, "Address to Commissioners of 200th General Assembly of the Presbyterian Church (USA), St. Louis, Missouri; June 7, 1988."

[^104]: Philip Ney, Claudia Sheils, and Marek Gajowy, "Post-Abortion Survivor Syndrome: Signs and Symptoms," *Southern Medical Journal* 99, no. 12 (December 2006): 1405--1406, https://doi.org/10.1097/01.smj.0000251372.56344.bf.

[^105]: "When they are able, from reliable evidence, to prove some fact of physical science, we shall show that it is not contrary to our Scripture. But when they produce from any of their books a theory contrary to Scripture, and therefore contrary to the catholic faith, either we shall have some ability to demonstrate that it is absolutely false, or at least we ourselves will hold it so without any shadow of a doubt. And so we will cling to our Mediator, 'in whom are hidden all the treasures of wisdom and knowledge,' that we will not be led astray by the glib talk of false philosophy or frightened by the superstition of false religion." Augustine, *Literal Commentary on Genesis* 1.21.41, trans. J. H. Taylor.

[^106]: Thus Augustine, on the question of the physical disposition of heaven: "But someone may ask: 'Is not Scripture opposed to those who hold that heaven is spherical, when it says "who stretches out heaven like a skin"?' Let it be opposed indeed if their statement is false. The truth is rather in what God reveals than in what groping men surmise. But if they are able to establish their doctrine with proofs that cannot be denied, we must show that this statement of Scripture about the skin is not opposed to the truth of their conclusions. . . . But if it is necessary, as it surely is, to interpret these two passages so that they are shown not to be contradictory but to be reconcilable, it is also necessary that both of these passages should not contradict the stories that may be supported by true evidence, by which heaven is said to be curved on all sides in the shape of a sphere, provide only that this is proved." *Literal Commentary on Genesis* 2.9.

[^107]: "It is admitted that theologians are not infallible, in the interpretation of Scripture. It may, therefore, happen in the future, as it has in the past, that interpretations of the Bible, long confidently received, must be modified or abandoned, to bring revelation into harmony with what God teaches in his works. This change of view as to the true meaning of the Bible may be a painful trial to the Church, but it does not in the least impair the authority of the Scriptures. They remain infallible; we are merely convicted of having mistaken their meaning." Charles Hodge, *Systematic Theology*, 3 vols. (1872--73; Eerdmans, 1982), 1:59.

[^108]: Indeed, because God is infallible in *all* His works and cannot err in His revelation of Himself, both natural and special revelation may be said to be infallible, but not any *interpretation* of those revelations.

[^109]: "Well, after all, it's living, isn't it? And if it's living, what is it if it's not a human being? A mouse? A dog? A monkey?" Richard John Neuhaus in an unpublished paper given at the Consultation on the Church and Abortion, sponsored by Presbyterians Pro-Life, Princeton Theological Seminary, February 28--29, 1992.

[^110]: See Job 10:8--12: "Your hands fashioned and made me altogether, and would You destroy me? Remember now, that You have made me as clay; and would You turn me into dust again? Did You not pour me out like milk and curdle me like cheese; clothe me with skin and flesh, and knit me together with bones and sinews? You have granted me life and lovingkindness; and Your care has preserved my spirit."

[^111]: John Paul II, *Evangelium Vitae*, March 25, 1995, §§ 60--61, https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_25031995_evangelium-vitae.html, quoting Sacred Congregation for the Doctrine of the Faith, *Declaration on Procured Abortion*, November 18, 1974, §§ 12--13, https://www.vatican.va/roman_curia/congregations/cfaith/documents/rc_con_cfaith_doc_19741118_declaration-abortion_en.html.

[^112]: The SLED acronym was developed by the Roman Catholic philosopher Stephen Schwarz in his 1990 book *The Moral Question of Abortion* (Loyola University Press).

[^113]: Re: sight, eye movements and reactions occur as early as 12 weeks. See Tryphena Humphrey, "Some Correlations between the Appearance of Human Fetal Reflexes and the Development of the Nervous System," in *Progress in Brain Research*, vol. 4, *Growth and Maturation of the Brain*, ed. Dominick P. Purpura and J. P. Schadé (Elsevier, 1964), 93--135, https://doi.org/10.1016/S0079-6123(08)61273-X.

    Re: hearing, see Christine Moon, Hugo Lagerkrantz, and Patricia Kuhl, "Language Experienced In Utero Affects Vowel Perception after Birth: A Two-Country Study," *Acta Paediatrica* 102, no. 2 (February 2013): 156--160, https://doi.org/10.1111/apa.12098; also Eino Partanen et al., "Learning-Induced Neural Plasticity of Speech Processing before Birth," in *Psychological and Cognitive Sciences* 110, no. 37 (August 26, 2013): 15145--15150, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3773755/.

    Re: pain, recent research has continually pushed back the developmental threshold at which the unborn are known to be able to feel pain. See, e.g., Stuart Derbyshire and John Bockmann, "Reconsidering Fetal Pain," *Journal of Medical Ethics* 46, no. 1 (2020): 3--6, http://dx.doi.org/10.1136/medethics-2019-105701. For other aspects of early fetal development, see Katrina Furth, *15 Facts at 15 Weeks*, On Science 3 (Arlington: Charlotte Lozier Institute, 2021), https://lozierinstitute.org/15-facts-at-15-weeks/.

[^114]: Linda Rodriguez McRobbie, "The Man in the Iron Lung," *The Guardian*, May 26, 2020, https://www.theguardian.com/society/2020/may/26/last-iron-lung-paul-alexander-polio-coronavirus.

[^115]: John Donne, *Devotions upon Emergent Occasions* (1624), ch. 17.

[^116]: Comments on Luke 10:30, trans. Jürgen von Hagen.

[^117]: Eugene Quay, "Justifiable Abortion," *The Georgetown Law Journal*, Winter 1960, 178. Quay, the founding editor of *The Georgetown Law Journal*, was a member of the American Law Institute whose work recommending legislative changes toward judicial reform were, at the time, being corrupted by a movement promoting the liberalization of state laws concerning abortion. "Justifiable Abortion" was his witness against this movement.

[^118]: John T. Noonan, "Restoring the Protection of Life to the Constitution," prepared statement in *Constitutional Amendments Relating to Abortion: Hearings Before the Subcommittee on the Constitution of the Committee on the Judiciary, United States Senate, Ninety-seventh Congress, First Session, on S.J. Res. 17, S.J. Res. 18, S.J. Res. 19, and S.J. Res. 110* (1983), 46.

[^119]: (William Morrow, 2005).

[^120]: Ibid., 137.

[^121]: Ibid., 138.

[^122]: Ibid., 139.

[^123]: Ibid., 138.

[^124]: Michael Giandrea and Shawn Sprague, "Estimating the U.S. Labor Share," *Monthly Labor Review*, U.S. Bureau of Labor Statistics, February 2017, https://doi.org/10.21916/mlr.2017.7.

[^125]: See "Labour Share of GDP, Comprising Wages and Social Protection Transfers," Sustainable Development Goals, United Nations Economic Commission for Europe, https://w3.unece.org/SDG/en/Indicator?id=30.

[^126]: All values are in US dollars.

[^127]: "Level of GDP Per Capita and Productivity," Organisation for Economic Co-operation and Development, https://stats.oecd.org/index.aspx?DataSetCode=PDB_LV.

[^128]: "Employment Status of the Civilian Noninstitutional Population by Age, Sex, and Race," Labor Force Statistics from the Current Population Survey, U.S. Bureau of Labor Statistics, https://www.bls.gov/cps/aa2019/cpsaat03.htm.

[^129]: Table 3 under "Access to Historical Data for the Tables of the Usual Weekly Earnings of Wage and Salary Workers," U.S. Bureau of Labor Statistics, https://www.bls.gov/webapps/legacy/cpswktab3.htm.

[^130]: Katherine Kortsmit et al., "Abortion Surveillance---United States, 2019," *Surveillance Summaries* 70, no. 9 (November 26, 2021): 1--29, CDC, https://www.cdc.gov/mmwr/volumes/70/ss/ss7009a1.htm.

[^131]: Credit Suisse Research Institute, *Global Wealth Report 2019*, 44.

[^132]: S. D. Mumford and E. Kessel, "Role of Abortion in Control of Global Population Growth," *Clinical Obstetrics and Gynecology* 13, no. 1 (March 1986):19--31.

[^133]: Max Kummerow, "Reproductive Biology of Abortion," The Overpopulation Project, January 13, 2019, https://overpopulation-project.com/reproductive-biology-of-abortion/.

[^134]: Donella Meadows et al., *The Limits to Growth* (Universe Books, 1972), http://www.donellameadows.org/wp-content/userfiles/Limits-to-Growth-digital-scan-version.pdf.

[^135]: Christof Rühl and Titus Erker, executive summary in "Oil Intensity: The Curiously Steady Decline of Oil in GDP," Center on Global Energy Policy at Columbia University SIPA, September 9, 2021, https://www.energypolicy.columbia.edu/research/report/oil-intensity-curiously-steady-decline-oil-gdp.

[^136]: FAO, IFAD, UNICEF, WFP and WHO, *The State of Food Security and Nutrition in the World 2020* (Rome: FAO, 2020), ch. 1, https://www.fao.org/3/ca9692en/online/ca9692en.html#chapter-1_1.

[^137]: To this point, embryos (i.e., embryos created via IVF) are transferred from one person to another under property law in the United States, denying them personhood.

[^138]: Daniel Kevles, "Eugenics and Human Rights," *The BMJ* 319 (August 14, 1999):435--438, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1127045/.

[^139]: Mother Teresa, "Notable and Quotable," *Wall Street Journal*, February 25, 1994, A14.

[^140]: Cf. John Locke, *Second Treatise of Government* 2.6: "The state of nature has a law of nature to govern it, which obliges every one: and reason, which is that law, teaches all mankind, who will but consult it, that being all equal and independent, no one ought to harm another in his life, health, liberty, or possessions: for men being all the workmanship of one omnipotent, and infinitely wise maker; all the servants of one sovereign master, sent into the world by his order, and about his business; they are his property, whose workmanship they are, made to last during his, not one another's pleasure: and being furnished with like faculties, sharing all in one community of nature, there cannot be supposed any such subordination among us, that may authorize us to destroy one another, as if we were made for one another's uses, as the inferior ranks of creatures are for our's. Every one, as he is bound to preserve himself, and not to quit his station wilfully, so by the like reason, when his own preservation comes not in competition, ought he, as much as he can, to preserve the rest of mankind, and may not, unless it be to do justice on an offender, take away, or impair the life, or what tends to the preservation of the life, the liberty, health, limb, or goods of another."

[^141]: *Black's Law Dictionary* 1324 (6th ed. 1990). Emphasis in original.

[^142]: 1 William Blackstone, *Commentaries* 129--130.

[^143]: "Quickening," *Bouvier's Law Dictionary*, vol. 3, 3rd ed. (West Publishing, 1914), 2784--2785.

[^144]: *Dobbs v. Jackson Women's Health Organization*, No. 19-1392, 2022 WL 2276808, at \*7 (US June 24, 2022). This quote is from pp. 5--6 of Justice Alito's opinion published in the slip opinion in the morning on June 24, 2022, accessed June 24, 2022, https://www.supremecourt.gov/opinions/21pdf/19-1392_6j37.pdf.

[^145]: For one of the best summaries of historical Jewish teaching on abortion, see J. David Bleich, "Abortion and Jewish Law," *New Perspectives on Human Abortion*, ed. Thomas Hilgers, Dennis Horan, and David Mall (Aletheia Books, 1981), 405--419.

[^146]: As noted earlier, it was a common practice for Roman fathers to abandon their infant children to die of exposure.

[^147]: Tacitus, *Histories* 5.5: "Yet they \[the Jews\] take care that their multitude grows; for indeed to kill any of their children is unspeakable, and they hold that the souls of those killed in battle or by penalty of death are immortal: hence their love of reproducing and their disregard for dying. They bury rather than burn their dead."

[^148]: Thus Josephus, *Against Appion* 2.202: "\[The Law\] mandates that they raise all the children, and forbids women either from aborting the seed or from destroying it; but if any \[woman\] should appear \[to have done this\], she would be a child murderer, having destroyed a soul and diminished the race."

[^149]: "Why Jews Oppose Abortion," *The Review of the News*, May 1, 1974, 1--6. Emphasis in the original.

[^150]: As quoted in Bill Moloney, "Jewish View," *National Right to Life News*, June 1979, 6.

[^151]: Jesus speaks of "joy that a human being has been born into the world," indicating that the human being exists prior to birth. For more on the biblical teaching of personhood prior to birth, see the next section of this paper, "The Testimony of Scripture."

[^152]: For more on this, see Daniel Schiff, "Evaluating Life," in *Abortion in Judaism* (Cambridge University Press, 2002), 27--57.

[^153]: "Ipsae quoque divites, ne per plures suum patrimonium dividatur, in utero proprios necant fetus, et parricidalibus succis in ipso genitali alvo pignora sui ventris exstinguunt, priusque aufertur vita quam tradatur. Quis docuit nisi homo filios abdicari?"

[^154]: "Aliquando eo usque pervenit haec libidinosa crudelitas vel libido crudelis, ut etiam sterilitatis venena procuret et si nihil valuerit, conceptos fetus aliquo modo intra viscera exstinguat ac fundat, volendo suam prolem prius interire quam vivere, aut si in utero iam vivebat, occidi ante quam nasci. Prorsus si ambo tales sunt, coniuges non sunt; et si ab initio tales fuerunt, non sibi per connubium, sed per stuprum potius convenerunt."

[^155]: *Lectures on Genesis Chapters 21--25*, ed. Jaroslav Pelikan, vol. 4 in *Luther's Works* (St. Louis: Concordia, 1955--1986), 304.

[^156]: Trans. Charles William Bingham (1852), in *Harmony of the Law*, vol. 3, The Ages Digital Library Commentary (Books for the Ages, 1998), 32.

[^157]: John Paul II, *Evangelium Vitae*, § 61.

[^158]: Peter Singer, *Practical Ethics* (Cambridge University Press, 1993), 136.

[^159]: Calvin, comments on John 18:28, *Commentary on the Gospel According to John*, vol. 2 trans. William Pringle (Wipf & Stock, 2021), 205.

[^160]: Psalms 119:73; 139:13.

[^161]: One biblical argument for this position is that "the pagan altars in the valley of Ben-Hinnom where children were sacrificed are also described as altars to Ba'al by the prophet Jeremiah." Caleb Strom, "Was Moloch Really Ba'al, the Ancient God Who Demanded Child Sacrifice?" Ancient Origins, February 10, 2019, https://www.ancient-origins.net/myths-legends-asia/identity-moloch-0011457. For more information, see the sources referenced Strom, as well as the references in the article on "Moloch" on Wikipedia, https://en.wikipedia.org/wiki/Moloch#References.

[^162]: "Ancient Carthaginians Really Did Sacrifice Their Children," News & Events, University of Oxford, January 23, 2014, https://www.ox.ac.uk/news/2014-01-23-ancient-carthaginians-really-did-sacrifice-their-children.

[^163]: Mary Elizabeth Williams, "So What If Abortion Ends Life?" *Salon*, January 23, 2013, https://www.salon.com/2013/01/23/so_what_if_abortion_ends_life/.

[^164]: October 4, 2010, https://www.huffpost.com/entry/harvest-rites-blood-for-b_b\_746169.

[^165]: Cyril of Alexandria, *Catechetical Lectures* 12.25--26, trans. Edwin Hamilton Gifford.

[^166]: "And when men strive, and have smitten a pregnant woman, and her children have come out, and there is no mischief, he is certainly fined, as the husband of the woman doth lay upon him, and he hath given through the judges; and if there is mischief, then thou hast given life for life, eye for eye, tooth for tooth, hand for hand, foot for foot, burning for burning, wound for wound, stripe for stripe" (Young's Literal Translation).

    There has been much debate over the interpretation of this text. Perhaps the biggest question is how to understand the Hebrew here translated "mischief." Some modern scholars have even tried to make the case the text supports elective abortion. Evangelical scholars have responded by arguing "mischief" (Hebrew *\'āsôn*, [יצא]{dir="rtl"}) does not refer to miscarriage, but premature birth. Cf. U. Cassuto, *Commentary on the Book of Exodus* (Jerusalem Magnes, 1967), 275; H. W. House, "Miscarriage or Premature Birth: Additional Thoughts on Exodus 21:22--25," *Westminster Theological Journal* 41 (Fall 1978): 108--123; W. C. Kaiser, *Toward Old Testament Ethics* (Zondervan, 1983), 102--104, 168--172; also J. Calvin, *Commentary on the Four Last Books of Moses* (Baker, 1979); C. F. Keil and F. Delitzsch, *Exodus* (Eerdmans, n.d.). See also John Makujina, "The Semantics of [יצא]{dir="rtl"} in Exodus 21:22: Reassessing the Variables That Determine Meaning," *Bulletin for Biblical Research* 23, no. 3 (2013): 305--321.

    The interpretation held more broadly across history is "miscarriage." See Russell Fuller, "Exodus 21:22--23: The Miscarriage Interpretation and the Personhood of the Fetus," *Journal of the Evangelical Theological Society* 37, no. 2 (June 1994): 169--184; also Makujina.

    A second, related matter involves the LXX reading of this passage, which, instead of understanding the issue as one of "mischief" or "no mischief," distinguishes between a "formed" and "unformed" fetus. This distinction depends upon ancient opinions about ensoulment, and represents the interpretation of most of the church fathers. A majority of modern exegetes prefer the Hebrew Masoretic reading here, yet arguments in favor of the LXX's reading are substantial, and should not be dismissed out of hand in reference to the "formed" and "unformed" child. Cf. Stanley Isser, "Two Traditions: The Law of Exodus 21:22--23 Revisited," *The Catholic Biblical Quarterly* 52, no. 1: 30--45.

    Regardless of one's conclusions concerning the text's meanings and interpretations, Exodus 21:22--23 provides no support for elective abortion.

[^167]: See, e.g., Deuteronomy 12:31; 18:10; 2 Kings 16:3; 17:17; 17:31; 21:6; 2 Chronicles 28:3; 33:6; Jeremiah 7:31; 19:5; and Ezekiel 16:21; 20:26, 31; 23:37.

[^168]: Lawrence Stager and Samuel Wolff, "Child Sacrifice at Carthage---Religious Rite or Population Control?" *Biblical Archeology Review*, January/February 1984: 32--51. For a time scholars attempted to deny that child sacrifices to the gods really happened as reported, but new research published in the journal *Antiquity* leaves it beyond question, even suggesting that it might be one of the reasons the city was founded in the first place.

[^169]: The word comes, through French and Latin, from Greek *sardonios*, itself an alteration of Greek *sardinia*, associated with a plant from Sardinia. The ancients believed that eating this plant caused facial convulsions and led to death. See Stager and Wolff, 33.

[^170]: Translation by P. G. Mosca, *Child Sacrifice in Canaanite and Israelite Religion: A Study in Mulk and Molech*, PhD dissertation, Harvard University, 1975, 22, as quoted in Stager and Wolff, 33.

[^171]: *Apology* 9.24, from *Apology and De Spectaculis*, trans. T. R. Glover (Loeb Classical Library, 1931).

[^172]: Thus, for φαρμακεία, the Liddell, Scott, Jones Ancient Greek Lexicon gives "of abortifacients" as one definition, citing Soranus (1.59; fl. 1st/2nd century AD). By contrast, BDAG does not include this specific gloss for either *pharmakeia* or *pharmakon* despite Soranus having written within the New Testament time period and BDAG's inclusion of citations from several less significant medicinal writers. One might anticipate a correction of this oversight in future editions. See also Hippocrates, *Oath* 18--20: "Neither will I administer a poison \[*pharmakon*\] to anybody when asked to do so, nor will I suggest such a course. Similarly, I will not give to a woman a pessary to cause abortion."

[^173]: Riddle, *Eve's Herbs: A History of Contraception and Abortion in the West* (Harvard University Press, 1997).

[^174]: For an extended discussion of medicine as "art," and not simply "science," as well as a stunning essay on abortion, see Richard Selzer, *Mortal Lessons: Notes on the Art of Surgery* (Harcourt Brace & Co., 1974). Selzer was a second-generation physician and denied the existence of God.

[^175]: Precise data is absent, but a ballpark figure for the maternal mortality rate is between 0.5 and 2 percent.

[^176]: These and other terms were broad, overlapping, and often used interchangeably; see, e.g., Matthew Dickie, *Magic and Magicians in the Greco-Roman World* (Routledge, 2001), 34; but on the other hand, Richard Greenfield, "Magic and the Occult Sciences" in *The Cambridge Intellectual History of Byzantium* (Cambridge University Press, 2017), 220.

    Even a single term's meaning was often context dependent; cf. *magos* in the New Testament, which is used with reference to the *magi* of Matthew 2 as well as Simon the Magician in Acts 8. On balance, it is best to consider *magos*, *pharmakos*, etc., as related terms that sometimes retain their nuances~~---~~and indeed the standard lexica generally hold to this practice.

[^177]: Cf. Revelation 18:23.

[^178]: Cf. Alciphron, *Epistolae* 4.10.3; also Basil, *Letters* 188.8.

[^179]: Cf., among many others, Theophrastus, Περὶ φυτῶν ἱστορία 9.18.5.

[^180]: Cf. Euripides, *Hippolytus* 509--516.

[^181]: See, e.g., Apuleius, *Metamorphoses* 1.9ff. For more on reproductive spells, see also Jean-Jacques Aubert, "Threatened Wombs: Aspects of Ancient Uterine Magic," *Greek, Roman, and Byzantine Studies* 30, no. 3 (1989): 421--449.

[^182]: See Jerome, *Ad Eustochium* (*Letters* 22.13).

[^183]: 1 Corinthians 6:9--11.

[^184]: "But the cowardly, unbelieving, abominable, murderers, sexually immoral, sorcerers, idolaters, and all liars shall have their part in the lake which burns with fire and brimstone, which is the second death." Revelation 21:8.

[^185]: οὐ φονεύσεις, οὐ μοιχεύσεις, οὐ παιδοφθορήσεις, οὐ πορνεύσεις, οὐ κλέψεις, οὐ μαγεύσεις, οὐ φαρμακεύσεις, οὐ φονεύσεις τ́κνον ἐν φθορᾷ, οὐδὲ γεννηθὲν ἀποκτενεῖς. *Didache* 2.2.

[^186]: Although the crimes of rape and incest are distinct, the latter often involves the former, so we will mainly address rape.

[^187]: For instance, during a debate, Richard Mourdock, the 2012 US Senate candidate for Indiana, uttered the words, "I just struggled with it myself for a long time but I came to realize: Life is that gift from God that I think even if life begins in that horrible situation of rape, that it is something that God intended to happen." His confession of faith in God's sovereignty brought an abrupt end to his previously successful candidacy. See Kevin Robillard, "Buchanan: Mitt Romney Rejects 'Rape' Remark," *Politico*, October 24, 2012, http://www.politico.com/news/stories/1012/82808.html.

[^188]: See this report from the Gesundheitsberichterstattung des Bundes (Federal Health Monitoring System): https://www.gbe-bund.de:443/gbe/pkg_olap_tables.prc_archiv?p_indnr=240&p_archiv_id=1081842&p_sprache=E. Note as well that abortions related to the health of the mother make up less than 4 percent of the total, and this where health is defined broadly as physical and mental health, and a doctor must certify the threat in writing.

[^189]: In the United States, government agencies almost never require the keeping of data on abortions after rape or incest, or due to health concerns related to the mother. See Kortsmit et al., "Abortion Surveillance."

[^190]: According to a 2004 anonymous survey conducted by the Guttmacher Institute among 1,209 women who had aborted their children, less than 0.5 percent were related to rape, and 4 percent to the mother's health. See Lawrence Finer et al., "Reasons U.S. Women Have Abortions: Quantitative and Qualitative Perspectives," *Perspectives on Sexual and Reproductive Health* 37 (2005), no. 3: 110--118. Florida is exceptional among the states, providing an annual report on abortions which includes a statement of reasons given for the abortion. In 2020, 0.16 percent of abortions were related to rape and incest, 1.68 percent to the mother's physical health, and 1.88 percent to the mother's psychological health. See "Reported Induced Terminations of Pregnancy (ITOP) by Reason, by Trimester," 2020, https://ahca.myflorida.com/MCHQ/Central_Services/Training_Support/docs/TrimesterByReason_2020.pdf.

[^191]: We are not declaring the unborn child's absolute innocence here. In Psalm 51, David confesses he was "conceived in sin." Saying this, David was not referring to any sin of his father and mother in the circumstances of his conception, but to his own sin. David's confession of his own original sin from the moment of his conception is equally true of all men and women. In terms of relative innocence, though, the unborn child is the most innocent of all men.

    Still, in connection with the entirety of this paper, Calvin's comments on David's confession of guilt from his conception in the womb are instructive:

    > Interpreters have very properly rendered \[the Hebrew\] "hath conceived me." The expression intimates that we are cherished in sin from the first moment that we are in the womb. David, then, is here brought, by reflecting on one particular transgression, to cast a retrospective glance upon his whole past life, and to discover nothing but sin in it. . . . \[David\] refers to original sin with the view of aggravating his guilt, acknowledging that he had not contracted this or that sin for the first time lately, but had been born into the world with the seed of every iniquity.
    >
    > The passage affords a striking testimony in proof of original sin entailed by Adam upon the whole human family. It not only teaches the doctrine, but may assist us in forming a correct idea of it. . . . The Bible, both in this and other places, clearly asserts that we are born in sin, and that it exists within us as a disease fixed in our nature. David does not charge it upon his parents, nor trace his crime to them, but . . . before the Divine tribunal, confesses that he was formed in sin, and that he was a transgressor ere he saw the light of this world. (Comments on Psalm 51:5, *Commentary on the Book of Psalms*, vol. 2, trans. James Anderson \[Calvin Translation Society, 1846\], 290)

[^192]: Under the Mosaic Law, rape of a married woman was punishable by death (Deut. 22:22--23), and Western law has consistently punished rape with harsh penal sanctions.

[^193]: *City of God* 1.18: "Far be it from us to so misapply words. Let us rather draw this conclusion, that while the sanctity of the soul remains even when the body is violated, the sanctity of the body is not lost; and that, in like manner, the sanctity of the body is lost when the sanctity of the soul is violated, though the body itself remains intact. And therefore a woman who has been violated by the sin of another, and without any consent of her own, has no cause to put herself to death; much less has she cause to commit suicide in order to avoid such violation, for in that case she commits certain homicide to prevent a crime which is uncertain as yet, and not her own."

[^194]: "An Impolite Interview with Ken Kesey," *The Realist*, no. 90 (May/June 1971): 46--47, http://www.ep.tc/realist/90/46.html. Emphases original.

[^195]: Westminster Confession of Faith, 3.1, https://evangelpresbytery.com/westminster-confession-of-faith/#III.

[^196]: C. Everett Koop, interview with Dick Bohrer, *Moody Monthly*, May 1980, reprinted in Dick Bohrer, *Sell Your Homework: 24 Ways to Write What You Think*, lesson 8 ("The Speech Critique") (Glory Press Books, 2005), 17.

[^197]: "Abortion---Yesterday, Today, and Tomorrow," in *The Case for Legalized Abortion Now* (Diablo Press, 1967), 9.

[^198]: It is also worth noting that a 2015 study in the *New England Journal of Medicine* (*NEJM*) indicated that "Prenatal exposure to maternal cancer with or without treatment did not impair the cognitive, cardiac, or general development of children in early childhood." Frédéric Amant et al., "Pediatric Outcome after Maternal Cancer Diagnosed during Pregnancy," *NEJM* 373, no. 19: 1824--1834, https://www.nejm.org/doi/full/10.1056/NEJMoa1508913.

[^199]: It may not need to be said, but this is the very opposite of the mother paying for an abortion. This mother takes the life of her child, almost never to save her own life or health, but to keep her future plans and lifestyle intact and unhindered.

[^200]: "In the United States, the current \[1995\] standard of care in obstetrical practice is to offer either CVS or amniocentesis to women who will be greater than or equal to 35 years of age when they give birth . . ." Richard Olney et al., "Chorionic Villus Sampling and Amniocentesis: Recommendations for Prenatal Counseling," Morbidity and Mortality Weekly Report (MMWR), CDC, July 21, 1995, https://www.cdc.gov/mmwr/preview/mmwrhtml/00038393.htm.

[^201]: Laura Carlson and Neeta Vora, "Prenatal Diagnosis: Screening and Diagnostic Tools," *Obstetrics and Gynecology Clinics of North America* 44, no. 2 (June 2017): 245--256, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5548328/*.*

[^202]: For wrongful *birth*, see, as an example, Turpin v. Sortini, 31 Cal. 3d 220 (1982), https://law.justia.com/cases/california/supreme-court/3d/31/220.html. For wrongful *life*, see, as an example, Curlender v. Bio-Science Laboratories, 106 Cal. App. 3d 814 (1980), https://law.justia.com/cases/california/court-of-appeal/3d/106/811.html. In *Curlender*, the California appellate court found *Roe v. Wade* to be "of considerable importance in defining the parameters of 'wrongful-life' litigation," because of the Supreme Court's determination "that parents have a constitutionally protected right to obtain an abortion during the first trimester of pregnancy," at 820.

[^203]: Rebecca Lobo and Garnett Genuis, "Socially Repugnant or the Standard of Care: Is There a Distinction between Sex-Selective and Ability-Selective Abortion?" *Canadian Family Physician* 60, no. 3 (March 2014): 212--216, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3952749/.

[^204]: One of us participated in a debate over abortion at the General Assembly of the Presbyterian Church (USA) in which each side was asked to summarize the other side's position. He was asked to go first and summarized the abortionists' position by saying they felt any abortion is tragic, but there are times when the circumstances of a woman's pregnancy are so harmful to the woman that having an abortion is less tragic than the alternative. Further, that since it's unclear whether or not the unborn is a real human life, choosing to have an abortion can be the moral decision. With anger, the female abortion proponent, nearly shouting, said, "No!"

    The moderator responded, "No what? Are you saying this summary of your position isn't accurate?"

    She responded, "Yes! We are *not* saying it's *not* a life. We are saying the woman has a right to have an abortion *whether or not it's a life*!"

[^205]: Hugo Grotius, *De Jure Belli ac Pacis Libri Tres*, 121 (1.3.16).

[^206]: 1 William Blackstone, *Commentaries* \*42.

[^207]: See Westminster Larger Catechism, question 138, https://evangelpresbytery.com/westminster-larger-catechism/#Law.

[^208]: See, e.g., Indiana Code § 16-21-11-4, which recognizes parents' right to determine final disposition of the body of their little one lost to miscarriage.

[^209]: See Winston Churchill, in a 1942 speech commenting on the battle of El Alamein. "Autumn 1942 (Age 68)," International Churchill Society, March 12, 2015, https://winstonchurchill.org/the-life-of-churchill/war-leader/1940-1942/autumn-1942-age-68/.

[^210]: It may also be instructive that, in each such case, the words shift from active to passive voice: the deeds of the king (for good or for ill) are expressed in active voice, while the persistence of the high places is shifted into passive voice ("were not taken away"). This may represent a lower-level criticism of the king.

[^211]: Herman Melville, *Moby Dick*, ch. 8.

[^212]: See Resolution 15 from The Lambeth Conference, 1930, Anglican Communion, https://www.anglicancommunion.org/resources/document-library/lambeth-conference/1930/resolution-15-the-life-and-witness-of-the-christian-community-marriage.aspx.

[^213]: "Protestants Endorse Birth Control," *Birth Control Review* 15, no. 4 (April 1931): 102.

[^214]: Quoted in Howard Kainz, "Failing to Connect the Dots on Contraception," *First Things*, February 8, 2012, https://www.firstthings.com/web-exclusives/2012/02/gop-fails-to-connect-the-dots-on-contraception.

[^215]: As reported by Richard Soloway, *Birth Control and the Population Question in England, 1877--1930* (University of North Carolina Press, 1982), 103.

[^216]: "Covenant and Creation: Theological Reflections on Contraception and Abortion," report delivered to the 195th General Assembly (1983) of the Presbyterian Church (USA), 17. The GA received this report and adopted its policy statements and recommendations.

[^217]: David Roach, "How Southern Baptists Became Pro-Life," *Baptist Press*, January 16, 2015, https://www.baptistpress.com/resource-library/news/how-southern-baptists-became-pro-life/.

[^218]: Dennis Quinn, "Few U.S. Sermons Mention Abortion, Though Discussion Varies by Religious Affiliation and Congregation Size," Pew Research Center, April 29, 2020, https://www.pewresearch.org/fact-tank/2020/04/29/few-u-s-sermons-mention-abortion-though-discussion-varies-by-religious-affiliation-and-congregation-size/.

[^219]: Lisa Cannon Green, "Survey: Women Go Silently from Church to Abortion Clinic," Focus on the Family, August 17, 2021, https://www.focusonthefamily.com/pro-life/survey-women-go-silently-from-church-to-abortion-clinic/.

[^220]: David Masci, "American Religious Groups Vary Widely in Their Views of Abortion," Pew Research Center, January 22, 2018, https://www.pewresearch.org/fact-tank/2018/01/22/american-religious-groups-vary-widely-in-their-views-of-abortion/.

[^221]: "Older women likewise are to be reverent in their behavior, not malicious gossips nor enslaved to much wine, teaching what is good, so that they may encourage the young women to love their husbands, to love their children, to be sensible, pure, workers at home, kind, being subject to their own husbands, so that the word of God will not be dishonored." Titus 2:3--5.

[^222]: "But not one has done so who has a remnant of the Spirit. And what did that one do while he was seeking a godly offspring? Take heed then to your spirit, and let no one deal treacherously against the wife of your youth." Malachi 2:15.

[^223]: For more, see "Man's Duty to Protect Woman," Majority Report of the Presbyterian Church in America's General Assembly Ad Interim Study Committee on Women in the Military, 2001, https://www.pcahistory.org/pca/studies/01-278.html.

[^224]: For more information on embryo adoption, see the website of the National Embryo Donation Center, https://www.embryodonation.org/; or the website of Nightlight Christian Adoption's "Snowflakes" program, https://nightlight.org/snowflakes-embryo-adoption-donation/.

[^225]: See Revelation 8.

[^226]: Pierre Viret, *The Christian and the Magistrate: Roles, Responsibilities, and Jurisdictions*, trans. R. A. Sheats (Psalm 78 Ministries, 2015), ch. 7, Kindle.

[^227]: Speech at New Haven, Connecticut, March 6, 1860, *Collected Works of Abraham Lincoln*, vol. 4 (University of Michigan Digital Library Production Services, 2001), 21, http://name.umdl.umich.edu/lincoln4. Emphases original.

[^228]: Westminster Larger Catechism, question 135.

[^229]: See Michael Card's 1984 song, "Spirit of the Age":

    I thought that I heard crying coming through my door.

    Was it Rachel weeping for her sons who were no more?

    Could it have been the babies crying for themselves,

    Never understanding that they died for someone else?

    A voice is heard of weeping and of wailing.

    History speaks of it on every page:

    Of innocent and helpless little babies,

    Offerings to the spirit of the age.

    No way of understanding this sad and painful sign;

    Whenever Satan rears his head, there comes a tragic time.

    If he could crush the cradle, then that would stop the cross;

    He knew that once the Light was born, his every hope was lost.

    Now every age has heard it, this voice that speaks from hell:

    "Sacrifice your children and for you it will be well."

    The subtle serpent's lying, his dark and ruthless rage;

    Behold, it is revealed to be the spirit of the age.

    Soon all the ones who seemed to die for nothing

    Will stand beside the Ancient of Days.

    With joy we'll see that Infant from a manger

    Come and crush the spirit of the age.

[^230]: One example of such is David DeBoor Canfield's "Sighs and Sorrows," Sonata No. 2 for Violin and Piano (1987; rev. 2010), a work protesting abortion.

[^231]: John Paul II, *Evangelium Vitae*, § 73. The concluding quote is from *Declaration on Procured Abortion*, § 22.

[^232]: On the other hand, Republican presidents have also been responsible for a number of disappointments on abortion: e.g., Sandra Day O'Conner, Anthony Kennedy, and David Souter.

[^233]: As but one example, the Federalist Society, an organization that advocates for originalism in constitutional interpretation, was founded in 1982. In recent elections, Republican candidates (especially Donald Trump) have made a cornerstone of their platform a commitment to choosing judges that are approved by the Federalist Society.

[^234]: From the 2020 Democratic party platform:

    > We believe unequivocally, like the majority of Americans, that every woman should be able to access high-quality reproductive health care services, including safe and legal abortion. We will repeal the Title X domestic gag rule and restore federal funding for Planned Parenthood, which provides vital preventive and reproductive health care for millions of people, especially low-income people, and people of color, and LGBTQ+ people, including in underserved areas.
    >
    > Democrats oppose and will fight to overturn federal and state laws that create barriers to reproductive health and rights. We will repeal the Hyde Amendment, and protect and codify the right to reproductive freedom. ("Achieving Universal, Affordable, Quality Health Care," Democrats.org, accessed June 21, 2022, https://democrats.org/where-we-stand/party-platform/achieving-universal-affordable-quality-health-care/)

[^235]: François de La Rochefoucauld, *Maxims*, no. 218.

[^236]: This publication is by the Center for Family and Human Rights, covering life and social policy issues at the United Nations and other international entities.

[^237]: These analyze fetal DNA in the mother's bloodstream.

[^238]: A piece of the placenta is removed and tested.

[^239]: Amniotic fluid from the area surrounding the baby is withdrawn and tested.

[^240]: Maternal blood tests are frequently used to screen for Down syndrome, trisomy 18 and trisomy 13. The Mayo Clinic reports that 15 percent of women receive a false negative and 5 percent receive a false positive for Down syndrome ("First Trimester Screening," Mayo Clinic, https://www.mayoclinic.org/tests-procedures/first-trimester-screening/about/pac-20394169). More recently, these non-invasive prenatal screenings (NIPS) have been used for other genetic micro-deletions. A 2017 study concluded that the false positive rate for the detection of some of the micro-deletion syndromes could be as high as 90 percent (Henna Advani et al., "Challenges in Non-invasive Prenatal Screening for Sub-chromosomal Copy Number Variations Using Cell-Free DNA," *Prenatal Diagnosis* 37, no. 11 \[November 2017\]: 1067--1075, https://doi.org/10.1002/pd.5161). Even the *New York Times* found this news troubling (Sarah Kliff and Aatish Bhatia, "When They Warn of Rare Disorders, These Prenatal Tests Are Usually Wrong," *The Upshot* (blog), *New York Times*, January 1, 2022, https://www.nytimes.com/2022/01/01/upshot/pregnancy-birth-genetic-testing.html). A 2014 study in France determined that ultrasounds yielded a false positive rate of 8.8 percent and a misclassification rate of 9.2 percent (Anne Debost-Legrand et al., "False Positive Morphologic Diagnoses at the Anomaly Scan: Marginal or Real Problem, A Population-Based Cohort Study," *BMC Pregnancy and Childbirth* 14, art. no. 112, March 24, 2014, https://doi.org/10.1186/1471-2393-14-112). Chorionic villus sampling (CVS) and amniocentesis are generally recommended only after an abnormality is indicated by means of less invasive maternal blood tests or ultrasounds. Neither of these methods is foolproof: "A false positive rate was reported to be 3.6% for early amniocentesis and 8% for mid-trimester amniocentesis" (Zarko Alfirevic, Faris Mujezinovic, and Karin Sundberg, "Amniocentesis and Chorionic Villus Sampling for Prenatal Diagnosis," *Cochrane Database of Systematic Reviews* 2003, no. 3, https://doi.org/10.1002/14651858.CD003252). Both CVS and amniocentesis can lead to the death of the baby in the womb; for pregnant women at least 35 years old, the risk of the baby dying from amniocentesis is the same as the risk of the child having, for example, Down syndrome (Susan Pauker and Stephen Pauker, "Prenatal Diagnosis---Why Is 35 a Magic Number?" *NEJM* 330, no. 16 \[April 21, 1994\]: 1151--1152, https://doi.org/10.1056/nejm199404213301610). For CVS the rate of the baby dying after the procedure was around 2.5 percent (Laird Jackson et al., "A Randomized Comparison of Transcervical and Transabdominal Chorionic-Villus Sampling," *NEJM* 327, no. 9 \[August 27, 1992\]: 594--598, https://doi.org/10.1056/NEJM199208273270903).

[^241]: We are aware this concept of "empathy" has become controversial in some parts of the church recently. No question false empathy is abroad and social media is the perfect breeding ground. While conceding that the word can be abused, the abuse of a thing does not invalidate its proper use. The *Oxford English Dictionary* defines "empathy" as "the ability to understand and share the feelings of another." Thus empathy is a critical component of the character of Christian charity:

    > For we do not have a high priest who cannot sympathize with our weaknesses, but One who has been tempted in all things as we are, yet without sin. (Heb. 4:15)
    >
    > When Jesus therefore saw her weeping, and the Jews who came with her also weeping, He was deeply moved in spirit and was troubled, and said, "Where have you laid him?" They said to Him, "Lord, come and see." Jesus wept. (John 11:33--35)
    >
    > And if one member suffers, all the members suffer with it; if one member is honored, all the members rejoice with it. (1 Cor. 12:26)

[^242]: John Calvin, comments on Acts 15:2, *The Acts of the Apostles 14--28*, trans. John W. Fraser, ed. David W. Torrance and Thomas F. Torrance (Eerdmans, 1995), 27.

[^243]: A clinic, properly called, is a place where the healing arts are practiced---not a place presided over by an executioner of the innocent and defenseless. From the *Online Etymology Dictionary*: "1620s, 'bedridden person, one confined to his bed by sickness,' from French *clinique* (17c.), from Latin *clinicus* 'physician that visits patients in their beds,' from Greek *klinike* (*techne*) '(practice) at the sickbed,' from *klinikos* 'of the bed,' from *kline* 'bed, couch, that on which one lies,' from suffixed form of PIE root *klei*- 'to lean.'" Accessed April 10, 2022, https://www.etymonline.com/word/clinic.

[^244]: A note of encouragement on this. One married couple of our congregation traveled across Europe a couple years ago with a brood of four, ages 1, 2, 6, and 8. They reported: "We walked out of our Airbnb as a family of 6, and a very old Italian woman looked at our kids and her eyes filled with tears and she said, 'Bella! Bella! Bella familia!' On more than one occasion we had waiters go out of their way to serve us because they were so thrilled that we were out and about with so many small children. The Italians were smitten, and even the French were accommodating to an extreme."

[^245]: Herman Melville, *Moby Dick*, ch. 134.

[^246]: Cf., e.g., Augustine, *On Marriage and Concupiscence* 1.15.17 (AD 419--420): "Indeed, sometimes this lustful cruelty or cruel lust \[*libidinosa crudelitas vel libido crudelis*\] extends so far that it obtains poisons of sterility \[*sterilitatis venena*\]; and, if nothing else works, \[it\] snuffs out and breaks up by some means the offspring conceived in the womb, preferring its own offspring to perish before it lives \[*prius interire quam vivere*\]; or, if it was already living in the womb, to be killed before being born \[*occidi antequam nasci*\]."

    Cf. also John Chrysostom (AD 391): "Why do you sow where the field is eager to destroy the fruit, where there are medicines of sterility? Where there is murder before birth? You do not even let a harlot remain only a harlot, but you make her a murderess as well. . . . Indeed, it is something worse than murder, and I do not know what to call it; for she does not kill what is formed but prevents its formation. What then? Do you condemn the gift of God and fight with his \[natural\] laws? . . . Yet such turpitude . . . the matter still seems indifferent to many men---even to many men having wives. In this indifference of the married men there is greater evil filth; for then poisons are prepared, not against the womb of a prostitute, but against your injured wife. Against her are these innumerable tricks." *Homilies on Romans* 24, trans. J. Walker, J. Sheppard, and H. Browne.

[^247]: "Far be it, then, from us to doubt that all number is known to Him 'whose understanding,' according to the Psalmist, 'is infinite.' The infinity of number, though there be no numbering of infinite numbers, is yet not incomprehensible by Him whose understanding is infinite. And thus, if everything which is comprehended is defined or made finite by the comprehension of him who knows it, then all infinity is in some ineffable way made finite to God, for it is comprehensible by His knowledge. Wherefore, if the infinity of numbers cannot be infinite to the knowledge of God, by which it is comprehended, what are we poor creatures that we should presume to fix limits to His knowledge, and say that unless the same temporal thing be repeated by the same periodic revolutions, God cannot either foreknow His creatures that He may make them, or know them when He has made them? God, whose knowledge is simply manifold, and uniform in its variety, comprehends all incomprehensibles with so incomprehensible a comprehension, that though He willed always to make His later works novel and unlike what went before them, He could not produce them without order and foresight, nor conceive them suddenly, but by His eternal foreknowledge." *City of God* 12.18, trans. Marcus Dods.

[^248]: One of us recalls an elder telling him that the wife of one of the staff members of the church had just found out she was pregnant. He said the staff member had come to him asking what they should do, since his wife had been on some medication that might have harmed the child and they were fearful. The elder explained he'd suggested the staff member consider abortion, explaining to his pastor, "I consider abortion a matter of stewardship."

[^249]: G. K Chesterton, "The Unfinished Temple," ch. 5 in *What's Wrong with the World*, https://www.gutenberg.org/files/1717/1717-h/1717-h.htm.

[^250]: Hard data on Roman fertility in general, let alone Christian Roman fertility, is lacking. But Stark, *The Rise of Christianity: A Sociologist Reconsiders History* (Princeton University Press, 1996), 122--128, considering the available evidence, lays out a compelling argument for a healthy increase in the Christian fertility rate in the late Roman world, pointing in particular to the following advantages held by Christians in comparison to pagans: (1) abhorrence of abortion and infanticide, (2) objections to contraception, (3) a positive view of marriage (even in cases of mixed marriage), and (4) a high percentage of women of childbearing age. There is also some testimony from primary sources of the time. Noting this, Stark comments, "Differential fertility was taken as fact by the ancients," and quotes Minucius Felix approvingly: "Day by day the number of us is increased \[because of\] \[our\] fair mode of life" (122).

[^251]: Put in place by Emperor Septimius Severus (193--211): "A woman who intentionally induces an abortion is to be sentenced by the Governor to temporary exile; for it can be considered dishonorable for a woman to defraud a husband of his children with impunity." *Digesta* 47.11.4*.*

[^252]: Particularly under Theodosius II (408--450): "If anyone commit the crime of killing an infant, this evil shall constitute a capital offense." *Codex Theodosianus* 9.14.1.

[^253]: "Two laws have been enacted, one against a woman who, through dislike to her husband, takes pains to produce an abortion upon herself, and accomplishes the death of her unborn child, and another enacted against the husband requiring him to repudiate a woman who has been guilty of such an outrage." Leo later says that such a woman "has committed a crime which is an outrage . . . against Nature." *The New Constitutions of the Emperor Leo* 31, trans. S. P. Scott, https://droitromain.univ-grenoble-alpes.fr/Anglica/NL31_Scott.htm.

[^254]: This does not mean that the practice of abortion ended immediately, of course. Indeed, child murder was apparently slow to decline. Law, as all else, is bound by God's decrees, but law cannot in itself change hearts.

[^255]: J. R. R. Tolkien, "The Last Debate," ch. 9 in bk. 1 of *The Lord of the Rings: The Return of the King*.

[^256]: Richard John Neuhaus, "We Shall Not Weary, We Shall Not Rest," speech given at the conclusion of the 2008 annual convention of National Right to Life, July 5, 2008, as published on July 11, 2008, in *First Things*, https://www.firstthings.com/web-exclusives/2008/07/we-shall-not-weary-we-shall-not-rest.